### ISSUE TITLE
Feature Request:  Multi-row LaTeX Output with Repetition of the Value for the First Page Row

### ISSUE THREAD

**Issue by billdenney** [haozhu233/kableExtra#100]
Thank you for the package!

I wonder if you could incorporate something like (https://tex.stackexchange.com/questions/79143/how-to-repeat-cell-content-on-next-page-for-longtable-using-multirow) into kableExtra?  Specifically:  Could an option for `collapse_rows` be given that would collapse rows using LaTeX code similar to that in the Stack Exchange answer?  And, could that answer be expanded to handle collapsing multiple columns instead of the single column that the Stack Exchange answer works for?

**Comment by haozhu233** [comment]
Hi, @billdenney, that SE answer self-defined a marco `topic`, which is sort of getting beyond what this package can do. Right now rmarkdown only allows us to pass in latex package names. 

Also, in your case, if you have a complex table that is full with text, you should be able to write the tex code directly in rmarkdown.

**Comment by billdenney** [comment]
That's reasonable.  Thank you.
