### ISSUE TITLE
Enhancement: Ability to add lines to kable tables using hline, cline, etc.

### ISSUE THREAD

**Issue by eipi10** [haozhu233/kableExtra#101]
It doesn't look like there's a way to add rule lines to using `kableExtra` (please correct me if I'm wrong about this), so I thought I would add this as an enhancement request. Below is an example of an `rmarkdown` document that includes a table with a few types of horizontal lines (though it would be nice to be able to add vertical lines too). I've used `xtable` to illustrate, but I prefer `kableExtra` because of the ease of adding grouping columns/rows and cell formatting. The output table is just below the code.

````
---
output: bookdown::pdf_document2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(xtable)
options(xtable.comment=FALSE,
        xtable.include.rownames=FALSE)
```

```{r results="asis"}
mtcars = cbind(Model=rownames(mtcars), mtcars)

addtorow = list(list(-1,3,4,10,15),
                c("\\toprule[0.2em]{}","\\cline{2-6}","\\midrule{}",
                  "\\cline{2-6}", "\\bottomrule[0.5em]{}"))

print(xtable(mtcars[1:15, 1:6]),
      add.to.row=addtorow,
      booktabs=TRUE,
      hline.after=c(0,12,13))
```
````

![screen shot 2017-11-14 at 2 34 48 pm](https://user-images.githubusercontent.com/436817/32808737-ff627172-c948-11e7-82c5-a32dd27a3f69.png)

**Comment by haozhu233** [comment]
@eipi10 nice suggestion! I wrote s module to do cmidrule things when dealing with `collapse_rows`. I think I should be able to expend it to row_spec

**Comment by haozhu233** [comment]
Hi, @eipi10, sorry for the delay. I just added this feature to `row_spec`. Now you can use `hline_after` or `extra_latex_after` to add additional contents after certain rows. :)
<img width="398" alt="screen shot 2018-01-14 at 4 28 22 pm" src="https://user-images.githubusercontent.com/7014590/34920891-4322a68c-f948-11e7-8e91-b21e21b4ca2e.png">

**Comment by eipi10** [comment]
Thanks!

- Joel

**Comment by stvrd** [comment]
Hello, this is a great feature - unfortunately not yet available for **html**-output. I am creating all my tables with `kable(x) %>% kable_styling(...) %>% row_spec(...)`. It would be great to have the options `border_above` and `border_below`  to remove certain horizontal lines or to add black horizontal lines under or over specific rows.
