### ISSUE TITLE
How can we align the table created when using Scroll box?

### ISSUE THREAD

**Issue by winterwang** [haozhu233/kableExtra#106]
Hi, when using the Scroll box feature to embed big(or long) table for websites, the `position=center` option within `kable_styling()` seems not functioning.

Do you have any suggestion for positioning a scroll box table in an HTML file? 

Many thanks!

**Comment by haozhu233** [comment]
If you have already specify a width value for the scroll box like "400px", you can try to use the `extra_css` in `scroll_box` and put `margin-left: auto; margin-right: auto;` there.

**Comment by winterwang** [comment]
Awesome! Problem solved, cheers!

`scroll_box(width = "400px", height = "500px", extra_css="margin-left: auto; margin-right: auto;")`
