### ISSUE TITLE
Problem with border_left in column_spec

### ISSUE THREAD

**Issue by steffilazerte** [haozhu233/kableExtra#107]
Hi, when I try to use the `border_left` argument of `column_spec` something goes funny and the document spits out latex code as text in addition to a malformed table.

Here is the testing.Rmd file ([testing.txt](https://github.com/haozhu233/kableExtra/files/1536231/testing.txt), I saved as txt so I could upload to github)

This Rmd file produces the following output: 
- [testing.pdf](https://github.com/haozhu233/kableExtra/files/1536229/testing.pdf)
- [testing_tex.txt](https://github.com/haozhu233/kableExtra/files/1536234/testing_tex.txt) (saved to txt so I could upload)

Let me know if there's anything I can do to help track down this problem. Thanks for `kableExtra`!

**Comment by haozhu233** [comment]
Hi, @steffilazerte Sorry for the delay. This bug has been fixed now. I will update the CRAN ver in a few days.

**Comment by steffilazerte** [comment]
No worries, thanks for the fix!
