### ISSUE TITLE
kableExtra incompatible with \usepackage{fancyhdr}?

### ISSUE THREAD

**Issue by hemip** [haozhu233/kableExtra#11]
Hi,
I was really thrilled when I found kableExtra and managed to produce some fancy tables. However, when I copied the code into my markdown report I lost some other features in the document instead.

I had previously managed to configure headers and footers with the 'fancyhdr' package (see the added lines below). But as soon as I includes 'library(kableExtra)' the headers and footers disappear. Any idea about the incompatability?

/hans

header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancyplain}
- \fancyfoot[LE,RO]{\thepage}
- \rhead{\includegraphics[height=2cm]{slu.png}}

**Comment by haozhu233** [comment]
You should upgrade your rmarkdown to the dev version. There was a bug there that prevents loading latex packages from 2 sources. See #5 for details.

**Comment by haozhu233** [comment]
In case my answer cannot solve the problem. ;)

**Comment by p-phillips** [comment]
Just to confirm,

`devtools::install_github("rstudio/rmarkdown")
`
solves the problem.

Could you add this to the known limitations in teh README ?  I spent hours trying to track this problem down last night.

**Comment by hemip** [comment]
Dear Haozhu,

Thanks for quick response and amazing work. After upgrading rmarkdown and also kableExtra to latest dev-versions both my problems are gone.

Best wishes,
Hans

**Comment by haozhu233** [comment]
@p-phillips Ops, sorry about that 😋. I just added a sentence and highlighted it in the limitation section

@hemip I'm glad it helps. :)
