### ISSUE TITLE
first column appearing outside of the table in html tags

### ISSUE THREAD

**Issue by ericpgreen** [haozhu233/kableExtra#110]
I posted to SO a while back about the first column appearing outside of the table in html tags when using `kable_styling()`. Any clues to what might be causing this behavior?

[SO](https://stackoverflow.com/questions/46820236/first-column-outside-of-kable-table-with-kable-styling)

**Comment by haozhu233** [comment]
Hmm, I still cannot reproduce the bug. Can you try to remove ` results='asis'` and let me know what happens? `kable` doesn't need you to specify `asis` anymore.

**Comment by ericpgreen** [comment]
Thanks, @haozhu233. I get the same result. 

My colleague in the office can't reproduce this either. 

```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.5

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] backports_1.1.1 magrittr_1.5    rsconnect_0.8.5 rprojroot_1.2   htmltools_0.3.6 tools_3.3.2     yaml_2.1.15    
 [8] Rcpp_0.12.14    stringi_1.1.6   rmarkdown_1.8   knitr_1.17      stringr_1.2.0   digest_0.6.12   evaluate_0.10.1
```

**Comment by haozhu233** [comment]
Hi, @ericpgreen, thanks for the session info. I'm sure it's not a mac issue as I did the programming on a mac as well. Can you send me the raw HTML code generated by the code?

**Comment by ericpgreen** [comment]
Thanks. It's quite long, so saved to `txt`.
[test.txt](https://github.com/haozhu233/kableExtra/files/1589606/test.txt)

**Comment by haozhu233** [comment]
I see. The first column was treated as `code` by rmarkdown.
```
<thead>
<pre><code>&lt;tr&gt;&lt;th style=&quot;text-align:left;&quot;&gt; v1 &lt;/th&gt;</code></pre>
<th style="text-align:left;">
v2
</th>
</tr>
</thead>
```
Could you also execute the `kable` code in R console and let me what you get? I want to know what makes rmarkdown think they are codes. Thanks!

**Comment by ericpgreen** [comment]
Here's what I get in the console:

```
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead><tr>
<th style="text-align:left;"> v1 </th>
   <th style="text-align:left;"> v2 </th>
  </tr></thead>
<tbody>
<tr>
<td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> 3 </td>
  </tr>
<tr>
<td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> 4 </td>
  </tr>
</tbody>
</table>
```

**Comment by haozhu233** [comment]
@ericpgreen I just tried to fix this behavior via https://github.com/haozhu233/kableExtra/commit/0a98df0fea857b9306164b6ea9b55d3079ce15d1. Could you try to reinstall from github and let me know what you can get now?

**Comment by ericpgreen** [comment]
magical. works now. thanks for taking the time to fix a problem no one could seem to reproduce.

**Comment by haozhu233** [comment]
lol Great! Thank you for your fast feedback! :D
