### ISSUE TITLE
Underscore in footnote doesn't knit to pdf

### ISSUE THREAD

**Issue by murraycadzow** [haozhu233/kableExtra#115]
Hi,
Absolutely love this package! I saw that there were some new footnote options that were available and wanted to try them out but came across this error in doing so

I found that with the dev version (specifically commit 182cfbd) when there is an underscore in the footnote that the document won't knit

here is an example Rmarkdown
```
---
output: pdf_document
---

\```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(magrittr)
library(kableExtra)
\```

\```{r}
kable(cars, caption = 'table caption', format = 'latex', escape = TRUE) %>% kableExtra::footnote(general = 'an_underscore', escape = TRUE)
\```
```

and I get the following error message:
! Missing $ inserted.
<inserted text> 
                $
l.252 \multicolumn{2}{l}{an_underscore}

pandoc: Error producing PDF
Error: pandoc document conversion failed with error 43
Execution halted

Switching escape to FALSE in either command still has the error

Hope that this is of use and keep up the great work

thanks
Murray

Session info:

setting  value                       
version  R version 3.4.3 (2017-11-30)
system   x86_64, linux-gnu           
ui       X11                         
language en_NZ                       
collate  en_NZ.UTF-8                 
tz       NZ                          
date     2018-01-17

package     * version    date       source                               
backports     1.1.2      2017-12-13 cran (@1.1.2)                        
base        * 3.4.3      2017-12-01 local                                
colorspace    1.3-2      2016-12-14 CRAN (R 3.3.2)                       
compiler      3.4.3      2017-12-01 local                                
datasets    * 3.4.3      2017-12-01 local                                
devtools      1.13.3     2017-08-02 CRAN (R 3.4.1)                       
digest        0.6.14     2018-01-14 cran (@0.6.14)                       
evaluate      0.10.1     2017-06-24 cran (@0.10.1)                       
graphics    * 3.4.3      2017-12-01 local                                
grDevices   * 3.4.3      2017-12-01 local                                
hms           0.3        2016-11-22 CRAN (R 3.3.2)                       
htmltools     0.3.6      2017-04-28 CRAN (R 3.4.0)                       
httr          1.3.1      2017-08-20 cran (@1.3.1)                        
kableExtra  * 0.7.0.9000 2018-01-16 Github (haozhu233/kableExtra@182cfbd)
knitr       * 1.18       2017-12-27 cran (@1.18)                         
magrittr    * 1.5        2014-11-22 CRAN (R 3.3.1)                       
memoise       1.1.0      2017-04-21 CRAN (R 3.4.0)                       
methods     * 3.4.3      2017-12-01 local                                
munsell       0.4.3      2016-02-13 CRAN (R 3.3.2)                       
plyr          1.8.4      2016-06-08 CRAN (R 3.3.2)                       
R6            2.2.2      2017-06-17 cran (@2.2.2)                        
Rcpp          0.12.14    2017-11-23 cran (@0.12.14)                      
readr         1.1.1      2017-05-16 CRAN (R 3.4.0)                       
rlang         0.1.2      2017-08-09 cran (@0.1.2)                        
rmarkdown     1.8        2017-11-17 cran (@1.8)                          
rprojroot     1.3-2      2018-01-03 cran (@1.3-2)                        
rvest         0.3.2      2016-06-17 CRAN (R 3.3.2)                       
scales        0.5.0      2017-08-24 CRAN (R 3.4.1)                       
stats       * 3.4.3      2017-12-01 local                                
stringi       1.1.5      2017-04-07 CRAN (R 3.4.0)                       
stringr       1.2.0      2017-02-18 CRAN (R 3.4.0)                       
tibble        1.3.4      2017-08-22 cran (@1.3.4)                        
tools         3.4.3      2017-12-01 local                                
utils       * 3.4.3      2017-12-01 local                                
viridisLite   0.2.0      2017-03-24 CRAN (R 3.4.0)                       
withr         2.0.0      2017-07-28 CRAN (R 3.4.1)                       
xml2          1.1.1      2017-01-24 CRAN (R 3.3.2)                       
yaml          2.1.16     2017-12-12 cran (@2.1.16)

rmarkdown::pandoc_version()
[1] ‘1.19.2.1’

**Comment by murraycadzow** [comment]
As a follow up I have discovered that this works:

```{r}
kable(cars, caption = 'table caption', format = 'latex', escape = TRUE) %>% kableExtra::footnote(general = 'an\\\\_underscore', escape = FALSE)
```

but not
```{r}
kable(cars, caption = 'table caption', format = 'latex', escape = TRUE) %>% kableExtra::footnote(general = 'an\\_underscore', escape = TRUE)
```

I don't understand what's going on behind the scenes well with the markdown -> tex -> pdf, but perhaps there is a way that the default setting is the text entered comes out verbatim?

Thanks
Murray

**Comment by haozhu233** [comment]
Hi, @murraycadzow I totally agree with you that we should make things easier for people to use and thank you for raising this issue! I will look into that.
