### ISSUE TITLE
After adding "repeat_header" the footnote of a longtable is misplaced?

### ISSUE THREAD

**Issue by koliii** [haozhu233/kableExtra#116]
Please see this example:

````{r}
sampleTable <- data.frame(C1 = c(rep("a", 25), rep("b", 25)),
                          C2 = 1:50
                          )

kable(sampleTable,
      format = "latex",
      booktabs = T,
      longtable = T,
      caption = "Sample table") %>%
  collapse_rows(columns = 1) %>%
footnote(general = "Here is a general comments of the table. ")%>%
  kable_styling(latex_options = "repeat_header")`

**Comment by haozhu233** [comment]
Now the bottom rule will appear in the right place, although you need to put `kable_styling` before `footnote`.

```
kable(mtcars,
      format = "latex",
      booktabs = T,
      longtable = T,
      caption = "Sample table")  %>%
  kable_styling(latex_options = "repeat_header")%>%
  footnote(general = "Here is a general comments of the table. ")
```

**Comment by koliii** [comment]
Still longtable not similar to small table latex pdf output.

Small table
![screenshot from 2018-03-27 07-34-52](https://user-images.githubusercontent.com/28312545/37942570-6847c4e8-3191-11e8-8598-66d999933be7.png)

Longtable

![screenshot from 2018-03-27 07-27-37](https://user-images.githubusercontent.com/28312545/37942576-744a2060-3191-11e8-90fe-ade3a463c0b3.png)

**Comment by haozhu233** [comment]
@koliii Have you flipped the order of `kable_styling` and `footnote` as I suggested? I should have already fixed this.

**Comment by koliii** [comment]
Sorry @haozhu233 , I'm not able to correct it. Kindly see an attached a screen shot of `R` codes.
![screenshot from 2018-03-28 09-26-12](https://user-images.githubusercontent.com/28312545/38008079-4e528738-326a-11e8-971c-3dfc7f593892.png)
