### ISSUE TITLE
How to round digits of a column when using cell_spec function?

### ISSUE THREAD

**Issue by koliii** [haozhu233/kableExtra#117]
I used these codes to produce the attached output. Problem is after using `cell_spec` function column `C.alpha` is not rounding to 2 digits like the other columns in the output.

````{r, results='asis'}
# check unidimensionality
craft_plspm1$unidim %>%
  mutate(
    C.alpha = cell_spec(C.alpha, "latex",
                        color = ifelse(C.alpha < 0.70, "red", "black"))
    ) %>%
  kable(format = "latex",
        escape = F,
        booktab = T,
        digits = 2,
        caption = "Unidimensionality of reflective blocks")
````
Output table is:

![screenshot from 2018-01-22 11-11-17](https://user-images.githubusercontent.com/28312545/35206910-cfb20494-ff65-11e7-9c7a-a5b0258d8a44.png)

**Comment by haozhu233** [comment]
Try
```
craft_plspm1$unidim %>%
  mutate(
    C.alpha = cell_spec(round(C.alpha, 2), "latex",  # Here
                        color = ifelse(C.alpha < 0.70, "red", "black")) 
    ) %>%
  kable(format = "latex",
        escape = F,
        booktab = T,
        digits = 2,
        caption = "Unidimensionality of reflective blocks")
```

**Comment by koliii** [comment]
Thank you so much @haozhu233 , your suggestion worked perfect, beautiful table output. 
![screenshot from 2018-01-22 12-48-21](https://user-images.githubusercontent.com/28312545/35209249-c15adc06-ff72-11e7-8a00-cae1510b45da.png)

In my opinion, among all open source communities, `R` community is the best. :)

**Comment by koliii** [comment]
And what should I do to make only these red digits bold as well?

**Comment by koliii** [comment]
Using your awesome table examples, I did this for bold:

````{r, results='asis'}
# check unidimensionality
craft_plspm1$unidim %>%
  mutate(
    Construct = row.names(.),
    C.alpha = cell_spec(round(C.alpha, 2), "latex", bold = T,
                        color = ifelse(C.alpha < 0.70, "red", "black"),
                        font_size = spec_font_size(C.alpha)) # bold here
    ) %>%
  select(Construct, Mode, MVs, C.alpha, DG.rho, eig.1st, eig.2nd) %>%
  kable(format = "latex",
        escape = F,
        booktab = T,
        digits = 2,
        caption = "Unidimensionality of reflective blocks") %>%
  footnote(general = c("AUT and CSC are second-order constructs.;"),
           alphabet = c("C.alpha > 0.70; DG.rho > 0.70; eig.1st > 1; 
                        eig.2nd < 1"),
           general_title = "Note:",
           alphabet_title = "Recommended values:")
```
`

And output is

![screenshot from 2018-01-22 13-16-10](https://user-images.githubusercontent.com/28312545/35210112-e77da388-ff76-11e7-9781-4cd511ce5992.png)

**Comment by haozhu233** [comment]
@koliii There was a bug in kableExtra 0.61 that prevents you from doing these. You need to update your package to 0.7.0.

**Comment by koliii** [comment]
I'm not able to bold only red digits,

![screenshot from 2018-01-22 23-12-29](https://user-images.githubusercontent.com/28312545/35235429-14deb79c-ffca-11e7-9461-541c6c9e4815.png)

**Comment by koliii** [comment]
Thanks, your suggestion worked good and produced this table output:

![screenshot from 2018-01-23 00-04-09](https://user-images.githubusercontent.com/28312545/35237586-1da81fa6-ffd1-11e7-941c-fcabf203a8fb.png)
