### ISSUE TITLE
HTML output: add_header_above and collapse_rows not working together

### ISSUE THREAD

**Issue by angelo-pereira** [haozhu233/kableExtra#119]
(Using kableExtra `0.7.0.9000´)
Adding headers and collapsing rows on the same html table produces the error:
```
Error in xml_children(x)[[search]] : subscript out of bounds
Calls: <Anonymous> ... <Anonymous> -> collapse_rows -> collapse_rows_html -> xml_child
```
(pdf output works fine)

Here is a reproducible example, adapting the code from the manual for grouping multirow cells:

```
collapse_rows_dt <- data.frame(C1 = c(rep("a", 10), rep("b", 5)),
                 C2 = c(rep("c", 7), rep("d", 3), rep("c", 2), rep("d", 3)),
                 C3 = 1:15,
                 C4 = sample(c(0,1), 15, replace = TRUE))

kable(collapse_rows_dt, "html", align = "c") %>%
    kable_styling(full_width = F) %>%
    add_header_above(c(" ", "Test" = 3)) %>% 
    column_spec(1, bold = T) %>%
    collapse_rows(columns = 1:2)

```

**Comment by haozhu233** [comment]
I see. I will try to fix it. In the mean time, if you `collapse_rows` before you `add_header_above`, the error will be gone.

**Comment by angelo-pereira** [comment]
Thanks!

**Comment by angelo-pereira** [comment]
While you're at it, I just found out that if you add a `column_spec` AFTER a `collapse_rows` you get the same error. Equally, it works on the reverse order.

**Comment by vahabo** [comment]
One more point :
In my hands add_header_above and include_empty do not work. Appreciate your notice on this issue

`mtcars %<>% mutate(am=factor(am, labels = c("No","Yes")), vs=factor(vs, labels = c("No","Yes")))
mytable<-descrTable(vs~wt+am, 
                  data = mtcars, method = 4,
                    q.type = c(1,1),byrow = T,include.miss = T, digits = c(wt=0),
                      hide.no = "No") 
export2md(mytable, format = "html", header.labels = c("p.overall"="p-value"),
        caption = "Table 1 ", strip = F,first.strip = T) %>%
          add_header_above(header = c("","n(%)"=2,""), line = T,include_empty = TRUE,
                   extra_css = "border-top:2px solid black;")`
