### ISSUE TITLE
% bug, continued

### ISSUE THREAD

**Issue by hemip** [haozhu233/kableExtra#12]
Hi again,

I was hit by the % bug. I downloaded the dev-version yesterday, and it worked in one of my tables. A table using booktabs and an added extra header row.

However, in the second table where I also grouped rows, it was only possible to use '%' in one column! As soon I added percent values in more than one column the grouping disappeared.

/hans

**Comment by haozhu233** [comment]
Yeah, I think this problem should have been addressed in the current version. I fixed it together with #9 and made the update earlier today. Can you try to install it again?

**Comment by hemip** [comment]
Thanks for the good work. The new version works as expected...
