### ISSUE TITLE
How to insert math symbols in footnote of kableextra table?

### ISSUE THREAD

**Issue by koliii** [haozhu233/kableExtra#120]
Hi Hao Zhu, @haozhu233 

I tried this example

```
library(kableExtra)

dt <- mtcars[1:5, 1:6]

knitr::kable(dt, "latex", align = "c", booktabs = T) %>%
  footnote(
    general = "Here is a general comments of the table. ",
    number = c("y = a+b;", "e = mc^2;"), # math
    alphabet = c("Footnote A; ", "Footnote B; "),
    symbol = c("Footnote Symbol 1; ", "Footnote Symbol 2"),
    general_title = "General: ", number_title = "Type I: ",
    alphabet_title = "Type II: ", symbol_title = "Type III: ",
    footnote_as_chunk = T
  )

```

**Comment by SWolf23** [comment]
Hi

there is an option in footnote called 'escape' set it to FALSE then you can write Latex Code in the Comments and it will work.
`\documentclass{article}
\begin{document}
<<>>=
library(kableExtra)
dt <- mtcars[1:5, 1:6]
knitr::kable(dt, "latex", align = "c", booktabs = T) %>%
  footnote(
    general = "Here is a general comments of the table. ",
    number = c("$y = a+b;$", "$e = {mc}^{2};$"), # math
    alphabet = c("Footnote A; ", "Footnote B; "),
    symbol = c("Footnote Symbol 1; ", "Footnote Symbol 2"),
    general_title = "General: ", number_title = "Type I: ",
    alphabet_title = "Type II: ", symbol_title = "Type III: ",
    footnote_as_chunk = T, escape=F
  )
@
\end{document}`

**Comment by koliii** [comment]
Thanks @SWolf23

**Comment by rubemd** [comment]
Concerning this topic, I am having troubles to put a % sign in a footnote. I tried $%$, $\%$, but I don't have success. Could you please check on it?

tab <- tribble(~Software, ~Persistência, ~Detecção, ~Fatalidades (Total), ~Fatalidades/ano, ~Fatalidades/km/ano,
"Carcass", "37,94", "0,80 (0,70-0,87)", "29.066 (19.932-43.278)", "7.267 (4.983-10.820)", "8,43 (5,72-12,42)",
   "Siriema", "25,94", "0,80", "40.934", "10.233", "11,75"
  )

dt_footnote <- tab
dt_footnote[1,2] <- paste0(dt_footnote[1,2], footnote_marker_alphabet(1, format = "latex"))
dt_footnote[2,2] <- paste0(dt_footnote[2,2], footnote_marker_alphabet(2, format = "latex"))

kable(dt_footnote, caption = "Comparação entre métodos e respectivos valores obtidos para determinação da magnitude de fatalidades de sapos-cururu.", format = "latex", booktabs = T, escape = F) %>% 
  kable_styling(latex_options = c("hold_position", "scale_down")) %>% 
  footnote(escape = F, general =  "Intervalos de confiança inferior e superior (95 porcento) são apresentados entre parênteses; ", general_title = "Legenda: ", footnote_as_chunk = T, alphabet = c("Média em dias; ", "Dias para remoção de 63$\%$ porcento das carcaças"))

**Comment by koliii** [comment]
I too got the error on inserting `$%$` in kableextra table footnote

![screenshot from 2018-01-25 19-28-28](https://user-images.githubusercontent.com/28312545/35391873-f1a6b138-0205-11e8-887c-f31ac7978929.png)

**Comment by haozhu233** [comment]
There is a bug in `footnote`'s escape. It seems like I should use double escape there. 

Similar issue reported in 
https://github.com/haozhu233/kableExtra/issues/115

**Comment by SWolf23** [comment]
I don't know why but it works if you escape the % with 4 times \  ;
Means `\\\\%`
```
library(kableExtra)
dt <- mtcars[1:5, 1:6]
knitr::kable(dt, "latex", align = "c", booktabs = T) %>%
  footnote(
    general = "Here is a general comments of the table. ",
    number = c("$y = a+b;$", "$e = mc^2;$","\\\\%"), # math
    alphabet = c("Footnote A; ", "Footnote B; "),
    symbol = c("Footnote Symbol 1; ", "Footnote Symbol 2"),
    general_title = "General: ", number_title = "Type I: ",
    alphabet_title = "Type II: ", symbol_title = "Type III: ",
    footnote_as_chunk = T, escape=F
  )
```

**Comment by rubemd** [comment]
Yes, @SWolf23, I saw it in the issue @haozhu233 mentioned and it also worked for me! Thank you!

**Comment by haozhu233** [comment]
@rubemd @SWolf23 Thank you so much for point out the solution! Also, please be aware that this is a bug that will be addressed soon. Once the bug is fixed, you'll need to change the quadruple slash back to double. Sorry about this confusion. :P
