### ISSUE TITLE
caption text size changes in longtable when font_size is used

### ISSUE THREAD

**Issue by gosianow** [haozhu233/kableExtra#124]
In the "standard" table, only the the size of the text in the table changes when using `font_size` option and the caption text size is as in the rest of the text file, which is what I expect. 
In the "longtable" output, also the caption text size changes when `font_size` is defined, which is something I do not want. How could I prevent that?

```
library(knitr)
library(kableExtra)

dt <- mtcars[1:5, 1:6]

kable(rbind(dt, dt, dt, dt, dt, dt), "latex", caption = "Not longtable text text text text.", booktabs = TRUE, linesep = "") %>%
  kable_styling(latex_options = c("repeat_header", "HOLD_position"), font_size = 7)

kable(rbind(dt, dt, dt, dt, dt, dt, dt, dt, dt, dt, dt, dt), "latex", caption = "Longtable text text text text.", booktabs = TRUE, linesep = "", longtable = TRUE) %>%
  kable_styling(latex_options = c("repeat_header", "HOLD_position"), font_size = 7)

```

**Comment by haozhu233** [comment]
It's very difficult to implement it in longtable, especially when you want to have repeat_header. See this if you want to hack around latex: https://tex.stackexchange.com/questions/392097/how-to-change-font-size-of-table-entries-without-changing-caption-fontsize/392137
