### ISSUE TITLE
group_rows() and add_indent() do not work together with HTML tables

### ISSUE THREAD

**Issue by rabutler** [haozhu233/kableExtra#127]
Consider the following example, in which I would expect the "Valiant' row to be indented more than the two "Hornet" rows above it. 

```
kable(mtcars[1:10, 1:6], "html", caption = "Group Rows") %>%
  kable_styling("striped", full_width = F) %>%
  group_rows(index = c(" " = 3, "Group 1" = 4, "Group 2" = 3)) %>%
  add_indent(6)
```

Currently, in v0.7.0, this results in the following table:
![image](https://user-images.githubusercontent.com/7244282/35583742-20734258-05b0-11e8-9285-5b9fc8efb05b.png)

I believe this is because the html output includes the `"indentlevel"` attribute in all lower case; however, the `add_indent_html()` function is checking if the `"indentLevel"` attribute is already set. I'm a little confused, because it also appears to be setting the `"indentLevel"` attribute, but the output is all lower case. Either way, when I edit this function to always use the lower case version, it seems to work as shown below:

![image](https://user-images.githubusercontent.com/7244282/35583902-90590f3a-05b0-11e8-8db6-ed2e7941db31.png)

If you agree this is an issue, I have already made the changes on my fork, and can submit a PR (even though it's a pretty easy fix.) I also didn't check how it is working with latex.

Thanks for all your work on this package!

**Comment by haozhu233** [comment]
Great! Thanks for submitting this issue and looking into my code. I'm a little surprised to see this behavior too. As you mentioned, all codes seem to be correct. 

I did change the read html table from from `xml2::read_xml` to `xml2::read_html` in the last version. Maybe that's the reason why it happens. No matter what, it still surprises me in this case. 

I guess you can go ahead and change things to lower cases. The LaTeX is going through a different mechanism so we don't need to worry about that. :) Thank you!

**Comment by rabutler** [comment]
Yes, I believe the change from `xml2::read_xml` to `xml2::read_html` is the root of the issue. The following compares the output of the two different approaches, and you'll see the indent level changes from came-case to all lower case. (This uses v0.7.0)

```
zz <- kable(mtcars[1:3,1:3], "html") %>% kableExtra::add_indent(2)

kableExtra:::xml_tpart(
  xml_child(xml_child(read_html(as.character(zz), options = c("RECOVER", "NOERROR")), 1), 1),
  "tbody"
)
# output: 
{xml_node}
<tbody>
[1] <tr>\n   <td style="text-align:left;"> Mazda RX4 </td>\n   <td style="text-align:right;"> 21.0 </td>\n   <td  ...
[2] <tr>\n   <td style="text-align:left; padding-left: 2em;" indentLevel="1"> Mazda RX4 Wag </td>\n   <td style=" ...
[3] <tr>\n   <td style="text-align:left;"> Datsun 710 </td>\n   <td style="text-align:right;"> 22.8 </td>\n   <td ...

kableExtra:::xml_tpart(
  read_xml(as.character(zz), options = c("COMPACT")),
  "tbody"
)

# output
{xml_node}
<tbody>
[1] <tr>\n   <td style="text-align:left;"> Mazda RX4 </td>\n   <td style="text-align:right;"> 21.0 </td>\n   <td  ...
[2] <tr>\n   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> Mazda RX4 Wag </td>\n   <td style=" ...
[3] <tr>\n   <td style="text-align:left;"> Datsun 710 </td>\n   <td style="text-align:right;"> 22.8 </td>\n   <td ...
```

I'll go ahead and submit the PR
