### ISSUE TITLE
kable_styling output raw html rather in R markdown/notebook

### ISSUE THREAD

**Issue by 33Vito** [haozhu233/kableExtra#129]
Hi, 

I found this issue when running some old code which worked perfectly before. Somehow the html table spit out by kable_styling would output raw html rather than a table. Btw, the vanilla `kable` command worked as usual. 

![image](https://user-images.githubusercontent.com/19360266/35718066-cba324d0-0836-11e8-88f4-007db235d84b.png)

**Comment by haozhu233** [comment]
Hi, @33Vito, I have already addressed this issue in the dev version.

See https://stackoverflow.com/questions/48409288/how-to-show-kable-kableextra-tables-in-r-markdown-notebook-not-just-in-the-knit/48415028#48415028
