### ISSUE TITLE
Can kableExtra solve the repeating header issues for long tables ?

### ISSUE THREAD

**Issue by p-phillips** [haozhu233/kableExtra#13]
Hi

Would it be possible for kableExtra to have a flag/option which forced the header row to repeat on each new page for long tables ?

Pete

**Comment by haozhu233** [comment]
Great idea! I just added a new option `repeat_header` in `latex_options` under `kable_styling`. 

Here is a quick example
```
library(knitr)
library(kableExtra)

dt <- rbind(mtcars, mtcars) 

kable(dt, "latex", longtable = T, booktabs = T) %>%
  add_header_above(c(" ", "a" = 6, "b" = 5)) %>%
  kable_styling(latex_options = "repeat_header")
```

**Comment by p-phillips** [comment]
Excellent. Thanks for that.
That brings up another enhancement question which I shall open an issue for
