### ISSUE TITLE
Weird error when rendering a "striped" kable

### ISSUE THREAD

**Issue by gorkang** [haozhu233/kableExtra#130]
OK, this has been quite difficult to disentangle for me, and I am still not sure what is going on. I managed to simplify the problem enough so maybe you can take a look. I attach a reproducible example: [BUG_kableExtra.zip](https://github.com/haozhu233/kableExtra/files/1696863/BUG_kableExtra.zip)

The gist is that rendering a kable with `kable_styling(latex_options = "striped")` in a.Rmd file after having loaded kableExtra in a different file gives an error similar to:

>     ! Undefined control sequence.
>      l.140 \rowcolors
>      
>      pandoc: Error producing PDF
>      Error: pandoc document conversion failed with error 43

The best way I can explain it is with different scenarios. But first imagine I have two files, `x1.Rmd` and `x2.Rmd`. In both files I load kableExtra, but only in x2.Rmd I use the  `kable_styling(latex_options = "striped")` parameter. I use a third file `script.R` to render the two Rmd's.

## Scenario A) Running these two in this order gives error

```
# In script.R
rmarkdown::render("x1.Rmd")
rmarkdown::render("x2.Rmd")
```

## Scenario B) Running these two in this order gives error
```
# In script.R
library(kableExtra)
rmarkdown::render("x2.Rmd")
```

## Scenario C) Running the same files but reversing the order WORKS
```
# In script.R    
rmarkdown::render("x2.Rmd")
rmarkdown::render("x1.Rmd")
```
    
## Scenario D) Running the same files in the same order but detaching kableExtra first WORKS
```
# In script.R
rmarkdown::render("x1.Rmd")
detach("package:kableExtra", unload=TRUE)
rmarkdown::render("x2.Rmd")
```
I hope this is clear enough, and sorry for the long report. 

Oh, and thanks for this awesome package!

**Comment by haozhu233** [comment]
Hi, @gorkang, I wrote a detailed explanation on SO a while ago. I think it will solve your problem. https://stackoverflow.com/questions/46080853/why-does-rendering-a-pdf-from-rmarkdown-require-closing-rstudio-between-renders/46083308#46083308
