### ISSUE TITLE
Grouped rows with LaTex when using align argument

### ISSUE THREAD

**Issue by ghislainv** [haozhu233/kableExtra#137]
When using the 1L length align argument in knitr::kable such as align="ccc", the pattern is automatically repeated when the format is "latex". This prevent group_rows to work as expected and produces a \multicolumn with too many columns in the .tex file.

In place, the user should indicate align=("c","c","c"). In this case, the pattern is not repeated and \multicolumn uses the right number of columns.

Maybe this should be indicated in the documentation of kableExtra::group_rows().

PS: Thanks for the fantastic kableExtra package. It is very useful !

**Comment by haozhu233** [comment]
Hi, @ghislainv, great suggestion! I will add some notes to the documentation! Thanks!

**Comment by haozhu233** [comment]
I added some notes to the grouped rows section in the PDF vignette. :)
