### ISSUE TITLE
Spacing after fifth row

### ISSUE THREAD

**Issue by tormodb** [haozhu233/kableExtra#139]
Thanks for producing this fantastic package!

I noticed that there is a slight vertical space between every fifth row (when formatted as latex). Is it possible to turn this spacing on or off?

**Comment by haozhu233** [comment]
Hi, @tormodb See this SO question: https://stackoverflow.com/questions/45409750/get-rid-of-addlinespace-in-kable

**Comment by tormodb** [comment]
Great, thanks for the speedy reply!

Tormod



På 23. februar 2018 kl. 21:13:38, Hao Zhu (notifications@github.com<mailto:notifications@github.com>) skrev:

Hi, @tormodb<https://github.com/tormodb> See this SO question: https://stackoverflow.com/questions/45409750/get-rid-of-addlinespace-in-kable

**Comment by haozhu233** [comment]
:)
