### ISSUE TITLE
could you have an option for multipage tables which adds the string "(cont)" (or similar) to the caption ? 

### ISSUE THREAD

**Issue by p-phillips** [haozhu233/kableExtra#14]
If you have a multipage table the caption doesn't differentiate between whether it is the start of the table or a continuation.

could you have an option which adds this requirement ?

thanks again
Pete

**Comment by haozhu233** [comment]
Thanks for the suggestion again. I changed the default behavior of `repeat_header` by replacing the caption with a "... continued" text. You can also define your customized message by using `repeat_header_text` option. I just pushed the changes to github. You can check it out. 🚀

```
library(knitr)
library(kableExtra)
dt <- rbind(mtcars, mtcars) 

kable(dt, "latex", longtable = T, caption="test table", booktabs = T) %>%
  add_header_above(c(" ", "a" = 6, "b" = 5)) %>%
  kable_styling(latex_options = "repeat_header", repeat_header_text = "Table 2 cont.")
```

**Comment by p-phillips** [comment]
Hi Hao

Would it be possible just to add the string "(continued)" (in italics) after the caption ?

So I have a caption on a long table:  

  Table 2: Raw data for individual experiments

I'd like it to say (on the second and subsequent pages):

  Table 2: Raw data for individual experiments (_continued_)

Also, is there some default grouping going on with ktableExtra ?  It appears to be logically grouping my data by the second column.  My data is in groups of 5, and it may be that ktableExtra groups by 5 anyway ?

Awesome package.

**Comment by haozhu233** [comment]
Since not every table has a caption, I was too lazy to write another if statement, but you caught me. lol

Now, I put the caption back in https://github.com/haozhu233/kableExtra/commit/fdec184eb14d0e3be0c0574cc78241df218d6c52. You can try it out. :)

The last point you mentioned is actually a default feature of `knitr::kable` to enhance the looks of long tables. That feature was introduced in 2013 and it has an interesting discussion. You can check it out: https://github.com/yihui/knitr/issues/666

**Comment by p-phillips** [comment]
Beautiful.  That is perfect.  I just ran it on a data set I'm taking to Berlin on Sunday for a meeting, and it works perfectly.

Thanks for this.

I spend a lot of time using table packages (kable, pandoc, tables, xtables etc). Your kableExtra package is terrific - makes a lot of the things we have had to mess around with latex for very easy.

I hope you continue to add features to this.

Pete

**Comment by p-phillips** [comment]
OK - just a slight flaw ...  the gray bars overwrite the title and caption.
![screenshot from 2017-06-08 23-35-49](https://user-images.githubusercontent.com/1607374/26953623-6fe69d74-4ca3-11e7-802f-7ac9290395d6.png)


![screenshot from 2017-06-08 23-36-38](https://user-images.githubusercontent.com/1607374/26953632-8197f1f8-4ca3-11e7-81a2-1cc73796baca.png)

**Comment by haozhu233** [comment]
Haha, thanks for your kind words, @p-phillips ! :) 

Thanks to the last point you raised here, I made a small improvement on the striped rows feature for longtable. Somehow longtable is not as smart as tabular. If you have a caption, you should reverse the order of color code to make it work... Another dirty latex pithole.. 😂
