### ISSUE TITLE
inherit automatic output detection from kable

### ISSUE THREAD

**Issue by maxheld83** [haozhu233/kableExtra#141]
When used inside some `*.rmd`, `knitr::kable()` does not ordinarily require a `format =` argument, because it can infer the correct output format from the runtime environment (inside, say, `rmarkdown::render_site()` and friends).

This is quite convenient, because we can have the same `kable()`s, for *both* PDF and HTML output.

However, kableExtra throws a warning, whenever it does not find a format in `kable()`:

```
1: In kableExtra::kable_styling(., full_width = TRUE, latex_options = c("striped",  :
  Please specify format in kable. kableExtra can customize either HTML or LaTeX outputs. See https://haozhu233.github.io/kableExtra/ for details.
```

I understand that kableExtra does a lot of things that are format-*specific*, but it would still be more convenient if it could work without a warning, and just apply whichever `kableExtra::...` makes sense (which is current behavior).

**Comment by haozhu233** [comment]
See https://github.com/haozhu233/kableExtra/issues/166 for details. With the latest version (on its way to CRAN), when the package is being loaded, the global option for table format is automatically defined. Thanks!
