### ISSUE TITLE
Missing an Apostrophe in Description field preventing a clean devtools::install_github("kableExtra")

### ISSUE THREAD

**Issue by ownalizer** [haozhu233/kableExtra#142]
Thanks for the useful package. I've had some problems doing devtools::git_install("kableExtra")
The problems lie in the Description file I think...

person('Yoni', 'Sidi', role = 'ctb')， <---- line 14 is not the normal comma used by R and causes an error
person('Brian', 'Salzer', role = 'ctb )     <--- line 15 in descrition file is missing an apostrophe after ctb

Which causes this error when I try to use devtools::install_github("kableExtra")

*installing *source* package 'kableExtra' ...
Error : Invalid DESCRIPTION file

Malformed Authors@R field:
  <text>:11:38: unexpected INCOMPLETE_STRING
11:     person('Brian', 'Salzer', role = 'ctb )
12:     )
                                         ^

**Comment by haozhu233** [comment]
Ah, thanks for pointing it out!
