### ISSUE TITLE
devtools::install_github("haozhu233/kableExtra") Installation fails Due to Description File

### ISSUE THREAD

**Issue by ownalizer** [haozhu233/kableExtra#144]
The comma on line 14 of the description file is not the right comma used by R for some reason. This is causing the command devtools::install_github("haozhu233/kableExtra") to fail.

```* installing *source* package 'kableExtra' ...
Error in parse(con, encoding = "UTF-8") : 10:41: unexpected symbol
9:     person('Rob', 'Shepherd', role = 'ctb'),
10:     person('Yoni', 'Sidi', role = 'ctb')?                                            ^
ERROR: installing package DESCRIPTION failed for package 'kableExtra'
```

A very sneaky comma error haha

**Comment by haozhu233** [comment]
Fixed now. Thanks again! I didn't realize it was that comma that caused this issue.
