### ISSUE TITLE
color_bar() in Shiny

### ISSUE THREAD

**Issue by prokulski** [haozhu233/kableExtra#147]
When you use color_bar() and then send table (html) to Shiny's tableOutput() it won't work. I've example:

in ui.R:
```
...
tableOutput("senti_table")
...
```

in server.R:
```
...
      output$senti_table <- function() {
         senti_table %>%
            group_by(category) %>%
            summarise(n = n()) %>%
            ungroup() %>%
            mutate(n = color_bar("lightgreen")(n)) %>%
            knitr::kable("html") %>%
            kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"),
                          full_width = FALSE, font_size = 10)
      }
...
```

Finaly I got table with

```
<span style="display: inline-block; direction: rtl; border-radius: 4px; padding-right: 2px; background-color: lightgreen; width: 100.00%">7</span>
```
in n-column :/

**Comment by haozhu233** [comment]
Hi @prokulski, sorry for this very late reply, I think you forgot to put `escape=F` in your `knitr::kable` step. Also, if you have `full_width = F`, I recommend you to define a column width for the `color_bar` column. If you don't have a defined column width, that column will be very thin.
