### ISSUE TITLE
[Feat. req] Grouping rows the same way like headers

### ISSUE THREAD

**Issue by kn1g** [haozhu233/kableExtra#15]
Hi,

you did awesome work! But why did you implement two different ways to group rows and cols?
I need to group the rows not just once. Like "add_header_above" I need to group the goups again.

Wouldn't it be more consistent to implement a function like "add_rowgroup_left"?

Maybe I did just miss how to do it? Is there a way to group the rows in multiple layers?

Best,
kn1g

**Comment by haozhu233** [comment]
Hi, @kn1g, thank you for your suggestion! The syntax for `add_header_above` is good for adding an entire row/column but `group_rows` is actually trying to use a labeling *row* & some indentations to build the "grouping" look. In this case, using an empty string to indicate some rows don't need grouping doesn't make too much sense. Also, for me, rows are more "dynamic" than columns when I generate tables. With precise index positions, it's a lot easier for users to build a dynamic table with flexible number of rows, especially in shiny: users can quickly check the first column variable to get the index number (at least that's how I was using it). 

Right now, it's not so easy to group rows in multiple layers. I will think about it and see if I should add a `add_rowgroup_left` to add actual columns there. I will leave this issue open.

**Comment by haozhu233** [comment]
I added a new function `add_header_left` to the dev version to achieve this feature. If any of you have any suggestions, please feel free to let me know. 

<img width="465" alt="screen shot 2017-06-15 at 5 18 47 pm" src="https://user-images.githubusercontent.com/7014590/27202304-04b1c3ac-51ef-11e7-9457-f0eff35711a0.png">

**Comment by tkaraouzene** [comment]
Hello ! 
Thank you for your wonderful package
I just have a question, Is it possible to use an existing column as a left_header (with similar values grouped)

Thanks again,
Regards

**Comment by haozhu233** [comment]
Hi, @tkaraouzene, I'm still working on this part. You may expect to see some changes on this function recently. 

I did a little experiment with a function called `collapse_rows()`. I have written the HTML side but the LaTeX part seems too complicated. Is that what you are looking for?

**Comment by tkaraouzene** [comment]
Hi, 

It probably does what I want, however, it doesn't seem to work with me (even in HTML).
Whatever I would use it in LaTeX, so I will just wait...

Thanks again

**Comment by haozhu233** [comment]
Hi, @tkaraouzene, I implemented the `collapse_row` in both HTML and LaTeX now and you can find the documentation in the last section of the doc site (http://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf). You can try it out and let me know what you think. 

Also, with this feature being added, I'm wondering if it's still necessary to keep `add_header_left` cuz they are doing basically the same thing. **For anyone who cares about this feature, please let me know what you think**. 

No matter what, it wraps up `kableExtra` 0.3.0. I'm planning for a CRAN release in the next following days. If any of you have any comments or suggestions, let me know.

**Comment by tkaraouzene** [comment]
Hi, @haozhu233, thanks for your feedback.

I just tried the `collapse_rows` function and it seems to perfectly work within my Rmd files. Nice ! 
However, I am currently writing my Ph.D. and to do that I am using both [bookdown](https://github.com/rstudio/bookdown) and [thesisdown](https://github.com/ismayc/thesisdown) packages and it seems to generate some errors (I am trying to identify) when I am using it. 
By the way, I have the same error when I use the function `column_spec(bold = TRUE)`.

I am trying to find where it comes from, I let you know if I find something.
If you are interested in I joined the log file describing the errors I get: [thesis.log.txt](https://github.com/haozhu233/kableExtra/files/1104522/thesis.log.txt)

Thanks again

**Comment by tkaraouzene** [comment]
@haozhu233 , About `add_header_left_function` I agree with you that `collapse_rows` does basically the same thing. 
So to my mind, there is no matter to continue to maintain it, but it is up to you, of course ^^

**Comment by danmsf** [comment]
Thanks for your package and great job!
I don't know if it's a local problem of mine, but I'm running the dev version and I noticed that `collapse_rows` returns an error `Error: search must be of length 1` when  I only specify 1 column to collapse, but seems to work fine for more than one column.

**Comment by haozhu233** [comment]
@danmsf Thanks for reporting! I just fixed the bug in the latest dev version.

**Comment by danmsf** [comment]
Great!! Thanks.
 By the way , is there a way to change the names of the tables original
coloumn names? If not a simple wrapper around 'names' would do the trick...
Thanks again

**Comment by haozhu233** [comment]
@danmsf if I understand you correctly, you can do it through the col.names option in base kable.

**Comment by danmsf** [comment]
Great thanks!

**Comment by haozhu233** [comment]
For LaTeX `collapse_rows`, I added some extra cline/cmidrule to distinguish rows. Booktab tables with `collapse_rows` now does look different because of the added lines but it helps a lot on reading the table (personally opinion).
