### ISSUE TITLE
Unwanted [t] appearing in PDF above table...

### ISSUE THREAD

**Issue by JeffreyRacine** [haozhu233/kableExtra#153]
Greetings,

Love the package, recently a [t] has started appearing in the PDF output above a table... minimal example follows...

```
---
output: bookdown::pdf_document2
---

```{r setup, include=FALSE}
library(kableExtra)
```

```{r atable,results='asis',echo=FALSE}
foo <- data.frame(matrix(rnorm(10),5,2))
knitr::kable(foo, caption="Notice [t] appearing above table.") %>%
kable_styling(latex_options =  c("hold_position"))
```
```

PDF produced appears below...

[debug.pdf](https://github.com/haozhu233/kableExtra/files/1816705/debug.pdf)

> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-apple-darwin17.4.0/x86_64 (64-bit)
Running under: macOS High Sierra 10.13.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.4.4  backports_1.1.2 bookdown_0.7.1  magrittr_1.5    rprojroot_1.3-2 htmltools_0.3.6 tools_3.4.4    
 [8] yaml_2.1.18     Rcpp_0.12.16    stringi_1.1.7   rmarkdown_1.9.4 knitr_1.20      xfun_0.1        stringr_1.3.0  
[15] digest_0.6.15   evaluate_0.10.1
>

**Comment by yoyoregime** [comment]
Hi.
I also love the package and use it extensively. I also started getting the [t] starting to pop-up as well. At first I thought it was because I recently upgraded the kableExtra package. I downgraded,  but that didn't make the problem go away. On a hunch, I downgraded the knitr package, which I recently upgraded... I reverted to knitr 1.19 and the extra [t] disappeared.

**Comment by JeffreyRacine** [comment]
Greetings,

Thanks for this... did you file and issue for knitr then?

**Comment by haozhu233** [comment]
Hmm, I created this issue in https://github.com/yihui/knitr/pull/1519 as an effort to fix https://github.com/yihui/knitr/issues/1487. I will fix it here.

**Comment by haozhu233** [comment]
Fixed now. Sorry for the delay. :)

**Comment by JeffreyRacine** [comment]
That indeed fixed the issue.

Thanks ever so much for your excellent work and contributions to the community!

**Comment by yoyoregime** [comment]
Awesome, thanks!
