### ISSUE TITLE
Adjacent Identical Values Cause Improper Grouping rows via multi-row cell

### ISSUE THREAD

**Issue by statsandthings** [haozhu233/kableExtra#154]
The following data frame has values of "c" in these two locations: [2, 10] and [2, 11]. These two values of "c" are in adjacent groups, groups "a" and "b". If you generate the data frame this will be easier to see.

```
collapse_rows_dt <- data.frame(C1 = c(rep("a", 10), rep("b", 5)),
                 C2 = c(rep("c", 11), rep("d", 4)),
                 C3 = 1:15,
                 C4 = sample(c(0,1), 15, replace = TRUE))
```

If you use `collapse_rows` on this data frame the "c" from group "a" bleeds into group "b" breaking the table. The first grouping of "c's" should stay in the "a" group and there should be a single "c" group in the "b" group.

```
kable(collapse_rows_dt, "html", align = "c") %>%
  kable_styling(full_width = F) %>%
  column_spec(1, bold = T) %>%
  collapse_rows(columns = 1:2)
```

**Comment by haozhu233** [comment]
Hi, @statsandthings, `collapse_rows` was not designed to identify unique combinations of two columns. You can try the following alternative approach but I'm not sure if this is what you need. 

```
collapse_rows_dt %>%
  mutate(C1 = paste(C1, "-", C2)) %>%
  select(-C2) %>%
  kable("html", align = "c") %>%
  kable_styling(full_width = F) %>%
  column_spec(1, bold = T) %>%
  collapse_rows(columns = 1)
```

**Comment by statsandthings** [comment]
Hello @haozhu233 - that is a good work around. Thanks for the tip.
