### ISSUE TITLE
Missing backslash in help for kable_as_image()

### ISSUE THREAD

**Issue by sjkiss** [haozhu233/kableExtra#155]
In the help for kable_as_image(), include_header_includes requires two backslashes, one as an escape. Currently reads: 

`latex_header_includes A character vector of extra LaTeX header stuff. Each element is a row. You can have things likec("\usepackage{threeparttable}", "\usepackage{icons}")
`
Should read:

`latex_header_includes | A character vector of extra LaTeX header stuff. Each element is a row. You can have things like c("\\usepackage{threeparttable}", "\usepackage{icons}")
`

**Comment by haozhu233** [comment]
Haha, thanks for letting me know. Fixed now.
