### ISSUE TITLE
row_spec(0, align="l") not working for add_header_above rows

### ISSUE THREAD

**Issue by renkun-ken** [haozhu233/kableExtra#156]
![image](https://user-images.githubusercontent.com/4662568/37861434-9c2b1e8c-2f74-11e8-91c8-822b3e8caf67.png)

I use `row_spec(0, align = "l")` with the table above but the alignment does not change. I tried `row_spec(0, underscore = TRUE)` and it works only for the original header row. I'm wondering if there's an easy way to specify alignments to all the header rows no matter it's the original header row or header rows added by `add_header_above`?

**Comment by haozhu233** [comment]
@renkun-ken I added an `align` option to `add_header_above` so now it's easier to set it there. Does it fulfill your need? 
```
kable(mtcars[1:5, 1:5], "latex", booktabs = T) %>%
  kable_styling() %>%
  row_spec(0, align = "l") %>%
  add_header_above(c(" ", "aaa" = 2, "BBB" = 3), align = "l")
```

**Comment by renkun-ken** [comment]
This works perfectly for me. Thanks!
