### ISSUE TITLE
best practice for newline for LaTeX Table with knitr::kable and kableExtra

### ISSUE THREAD

**Issue by EconomiCurtis** [haozhu233/kableExtra#157]
Any advice on best practices for adding new lines with LaTeX tables? 

The following typical "first guesses" lead to errors. And new lines are handled inconsistently between html and pdf. 

``` r

data.frame(
  c1 = c("a","b"),
  c2 = c(1,2),
c3 = c(3,4)
) %>% 
  kable(
    col.names = c("Column\nOne","Column\\Two","Column \newline Three")
  )

```

`add_header_...` offers one option.

**Comment by haozhu233** [comment]
Hi, @EconomiCurtis, I added a new document explaining how to wrap texts/insert linebreaks in LaTeX. Note that the new `linebreak` function described there is only available on github right now. 

http://haozhu233.github.io/kableExtra/best_practice_for_newline_in_latex_table.pdf

**Comment by ABSOD** [comment]
Thanks for this "Best Practice" document.  The suggestions here do not work for my application.  I consistently have tables that are wider than my  (Landscape) page:
For example, this code:
```
f.latextab <- f.educctyTab  %>%
    kable(align=c("lllrrrrr"),
          caption=tab_head, row.names=FALSE,
          format="latex", booktabs=TRUE, col.names = names(f.educctyTab))  %>%
    kable_styling(latex_options="HOLD_position",font_size=10)  %>%
    row_spec(0, align = "c") %>%
    column_spec(1:2, width = "3cm") %>%
    column_spec(3:8, width = "2cm") %>%
    kableExtra::footnote(outCap,threeparttable=T) 
```
which follows the esample from the "Best Practices' document, produces a table wider than the page and does NOT wrap the column names.  

BTW, here are the column names:
 names(f.educctyTab) <- c("Agency/County","Poverty Level","Value", "Less Than High School",
                          "High School Graduate",
                         "Some College, Associates Degree",
                        "Bachelor's Degree or Higher", "Total")
The "linebreak" option described in the document doesn't work either.  I'd apprieceate any ideas to make this work..
