### ISSUE TITLE
kable with %>% inside a for loop keeps generating html pages before the full table is compiled

### ISSUE THREAD

**Issue by lizzyhuang** [haozhu233/kableExtra#160]
This is my sample code. When I clicked "Knit" in RStudio, the 3 tables inside the for loop kept popping up in html pages (so 3 pages generated), before I got my result (a html page with all 3 tables aligned). Is there a way to suppress those unnecessary html pages while compiling?

---
title: "Sample code"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r load-library, echo = F, message = F, warning = F}
library(dplyr)
library(knitr)
library(kableExtra)
library(ggplot2)
options(knitr.table.format = "html")
data(mtcars)
```

```{r echo = F, results = "asis"}
for (i in 1:3) {
  plot(rnorm(10))
  p = kable(head(iris)) %>%
    group_rows(group_label = "test", start = 1, end = 5)  # This is the line that generates all the html
  print(p)
}
```

**Comment by haozhu233** [comment]
can you try to install the github version and let me know the result?

**Comment by lizzyhuang** [comment]
I'm installing the github version now. Before I get to the result, I edited the title, because I just found out it's not about "group_rows", it's about the pipeline "%>%"

I did the following code, and the html pages still popped up before the final result compiled (under the CRAN version of the package)

---
title: "Another sample code"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r load-library, echo = F, message = F, warning = F}
library(dplyr)
library(knitr)
library(kableExtra)
library(ggplot2)
options(knitr.table.format = "html")
data(mtcars)
```


```{r echo = F, results = "asis"}
for (i in 1:3) {
  plot(rnorm(10))
  p = kable(head(iris)) %>%
    kable_styling(bootstrap_options = c("striped", "hover"), full_width = F)  # This is the line that generates all the html
  print(p)
  cat('\n')
}
```
I'll let you know the results of the GitHub version later. Btw, thank you for the package. It's very helpful for reporting.

**Comment by lizzyhuang** [comment]
Sorry, my company machine doesn't allow me to get packages from GitHub. I'll try it tonight when I'm off work. I've changed the title so it's more accurate to the issue. Will let you know the results.

**Comment by haozhu233** [comment]
@lizzyhuang Great! I tried to fix this issue recently by adding some rstudioapi checks but wasn't sure if it got fixed since I can't reproduce this behavior by myself. Thanks for helping me out. :)

**Comment by lizzyhuang** [comment]
@haozhu233 ,
I knitted the Rmd file using the GitHub version of kableExtra (version 0.7.0.9000). It worked for both examples and no html pages popped out. When will this version be released on CRAN? I want to see whether I can use it at work and my company only allows packages from CRAN. Thank you.

**Comment by lizzyhuang** [comment]
@haozhu233 ,
Thank you. That's good enough.
