### ISSUE TITLE
Footnote fontsize in threeparttable

### ISSUE THREAD

**Issue by TrungLeVn** [haozhu233/kableExtra#162]
Dear haozhu233, 
Many thanks for your amazing package. The recent version is really good. 
I just wanna know is there any way to customize the font size of the footnote? I notice that if I choose the "threeparttable" option, the footnote always stays at "\small" fontsize in the Latex source code, no matter which fontsize I choose in the 'kable_styling' option.

Reproducable code: 
`library(knitr)`
`library(kableExtra) `
`options(knitr.table.format = "latex")`
`dt <- mtcars[1:5, 1:6]`
`kable(dt, "latex", align = "c") %>% 
  kable_styling(full_width = F,font_size = 3) %>% 
  footnote(general = "This is a long long long long long long long long long long long long long long long long footnote that I want to reduce font size",threeparttable = T)
`

**Comment by haozhu233** [comment]
Thanks for suggesting this. I will make an option for font size in footnote later. 👍

**Comment by haozhu233** [comment]
I removed the \small tag in threeparttable as it's unnecessary. Thanks!

**Comment by fedemolina** [comment]
You could use something like this:
\\footnotesize whatever you want to write in the footnote....
Instead of \\footnotesize you could change to another option. This works to me!
