### ISSUE TITLE
column_spec() doesn't play nicely with scroll_box()

### ISSUE THREAD

**Issue by ben519** [haozhu233/kableExtra#164]
I would like to use horizontal scrolling when my table is wide (via `scroll_box`). I would also like to be able to specify the width of a particular column (via `column_spec`).  Each of these methods works well on their own, but they don't seem to work together (or I may be using them incorrectly).

For example,

```
df <- data.frame(
  ColumnA = sample(5),
  ColumnB = sample(5),
  ColumnC = sample(5),
  ColumnD = sample(5),
  ColumnE = sample(5),
  ColumnF = sample(5),
  ColumnG = sample(5),
  ColumnH = sample(5),
  ColumnI = sample(5),
  ColumnJ = sample(5)
)

# With only a few columns to render, I get the column width I desire
kable(x = df[, 1:3], format = "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover"), position = "center") %>%
  column_spec(column = 1, width = "30em") %>%
  scroll_box(width = "100%")

# When there are many columns, they seem to be squished before the scroll_box is triggered 
kable(x = df, format = "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover"), position = "center") %>%
  column_spec(column = 1, width = "30em") %>%
  scroll_box(width = "100%")

```

Note that I'm on R version 3.4.3 and kableExtra_0.8.0

Thanks!

**Comment by haozhu233** [comment]
Hi @ben519 , please check out my answer to this SO:
https://stackoverflow.com/questions/46689392/make-html-table-columns-wider-prevent-words-from-wrapping-in-rmarkdown/46691360#46691360

Basically, in your case, you need:
```
kable(x = df, format = "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover"), position = "center") %>%
  column_spec(column = 1, width = "30em; display: inline-block;") %>%
  scroll_box(width = "400px")
```

**Comment by ben519** [comment]
Ah, shoot - I think my example was too simple.  I actually need to specify the width of a few columns.  How would you handle that because this seems to break?

```
kable(x = df, format = "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover"), position = "center") %>%
  column_spec(column = 1, width = "30em; display: inline-block;") %>%
  column_spec(column = 2:5, width = "30em; display: inline-block;") %>%
  scroll_box(width = "100%")
```

Thanks for all the help!

**Comment by haozhu233** [comment]
Thinking about adding a `min-width` to it. 
kable(x = df, format = "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover"), position = "center") %>%
  column_spec(column = 1:5, width = "30em; min-width: 30em;") %>%
  scroll_box(width = "100%")

**Comment by ben519** [comment]
Looks good so far.  Thanks @haozhu233
