### ISSUE TITLE
Experimenting auto_set_format

### ISSUE THREAD

**Issue by haozhu233** [haozhu233/kableExtra#166]
In current CRAN version of kableExtra, you still have to manually set formats for kable at least once. I didn't setup an auto-set-format mechanism because that will turn off kable's default markdown table if `kableExtra` is loaded. Now, since I'm creating more `pre-kable` functions like `cell_spec` or the recent `linebreak`, in the next version, I'm thinking about to be more aggressive for the sake of greater convenience. 

I just added [a few lines of codes](https://github.com/haozhu233/kableExtra/commit/f315512d232b81ee181af8aafb16e7eaca8871a5) which let the dev version of `kableExtra` set the global kable format option automatically upon loading. It will makes our life easier and the following code will be executable in both format. 

```
library(kableExtra)

kable(mtcars) %>%
  kable_styling()
```

I would like to get some ideas from the community. Please feel free to tell me if it's a good idea or totally messed up your code.

**Comment by wibeasley** [comment]
Conceptually, I like how the package leverages an environmental option that may already be set (ie, `knitr.table.format`), but writes & directly uses its own environmental option (ie, `kableExtra.auto_format`).

That seems like a good way to piggy back off another package (in a way that reduces the amount of code the user has to write), while still being coupled loosely enough that (a) you're not interfering with knitr's internals and (b) you're coupled loosely enough that knitr's changes are unlikely to break something in kableExtra code.
