### ISSUE TITLE
Text wrapping and linebreak don't work well together

### ISSUE THREAD

**Issue by triceraflops** [haozhu233/kableExtra#167]
Relating back to this: https://github.com/haozhu233/kableExtra/issues/157

When I add linebreak, the text wrapping is ignored and the text continues off the page.

When I set escape to F, the linebreak is ignored, but the text wrapping works. When I set escape to T, the linebreak works, but the text wrapping does not.

Taking the example from the documentation.

`
  dt2 <- data.frame(
    Item = c("Hello\nWorld this is a very very very very very very very very very very very very very very 
                    very very very very very very very very very very very very very very very very long line", 
                   "This\nis a cat"),
    Value = c(10, 100))

dt2 %>%
  mutate_all(linebreak) %>%
  kable("latex", booktabs=T, escape=F) %>%
  kable_styling(full_width=F, latex_options = c("striped", "scale_down")) %>%
  column_spec(1, width="30em")
`

**Comment by haozhu233** [comment]
Hmm, this is getting complicated. The correct LaTeX approach is to use `\newline` there instead of `makecell`. However, `\newline` will only work in "paragraph" mode (the column alignment thing you setup with column_spec).  Let me think about it and see if there is a better solution.

**Comment by haozhu233** [comment]
All right. With dev version now, it will automatically convert `makecell` to `newline` if necessary. row_spec has also been tested

https://github.com/haozhu233/kableExtra/commit/ae80df4d9890348b87088641caa49b40d2ba7fd3

**Comment by triceraflops** [comment]
Thanks!

**Comment by GalenStocking** [comment]
I'm having a similar problem. I have a \n inside a table, e.g.:
x_v_y \n x_v_z \n x

When I run the following in R Markdown:
df %>% mutate_all(linebreak) %>% kable(format="latex") %>%
   kable_styling(full_width = F)

I get the following in that cell:
\makecell[1] {x_v_y \\ x_v_z \\ x}

I'm on version 0.8.0.0001.

Happy to send some sample data if needed. Thanks!

**Comment by ZellW** [comment]
Curious.  Running this in an RMarkdown code bolock:

df <- data.frame(a="x\ny\nz")
df %>%
  mutate_all(linebreak) %>%
  kable("latex", escape=F) %>%
  kable_styling(full_width = F)

provides not output when rendered in HTML.  How can I get this to work.  The ability to have line feeds in a table cell has been driving me nuts!

**Comment by triceraflops** [comment]
@ZellW
The “latex” part in that code means kable will generate a latex table - which is basically pdf output.

Try changing it to “html”.

You might also want to read the documentation for the kable and kableExtra packages. The documentation for kableExtra is pretty good and has lots of examples.

**Comment by alexmosc** [comment]
> Try changing it to “html”.

This does not work as expected (line breaks in cells).

```
df <- data.frame(a="x\ny\nz")
df %>%
mutate_all(linebreak) %>%
kable("html", escape=F) %>%
kable_styling(full_width = F)
```

**Comment by alexmosc** [comment]
```
df <- data.frame(a="x<br>y<br>z")
df %>%
kable("html", escape=F) %>%
kable_styling(full_width = F)
```

<br> work for html format, and without mutating to linebreak.
