### ISSUE TITLE
Add table width example to documentation

### ISSUE THREAD

**Issue by isteves** [haozhu233/kableExtra#170]
I was struggling with displaying [some very wide tables](https://nceas.github.io/datateam-training/reference/example-solr-queries.html) properly in my bookdown, particularly since I didn't want to specify an exact width (as shown in the [vignette example](https://datateam.nceas.ucsb.edu/rstudio/help/library/kableExtra/doc/awesome_table_in_html.html)). Eventually I came across the solution of using `kableExtra::scroll_box(box_css = "overflow-x: auto")` based on comments in [this Github issue](https://github.com/GitbookIO/gitbook/issues/1626). 

I figured it might be worth adding to the documentation somewhere since I'll probably personally refer to it again, but wanted to run it passed you before doing anything.  Happy to PR if you think it's a good idea!

Full example: 

```
library(tidyverse)
library(knitr)
library(kableExtra)

tibble(rownumber = 1:10,
       extra1 = "some_really_long_file_name",
       extra2 = "some_really_long_file_name",
       extra3 = "some_really_long_file_name",
       extra4 = "some_really_long_file_name",
       extra5 = "some_really_long_file_name",
       extra6 = "some_really_long_file_name",
       extra7 = "some_really_long_file_name") %>% 
  knitr::kable(format = "html") %>% 
  kableExtra::kable_styling() %>% 
  kableExtra::scroll_box(box_css = "overflow-x: auto")
```

**Comment by haozhu233** [comment]
@isteves If I understand it correctly, I think you can also do it by `scroll_box(width="100%")`, correct? Of course, if you do that and don't want the boarder line, you still need to set `box_css` to be `NULL`. :P Yeah, I think it's a good idea to document it out in the vignette, no matter it's the `100%` or `overflow-x: auto`, you can make a decision. Also, when you make changes, please edit the file in the docs folder. I usually only update the vignette folder for CRAN updates. Thanks!

**Comment by isteves** [comment]
Oh didn't think of that, but that seems to be the same!  Sounds good.
