### ISSUE TITLE
Output LaTeX fragment directly?

### ISSUE THREAD

**Issue by zackbh** [haozhu233/kableExtra#176]
Huge fan of using kable + kableExtra. However, I often don't like to live exclusively in .Rnw documents, and it would be great if there were a way to directly write kable output to a .tex file for inclusion into a document? 

I can do this directly with xtable and texreg. But I can't seem to find a way to get kable output to directly write to a .tex file that I can \input{} later into a document. Does this method already exist? Or is it something that could be added?

**Comment by haozhu233** [comment]
I think you can always do following things, correct?
```
kable(mtcars, "latex") %>%
  cat(file = "~/Desktop/aaa.tex")
```
Are there anything you need for these fragments? I'm not very familiar with these workflow. I can definitely add some helper functions (PR are welcome as well) if they are useful.
