### ISSUE TITLE
column_spec() do not take actions in <thead>

### ISSUE THREAD

**Issue by leovan** [haozhu233/kableExtra#177]
I do column_spec(1:2, extra_css = 'display: none;') to hide some columns, but it only take actions in `<tbody>` but not in `<thead>`. I wish we can add a parameter to choose whether it take actions in both `<tbody>` and `<thead>`.

**Comment by haozhu233** [comment]
Sounds good. I will add this option

**Comment by leovan** [comment]
Awesome, thanks a lot @haozhu233.

**Comment by leovan** [comment]
Works fine, really appreciate @haozhu233.
