### ISSUE TITLE
plot multiple bulletpoints 

### ISSUE THREAD

**Issue by bartht** [haozhu233/kableExtra#178]
Hi,

I want to print a table containing lists with bullet points using kableExtra with knitr from R-Markdown. In the result I am trying to create a html.
The first table cell looks fine as is. But in all other cells the allignment of the bullets gets mixed up.
I have looked into the html code and it seems that he closes the unordered list after the first list element. 

![grafik](https://user-images.githubusercontent.com/38650864/39116359-88cb6f2c-46e4-11e8-844d-683d6b793a9a.png)

Since the code I use for both is same and I am quite new to the package I am quite lost. 
So any help or hint in the right direction would be highly appreciated. :)

In my original code I am forced to upload my data via a .csv file. 
But here`s a running example of what I have so far: 

``---
title: "Test Dashboard"
date: 

output: 
    flexdashboard::flex_dashboard:
      orientation: rows
           # self.contained: (TRUE) 
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------
### <b> <font size = "4"> Operative Maßnahmen </font> </b>
```{r echo=FALSE, warning=FALSE, results = 'asis'}
library(kableExtra)

test_import <- data.frame(
  column_1 = c("Random_1", "Random_2"),
  column_2 = c("* Lorem ipsum dolor sit amet, consetetur sadipscing elitr\ \n* Lorem ipsum dolor sit amet, consetetur sadipscing elitr", "* Lorem ipsum dolor sit amet, consetetur sadipscing elitr\ \n* Lorem ipsum dolor sit amet, consetetur sadipscing elitr"),
  column_3 = c("* 4/10 Test_1\ \n* 1/10 Test_2\ \n* 4/5 Test_3", "* 4/10 Test_1\ \n* 1/10 Test_2\ \n* 4/5 Test_3")
)


test_import %>%
  kableExtra::kable("html",escape = F) %>% 
    kable_styling(bootstrap_options = c("striped", "hover")) %>%
    column_spec(2:(ncol(test_import)-1), border_right = T, border_left = T)




``

**Comment by haozhu233** [comment]
I think this is a bug in pandoc when they parse HTML tags in table. If you run the code in console, you will see the markdown list was not converted to HTML and raw HTML code generated by this package are the same for those two rows. I guess there is nothing I can do at least in this package.
