### ISSUE TITLE
add_header_left for other formats

### ISSUE THREAD

**Issue by rabutler** [haozhu233/kableExtra#18]
Hi, it looks like `add_header_left()` is implemented for html and latex in your dev version. Do you plan on extending it to other formats?

Thanks!

**Comment by haozhu233** [comment]
Hi, @rabutler , `kableExtra` in general only supports html/latex tables as only these two formats accept advanced customizations like multirow. If you have a constant need of generating word tables for your collaborators, I would use `pander` instead. 😸

**Comment by rabutler** [comment]
Thanks @haozhu233! Some of my formatting got messed up when I specified the format as html, but my eventual output is html, so I'll play around with it some more. Thanks again.

**Comment by haozhu233** [comment]
@rabutler Great! Feel free to open up another issue for the "messed up" part.
