### ISSUE TITLE
vectorize kableExtra::group_rows to accept a list of groupings

### ISSUE THREAD

**Issue by yonicd** [haozhu233/kableExtra#182]
it would make life easier to have a vectorized version of `kableExtra::group_rows` that would create groupings of rows.

eg

now it is

```
set.seed(123)
test <- data_frame(x=sample(letters[1:4],20,replace = TRUE))%>%arrange(x)

knitr::kable(test,format = 'html')%>%
  kableExtra::kable_styling("striped", full_width = FALSE) %>%
  kableExtra::group_rows("a", 1, 4) %>%
  kableExtra::group_rows("b", 5, 9) %>%
  kableExtra::group_rows("c", 10, 13) %>%
  kableExtra::group_rows("d", 14, 20)
```

instead it would make it more programatic to have it be 

```
#[some named list containing name,start,end]
split_list <- test%>%dplyr::select(x)%>%dplyr::mutate(n=1:n())%>%split(x = .,f=.$x)%>%purrr::map(.f=function(x) range(x$n))

knitr::kable(x,format = 'html')%>%
  kableExtra::kable_styling("striped", full_width = FALSE) %>%
  kableExtra::group_rows(split_list)
```

**Comment by haozhu233** [comment]
Hi, @yonicd, there is one and that argument is called `index`. See http://haozhu233.github.io/kableExtra/awesome_table_in_html.html#group_rows_via_labeling

**Comment by yonicd** [comment]
ah. thanks. sorry for not reading the manual :)

**Comment by haozhu233** [comment]
@yonicd No worries. ;) I kept updating the same doc. It's likely this feature wasn't there when you read it last time :P
