### ISSUE TITLE
Changing alignment of row when width of column is fixed 

### ISSUE THREAD

**Issue by wuffi** [haozhu233/kableExtra#185]
Thanks a lot for writing this useful package and making it available to other people.
Sometimes it would be nice to have the header of a column with fixed width centered.
However, this doesn't seem to be possible:

    ---
    output: pdf_document
    ---

    ```{r echo=F}
      library(kableExtra)
      x <- matrix(1:4, ncol=2)
      knitr::kable(x, col.names=c('Long header', 'Long header'), align = 'r', "latex") %>%
        row_spec(0, align = 'c') %>%
        column_spec(1, width='4em')
    ```

It would be great, if this would work.

**Comment by haozhu233** [comment]
Hi, @wuffi, this feature has been added in the dev version. (See https://github.com/haozhu233/kableExtra/issues/180). Also, you need to specify `column_spec` first before you run `row_spec` to set the alignment.

**Comment by wuffi** [comment]
Dear Hao,
Thank you so much for your quick reply and implementing this feature.
