### ISSUE TITLE
disable underscore escape in html format

### ISSUE THREAD

**Issue by yonicd** [haozhu233/kableExtra#186]
how do i disable the underscore escape in the html output?

![screen shot 2018-04-26 at 14 56 39](https://user-images.githubusercontent.com/1755487/39326168-25fa072a-4962-11e8-9735-a4fb82a80d25.png)

**Comment by yonicd** [comment]
yeah... i think that when you force it to html style it causes problems in the github_doc compiler

**Comment by haozhu233** [comment]
Hmm, wait, I tried it out again on my laptop with R3.5 and all new r packages and the bug is gone. Err....

When I reproduced the bug, it was on a linux server with R 3.4.2 with latest version of packages. How about you?

**Comment by chendaniely** [comment]
Confirming that the switch from R 3.4.4 to  R 3.5 (3.5.3) resolved this issue, weird.

But I'm on different machines with also different versions of pandoc.

The version of pandoc on my R 3.4.4 is pandoc 1.17

The version of pandoc on my R 3.5.3 is 2.7

**Comment by hsmith9002** [comment]
I also have this issue. I have no problems with my iMac running R 3.5.2, but I have the escape issue described above on my laptop running R 3.6.1. This indeed seems like a version issue, but is it an issue with R version, knitr version, or pandoc version?
