### ISSUE TITLE
Warning message triggered by `row_spec(1, hline_after=T)`

### ISSUE THREAD

**Issue by wuffi** [haozhu233/kableExtra#188]
Dear Hao,
Sorry for disturbing you. The last line in the following function call gives me an error message with the latest development version, which is actually hard to interpret:

    ---
    output: pdf_document
    ---
    
    ```{r echo=F}
      library(kableExtra)
      x <- matrix(1:4, ncol=2)
      knitr::kable(x, col.names=c('Long header', 'Long header'), align = 'r', "latex") %>%
        row_spec(0, align = 'c') %>%
        column_spec(1, width='4em') %>%
        row_spec(1, hline_after = T)
    ```

Don't worry too much about, it is not a very urgent thing. My feeling is, that the message can actually be ignored.

**Comment by haozhu233** [comment]
Fixed now. Thanks!
