### ISSUE TITLE
Adding cmidrule to table

### ISSUE THREAD

**Issue by wuffi** [haozhu233/kableExtra#189]
The feature for collapsing cells adds the `cmidrule` from the *booktabs* package.
It would be great, if it would be generally possible to add a `cmidrule` between two rows.

**Comment by haozhu233** [comment]
Hi, @wuffi is this what you are looking for?
https://github.com/haozhu233/kableExtra/blob/master/R/row_spec.R#L32-L33

**Comment by wuffi** [comment]
Hi Hao,
A `cmidrule` would be different from `hline_after`, because `cmidrule` also adds space between two rows, whereas `hline_after` squeezes in a horizontal line.  
In short, `cmidrule` looks in many cases probably a bit more elegant.

**Comment by jjchern** [comment]
One solution is to use the `extra_latex_after` argument in the `row_spec()` function. Below is an example for adduing `\cmidrule`:

```R
library(kableExtra)

mtcars[1:3, 1:3] %>% 
    kable("latex", booktab = TRUE) %>% 
    row_spec(2, extra_latex_after = "\\cmidrule(l){2-3}")

#> \begin{tabular}{lrrr}
#> \toprule
#> & mpg & cyl & disp\\
#> \midrule
#> Mazda RX4 & 21.0 & 6 & 160\\
#> Mazda RX4 Wag &  21.0 &  6 &  160\\
#> \cmidrule(l){2-3}
#> Datsun 710 & 22.8 & 4 & 108\\
#> \bottomrule
#> \end{tabular}
```

**Comment by wuffi** [comment]
Thank you so much for your answer. This is exactly, what I was looking for.
