### ISSUE TITLE
auto index for group_rows

### ISSUE THREAD

**Issue by larmarange** [haozhu233/kableExtra#193]
When working with categorical variables and presenting bivariate or multivariate statistics, I usually have several rows per variable. In my tables, I have therefore o column indicating the variable and a second for the considered term or modality.

An option is to use `collapse_rows`. However, I usually find that `group_rows` provide a more readable result. However, it requires to manually compute the index named vector indicator how to group rows. It would be much easier to have an automatic ways of generating this index.

I'm using the following trick:

```r
auto_index_group_rows <- function(x) {
  lx <- dplyr::lead(x)
  
  index <- c()
  name <- c()
  n <- 0
  for (i in 1:length(x)) {
    n <- n + 1
    if (!identical(x[i], lx[i]) | i == length(x)) {
      index <- c(index, n)
      name <- c(name, x[i])
      n <- 0
    }
  }
  names(index) <- name
  index
}
```

```
> x <- c("a", "a", "a", "b", "b", "a", "c", "c")
> auto_index_group_rows(x)
a b a c 
3 2 1 2 
```

allowing to generate automatically the index vector: `group_rows(index = auto_index_group_rows(tab$var))`

I would wonder if such similar features would be relevant to be implemented directly in `kableExtra`?

**Comment by haozhu233** [comment]
Hi, @larmarange, I added an `auto_index()` function using the mechanism I was using in `collapse_rows`. 

Check it out: https://github.com/haozhu233/kableExtra/blob/master/R/group_rows.R#L198-L212

**Comment by larmarange** [comment]
Thanks a lot

**Comment by geotheory** [comment]
An example of usage would be really helpful.  Is there any way to avoid having to use a new `group_rows(...)` call for each group?  Ideally group_rows would be able to self-wrap around a variableso you could simply call:

    kable(iris, format = "html") %>% group_rows(var = 'Species')
