### ISSUE TITLE
Automatic indent in grouped rows not working when using escape

### ISSUE THREAD

**Issue by spotlight19** [haozhu233/kableExtra#195]
Hi haozhu233!  

When rows are grouped using `group_rows()` the rows are automatically indented with `\hspace{1em}`.
However, in one the row names I am using superscript (to add a footnote). For this I am using `escape = F`.
For this row, \hspace{1em} is not added and the row is consequently not indented like other rows. Below is a sample code:

`library(kableExtra)`
`at2=cbind(1:5,6:10,11:15)`
`rownames(at2)=c("one", "two", "three", "four$^1$", "five")`
`kable(at2,format = "latex",booktabs=T,escape = FALSE,col.names = month.abb[1:3])%>%`
`group_rows("group1",1,2)%>%`
`group_rows("group2",3,5)`

Result:
![image](https://user-images.githubusercontent.com/16651544/39686483-e96d953c-51e6-11e8-9b00-2213e1e4f9bf.png)

I tried to add indent separately also the particular row name but that is not working. Another problem encountered is I am unable to use "&" and "$" in row name (tried \\& and \\$, but didn't work).

**Comment by haozhu233** [comment]
For your 2nd question, You just have to double escape it. I will look into the indent problem

```
library(kableExtra)
at2=cbind(1:5,6:10,11:15)
rownames(at2)=c("one", "two", "three", "four$^1$", "five")
kable(at2,format = "latex",booktabs=T,escape = FALSE,col.names = month.abb[1:3])%>%
group_rows("group1\\\\&",1,2, escape = F)%>%  # <- Here
group_rows("group2",3,5)
```

**Comment by haozhu233** [comment]
Fixed now. Thanks!
