### ISSUE TITLE
some Font Color added header hack

### ISSUE THREAD

**Issue by dcbm** [haozhu233/kableExtra#198]
I have added locally a possibility to change the font color in `add_header_above`, which was a big cascade down to `htmlTable_new_header_generator` and `pdfTable_new_header_generator`. 

-  `htmlTable_new_header_generator`: in ` if (trimws(x[1]) == "") {...} else {paste0` in the `html`-string `style=\"color: ",color, "; "` where `color` is a parameter of the function

- `pdfTable_new_header_generator`: in `header_items <- ...` an updated line with           
`"\\\\color{", color,"}{", x[1], "}}")`, again `color` is a parameter of the generator function

For the `html_output` I use a hex code like #00A591 and for latex I define my colors in a styles.tex for generating a pdf with rmarkdown.

**Comment by haozhu233** [comment]
emm, so what is the problem here?
