### ISSUE TITLE
Adding footnote to header with column span > 1

### ISSUE THREAD

**Issue by amilesj** [haozhu233/kableExtra#202]
I am having trouble adding a footnote to a header with a column span > 1. It works with a column span of 1, with the following: 
```
kable(table4, 
  format = "latex", 
  booktabs = T,
  escape = F) %>%
  add_header_above(header = c("header1", "header2" = 2,  paste0("header3", "\\\\textsuperscript{a}")), escape = F)

```
But I want the header with the footnote (header3 in my example) to span 2 columns, so I added a `= 2` after the call to `paste0`, as shown below: 

```
kable(table4, 
  format = "latex", 
  booktabs = T,
  escape = F) %>%
  add_header_above(header = c("header1", "header2" = 2,  paste0("header3", "\\\\textsuperscript{a}") = 2), escape = F)

```

it fails and says `Error in parse(text = x, srcfile = src) : <text>:24:115: unexpected '='`

I am not sure if I am doing something wrong, or if this is a bug, but any suggestions would be appreciated!

**Comment by haozhu233** [comment]
Hi, @amilesj, the thing in `add_header_above` is a named vector and you just can't use paste for the names of the vector (check it out: `c(paste0("a", "b") = "a")`). You can either define the header outside of the pipes or use `setNames`

```
kable(table4, 
  format = "latex", 
  booktabs = T,
  escape = F) %>%
  add_header_above(header = setNames(c(1, 2, 2), c("header1", "header2",  paste0("header3", "\\\\textsuperscript{a}"))), escape = F)
```

**Comment by amilesj** [comment]
Ah, got it. I ended up defining the header outside of the pipes and it worked well. Thank you for the quick reply!
