### ISSUE TITLE
How do I color the text and background on add_header_above()

### ISSUE THREAD

**Issue by thatoipadmaja** [haozhu233/kableExtra#203]

**Comment by haozhu233** [comment]
I will add those options to `add_header_above()`

**Comment by thatoipadmaja** [comment]
Thanks a lot.. Kindly share the details of the options once you are done adding those options. It would be also great if each cell of the header could be colored differently also to represent the group.

**Comment by haozhu233** [comment]
After quite a while, I just added these features to `add_header_above`. :P Please check it out. 

An example:
https://github.com/haozhu233/kableExtra/blob/master/tests/visual_tests/add_header_above_html.Rmd#test-table-1
