### ISSUE TITLE
default footnote general_title is not APA style

### ISSUE THREAD

**Issue by jpritikin** [haozhu233/kableExtra#204]
It is currently "Note:" with a colon, but APA style dictates "Note." with a period.

**Comment by haozhu233** [comment]
"Note. " looks strange in tables with few footnotes, especially in HTML. After all, this package is not built for APA style.

**Comment by jpritikin** [comment]
You obviously do not regard APA style with profuse veneration. Shame on you. :-P

**Comment by haozhu233** [comment]
:-P
