### ISSUE TITLE
Copy README material to package documentation

### ISSUE THREAD

**Issue by wibeasley** [haozhu233/kableExtra#21]
You have a nice narrative in the repo's readme file.  Consider copying some of that to the documentation.  Specifically the [page dedicated to the entire package](https://github.com/haozhu233/kableExtra/blob/master/R/kableExtra-package.R).  I was about to start that, but I didn't want it to look like I wrote the material.

If you don't want to maintain duplicated material, maybe include a link (from the doc to the readme).  

I sometimes forget that nonvocal majority of R users know only CRAN, and not CRAN+GitHub.  A few days ago, I was recommending your package (to an analyst who works in a bank).  His institution currently blocks access to all of GitHub (including the normal website).  For people like that, the CRAN documentation is their only real option.

**Comment by haozhu233** [comment]
That is a great point! I'll do it once I got some time later today. Thanks for your suggestion! 👍👍👍

**Comment by haozhu233** [comment]
I just transferred some README docs to the package level documentation. Thanks again for your suggestion! :)
