### ISSUE TITLE
Cannot escape LaTeX macros in footnote

### ISSUE THREAD

**Issue by jvcasillas** [haozhu233/kableExtra#210]
When using LaTeX macros in a `kable` table, the argument `escape=FALSE` removes automatic escape characters and existing macros in the table compile correctly given that the `\` is escaped: `\\`. When setting `escape=FALSE` inside of `footnote()` I get errors when trying to escape. For example: 

```
kable(head(mtcars), format = 'latex') %>% 
  footnote(., escape = F,  "blah blah \\%")
```

Produces the following...

```
\multicolumn{12}{l}{\textbf{Note: } }\\
\multicolumn{12}{l}{blah blah %}\\
```

which throws an error when compiling.

**Comment by haozhu233** [comment]
I guess I should document it somewhere.... due to the mechanism of this package, you should use \\\\\\\\ to escape.

**Comment by jvcasillas** [comment]
Perfect. Thank you.
