### ISSUE TITLE
long html output in Rstudio from kableExtra::kable_styling()

### ISSUE THREAD

**Issue by joepowers16** [haozhu233/kableExtra#212]
In RStudio, kableExtra::kable_styling() produces excessively long html output that clutters the RMarkdown notebook. Is there anyway to suppress the html output within the RMarkdown notebook? 

Here is a reprex that produces long html output:
library(dplyr)
library(knitr)
library(kableExtra)

mtcars %>% 
  group_by(cyl, am, vs) %>% 
  summarise(mpg = mean(mpg)) %>% 
  knitr::kable(format = "html") %>% 
  kableExtra::kable_styling()

**Comment by haozhu233** [comment]
emm, yeah, it was working before. I will look into that over the weekend.

**Comment by joepowers16** [comment]
Works great now. Sorry for not closing this issue sooner.
