### ISSUE TITLE
cell_spec not working in kableExtra V 0.9.0

### ISSUE THREAD

**Issue by ITReuben** [haozhu233/kableExtra#217]
Hi there,

I'm attempting to use the cell_spec function in kableExtra v 0.9.0. I have had no issues using version 0.8.0, but when attempting to knit a HTML table the span tags used in the cell_spec are formatting as character entity references (i.e. &lt and &gt), resulting in the table not rendering.

`df <- head(cars)`

`df <- dplyr::mutate(df, speed = ifelse(speed == 4, `
                     `     kableExtra::cell_spec(speed, "html", color="red"),`
                     `     kableExtra::cell_spec(speed, "html", color="blue")))`

`knitr::kable(df, format="html")`

The images below shows the output of my markdown file, and the output to the console respectively.
![kableextra_bug](https://user-images.githubusercontent.com/39154596/41363576-278d5976-6f2c-11e8-8518-996c5bf5d884.png)

![kableextra_bug](https://user-images.githubusercontent.com/39154596/41363668-69bf8b34-6f2c-11e8-82f8-0e03492f7882.png)

Thanks,
Reuben

**Comment by haozhu233** [comment]
Can you try to put `escape=F` in your `kable` statement? like `kable(df, escape = F)`

**Comment by cityhunter007** [comment]
I have the same issue - anybody else?
