### ISSUE TITLE
Collapse_rows gives "could not find function xpath__element" error in V 0.9.0

### ISSUE THREAD

**Issue by davoodip** [haozhu233/kableExtra#218]
The code below worked for me in V 0.7.0 of the kableExtra package, but when it gives me an error when I run it in V 0.9.0.

`x <- kable(y) %>% 
kable_styling(c("striped","bordered","condensed")) %>% 
collapse_rows(columns = 1) %>% 
add_header_above(c(" " = 2, "April 2018" = 4, "October 2018" = 4, "April 2019" = 4, "October 2019" = 4)) `

The error is...
`Error in xpath_element(<S4 object of class "Element">) : could not find function "xpath_element"`

When I take out collapse_rows(), the code works, so that seems to be what is causing this issue, and I have no idea what this reference to the xpath_element function is because I do not use it anywhere. Could you please help me try to resolve this issue? Thanks!

**Comment by haozhu233** [comment]
I didn't use `xpath_element` anywhere either. I think it could be a `xml2` internal function. Could you try to update `xml2` to its latest version and see if it solves this problem?

**Comment by haozhu233** [comment]
@davoodip Great! That makes me wonder if I should increase the version requirement for `xml2`.. 🤔
