### ISSUE TITLE
Using `cell_spec` stops `digits`  argument from working

### ISSUE THREAD

**Issue by RichardJActon** [haozhu233/kableExtra#219]
When you use a function like `cell_spec` that adds raw HTML/LaTeX to the dataframe before you pass it to `kable` the `digits` arguments of cable stops working. (see the examples below)

```
data.frame("t"=c(1.39,2.01684065,3.64055),"t1"=c(1.39,2.01684065,3.64055),"a"=c("a","b","c")) %>% 
	mutate(t = cell_spec(t,color = if_else(t < 2,"red","grey"))) %>%
	kable(escape = FALSE,digits = c(2,3)) %>% 
	kable_styling(bootstrap_options = c("striped"))
```

<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> t </th>
   <th style="text-align:right;"> t1 </th>
   <th style="text-align:left;"> a </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> <span style="     color: red;">1.39</span> </td>
   <td style="text-align:right;"> 1.390 </td>
   <td style="text-align:left;"> a </td>
  </tr>
  <tr>
   <td style="text-align:left;"> <span style="     color: grey;">2.01684065</span> </td>
   <td style="text-align:right;"> 2.017 </td>
   <td style="text-align:left;"> b </td>
  </tr>
  <tr>
   <td style="text-align:left;"> <span style="     color: grey;">3.64055</span> </td>
   <td style="text-align:right;"> 3.641 </td>
   <td style="text-align:left;"> c </td>
  </tr>
</tbody>
</table>

```
data.frame("t"=c(1.39,2.01684065,3.64055),"t1"=c(1.39,2.01684065,3.64055),"a"=c("a","b","c")) %>% 
	kable(escape = FALSE,digits = c(2,3)) %>% 
	kable_styling(bootstrap_options = c("striped"))
```

<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> t </th>
   <th style="text-align:right;"> t1 </th>
   <th style="text-align:left;"> a </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 1.39 </td>
   <td style="text-align:right;"> 1.390 </td>
   <td style="text-align:left;"> a </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2.02 </td>
   <td style="text-align:right;"> 2.017 </td>
   <td style="text-align:left;"> b </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 3.64 </td>
   <td style="text-align:right;"> 3.641 </td>
   <td style="text-align:left;"> c </td>
  </tr>
</tbody>
</table>

Guessing wildly I suppose to fix this `kable` would have to parse the HTML/LaTex and find the numbers to round so could be tricky? but it would be useful to have some kind of rounding option in `cell_spec` itself as an interim solution.

**Comment by haozhu233** [comment]
Hi, @RichardJActon, a quick and easy solution for this is to use round directly in cell_spec. For example, in your case, inside the mutate function,

t = cell_spec(round(t, 3), ...)

**Comment by RichardJActon** [comment]
Thanks @haozhu233  - good point
