### ISSUE TITLE
Multiple column_specs don't work when outputting to LaTeX

### ISSUE THREAD

**Issue by stulacy** [haozhu233/kableExtra#222]
I've been trying to colour my columns in different colours using `column_spec` as the following MWE shows, however, only the first column spec is obeyed and the latter are ignored.

```{r}
library(knitr)
library(kableExtra)
library(dplyr)
```

```{r}
head(airquality) %>%
    kable("latex") %>%
    column_spec(1, color='white', background='#FF0000') %>%
    column_spec(2, color='white', background='#00FF00')
```

We can see in the output LaTeX that the first colour has been applied but not the second

`
\begin{tabular}{>{\leavevmode\color{white}\columncolor[HTML]{FF0000}}r|r|r|r|r|r}
`

Is there any way around this? Currently I'm manually editing the LaTeX, but I'd much prefer a solution within R so I can just press Knit. I'm on kableExtra_0.9.0 if that helps.

The screenshot below shows the resulting output.
![testing_kableextra](https://user-images.githubusercontent.com/10225071/41964756-c65e67e0-79f2-11e8-8e55-8c2664d49834.png)

**Comment by haozhu233** [comment]
Thanks! It looks like a bug that happens when you use HTML color code for background.... I will look into that. In the mean time, try to use the original latex color code. http://latexcolor.com/

**Comment by stulacy** [comment]
Using LaTeX color code works perfectly, I should have been doing this from the start.
Here's a MWE in case it helps anyone in the future who wants to use RGB values in LaTeX.  Firstly, define the colors in your YAML header.
```

output: pdf_document
header-includes:
    - \definecolor{myred}{RGB}{248,101,112}
    - \definecolor{myyellow}{RGB}{196,149,10}
    - \definecolor{mygreen}{RGB}{12,194,48}
```

Then you can simply refer to these colors by their name.

```
head(airquality) %>%
    kable("latex") %>%
    column_spec(1, color='white', background='myred') %>%
    column_spec(2, color='white', background='myyellow') %>%
    column_spec(3, color='white', background='mygreen')
```
