### ISSUE TITLE
group_rows bold text with subscript

### ISSUE THREAD

**Issue by pontusps** [haozhu233/kableExtra#224]
Hi, 

I really love this package, and I've been using it a lot to create beautiful tables for all my .Rmd pdfs!  😃 
I was wondering if it is possible to add **bolded text**, with <sub>**subscript**</sub>, to the `kableExtra::group_rows` group-label? 

I seem to get it to work using the latex bm-package in the `caption()` argument for `knitr::Kable`.  But not for `kableExtra::group_rows`. 

Below is the ( needs "header-includes:  - \usepackage{bm}" in the YAML header to reproduce in Rmd)

```
library(tidyverse)

knitr::kable( mtcars[1:4,1:4], format = 'latex',  
              booktabs = T,
              escape = F, 
              caption = 'All the $\\bm{Cars_{sub}}$ in the world.') %>%
  kableExtra::group_rows('$\\bm{RowA_{sub}}$',1,2, escape = F) %>%
  kableExtra::group_rows('$\\bm{RowB_{sub}}$',3,4, escape = F) 
```
Gets me this: 

<img width="342" alt="with_bm" src="https://user-images.githubusercontent.com/17905551/42332029-4ca401f4-8077-11e8-9ace-1465d64c162d.png">

Removing the "\\bm" in `kableExtra::group_rows`... 

```
library(tidyverse)

knitr::kable( mtcars[1:4,1:4], format = 'latex',  
              booktabs = T,
              escape = F, 
              caption = 'All the $Cars_{sub}$ in the world.') %>%
  kableExtra::group_rows('$RowA_{sub}$',1,2, escape = F) %>%
  kableExtra::group_rows('$RowB_{sub}$',3,4, escape = F) 
```
gets me this: 

<img width="323" alt="without_bm" src="https://user-images.githubusercontent.com/17905551/42332054-5be33b76-8077-11e8-825b-38c150204ef1.png">

Just removing the subscript makes the group-label bold ofc, but I would really like to include both bolded text and bolded subscript-text (or a bolded math-symbol). Is there anyway to have both **bold text** and <sub>**subscript**</sub>, just like in caption() from `knitr::Kable()`, that I'm missing? 

Thanks a lot for an amazing package!

**Comment by haozhu233** [comment]
Haha, sorry for the confusion. Due to the mechanism of how `kableExtra` works, you actually need `\\\\` to do all escaping in `kableExtra` latex functions. 

Also, you may like the `usepackage_latex` function in this package. In this case, you can add `usepackage_latex("bm")`some where in the document

**Comment by pontusps** [comment]
Awesome, thanks a lot!
