### ISSUE TITLE
Adding header as a simple vector

### ISSUE THREAD

**Issue by royfrancis** [haozhu233/kableExtra#225]
In your example to add grouped header

```
kable(dt) %>%
  kable_styling("striped") %>%
  add_header_above(c(" " = 1, "Group 1" = 2, "Group 2" = 2, "Group 3" = 2))

```
The grouped header labels are provided as a named vector:

```
> c(" " = 1, "Group 1" = 2, "Group 2" = 2, "Group 3" = 2)
        Group 1 Group 2 Group 3 
      1       2       2       2 
```

Is it not possible to provide a simple vector equal tot he number of columns?

`c("","Group 1","Group 1","Group 2","Group 2","Group 3","Group 3")`

I am creating a table programmatically, where I do not know in advance the exact number of columns.

My current solution is to use `rle()` to get the groups and counts.

```
> rle(c("","Group 1","Group 1","Group 2","Group 2","Group 3","Group 3"))
Run Length Encoding
  lengths: int [1:4] 1 2 2 2
  values : chr [1:4] "" "Group 1" "Group 2" "Group 3"
```

I think this could be simplified.

**Comment by haozhu233** [comment]
Emm, `rle` is what I was using in `collapse_rows`. I mean I can add this kind of functionality and add a switch to control it. However I sort of feel like users can easily write their own wrapper function to do the conversion if they have such a need. It may not seem to worth it to add this functionality while making things complicated...
