### ISSUE TITLE
Hide column names

### ISSUE THREAD

**Issue by royfrancis** [haozhu233/kableExtra#226]
Imagine I have a data.frame like this

```
x <- data.frame(head=c("g","g","p","p"),type=c("a","b","b","a"),num=c(2,5,3,8),class=c("k","k","m","n"))
x

  head type num class
a    g    a   2     k
b    g    b   5     k
c    p    b   3     m
d    p    a   8     n
```

I have many columns and few rows, so I wish to display it in horizontal format. So I add some fake row names.

`rownames(x) <- letters[1:nrow(x)]`

And transpose the table

```
x1 <- as.data.frame(t(x))
x1

      a b c d
head  g g p p
type  a b b a
num   2 5 3 8
class k k m n
```

Now I want to have grouped labels 'head' on top and remove 'head' it from the table.

```
x1[2:5,] %>%
  kable(format="html") %>%
  kable_styling("striped") %>%
  add_header_above(c(" "=1,"g"=2,"p"=2))
```

![temp1](https://user-images.githubusercontent.com/5083500/42410076-6e306cd6-81e4-11e8-8f7a-74dff2184963.png)

How do I get rid of the temporary column names: a, b, c etc?
Thanks.

**Comment by haozhu233** [comment]
Sorry, I guess there is no easy solution for this request.

**Comment by eupimenta** [comment]
I've the same issue. Any solution?

**Comment by eupimenta** [comment]
I think we could rename the colnames with the values in row number one, and then make sure that this column (which now received the row right below) is formatted with the same font style of the below rows. 

The other solution that i think it might be more interesting, is to add a parameter to _kable_ function that aloud the user to "Hide" the native column names of the data frame.
![kable_table](https://user-images.githubusercontent.com/10904011/82622233-a3561380-9bb3-11ea-9e6b-a430b2ef5d6c.PNG)
