### ISSUE TITLE
Horizontal lines for HTML

### ISSUE THREAD

**Issue by jgellar** [haozhu233/kableExtra#230]
I've been trying to add a horizontal line to an HTML table using `row_spec(rownum, hline_after = TRUE)`, but it's not showing up. Is it true that there is currently not a way to do this for HTML?

**Comment by haozhu233** [comment]
There is but it's not out-of-box though. 

```
kable(mtcars) %>% kable_styling() %>% row_spec(1, extra_css = "border-bottom: solid;")
```
