### ISSUE TITLE
Error loading the kable Extra package

### ISSUE THREAD

**Issue by Farzana-Jahan** [haozhu233/kableExtra#232]
Hi, I installed the kableExtra package as: 
 install.packages("kableExtra")
After installation when I load 
library(kableExtra)
 in my markdown document script it is giving the following error:
Error: package or namespace load failed for ‘kableExtra’:
 .onLoad failed in loadNamespace() for 'kableExtra', details:
  call: NULL
  error: 'is_latex_output' is not an exported object from 'namespace:knitr'
In addition: Warning message:
package ‘kableExtra’ was built under R version 3.5.1 

Can you please tell me why this is happening and how to solve it?

**Comment by christinabrady** [comment]
I've updated knitr to 1.17 and am still having this problem. I'm using R 3.4.4 on Windows 7.

**Comment by Farzana-Jahan** [comment]
Please update R to its latest version, 3.5.2, it will work. It also works on R 3.5.1, but it will not work in 3.4.4. Thanks.

**Comment by maormilgrom** [comment]
Hi,
I'm also having a problem loading the package.
I get the following message:

Error: package or namespace load failed for ‘kableExtra’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]): namespace ‘rlang’ 0.4.1 is already loaded, but >= 0.4.5 is required

I run R version 3.6.1, and have updated knitr. 

Thanks for your help.

**Comment by hongyunsoo** [comment]
Hi,
I am also having the same issue while loading the package.
I have tried uninstalling and reinstalling the package, uninstalling and reinstalling both R and RStudio, and updated all the packages. None of it has worked so far. Currently, I am using R version 4.0.3. The exact message is after library(kableExtra) is:

Error: package or namespace load failed for ‘kableExtra’ in readRDS(nsInfoFilePath):
 error reading from connection
In addition: Warning message:
In readRDS(nsInfoFilePath) : error reading the file

Thanks for all your help.

**Comment by wangariJM** [comment]
Hi 
I am having this issue
processing file: doc.Rmd
                                                                                                             

Quitting from lines 20-22 [setup] (doc.Rmd)
Error:
! package or namespace load failed for 'kableExtra':
 .onLoad failed in loadNamespace() for 'kableExtra', details:
  call: !is.null(rmarkdown::metadata$output) && rmarkdown::metadata$output %in% 
  error: 'length = 2' in coercion to 'logical(1)'
Backtrace:
 1. base::library(kableExtra)
 2. base::tryCatch(...)
 3. base (local) tryCatchList(expr, classes, parentenv, handlers)
 4. base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5. value[[3L]](cond)
Execution halted
