### ISSUE TITLE
newline latex table 

### ISSUE THREAD

**Issue by koliajaykr** [haozhu233/kableExtra#233]
I'm not sure what is wrong here
`dt2 <- data.frame(
Item = c("Hello\nWorld", "This\nis a cat"),
Value = c(10, 100)
)`

`dt2 %>%
mutate_all(linebreak) %>%
kable("latex", booktabs = T, escape = F,
col.names = linebreak(c("Item\n(Name)", "Value\n(Number)"), align = "c"))`

because output as latex table is this
![screenshot from 2018-08-07 16-50-07](https://user-images.githubusercontent.com/28312545/43773102-361acb34-9a62-11e8-931e-030311244e0b.png)

**Comment by koliii** [comment]
It may help, html table output for the above code is:
![screenshot from 2018-08-07 17-11-47](https://user-images.githubusercontent.com/28312545/43773981-2c0b4828-9a65-11e8-8c7c-5795aa21c100.png)

**Comment by vincentarelbundock** [comment]
Looks fine on my computer using the latest github master. Please supply a fully reproducible example in a new issue if you still have problems.
