### ISSUE TITLE
row_spec() drops an empty cell

### ISSUE THREAD

**Issue by jjchern** [haozhu233/kableExtra#235]
Suppose the table of interest has a row (see row 1 below) that contains two (or more) empty cells:

```R
library(tidyverse)
library(kableExtra)

mtcars[1, 1:3] %>% 
     add_row(.before = 1, mpg = "Group 1", cyl = "", disp = "")

#>       mpg cyl disp
#> 1 Group 1         
#> 2      21   6  160
```

The LaTeX code (see below) for the first row below the column names has two "&" signs: `Group 1 &  & \\`. 

```R
mtcars[1, 1:3] %>% 
    add_row(.before = 1, mpg = "Group 1", cyl = "", disp = "") %>% 
    kable("latex")

#> \begin{tabular}{l|l|l}
#> \hline
#> mpg & cyl & disp\\
#> \hline
#> Group 1 &  & \\
#> \hline
#> 21 & 6 & 160\\
#> \hline
#> \end{tabular}
```

Adding `row_spec(1, bold = TRUE)`, however, drops one of the two "&" signs:

```R
mtcars[1, 1:3] %>% 
    add_row(.before = 1, mpg = "Group 1", cyl = "", disp = "") %>% 
    kable("latex") %>% 
    row_spec(1, bold = TRUE)

#> \begin{tabular}{l|l|l}
#> \hline
#> mpg & cyl & disp\\
#> \hline
#> \textbf{Group 1} & \textbf{}\\
#> \hline
#> 21 & 6 & 160\\
#> \hline
#> \end{tabular}
```

I think the effect of `row_spec(1, bold = TRUE)` should be `\textbf{Group 1} & \textbf{} & \textbf{}\\`, rather than `\textbf{Group 1} & \textbf{}\\`. That is, one cell is missing.

The possible reason seems to be in the regular expression code in the `latex_row_cells()` function in [`util.R`](https://github.com/haozhu233/kableExtra/blob/master/R/util.R#L47-L49):

```R
latex_row_cells <- function(x) {
  strsplit(x, " \\& ")
}
```

Perhaps dropping a space after " \\&" would fix the bug. This is how I do it in my local branch: https://github.com/jjchern/kableExtra/commit/e554f284a692293bc5aa208150f432f1c1344294.

If you think dropping the space is a reasonable fix and would not introduce more problems, I'm happy to submit a PR. Otherwise, I thought I should report the issue and see if you have any other solution.

**Comment by haozhu233** [comment]
@jjchern Thanks for reporting this bug and sorry for the delayed response. :P 

I looked into the issue and as you said, it seems to be a bug in `base::strsplit`. If we drop the space, I'm afraid it may create issues in other cases. At the same time, it seems that `stringr::str_split` is able to give the correct output. 

```
> strsplit("Group 1 &  & ", " \\& ")
[[1]]
[1] "Group 1" ""       
```

```
> stringr::str_split("Group 1 &  & ", " \\& ")
[[1]]
[1] "Group 1" ""        ""       
```
