### ISSUE TITLE
column_spec not working for data with single column

### ISSUE THREAD

**Issue by eddjberry** [haozhu233/kableExtra#237]
Hi,

Thanks for creating such an awesome package! Just a little issue I've come across:
`column_spec()` doesn't seem to work with a data frame that only contains a single column when outputting to pdf. I've included a reprex below.

```
---
title: "kableExtra reprex"
output: pdf_document
---

{r setup, include=FALSE}
library(dplyr)
library(knitr)
library(kableExtra)
```

# A single column
This doesn't work
```{r}
df <-
  data.frame(
    id = 1:2,
    text = c(
      'Some rather long text that goes on for quite a while',
      'Some rather long text that goes on for quite a while'
    )
  )

df %>%
  select(text) %>%
  kable(booktabs = T) %>%
  kable_styling(full_width = F) %>%
  column_spec(1, width = '1in')
```

# Two columns
This works fine
```{r}
df %>%
  kable(booktabs = T) %>%
  kable_styling(full_width = F) %>%
  column_spec(2, width = '1in')
```

**Comment by vincentarelbundock** [comment]
This works in the dev version of the package

![Screenshot 2023-12-04 190645](https://github.com/haozhu233/kableExtra/assets/987057/ea3e4fdd-01ac-4cff-8ef7-ed701105cbca)
