### ISSUE TITLE
Issue with kable_as_image()

### ISSUE THREAD

**Issue by zebryjiang** [haozhu233/kableExtra#238]
I am trying to save Kable tables in R Markdown to a PPT file. And received the following error.
```
sh: xelatex: command not found
Quitting from lines 67-81 (CCA.rmd) 
Error in kable_as_image(FINAL_T1A) : 
  Ghostscript is required to read PDF on windows. Please download it here: https://ghostscript.com/
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> kable_as_image
Execution halted
```
The thing is I am actually on a Mac, so I really don't know why

**Comment by zebryjiang** [comment]
Solved by installing MacTex, but the output table was too wide, that not all parts of it is included in the picture.

**Comment by haozhu233** [comment]
Yeah, kable_as_image seems to has some issues with tinytex. This kind of bug is always difficult to locate and debug..
