### ISSUE TITLE
documentation error in "Create Awesome LaTeX Table"

### ISSUE THREAD

**Issue by p-phillips** [haozhu233/kableExtra#240]
Only minor, but the pdf (dated 2018-05-21) on creating latex tables says in the overview:

    To learn how to generate complex tables in **LaTeX**, please visit http://haozhu233.
    github.io/kableExtra/awesome_table_in_html.html

It should, of course be html, not LaTeX.
Pete

**Comment by haozhu233** [comment]
Haha, thanks! Fixed now.
