### ISSUE TITLE
column_spec doesn't always work with width for HTML

### ISSUE THREAD

**Issue by kgottstine** [haozhu233/kableExtra#242]
I have ran into this issue several different times and this is the most reproducible example. I am using HTML output.

I can adjust one column:
```
data.frame(RRmin=1, RRmax=10) %>%
   dplyr::rename(`Reportable Range Min` = RRmin, `Reportable Range Max` = RRmax) %>%
   kable() %>%
   column_spec(1, width = "0.5in") %>%
   kable_styling(c("bordered", "condensed"), full_width = F)
```
which gives this table:
![image](https://user-images.githubusercontent.com/29205815/44482769-5082ad00-a617-11e8-8087-ae14c29c7ba5.png)

but if I try to adjust both columns it doesn't work:

```
data.frame(RRmin=1, RRmax=10) %>%
   dplyr::rename(`Reportable Range Min` = RRmin, `Reportable Range Max` = RRmax) %>%
   kable() %>%
   column_spec(1:2, width = "0.5in") %>%
   kable_styling(c("bordered", "condensed"), full_width = F)
```
which gives this table:
![image](https://user-images.githubusercontent.com/29205815/44482855-7f991e80-a617-11e8-9dfa-142ccc3d3148.png)

**Comment by haozhu233** [comment]
This is a bug that need to be fixed. Thanks for reporting!

**Comment by kgottstine** [comment]
Great, thanks @haozhu233 ! 

Any idea on a time frame for the next release? Was hoping to get to use kableExtra for some reports I need to do this fall but they need to be in a very standard format, otherwise I need to look for a different package. Thanks!

**Comment by kgottstine** [comment]
Thanks! This works great. Must have missed the `include_thead` option before. 

I am noticing other things that may be related and am searching for a solution for this as well. When I manipulate the width of some columns I expected the other ones to stay condensed but it is not working in this way. I can't exactly give a reproducible example since the code to get to this stage is rather extensive but I can give you the code used for the table.

When I create the table with no adjustments, all the columns are tight and there is no excess space. 

```
aov %>%
    kable(digits = c(0, 0, prec, 0, rep(prec+1, 10)), align = "r") %>%
    add_header_above(c(" " = 4, "Repeatability (Within Run)" = 2, "Within Day" = 2, "Between Day" = 2, "Within Day" = 2, "Within Lab (Total)" = 2)) %>%
    collapse_rows(1) %>%
    kable_styling(c("bordered", "condensed"), full_width = F) %>%
    footnote(general = units, general_title = "Conventional Units:", footnote_as_chunk = T)
```
![image](https://user-images.githubusercontent.com/29205815/44590272-c4909280-a788-11e8-9e85-e4062fafcea4.png)

But the SD and %CV columns, I wanted to be the same width. So I used `column_spec` to make this happen. The desired result happened with those columns, however, the length of the table increased and then you can see the System and Fluid ID columns have excess white space now.

```
aov %>%
    kable(digits = c(0, 0, prec, 0, rep(prec+1, 10)), align = "r") %>%
    add_header_above(c(" " = 4, "Repeatability (Within Run)" = 2, "Within Day" = 2, "Between Day" = 2, "Within Day" = 2, "Within Lab (Total)" = 2)) %>%
    collapse_rows(1) %>%
    column_spec(column = c(5:14), width = "0.5in", include_thead = T) %>%
    kable_styling(c("bordered", "condensed"), full_width = F) %>%
    footnote(general = units, general_title = "Conventional Units:", footnote_as_chunk = T)
```

![image](https://user-images.githubusercontent.com/29205815/44590217-a034b600-a788-11e8-81a1-8769e779be56.png)

Any ideas on how to fix that? Thanks so much!

**Comment by haozhu233** [comment]
Can you try to move column_spec ahead of add_header_above?

**Comment by kgottstine** [comment]
Tried that as well, gives the same result.

**Comment by haozhu233** [comment]
Emm, this is kind of hard for me to reproduce. I tried mtcars with your codes (with very little modifications) but it looks normal..

![screen shot 2018-08-24 at 11 29 26 am](https://user-images.githubusercontent.com/7014590/44593379-2ead3580-a791-11e8-9774-343cdded907e.png)

**Comment by kgottstine** [comment]
It seems like the longest column header Repeatability (Within Run) is what's triggering this. I also used the mtcars to re-create with the addition of this header and you can see the first column is now much wider

```
mtcars %>%
  kable(align = "r") %>%
  column_spec(column = c(3:12), width = "0.5in", include_thead = T ) %>%
  add_header_above(c(" " = 2, "Repeatability (Within Run)" = 2, "Within Day" = 2, "Between Day" = 2, "Within Day" = 2, "Within Lab (Total)" = 2)) %>%
  kable_styling(c("bordered", "condensed"), full_width = F, position = "l") %>%
```
![image](https://user-images.githubusercontent.com/29205815/44593669-0c67e780-a792-11e8-8886-8078eeae5e08.png)

**Comment by haozhu233** [comment]
Well, this is a HTML behavior. Since we didn't define width for the extra header row, it sort of behave randomly. See: https://codepen.io/haozhu233/pen/NLGQwY

I can add a width option to add_header_above but I would say it will be more difficult to use than you go ahead and manually define width for column 1 & 2 😂

**Comment by shivamkhandelwal314** [comment]
Hi ,
I am some creating table using the kable extra package. However I came across an strange error. The below code is working fine in my system, however it throws an error when it is run on another system. Not able to figure out what exactly is the reason behind this
![image](https://user-images.githubusercontent.com/36129170/50472284-1f0f5900-09de-11e9-9f9d-0a131e6609a1.png)
