### ISSUE TITLE
collapse_rows not working for latex when columns = last column

### ISSUE THREAD

**Issue by quocpeyrot** [haozhu233/kableExtra#243]
the following code works for html but not for latex:

> collapse_rows_dt <- data.frame(C1 = c(rep("a", 2), rep("b", 3)),
                 C2 = 1:5,
                 C3 = c(rep("foobar", 2), 1:3)
                 )
>
> kable(collapse_rows_dt, align = "c") %>%
>   collapse_rows(3, latex_hline = "none", valign = "middle")

in latex mode, collapse_rows(latex_hline = "none", valign = "middle") would almost work : it would collapse the last row properly, but also the first one. It seems in latex mode, columns must be a seq from 1 to "n" to properly collapse the column "n".

I'm running
RStudio 1.1.456 on OSX
R version 3.5.1 (2018-07-02)
kableExtra_0.9.0

**Comment by jakob-r** [comment]
@quocpeyrot Maybe you can install my hopefully fixed version (see PR) and check if it works.

**Comment by haozhu233** [comment]
@jakob-r Thanks a lot for fixing this issue! I tested around and it seems to work perfectly!
