### ISSUE TITLE
Add linebreaks to rotated header row

### ISSUE THREAD

**Issue by suvivainio** [haozhu233/kableExtra#245]
I have long column titles which I'd like to rotate 90 degrees and line wrap. I tried to follow [best practice for line breaks](https://github.com/haozhu233/kableExtra/issues/157) but adding line_spec with angle=90 is not enough, there are no line breaks. 

Maybe it is question about line height? I didn't find a way to force line height and this way test whether the title would wrap. (The newbie that I am.)

```
dt_lb <- data.frame(
  Item = c("Hello\nWorld", "This\nis a cat"),
  Value = c(10, 100)
)
dt_lb %>%
  mutate_all(linebreak) %>%
  kable("latex", booktabs = T, escape = F,
    col.names = linebreak(c("Item\n(Name)", "Value\n(Number)"), align = "c")) %>%
 row_spec(0, angle = 90)
```
Linebreaks are definitely there when I check the kable output, but somehow Latex just doesn't wrap the lines.

```
\begin{tabular}{lr}
\toprule
\rotatebox{90}{\multicolumn{1}{l}{\ttfamily{\makecell[l]{Item\\(Name)}}}} & \rotatebox{90}{\multicolumn{1}{l}{\ttfamily{\makecell[l]{Value\\(Number)}}}}\\
\midrule
\makecell[l]{Hello\\World} & 10\\
\makecell[l]{This\\is a cat} & 100\\
\bottomrule
\end{tabular}
```

**Comment by vincentarelbundock** [comment]
this appears to be solved in Github master

![Screenshot 2023-12-04 192003](https://github.com/haozhu233/kableExtra/assets/987057/076f5896-ffd6-496d-99da-7e8949fb843e)
