### ISSUE TITLE
add_header_above without header section in input not possible

### ISSUE THREAD

**Issue by tomvanengeland** [haozhu233/kableExtra#246]
Dear Hao,
Thanks for the wonderful kableExtra package. I'm starting to use it quite intensively. 
However, I've found an issue that might be considered a bug:

If I do not want to include the original column names of a data.frame (for instance because I want to repeat  column headers (data.frame column names have to be unique)), I can leave them out using the option \col.names = NULL' in the kable function. This will produce html without a thead section. If I then want to add another column header using the add_header_above, this is not possible because the function throws the following error: no applicable method for 'nodeset_apply' applied to an object of class "NULL". This can be traced back to the absence of the thead section in the output of the kable function. A minimal exanple:

`
justsomedataset <- data.frame(alphabet=c("a","b","c","d","a","b","c","d"),                      numbers=c(1.95,4.35,5.36,7.45,8.51,9.22,64.77,87.98),                      colors=c("yellow","red","yellow","green","blue","red","purple","black"))

justsomedataset %>% kable(align="c",format="html",row.names=FALSE,col.names=NULL,escape=FALSE) %>% add_header_above(header=c(` `=1,`twocolstogether`=2))
`

So the bottom line is: add_header_above can only be used if there is already a column header in the table.

I hope this is useful to you.

Best regards,
Tom

**Comment by jacob-long** [comment]
This issue applies to the group_rows function as well.

**Comment by rcragun** [comment]
This is an issue for html format, but it works fine with latex format.

**Comment by haozhu233** [comment]
Fixed in #423
