### ISSUE TITLE
Trailing Blanks of Each cell

### ISSUE THREAD

**Issue by zebryjiang** [haozhu233/kableExtra#248]
Hi,

I am preparing a table that each cell is percentage values.
If it is significant, it is written as "60%*", and if it is not, "60% ".

I want to keep the " " (blank) after the percent sign, so that the cells can align on the %.

But it looks that when using kable extra, it is "easting" my blank somehow. Any way to solve it?

Thank you very much!

**Comment by haozhu233** [comment]
Hi, @zebryjiang sorry for the delay. Can you tell me which format are you working on?

**Comment by themechanicalbear** [comment]
@zebryjiang 

It seems that kable_as_image is deprecated, so I thought maybe this might work for you. This is not using kableExtra only knitr. 

The output of a space character comes from latex and this solution depends on the font in the powerpoint. In my case using the Calibri font required 2 spaces for the alignment to work.

I know this doesn't answer the original question directly but hopefully, this is still helpful.


```{r table}
library(dplyr)
library(knitr)

mtcars_tbl <- mutate(mtcars, mpg_hp = scales::percent(mpg / hp)) %>%
    mutate(frmt_mpg_hp = case_when(mpg / hp > .20 ~ paste0(mpg_hp, "*"),
                                TRUE ~ paste0(mpg_hp, "&nbsp;", "&nbsp;"))) %>%
    select(mpg, hp, mpg_hp, frmt_mpg_hp)

kable(head(mtcars_tbl), align = 'rrrr')
```

**Comment by vincentarelbundock** [comment]
Insufficient information to diagnose. Please comment again with a minimal reproducible example if you still face the problem.
