### ISSUE TITLE
Repeat header in longtable repeats the \label from ktable()

### ISSUE THREAD

**Issue by fkroener** [haozhu233/kableExtra#25]
When using repeat_header I get latex warnings about the table's label being multiply defined.

This appears to stem from knitr::kable adding the environments' label inside its `table_info$caption`, which kableExtra copies when repeating the header.

I wonder whether there is any workaround?

Solution could probably be instead of adding "cont." or individual repeat_header_text to the end of the caption-string to require the user to set `repeat_header_text` to be the full caption again (as does longtable when manually constructing it via `\endfirsthead` and friends.)

This would add more flexibility and remove the label-repetition but might break currently expected behavior. Maybe check whether `repeat_header_text` is set, otherwise add (cont.).

**Comment by haozhu233** [comment]
I did a little exploration and it seems like I should remove the `\label{tab:...}` in the second page caption?

**Comment by fkroener** [comment]
Yes, that could work as well. 

Though I suppose having the option of setting the entire second caption again instead of just its tail would be nice too, adding flexibility for the user who might choose to say "Continuation of previous table".

**Comment by haozhu233** [comment]
Sure, I can add an option like `repeat_header_method` (or something else if you have a better idea) and you can set it to be either `replace` or `append` (default). What do you think?

**Comment by fkroener** [comment]
Sounds great.

Oh and while we're at it, maybe I may ask another question. Is there any example or way for the `group_rows` stuff to be automated?

I have a df with a column of groups and some data columns and I could create some for-loop to get the group-names and start_row / end_row for each of them - but I can't figure out how to press that into `%>%` syntax without manually specifying each `group_row`.

**Comment by haozhu233** [comment]
You can try out `collapse_rows` if you haven't. If you prefer the look of `group_rows` as I do, I can add a wrapper of `group_rows` in necessary.

**Comment by haozhu233** [comment]
@fkroener I added `repeat_header_method` with default value being `replace`. Also, I fixed the table double labeling issue.
