### ISSUE TITLE
'\\' to '\textbackslash{}' translation forbids citations and url links in kable tables

### ISSUE THREAD

**Issue by tinavisnovska** [haozhu233/kableExtra#250]
Hi, 
translating '\\' in R to '\textbackslash{}' in LaTex forbids using, for example, citations and urls in kable tables, when kableExtra is used. Is this intended behaviour?
Cheers.

**Comment by haozhu233** [comment]
`\` got translated into '\textbackslash{}' because it's a special symbol in latex and gets escaped. There are `escape` options in many of these functions. You can try to set `escape = F` so that these functions will know not to escape `\` for you.

**Comment by tinavisnovska** [comment]
Thanks for the reply, `escape=F` together with explicit specification of the kable table format (`format="latex"`) fixed it for me.
