### ISSUE TITLE
multiple tables

### ISSUE THREAD

**Issue by rb643** [haozhu233/kableExtra#251]
Is there a straightforward way to print the kable tables side-by-side in a markdown html? So if I have two of these in my code section but want to print them side by side:

kable(df, caption = "something about this table") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), 
                position = "left", full_width = F)

**Comment by haozhu233** [comment]
There are several ways. You can either try to set the first table to `float_left` so the table next to it will be positioned next to it. Another approach could be using things from shiny. 

```
library(kableExtra)
library(shiny)

fluidRow(
  column(6, HTML(kable(mtcars[1:5]))),
  column(6, HTML(kable(mtcars[1:5])))
) 
```

**Comment by vincentarelbundock** [comment]
Old issue with satisfactory answer. Closing so we can focus on issue which need action. Users can always find this later with the search function.
