### ISSUE TITLE
group_rows_latex and add_indent_latex are broken when table have near-duplicated rows

### ISSUE THREAD

**Issue by quocpeyrot** [haozhu233/kableExtra#254]
Hello,

it took me a while to reduce the testcase and track down that one ;-)
I'm going to submit a pull request with the fix, but here is the description.

with the following example, the current code is broken:

```R
c1 <- c("A", "B", "C",
        "A", "B", "C")
c2 <- c("12", "0", "0",
        "1", "0", "0")
df <- data.frame(c1, c2)

print(knitr::kable(
  df, booktabs = T, format = "latex"
) %>%
  group_rows(index = c(
                       "Foo" = 3,
                       "Bar" = 3
                       ))
)
````

this produce:

> \begin{tabular}{ll}
> \toprule
> c1 & c2\\
> \midrule
> \addlinespace[0.3em]
> \multicolumn{2}{l}{\textbf{Foo}}\\
> \hspace{1em}\addlinespace[0.3em]
> \multicolumn{2}{l}{\textbf{Bar}}\\
> \hspace{1em}A & 12\\
> \hspace{1em}B & \vphantom{1} 0\\
> \hspace{1em}C & \vphantom{1} 0\\
> A & 1\\
> \hspace{1em}B & 0\\
> \hspace{1em}C & 0\\
> \bottomrule
> \end{tabular}
> 

instead of the correct code:

> \begin{tabular}{ll}
> \toprule
> c1 & c2\\
> \midrule
> \addlinespace[0.3em]
> \multicolumn{2}{l}{\textbf{Foo}}\\
> \hspace{1em}A & 12\\
> \hspace{1em}B & \vphantom{1} 0\\
> \hspace{1em}C & \vphantom{1} 0\\
> \addlinespace[0.3em]
> \multicolumn{2}{l}{\textbf{Bar}}\\
> \hspace{1em}A & 1\\
> \hspace{1em}B & 0\\
> \hspace{1em}C & 0\\
> \bottomrule
> \end{tabular}
> 

The main issue is the line "A & 12" and "A & 1" which are not duplicated rows, but begin with the same pattern.
The "sub()" calls are therefore replacing the wrong line, hence the fail.

pull request incoming in a couple of minutes :-)

**Comment by haozhu233** [comment]
Thank you!
