### ISSUE TITLE
Combined footnote?

### ISSUE THREAD

**Issue by antagomir** [haozhu233/kableExtra#256]
Great pkg, thanks! I was trying to add a single footnote (add_foonote function) that would be cited in two different positions in a table. Since the footnote is shared, it would be useful to have an option where the footnote symbol can be kept identical across entries, resulting in a single footnote. Currently the add_footnote function adds a separate footnote (a,b,c,...) for every entry.

**Comment by haozhu233** [comment]
I’m not sure if I have fully understood this but if you are looking for a single footnote have you checked out the footnote_as_chunk option in footnote. Note that it’s not in add_footnote.

**Comment by antagomir** [comment]
Thanks. I mean something like in [this figure](https://i.stack.imgur.com/oHnlw.png) ("Multiple references to the same footnote inside a table environment"). The footnote_as_chunk does not solve this as far as I can see.

**Comment by haozhu233** [comment]
Emm, you can try out the "general footnote" in `footnote` and do the labeling manually by yourself. It might work... Otherwise, within the current setting, it's kind of difficult to implement.
