### ISSUE TITLE
Would you please implement a method to allow multiple titles for a table?

### ISSUE THREAD

**Issue by bxia2018** [haozhu233/kableExtra#258]
Hi Hao, 

Your kable package is fantastic! i have been looking for a R package to do customized reporting. Kable is the one which will work for me. 
I have worked in a Biotech company doing clinical trials for many years. In our work, we often need multiple titles for a table.  However the caption option in kable seems only handing one title. I tried to use '\n'  to break line  and it is ignored. However '\n' does work in footnote option. 

for example:
  kable(dt, "html", caption ="Protocol NP12345: Disposition Table\nITT population") %>%
  kable_styling() %>%
  add_indent(c(4:9)) %>% footnote(general = "Note: This table is produced by bxia \nwith dplyr and kable.",   general_title = "\n\n")

I used SAS for many years. Your kable package is the closest tool to famous SAS 'proc report'. Great job done and i hope you keep improving the package! 

thanks

**Comment by haozhu233** [comment]
Hi, @bxia2018, thanks for your kind words. If you don't need to export to a PDF document, you can simply replace your `\n` with the HTML line break `<br>`.

**Comment by bxia2018** [comment]
Thanks for quick response! that trick works!
