### ISSUE TITLE
math symbols in add_header_above

### ISSUE THREAD

**Issue by arcosdium** [haozhu233/kableExtra#259]
`
df <- data.frame(k=1:3, alpha = (1:3)/2, beta1 = sqrt(1:3), beta2= (1:3)^2)

kable(df,  
      col.names = c("$k$", "$\\alpha_k$", "$\\beta_k$",  "$\\beta_k$"),
      row.names = FALSE, digits = 1,
       booktabs = T, escape = FALSE)  %>%
   add_header_above(c(" "," ","$\\gamma = 0$", "$\\gamma = 1$"), escape = FALSE) 
`
gives gamma symbols in html, but only the word gamma in pdf

**Comment by haozhu233** [comment]
Hi, @arcosdium , could you give me a more detailed example (like the rmarkdown file)? I couldn't even get the word gamma in pdf. lol

**Comment by mcol** [comment]
For a pdf, the following block compiles for me (note the double backslashes): indeed the header above shows only the word gamma in italics rather than the Greek letter.

---
title: "Test"
output: pdf_document
---

```{r echo=FALSE}
library(knitr)
library(kableExtra)

df <- data.frame(k=1:3, alpha = (1:3)/2, beta1 = sqrt(1:3), beta2= (1:3)^2)
kable(df, digits=1,
  col.names = c("$k$", "$\\alpha_k$", "$\\beta_k$", "$\\beta_k$"),
  escape = FALSE) %>%
add_header_above(c("","","$\\gamma = 0$", "$\\gamma = 1$"), escape=FALSE)
```

**Comment by arcosdium** [comment]
That's right. One needs the  double backslashes. Sorry, they disapeared during copy and paste.  
 The symbols are very important for math papers.

**Comment by DanielReedOcean** [comment]
@arcosdium To get your original table working, I had to use **4** backslashes to escape gamma rather than the usual two, as @mcol mentioned above. For example,

```{r echo = FALSE, message = FALSE}
library(knitr)
library(kableExtra)

df <- data.frame(k=1:3, alpha = (1:3)/2, beta1 = sqrt(1:3), beta2= (1:3)^2)
kable(df, digits=1,
  col.names = c("$k$", "$\\alpha_k$", "$\\beta_k$", "$\\beta_k$"),
  escape = FALSE) %>%
add_header_above(c(" " = 1," " = 1,"$\\gamma = 0$" = 1, "$\\gamma = 1$" = 1), escape=FALSE)
```
produces

![capture1](https://user-images.githubusercontent.com/11167566/53038752-e1fe9a80-3453-11e9-8de8-260f64573f6c.PNG)

However,

```{r echo = FALSE, message = FALSE}
library(knitr)
library(kableExtra)

df <- data.frame(k=1:3, alpha = (1:3)/2, beta1 = sqrt(1:3), beta2= (1:3)^2)
kable(df, digits=1,
  col.names = c("$k$", "$\\alpha_k$", "$\\beta_k$", "$\\beta_k$"),
  escape = FALSE) %>%
add_header_above(c(" " = 1," " = 1,"$\\\\gamma = 0$" = 1, "$\\\\gamma = 1$" = 1), escape=FALSE)
```
gave the following (which I think is the desired result):
![capture2](https://user-images.githubusercontent.com/11167566/53038724-cdba9d80-3453-11e9-8bef-eaa0abf3aba7.PNG)

**Comment by haozhu233** [comment]
@DanielReedOcean Great! Thanks for this example! It's very helpful!

**Comment by valentinaandrade** [comment]
Hi @DanielReedOcean 
Thanks for the help. 

I do your recommendation and the console shows to me the following error:

! Misplaced \noalign.
\midrule ->\noalign 
                    {\ifnum 0=`}\fi \@aboverulesep =\aboverulesep \global \@...
l.657 \end{tabu}

Error: LaTeX failed to compile report.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See report.log for more info.
 Can you help me, please!
