### ISSUE TITLE
Add ability to customize header row (font size/centering)

### ISSUE THREAD

**Issue by norcalbiostat** [haozhu233/kableExtra#26]
This would be a great addition!

**Comment by haozhu233** [comment]
Thanks! This is another worth-thinking problem. It's a little tricky because HTML and LaTeX handles these things differently. It will get a little more complicated when multi-row header kicks in. Let me think about it and see what I can do.

**Comment by haozhu233** [comment]
I'm planning for a CRAN release recently. This feature will be implemented after that release. My current thought is to make a special case in `row_spec`. When users set `row = 0`, it means that they want to customize the original header row.

**Comment by haozhu233** [comment]
Now with the dev version, you can use something like `row_spec(your_kable, row = 0, font_size = 20, align = "c")` to specify the header row. :)
