### ISSUE TITLE
Having trouble with LaTeX formatting in add_header_above in R Markdown to PDF

### ISSUE THREAD

**Issue by MCM-Math** [haozhu233/kableExtra#260]
I'm having trouble with putting LaTeX formatting into add_header_above in R Markdown to PDF, because it keeps converting the LaTeX formatting into literal text ('\' to '\textbackslash{}' and '{' to '\{' and so on) regardless of what options I set, or how I enter in the formatting.  What works in the kable headers and body (cell_spec format), or what works in the main part of the R Markdown document (text_spec format), doesn't work in add_header_above.  It still just converts what is supposed to be code to literal text.  I've looked around through this site and others (StackOverflow, etc.) for potential solutions to this issue, but what works in the situations I've found doesn't work in add_header_above.

**Comment by haozhu233** [comment]
If you have use `cell_spec`, you need to put `escape = F` in `kable`.

**Comment by MCM-Math** [comment]
I tried that already.  I did that to get the main body and headers to have formatting, but it didn't get "add_header_above" to work, even with escape=F within add_header_above itself.

**Comment by haozhu233** [comment]
@MCM-Math You might need to put on `\\\\` to escape in some cases.... Could you give me a reproducible example? It's a little hard for me to provide any useful solution without an example. ;)

**Comment by MCM-Math** [comment]
The "\\\\" did end up working for me; sorry for not mentioning that earlier.  It seems that each command deals with the text conversion differently.  One general suggestion I have is to look at the generated tex file, and directly emulate the desired output for that file as directly as possible, if the function itself is too much of a hassle with respect to certain text characters.
