### ISSUE TITLE
GitHub issue templates

### ISSUE THREAD

**Issue by wibeasley** [haozhu233/kableExtra#261]
@haozhu233, After seeing a few responses from you to request reproducible examples, consider something premptive like this: https://help.github.com/articles/about-issue-and-pull-request-templates/

I’ve seen a few, such as https://github.com/tidyverse/ggplot2/issues/new

**Comment by haozhu233** [comment]
@wibeasley Thank you! This is a great suggestion! I will make one this afternoon. :)

**Comment by haozhu233** [comment]
Added. Thanks!
