### ISSUE TITLE
Add background color or border option for add_header_above

### ISSUE THREAD

**Issue by shubhexe** [haozhu233/kableExtra#262]
Hey there! I'm a huge fan of your package kableExtra and have been using it extensively now. But, I'm stuck somewhere. In one of the extra headers that I have added, because the table below it is huge, I'm not able to differentiate the subtables. Is it possible to color the background of my added header or a border around it so the tables below it become distinguishable? The "line=T" option doesn't work when you open the html in excel as the line disappears and even the "bordered". in kable_styling doesn't appear in excel. I know that you're working on adding enhancements to this but I kinda need this very soon. Thanks in advance :)
![image](https://user-images.githubusercontent.com/43207550/45424711-fd02fc80-b6b4-11e8-9aea-fc7e41c1e493.png)

**Comment by haozhu233** [comment]
I added color, background, extra_css and many other options to `add_header_above` in the dev version of kableExtra. Please check it out. :)

**Comment by shubhexe** [comment]
You're the best, man! Thank you so much! :)

**Comment by haozhu233** [comment]
I’m trying to cleaning up the issues and make a release in like a week.

**Comment by shubhexe** [comment]
Thank you so much!

**Comment by shubhexe** [comment]
Also, I'm currently converting html to excel using VBA. Do you have any plans to add a feature to save the html output directly as excel workbook?

**Comment by mariusrubo** [comment]
I'm not quite sure if my question is related. I would simply like to have a completely bordered table, where the headers have borders, too. How do I do that? I tried several options but only got the weird result shown below:

![kable_table](https://user-images.githubusercontent.com/24437119/53831074-304b8780-3f84-11e9-98b3-d4362e1c1e18.JPG)
