### ISSUE TITLE
bootstrap.min.js not included when building a gitbook in bookdown using kableExtra

### ISSUE THREAD

**Issue by gfiumara** [haozhu233/kableExtra#263]
**Describe the bug**

Building a `bookdown::gitbook` does not include `bootstrap.min.js`, creating a JavaScript error in `$(document).ready()` when attempting to use a missing method within `kePrint.js`.

I am unsure where in the dependency stack of packages this is a bug, so please forgive me if this should be reported elsewhere.

**To Reproduce**
index.Rmd:
````
---
title: "Test"
output: bookdown::gitbook
---

```{r, table}
kableExtra::kable_styling(knitr::kable(cars),
    bootstrap_options = c("striped", "hover"))
```

# This is a test bookdown::gitbook
````

In R, build the book:
`bookdown::render_book("index.Rmd")`

**What I Expect**
Changing the YAML at the top to read
````
output: 
    html_document:
         self_contained: false
````
and using RMarkdown to render this simple example (`rmarkdown::render("index.Rmd")`) includes the necessary Bootstrap JS.

**Comment by haozhu233** [comment]
@gfiumara kePrint does nothing more than turn on the bootstrap tooltip and popover... https://github.com/haozhu233/kableExtra/blob/master/inst/kePrint-0.0.1/kePrint.js Maybe I should not put them inside a `$(document).ready()`?

**Comment by gfiumara** [comment]
I understand that it doesn't do much. The problem I'm seeing is that in this particular case, the little that it does isn't possible because it failed to load another required JavaScript file that defines the functions being called. In my stripped down use-case, I'm not making use of tooltips or popovers, so my opinion would be the file should not be included in the first place.

I noticed this because in a larger project, I have code that is included that needs to run during `$(document).ready()`, but fails, because `kePrint.js` has an error first and so the browser terminates the rest of `$(document).ready()`.

When `kePrint.js` is included, ensure that all required dependencies are also included. Having it be smarter about `kePrint.js` is included in the first place (when tooltips or popovers are used) is a different issue.
