### ISSUE TITLE
Connecting add_header_above lines?

### ISSUE THREAD

**Issue by johnhenrypezzuto** [haozhu233/kableExtra#266]
Is it possible to connect the lines from multiple add_header_above inputs with a single line? 

For example the code 
```
add_header_above(c(" ", "Control" = 1,"Ideologically \n Diverse" = 1, "Difference" =1), line = TRUE)
```
Will produce a single a underline for each of the input, but they will not be connected. 

i.e., the latex code
\cmidrule(l{2pt}r{2pt}){2-2} \cmidrule(l{2pt}r{2pt}){3-3} \cmidrule(l{2pt}r{2pt}){4-4}

However the code:
```
add_header_above(c(" ", "Mean" = 3))
```
Would give the latex code
...
\cmidrule(l{2pt}r{2pt}){2-4} 

With one long line.
Is it possible to somehow connect the the two codes so I could end up with the final code being:

\multicolumn{1}{c}{ } & \multicolumn{1}{c}{Control} & \multicolumn{1}{c}{\makecell[c]{Ideologically \\ Diverse}} & \multicolumn{1}{c}{Difference} \\
\cmidrule(l{2pt}r{2pt}){2-4} ?

**Comment by haozhu233** [comment]
@johnhenrypezzuto 

Try to install the latest dev version. I added a `line_sep` option so you can customize the length of the gap. In your case, you can set `line_sep = 0`.
