### ISSUE TITLE
suggestions for group_row and row indention. 

### ISSUE THREAD

**Issue by bxia2018** [haozhu233/kableExtra#268]
Hi Hao,

This package is really getting great! Thank you so much!

There are some small things to be hammered out. One thing I can think of is the group_row labeling and row indention. At this moment, users need to count the range of rows for group labeling and indention. this might be ok if one needs to produce couple of tables sporadically. This method won't fit the bill in massive systemic programming to produce many tables. For example, in a simple demographic and baseline characteristics table, there are typically dozens variables to be summarized (both numeric and/or factor variables), it won't be practical to count rows for each variable manually for the sake of group labeling and indention.   Additionally, over the time of project, data may change. your counting is fine for now, but it may get screwed up later .  I came from SAS. There are some good ideas to borrow from there in these matters. 
For example, user can introduce another variable - "Group" for example. It is not displayable but can be used to control reporting.  we can break an empty line per each Group category except the first Group (eg, add a command %>% breakaline(by=Group)). Secondly, we can automatically indent rows within same Group category (eg TEXT column in sample data) if users opt for. 

For example, the following data:

<pre>  
  Group   order     TEXT       ARM A            ARM B       
    Gender    1         n             52            48       
    Gender    2         M     24 (46.15%)    27 (56.25%)      
    Gender    3         F     28 (53.85%)    20 (41.67%)      
    Gender    4         U           <NA>      1 (2.08%)       
    AGE       1         n            52             48       
    AGE       2   Mean(SD)    41.6 (15.08)  38.52 (13.65)     
    AGE       3     Median          40.5           37.5       
    AGE       4  Min - Max        14 - 73        12 - 74  
   .......
</pre>

Would be displayed as below:
<pre>
    Gender    
          n             52            48       
          M     24 (46.15%)    27 (56.25%)      
          F     28 (53.85%)    20 (41.67%)      
          U           '  '            1 (2.08%)       
   
    AGE  
          n            52             48       
          Mean(SD)    41.6 (15.08)  38.52 (13.65)     
          Median          40.5           37.5       
          Min - Max        14 - 73        12 - 74  
    ....
</pre>

I understand you have a busy schedule. and this task may take a while to program. I would like to bring this to your attention so that you may consider such enhancements in future. 

The overall idea is to massage data better, by programming, for better control of customized reporting.  some columns may be purely used for controlling of report (grouping, sub-grouping, ordering, formatting, etc) and thus can be opt out of being displayed. 

Thanks

**Comment by vincentarelbundock** [comment]
I believe this is now solved with `collapse_rows()`. Please comment again or raise a new issue with a feature request if this does not serve the purpose.
