### ISSUE TITLE
how to print a single html table to pdf?

### ISSUE THREAD

**Issue by randomgambit** [haozhu233/kableExtra#269]
Hi @haozhu233 ,

I was wondering if there is a simple solution to print an html table to pdf. I know that there is the `kable_as_image()` trick for tables rendered in `pdf`, but is there something for html tables?

See here for an example

https://stackoverflow.com/questions/52404799/how-to-print-an-html-kable-to-pdf

Thanks!!

**Comment by haozhu233** [comment]
Right now yes not perfect. You can save kable to an html using `save_kable` and then you can convert it to an image using webshot. See the example below. 

```
mtcars %>%
  kable() %>%
  kable_styling() %>%
  save_kable("test.html", self_contained = F)

webshot::webshot("test.html")
```

I will integrate this piece into save_kable() so it will be more automatic in the future.

**Comment by haozhu233** [comment]
All set now. Check it out with the dev version:

```
library(kableExtra)

mtcars %>%
  kable() %>%
  kable_styling() %>%
  save_kable("test.pdf")
```

**Comment by randomgambit** [comment]
pretty cool bro, pretty cool

**Comment by Gateux** [comment]
Hi haozhu, do you plan to integrate also excel output (with formatting) into save_kable? 

Thank you

**Comment by haozhu233** [comment]
https://haozhu233.github.io/kableExtra/save_kable_and_as_image.html

I made some improvements to `save_kable` and and added an `as_image` before I pushed 1.0 to CRAN. Now it works for html, pdf, png, jpeg... for both html and latex tables(only exception is u can't do save pdf to html). `as_image` put the plot in a temp file and then `include_graphics` in rmarkdown

**Comment by yxiao69** [comment]
I just tried 
mtcars %>%
  kable() %>%
  kable_styling() %>%
  save_kable("test.pdf")

but ending with error below:
Error in webshot::webshot(file_temp_html, file, ...) : 
  webshot.js returned failure value: 1

**Comment by inescomarella** [comment]
Hello, I had the same problem and the cause of this error was the folder name, it had an 'ç', after changing it worked just fine here.
