### ISSUE TITLE
Add ability to set order of footnote symbols (feature request)

### ISSUE THREAD

**Issue by jimvine** [haozhu233/kableExtra#271]
Some journals specify the order of symbols to use for table footnotes.  For example, the Journal of the Royal Statistical Society specifies:

> The order of symbols for footnotes in tables is †, ‡, §, §§, *, **, ††, ‡‡

[JRSS Notes on the Submission of Papers](https://wol-prod-cdn.literatumonline.com/pb-assets/hub-assets/rss/Notes_for_Authors_2018-1534776230420.pdf) (p5)

It would be great if it were possible to specify these.

**Comment by haozhu233** [comment]
Hi, @jimvine thanks for your suggestion! I just added a `symbol_manual` option to `footnote`. 

https://github.com/haozhu233/kableExtra/blob/149faedf582c0275a6e2545c3a0807b855a9f22f/R/footnote.R#L34-L35
