### ISSUE TITLE
Long footnote issue

### ISSUE THREAD

**Issue by waynelapierre** [haozhu233/kableExtra#272]
The code below creates a strange thing "makecell[l]" in the note, I was wondering how I can add long footnote to the table. 

```

dt <- mtcars[1:5, 1:4]



table_1 <- kable(dt, format = "latex",
                 caption = "Yearly value of the premiums",
                 align = "c", booktabs = TRUE) %>%
  kable_styling(latex_options = c("striped")) %>%
  footnote(general = "This table shows the yearly values of the Repurchase Premium, the Dividend Premium, and the 
           Difference Premium from 1971 to 2010. Means and standard deviations for the premiums are also shown.")


```

**Comment by haozhu233** [comment]
@waynelapierre Sorry for the delay. For long footnotes, you can try out the `threeparttable` option. The reason why there is a `makecell` is that you put a linespace in the middle of your text. 

```
dt <- mtcars[1:5, 1:4]
kable(dt, format = "latex",
                 caption = "Yearly value of the premiums",
                 align = "c", booktabs = TRUE) %>%
  kable_styling(latex_options = c("striped")) %>%
  footnote(general = "This table shows the yearly values of the Repurchase Premium, the Dividend Premium, and the Difference Premium from 1971 to 2010. Means and standard deviations for the premiums are also shown.",
           threeparttable = T)
```

**Comment by bsalak** [comment]
Hi there,
Unfortunately I have a similar problem which I can't get rid off by myself. Problem is a long footnote, but the "threeparttable=T" suggested in the post above does not help at all. The footnote determines the width of the table, although the columns are defined with units. 
I would be grateful if anybody could help me out here.

Please find my code below:
`          kable(t3mmod_LS, align = c(rep("l",1), rep("c",3)),escape = F) %>% 
                    kable_styling( bootstrap_options = c("condensed"), full_width = F) %>% 
                    footnote(general = c("'Coeff' = coefficient, 'SE' = standard error, 'Coeff/SE' = z-score, 'CRA' = Cronbachs Alpha."), alphabet = c("Coefficient is fixed; significance is not applicable." ,"No EFA was calculated for the utilitaristic landscape connotation items, as at least three indicators are recommended for measuring a latent construct. Instead, the mean of the displayed variables are applied."), threeparttable = T) %>%
                    column_spec(1, width = "2.5cm") %>% 
                    column_spec(2:4, width = "2cm") %>% 
                    pack_rows("Arcadic landscape connotation. \n[NOI 8, CRA 0.95]", 1,8) %>%
                    pack_rows(paste0("Utilitarian landscape connotation.", footnote_marker_alphabet(2)), 9,10, escape = F)`

**Comment by igjar36** [comment]
FYI, I'm having the same problem, but only when there are carriage returns in the footnote text. 

`dt <- mtcars[1:5, 1:4]
kable(dt, format = "latex",
                 caption = "Yearly value of the premiums",
                 align = "c", booktabs = TRUE) %>%
  kable_styling(latex_options = c("striped")) %>%
  footnote(general = "This table shows the yearly values of the Repurchase Premium, 
           the Dividend Premium, and the Difference Premium from 1971 to 2010. Means and standard deviations for the premiums are also shown.",
           threeparttable = T)`
