### ISSUE TITLE
! LaTeX Error: Option clash for package xcolor.

### ISSUE THREAD

**Issue by mgei** [haozhu233/kableExtra#274]
There is an error when using xcolor for document styling and working with kableExtra at the same time.

This reproduces the error:

document.Rmd: (note I had to leave a gap where the code section starts `` ` for this post)
```
---
title: "Untitled"
output:
  pdf_document:
    latex_engine: xelatex
    includes:
      in_header: head.tex
---

`` `{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(knitr)
library(kableExtra)
`` `

## R Markdown

This is an R Markdown document. Markdown is a simple formatting syntax.
```

head.tex:
```
\usepackage{xcolor}
\usepackage{sectsty}
\sectionfont{\color[HTML]{007888}}
\subsectionfont{\color[HTML]{007888}}
```

The error is as in the title: ! LaTeX Error: Option clash for package xcolor.

Is there anything I can do?

**Comment by haozhu233** [comment]
Hi, @mgei, sorry for the delay. To solve this issue, you should first ask `kableExtra` not to automatically load those preset latex packages for you and then manually load them with your options.

```{r}
options(kableExtra.latex.load_packages = FALSE)
```

Please see page 3 of this doc for the list of latex packages you need and other details. 

https://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf

**Comment by jpolonsky** [comment]
I have a similar issue, but only with the tufte::tufte_handout class. Although in the [documentation](https://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf) you state:

If you are using R Sweave, beamer, R package vignette template, **tufte** or some customized rmarkdown templates, you can put the following meta data into the yaml section. If you are familar with LaTeX and you know what you are doing, feel free to remove unnecessary packages from the list.
```
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage[table]{xcolor}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
```

this doesn't seem to work with the tufte class. My reproducible .Rmd code is below:

```
---
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage[table]{xcolor}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage[normalem]{ulem}
output:
  tufte::tufte_handout
  # pdf_document
---

```{r, message=FALSE, echo=FALSE, warning=FALSE}
library(kableExtra)
library(knitr)
library(tidyverse)

mtcars %>% 
  kable(booktabs = TRUE) %>% 
  kable_styling(latex_options = c("striped"))
```


```

which gives the error: `! LaTeX Error: Option clash for package xcolor.`. If you comment out the uncomment the `tufte::tufte_handout` output and replace with `pdf_document`, it works. 

Is there a way to get this styling in tufte_handout class without the clash? If I hide this option in `header-includes` the styling doesn't work

**Comment by cchapus** [comment]
Dear all,

I have exactly the same issue currently with kableextra.
So I tried to do a minimal installation in order to reproduce the issue.

Clean installation of R v3.5.1, Rstudio. Installation of tidyverse, kablextra and tinytex packages.
Used the `install_tinytex(force = TRUE)`.

Finally trying to produce a pdf with this .Rmd file:
```
---
title: "Untitled"
author: "Test"
date: "20 novembre 2018"
output:
  pdf_document: default
---

`` `{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
`` `

## Test kable Extra

`` `{r}
library(kableExtra)
#library(knitr)
kable(mtcars, format = "latex")
`` `
```

And I got this error message: 
```
output file: test_kableextra.knit.md

! LaTeX Error: Option clash for package xcolor.

Erreur : Failed to compile test_kableextra.tex. See test_kableextra.log for more info.
Exécution arrêtée
```

If I comment the `library(kableExtra)` and comment out the `library(knitr)`, it's working.

I tried to use the `awesome_table_in_pdf.Rmd` file, and it's not working on my computer. Same xcolor error.

**Comment by cchapus** [comment]
I forgot to add:

Using `html_document: default` is working. It seems to be only an issue with `pdf_document`

**Comment by cchapus** [comment]
Here is the log.

[test_kableextra.log](https://github.com/haozhu233/kableExtra/files/2601853/test_kableextra.log)

**Comment by cchapus** [comment]
Ok I figured out a way to make it work with `pdf_document`.

You need to add `echo = FALSE` in all the r chunk options. If the code is displayed at any point of the document, a conflict occurs with xcolor.

If no code display, kableextra is working. Perhaps I should open a new issue.
