### ISSUE TITLE
Cell_Spec for more than one condition?

### ISSUE THREAD

**Issue by soleyjh** [haozhu233/kableExtra#275]
**Describe the bug**
I'm trying to understand how to make the same column red and italic based on TWO conditions -- not one. My solution is two cell_spec() lines in the mutate function but that shows the HTML in the kable table.

**To Reproduce**
seven= cell_spec(seven,color =  ifelse(grid$flag %in% 1,"red","black")),
seven = cell_spec(seven, italic = (Sys.Date() - as.Date(grid$date, "%B %d, %Y") < 8))

**Comment by haozhu233** [comment]
@soleyjh I think you can put two conditions into one function call. Also, I think the reason why you see HTML in your table is that you forgot to put `escapt = F` in your kable

**Comment by soleyjh** [comment]
I just checked my kable and I have the condition escape = FALSE included so we can rule that problem out. I also re-ran the code outlined in the "To Reproduce" section and the column named "Seven" has the following output look for every single cell:

<span style=" color: Red;" >562,745</span> (it is properly italicizing the HTML for the second condition but it is -- unfortunately -- displaying the HTML as opposed to just the number with the proper format.

Can you elaborate on how I'd combine two conditions (based on different variables) into one function call (with the above example)?

**Comment by haozhu233** [comment]
@soleyjh like `seven= cell_spec(seven, color = ifelse(grid$flag %in% 1,"red","black"), italic = (Sys.Date() - as.Date(grid$date, "%B %d, %Y") < 8))`? 

Here is something I can reproduce:
```
library(kableExtra)
mtcars %>%
  mutate(
    mpg = cell_spec(mpg, color = ifelse(mpg > 20, "red", "black"),
                    bold = (cyl == 4))
  ) %>%
  kable(escape = F) %>%
  kable_styling()
```

**Comment by soleyjh** [comment]
That worked! Thank you so so much!
