### ISSUE TITLE
Italicize text in footnote

### ISSUE THREAD

**Issue by danliIDEA** [haozhu233/kableExtra#278]
I tried to italicize some text in the footnote (e.g., *** _p_ < .001) but to no avail. I am able to italicize text in the table caption or column names in kable using `\\textit{text I want to italicize}` with `escape` set to `FALSE`. However, the same trick doesn't work in `kableExtra::footnote`. I'm not sure if it's a bug or just something I didn't configure correctly. Could you please help?

Thanks!

**Comment by haozhu233** [comment]
Hi, @danliIDEA, sorry for the delay. The trick is that you need to use `\\\\` to do the escaping. For example `\\\\textit{text I want to italicize}`

**Comment by the-knife** [comment]
Hello,

I have the same issue, but in html format. Is there a similar trick. I used `<i>...</i>` with no effects.

**Comment by helgig1** [comment]
If anyone else has this problem... 
I had the same problem with italics in a footnote. I tried to use <i></i> with no luck, even though I but `escape = TRUE` in the kable() function.
**The solution**
Put `escape = TRUE` in the footnote() function.
```
library(dplyr)
library(kableExtra)
table(iris$Species) %>% 
    as.data.frame %>% 
    kable(format = "html") %>% 
    kableExtra::footnote(general = "This text is in <i>italics</i>",
                         escape = FALSE)
```

_sidenote_: I could not use astriks in the footnote, even though I had escape = FALSE, it always bolds my text. Bug I think. Using the html code (&#42;) did not help, still got bold text. Ended up using css to get an astriks.

**Comment by the-knife** [comment]
@helgig1 : Thank you!

**Comment by grszkthfr** [comment]
> Hi, @danliIDEA, sorry for the delay. The trick is that you need to use `\\\\` to do the escaping. For example `\\\\textit{text I want to italicize}`

Hi, is this still valid? Couldn't find anything in the [docs](http://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf) for footer (and header).

```
# LaTeX
  kbl(tab, 
      booktabs = T, align = "c", 
      caption = "\\textbf{What} a **caption**!", 
      row.names = F, escape = FALSE) %>%
    kable_classic(full_width = FALSE) %>% 
    add_header_above(c("", "", "", "", "\\\\textbf{A} \\\\textit{Header}" = 2, "", "")) %>%
    footnote(general= "\\\\textit{What} \\\\textbf{a} footnote!")
```

Produces 
![image](https://user-images.githubusercontent.com/25958195/98821834-58b1a780-2430-11eb-8304-3e4919fb5a3d.png)

I tried now everything von escaping as in the caption `\\` (which produces identical results as `\\\\`) up to `\\\\\` and `escape = TRUE` & `escape = FALSE`. Even `text_spec(..., bold = TRUE)` produced 
![image](https://user-images.githubusercontent.com/25958195/98823306-3587f780-2432-11eb-8d3a-73f984311a0a.png) in the footnote.

Let me now if I should file another issue, and thanks in advance! :slightly_smiling_face: 

Best
Jonas
