### ISSUE TITLE
kableExtra css vs radix css

### ISSUE THREAD

**Issue by wibeasley** [haozhu233/kableExtra#279]
Something in the new [radix package](https://rstudio.github.io/radix/)  is preventing the the kableExtra styles from rendering completely.  For instance, the `bootstrap_options` aren't being expressed at all.  And the (default) radix is blocking `full_width=TRUE` also.

I'm guessing that radix will get at least some traction, especially with the apparent advantages in webpages.  If kableExtra isn't compatible with radix, consider stating that, so people don't get frustrated.  If it is compatible, a dedicated vignette might be helpful, since it seems there are differences.

If there is a dedicated section/vignette on radix, consider mentioning if kableExtra is compatible with  [paged tables](https://rstudio.github.io/radix/tables.html#paged-tables).

````
---
title: "kableExtra css *vs* radix css "
output: 
  radix::radix_article
  # rmarkdown::html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
```{r}
library(magrittr)
mtcars %>% 
  dplyr::select(mpg, cyl, disp) %>% 
  head() %>% 
  knitr::kable(format = "html") %>%
  kableExtra::kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width        = TRUE # Radix does this by default
  ) 
```
````

![image](https://user-images.githubusercontent.com/1372890/46251890-5b560c00-c425-11e8-8068-593c3c6b948e.png)

**Comment by haozhu233** [comment]
I posted the link online now with a short description. Thank you for your suggestion! :)

https://haozhu233.github.io/kableExtra/using_kableExtra_in_radix.html
