### ISSUE TITLE
Add documentation for how to use kableExtra with bookdown's gitbook output format

### ISSUE THREAD

**Issue by hammer** [haozhu233/kableExtra#281]
Related to https://github.com/haozhu233/kableExtra/issues/263: I'd like to use the powerful table styling tools from `kableExtra` in my `gitbook`-formatted book, but because the Bootstrap CSS and JavaScript is not included, I'm out of luck.

It's a bit out of scope for this project but would likely increase your userbase meaningfully if your docs included information about how to include Bootstrap assets when using the Bookdown `gitbook` output format. This documentation probably belongs in the `bookdown` project but I have yet to see questions like https://stackoverflow.com/questions/52431057/how-to-add-local-dependencies-to-bookdown-project answered in that project.

I figured I'd file this issue in case others have the same need.

**Comment by haozhu233** [comment]
Hi, @hammer, thanks for your suggestions! I just added a bookdown example. Can you help me read through it and let me know if it's useful?

https://haozhu233.github.io/kableExtra/bookdown/index.html

**Comment by hammer** [comment]
Wow this is really great! I switched to K-M already for other reasons and will give this documentation a try shortly. Thanks for the quick response to a slightly off-topic request.

**Comment by haozhu233** [comment]
It is working, at least for the hovering part. I think for column width, you actually need 
`column_spec(..., width_min = "100em")`

https://www.w3schools.com/cssref/pr_dim_min-width.asp
