### ISSUE TITLE
add_header_above background color of " " cells

### ISSUE THREAD

**Issue by isubirana** [haozhu233/kableExtra#282]
Hi,

First of all, many thanks for kableExtra packages. It is awesome.

I have a table where a put and extra header above using the  `add_header_above` function from he github version which allows to specify a background color. The problem is that the cells with no underline (specified as " ") are not coloured. See the following code as an example:

```
# library(devtools)
# devtools::install_github("haozhu233/kableExtra")
library(kableExtra)
knitr::kable(head(mtcars), "html") %>%
  row_spec(0, background = "grey") %>%
  add_header_above(c(" " =1 , "Group 1" = 5, "Group 2" = 6), background="grey")
```
After executing this code, the first cell of header above is not coloured.

It is possible to colour the cells not underlined (with " ")?

Thanks in advance.

**Comment by haozhu233** [comment]
Hi, @isubirana, I added an option `include_empty` to add_header_above` with default = F. I think it will satisfy your need.

**Comment by Chanelle280** [comment]
How come when I scroll, using scroll box and add_header_above, there appears to be a gap that stretches across the entire table?

As I scroll, I can see the content that was just scrolled in this gap.

![image](https://user-images.githubusercontent.com/74219146/139952006-b5913cd5-810b-4e99-a912-36a77e605cea.png)
