### ISSUE TITLE
Decide indent when using `group_rows()

### ISSUE THREAD

**Issue by Rekyt** [haozhu233/kableExtra#283]
Hi @haozhu233, many thanks for building `kableExtra`. It's an awesome tool.

I'm generating tables automatically and thus heavily rely on `group_rows()` using `auto_index()`.
My problem is that I can't control the indentation of the rows (see `reprex` at the end).
See what I obtain:

![image](https://user-images.githubusercontent.com/5593751/47083013-b6eb0c80-d20f-11e8-95a8-bfdf184fecca.png)
I had the problem even when widening the first column.
From the `.tex` document I discovered that there were `\hspace{1em}` added to each line that moved my label.

It think it is because of the following line https://github.com/haozhu233/kableExtra/blob/6e6318829b4e6dab9c33f8a98892b887879066e3/R/group_rows.R#L196

Would it be possible to add an option in `group_rows()` to control indentation? Or at least to delete it?
I think it could be widely useful.

Thanks again!
Matthias

<details>
<summary> Rmd reprex </summary>
````
---
title: "Untitled"
author: "Matthias Grenié"
date: "17 octobre 2018"
output: pdf_document
---

```{r setup}
library("tidyverse")
library("knitr")
library("kableExtra")

my_df = structure(list(start = c("08:45", "09:15", "10:45", "11:00", 
"11:15", "11:30"), end = c("09:15", "10:15", "11:00", "11:15", 
"11:30", "11:45"), salle = c("Auditorium", "Auditorium", "Room 3", 
"Room 3", "Room 3", "Room 3"), titre = c("Opening Ceremony", 
"Biodiversity: From evolutionary origins to ecosystem functioning and extinction", 
"Using citizen data to assess ecological continuities", "How to go beyond the collection of data in citizen science projects? Opening the field of analysis and interpretation to citizens", 
"Biodiversity monitoring in farmland by farmers: lessons from the first seven years of the French Farmland Biodiversity Observatory", 
"Citizen scientists of a national garden butterfly survey shift to biodiversity-friendly garden practices with multi-annual participation"
), speaker = c(NA, "David Tilman", "Florence Matutini", "Sylvie Blangy", 
"Emmanuelle Porcher", "Nicolas Deguines"), session = c("Opening Ceremony", 
"Biodiversity: From evolutionary origins to ecosystem functioning and extinction", 
"Participative sciences in ecology", "Participative sciences in ecology", 
"Participative sciences in ecology", "Participative sciences in ecology"
)), row.names = c(NA, -6L), class = c("tbl_df", "tbl", "data.frame"
))

my_df %>%
    kable("latex", longtable = TRUE, booktabs = TRUE) %>%
    kable_styling(latex_options = c("striped", "repeat_header"),
                  full_width = TRUE) %>%
    column_spec(1:2, width = "2em") %>%
    column_spec(3, width = "4.5em") %>%
    column_spec(5, width = "8em") %>%
    group_rows(index = auto_index(my_df$session),
               latex_gap_space = "0.7em",
               extra_latex_after = "\\hspace{-1em}")
```
````
</details>

**Comment by haozhu233** [comment]
Sure, that sounds like an easy fix. I will add this option. :)

**Comment by haozhu233** [comment]
`indent` option added in https://github.com/haozhu233/kableExtra/commit/2742ffce5b74ee3d83854d6f628f2a61bc30fd4e

**Comment by Rekyt** [comment]
Thank you! That was really quick ;)

**Comment by nmahser** [comment]
Hey @haozhu233, I updated the package and still can't see option "indent". Could you please tell if anything else I needed to do? Also, thanks a lot for creating kableExtra. It makes life very much easier.

**Comment by Rekyt** [comment]
Hi @nmahser, have you tried installing it from github? You can do it by using the following code:

```r
# if the package devtools is not installed you can uncomment the following line
# install.packages("devtools")
devtools::install_github("haozhu233/kableExtra")
```

**Comment by nmahser** [comment]
Hi @Rekyt, thanks for the reply. I have been trying to do that but having some errors. Will figure it out soon, hopefully:)
