### ISSUE TITLE
str_replace_all needs a vector, not a dataframe

### ISSUE THREAD

**Issue by triceraflops** [haozhu233/kableExtra#285]
**Describe the bug**
From lines 25, 32 in the linebreak.R file.

stringr::str_replace_all needs a vector, otherwise the result seems to be not predictable. I say not predictable because I've been getting different results. But the constant thing is that it's not working with a dataframe.

The linebreak function works correctly when all cells have the newline '\n' character. Otherwise it just returns numbers.

**To Reproduce**
From the documentation - with the value column modified so there's no linebreaks.
```{r echo=F, message=F}
dt_lb <- data.frame(
  Item = c("Hello\nWorld", "This\nis a cat"),
  Value = c("Hello world", "This is a cat")
)
dt_lb %>%
  mutate_all(linebreak) %>%
  kable("latex", booktabs = T, escape = F,
        col.names = linebreak(c("Item\n(Name)", "Value\n(Number)"), align = "c"))
```

Another example
```{r echo=F, message=F}
df <- data.frame(col1 = c("old text 1", "old text 2", "old text 3"),
                 col2 = c("tri", "cera", "flops"))

#With the dataframe
str_replace_all(df, "old", "new")

#With the first column of the dataframe
str_replace_all(df$col1, "old", "new")

#With the second column of the dataframe
str_replace_all(df$col2, "old", "new")
```

It should be an easy fix, so I can work on this if you like.

**Comment by haozhu233** [comment]
Hmm, in the example you provided, the reason why it didn't work is that the Value column is a factor.

If you do 
```
dt_lb <- data.frame(
  Item = c("Hello\nWorld", "This\nis a cat"),
  Value = c("Hello world", "This is a cat"),
  stringsAsFactors = F
)
dt_lb %>%
  mutate_all(linebreak) %>%
  kable("latex", booktabs = T, escape = F,
        col.names = linebreak(c("Item\n(Name)", "Value\n(Number)"), align = "c"))
```
it will work. 

I'm adding a character conversion step to `linebreak` (https://github.com/haozhu233/kableExtra/commit/3e0e2b108e8ee1f91e3d105f576288a6dc38c21f) so in the future you don't need to worry about this kind of issues.

**Comment by triceraflops** [comment]
Ooops sorry! I didn't think of that. I've spent too much time using tibbles.
