### ISSUE TITLE
Suggestion:  transpose method for kable objects

### ISSUE THREAD

**Issue by dmurdoch** [haozhu233/kableExtra#288]
This is a suggestion for a new feature, rather than a bug report.

This user on Stackoverflow:  https://stackoverflow.com/q/53050266/2554330 had problems because they wanted to display a transposed table, but the transposing converted numbers to character and messed up the special formatting they were requesting.

Clearly it would be better to format first, transpose second.  The base `t()` function can't do that because a `knitr_kable` object is just a character string, but perhaps `kableExtra` can decode enough information about the structure that it could do a transpose.

**Comment by haozhu233** [comment]
@dmurdoch Thanks for your suggestion! I sort of like the approach camille provided in the answer. I feel like both the `round` and `big.mark` options provided in `kable` are just for convenience but people always have options to do the customization ahead of game. At the same time, transposing sounds like a very heavy transition to me. I'm just afraid having a function like this will open a can of worms. Hmm, I will think about it.

**Comment by dmurdoch** [comment]
Sure, that makes sense.  Feel free to close the issue.
