### ISSUE TITLE
\caption{} instead of \caption[]{} has the caption repeated in list of tables for each page

### ISSUE THREAD

**Issue by fkroener** [haozhu233/kableExtra#29]
With the fix for the multiply definition of \label in #25 I see we have another issue, which was actually the reason I opened #25.

With `\listoftables` in latex we have repeated entries for each page the table appears on, e.g.

this list of tables . . . . . . . . . . . . . . . . . . . . . . .  192 
this list of tables (cont)  . . . . . . . . . . . . . . . . . . .  202  
this list of tables (cont)  . . . . . . . . . . . . . . . . . . .  212  
this list of tables (cont)  . . . . . . . . . . . . . . . . . . .  222  
this list of tables (cont)  . . . . . . . . . . . . . . . . . . .  232

Changing `\caption{}` to `\caption[]{}` would only list the first caption. 
Unsure whether this warrants an option.

**Comment by haozhu233** [comment]
Fixed now. Please download the latest dev version. :)
