### ISSUE TITLE
trouble inserting linebreak in a cell containing string

### ISSUE THREAD

**Issue by bjce** [haozhu233/kableExtra#295]
First of all thank you very much for writing and maintaining `kableextra`: I really appreciate using this package!

**Describe the bug**
I want to insert a linebreak into a cell of text but can't. In the example below, I want to insert a linebreak between the string `group 1.1` and `group1.2`

I tried to read the documentation [("Best Practice for newline in LaTeX table")](https://haozhu233.github.io/kableExtra/best_practice_for_newline_in_latex_table.pdf) but couldn't solve the problem

Here is the code: 

```
library(dplyr)
library(knitr)
library(kableExtra)

mydf <- data.frame(
  # group = rep(letters[1:4], each = 2),
  row = c(1:8),
  group = c("group 1.1 \n group1.2", "group 2", "group 3", "group 4", "group 5", "group 6", "group 7", "group 8")
)

mydf %>%
# mutate_all(linebreak) %>%
kable() %>%
   kable_styling()
```

If I insert `mutate_all(linebreak) %>%` it doesn't solve the problem neither

I also tried the following piece of code 

```
library(dplyr)
library(knitr)
library(kableExtra)

mydf <- data.frame(
  # group = rep(letters[1:4], each = 2),
  row = c(1:8),
  group = c("group 1.1\ngroup1.2", "group 2", "group 3", "group 4", "group 5", "group 6", "group 7", "group 8")
)

mydf %>%
  mutate_all(linebreak) %>%
  kable("latex", escape = FALSE) %>%
  kable_styling()
```

The output is as expected when I perform `knit to pdf` however, there is no output if I do `knit to html` (and I want to copy the output to a word document)

**Comment by haozhu233** [comment]
Hi, @bjce, right now linebreak only works in latex. :P I thought for html, there shouldn't be a problem because `<br>` was so easy to add. However, now thinking about cross-format consistency, I feel like it might be a good idea to add this feature on.

**Comment by bjce** [comment]
Thank you very much for your answer @haozhu233. Again a big thank you for writing the package. It's really great and make beautiful tables. In the meantime I indeed found the `<br>` command and it works and this is why i closed the issue. However, another problem has emerged: I'm trying to print the sign `±` in a string of the type: `3.30&plusmn;0.23 (n=33)`. The output of the R notebook works find, i.e.: the string appears correctly with the `±` sign. However when I do a `knit to html`, all the the strings containing `&plusmn;` disappear. Unfortunately I couldn't reproduce the problem in small code and the table where the problem is very big with data to be published... Do you have any ideas?

**Comment by haozhu233** [comment]
Hi, @bjce, if `html` is your targeting format (no matter html_document or in notebook), I think just putting ± as symbol will work. Maybe you want to give it a try?

**Comment by bjce** [comment]
thank you for your answer @haozhu233. Well I tried that many times already
but the output is then `3.30??0.23 (n=33)` instead of `3.30± 0.23 (n=33)`

**Comment by bjce** [comment]
thank you for your answer @haozhu233. Well I tried that many times already
but the output is then `3.30??0.23 (n=33)` instead of `3.30± 0.23 (n=33)`

**Comment by haozhu233** [comment]
[Archive 4.zip](https://github.com/haozhu233/kableExtra/files/2601268/Archive.4.zip)

Hmm, it seems to be working for me. Please see the example. You might want to make sure your encoding is correct.

**Comment by bjce** [comment]
thank you again. Well the output in R notebook is correct. But the output of the html document gives me `group 1.1 <U+00B1> group1.2`
