### ISSUE TITLE
column_spec width fails with different screen resolution

### ISSUE THREAD

**Issue by Gateux** [haozhu233/kableExtra#298]
I set a specific column width (in pixels) for each column in my HTML table. This works fine on my widescreen, however, if the window is not maximized or I run the code on some smaller screen, column width fails, not even the proportions are being kept. I have tried all combinations of style and full_width option.

**Comment by haozhu233** [comment]
@Gateux Based on your description, I think you can try out the `width_min` option.

**Comment by Gateux** [comment]
True. This was an example of a dumb question. Please close, possibly delete :) Thank you

**Comment by haozhu233** [comment]
@Gateux no worries. this kind of question is hard to describe. :)
