### ISSUE TITLE
LaTeX math expression in group of columns header

### ISSUE THREAD

**Issue by stla** [haozhu233/kableExtra#30]
Hello, 

 The `kable` function has an option `escape` which allows to have LaTeX math expressions in the table - see <https://stackoverflow.com/questions/45391566/latex-math-expression-in-knitr-kable-sweave>

Is it possible to have a LaTeX math expression in the header of some grouped columns ? I'm afraid no, currently.

```
\documentclass{article}
\usepackage{booktabs}
\begin{document}

<<>>=
library(knitr)
library(kableExtra)
dat <- mtcars[1:5,1:5]
options(knitr.table.format = "latex")
@

<<results='asis'>>=
names(dat)[1] <- "$x^2$"
kable(dat, booktabs = TRUE, caption = "My table", escape = FALSE) %>% 
  add_header_above(c("", "", "$x^3$" = 4))
@

\end{document}
```

![capture](https://user-images.githubusercontent.com/4466543/28764317-fe960b28-75c4-11e7-96ac-bcf1509b3d44.PNG)

**Comment by haozhu233** [comment]
You are correct. Currently kableExtra will escape everything. It makes sense to add an escape option. I will work on that later.

**Comment by igorstorm** [comment]
I want to know that too! Is this fixed?

**Comment by haozhu233** [comment]
@igorstorm Yeah, most of the kableExtra functions has an escape option now.

**Comment by igorstorm** [comment]
How about greek letters? I tried:
`add_header_above(c("n", "$\\alpha$" = 4, "$\\beta$" = 4), align = "l", escape = F)`
But it doesn't show the greek letters. Do I have to do it differently?

**Comment by wuffi** [comment]
Sorry for writing to an old issue,
For me, the following code doesn't work:

    ---
    output: pdf_document
    ---

    ```{r echo=F}
      library(kableExtra)
      x <- matrix(1:4, ncol=2)
      knitr::kable(x, col.names=c('A', 'B'), align = 'c', 'latex', booktabs = T) %>%
        add_header_above(c("$x^2$" = 2))
    ```

**Comment by wuffi** [comment]
Stupid me. It does of course work, one just needs to set the `escape = F` option for the `add_header_above()` function as in:

    ---
    output: pdf_document
    ---
    
    ```{r echo=F}
      library(kableExtra)
      x <- matrix(1:4, ncol=2)
      knitr::kable(x, col.names=c('A', 'B'), align = 'c', 'latex', booktabs = T) %>%
        add_header_above(c("$x^2$" = 2), escape = F)
    ```

I hope this will also be helpful to others.
