### ISSUE TITLE
Row labels misaligned when using collapse_rows in continued longtable 

### ISSUE THREAD

**Issue by adityabandla** [haozhu233/kableExtra#314]
longtable with collapse_rows renders properly in a PDF if the table fits within one page. However, once the table is bigger than one page, text in the top most row (in the collapsed rows) always gets misaligned in the beginning of the next page 

I tried changing the valign option to "top", but the same thing happens

![image](https://user-images.githubusercontent.com/17331245/50485756-8efaff00-0a31-11e9-9f31-d1bef38dbafb.png)

**Comment by haozhu233** [comment]
Hi, @adityabandla it's always tricky to let multirow & longtable work together. You can find similar questions on Tex Exchange. For example
https://tex.stackexchange.com/questions/52100/longtable-multirow-problem-with-cline-and-nopagebreak
https://tex.stackexchange.com/questions/64956/prevent-longtable-breaking-in-multirow

The solution provided there are quite manual and are kind of difficult to get implemented in this package. Also, it sounds like a pure latex issue, which sort of drops out of the scope of this package.

**Comment by haozhu233** [comment]
````
---
title: "Test"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(kableExtra)
```

## Test

```{r kable, echo=FALSE}
dt <- mtcars %>%
  rownames_to_column()
long_dt <- bind_rows(dt, dt, dt, dt) %>%
  arrange(rowname)
kable(long_dt, "latex", longtable = T, booktabs = T) %>% 
  kable_styling(latex_options = c("repeat_header")) %>%
  collapse_rows(1, valign = "top", latex_hline = "none") %>%
  row_spec(43, extra_latex_after = "\\pagebreak")
```
````

I'm including the reproducible example I was using in case anyone want to solve this issue.

**Comment by krlmlr** [comment]
If we assume that each group fits one page, we can add `\nopagebreak` requests and `\pagebreak[0]` hints, which seem to do the job. I changed the example to `latex_hline = "major"` to be able to detect group ends.

Maybe kableExtra could support this as an option?

`````rmd
---
title: "Test"
output:
  pdf_document:
    keep_tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(kableExtra)
```

## Test

```{r kable, echo=FALSE}
dt <- mtcars %>%
  rownames_to_column()
long_dt <- bind_rows(dt, dt, dt, dt) %>%
  arrange(rowname)
kable(long_dt, "latex", longtable = T, booktabs = T) %>% 
  kable_styling(latex_options = c("repeat_header")) %>%
  collapse_rows(1, valign = "top", latex_hline = "major") %>% 
  gsub("\\\\\\\\($|\n)", "\\\\\\\\\\\\nopagebreak\\1", .) %>% 
  gsub("\\cmidrule", "\\pagebreak[0]\\cmidrule", ., fixed = TRUE)
```
`````

![Screenshot from 2020-08-02 06-42-48](https://user-images.githubusercontent.com/1741643/89115712-bc205680-d48b-11ea-93e7-b410c0e30225.png)

**Comment by haozhu233** [comment]
@krlmlr wow, this is magic!

I will add this as an option of collapse_rows. Let's call it `clean_cut`. Are there any downside for this approach? I want to set it as the default behavior. 

PS: the dark page looks very cool!

**Comment by krlmlr** [comment]
I've seen that without longtable the intermediate breaks are formatted nicer in general, I'm not sure this is related to my change. I'll share a reprex when I have a chance.

Of course, if a group is larger than one page, the table will run over. Other than that I'm not aware of problems here.

**Comment by haozhu233** [comment]
@krlmlr I see. I tested it around and I really like this approach. I will set it as default for longtable then. It will be called `longtable_clean_cut` with default `T`. Thanks a lot for this suggestion.

**Comment by krlmlr** [comment]
Thanks for picking this up. I'm wondering if we could make this work also for `"full"` and `"linespace"` -- looks like we only need to adapt the regex for `cmidrule`?

**Comment by haozhu233** [comment]
@krlmlr That was also what I was planning to. However, after I made such changes (minor groups: cmidrule + nopagebreak; major group: cmidrule + pagebreak hint), the major group still broke in half. :(

**Comment by krlmlr** [comment]
Thanks again, works for me without any workarounds!
