### ISSUE TITLE
Lose row indentation with last row in table with group_row when repeat_header is used

### ISSUE THREAD

**Issue by ph492** [haozhu233/kableExtra#316]
Thank you for such a brilliant package! 

** Lose row indentation with last row in table with group_row when repeat_header is used **
When a long table is produced without the latex option `repeat_header`, all rows are neatly indented using the `group_row` function. When the `repeat_header` function is used, the final row indentation is lost, I believe because it counts the repeated header as an extra row.  To compensate for this I have tried adding an extra row to the group, however I get the error: `there aren't that many rows in the table`.

```
---
title: "repeat_header with group_row bug?"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(knitr)
library(kableExtra)
```

A table with 64 rows

```{r cars, echo = FALSE}
long_dt <- rbind(mtcars, mtcars)
kable(long_dt, "latex", longtable = T, booktabs = T, caption = "Longtable") %>% 
  add_header_above(c(" ", "Group 1" = 5, "Group 2" = 6)) %>% 
  kable_styling(latex_options = c("repeat_header")) %>%
  group_rows("Group 1", 1, 32) %>%
  group_rows("Group 2", 33, 64)
```
```

<img width="405" alt="long_table" src="https://user-images.githubusercontent.com/33718887/50551236-72e79f80-0c75-11e9-898b-505dcd3f7434.png">

**Comment by haozhu233** [comment]
@ph492 Thanks for reporting this bug! The reason was that `repeat_header` adds a * to the end of last row. I loosen the regex criteria a little bit this time so that this little star won't be considered.

**Comment by ph492** [comment]
Thank you, really appreciate all your work on this excellent package
