### ISSUE TITLE
solve_enc() does not preserve object attributes

### ISSUE THREAD

**Issue by martinschmelzer** [haozhu233/kableExtra#320]
When using `latex_options = "striped"` (any other would work as well I guess), the error

```
Error in if (!kable_format %in% c("html", "latex")) { : 
  Argument of length 0
```
is raised.

**To Reproduce**

```
kable(mtcars, format = "latex") %>% kable_styling(latex_options = "striped")
```

**Comment by martinschmelzer** [comment]
Possible solution:

```
# Solve enc issue for LaTeX tables
solve_enc <- function(x) {
  #may behave differently based on Sys.setlocale settings with respect to characters
  out <- enc2utf8(as.character(base::format(x, trim = TRUE, justify = 'none')))
  mostattributes(out) <- attributes(x)
  out
}
```

**Comment by haozhu233** [comment]
Are you using the latest github version? I just made some changes to this “striped”. I’m wondering if this change causes this bug.

**Comment by martinschmelzer** [comment]
Just reinstalled from the master branch and got the same error.

**Comment by haozhu233** [comment]
Can you tell me which version of knitr are you using?

**Comment by martinschmelzer** [comment]
`knitr_1.21.6`

**Comment by haozhu233** [comment]
@martinschmelzer Fixed now. Thanks for your suggestion!

**Comment by haozhu233** [comment]
@martinschmelzer Just fixed another bug with the new striped rows.

**Comment by martinschmelzer** [comment]
Can imagine. After I fixed the first one, I had an error with the 
`striped_index` being out of bounds concerning the number of rows in 
`table_info$contents` element. Will play around tomorrow to see if it is 
still reproducible.

Am 7. Januar 2019 18:20:47 schrieb Hao Zhu <notifications@github.com>:

**Comment by martinschmelzer** [comment]
Can imagine. After I fixed the first one, I had an error with the 
`striped_index` being out of bounds concerning the number of rows in 
`table_info$contents` element. Will play around tomorrow to see if it is 
still reproducible.
