### ISSUE TITLE
longtable repeat_header_text not ignored when html output format

### ISSUE THREAD

**Issue by hansvancalster** [haozhu233/kableExtra#326]
Knitting an rmarkdown html_document fails when including `repeat_header_text = "\\textit{(foo)}` as an argument in `kable_styling()`. Would it be possible to make the below chunk work as expected for both pdf and html output? 

Reproducible example (using kableExtra_0.9.0):

````
---
output: 
  rmarkdown::html_document
---
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(kableExtra)

long_dt <- rbind(mtcars, mtcars)
```

```{r eval = FALSE}
# this won't work
kable(long_dt, 
      longtable = T, 
      booktabs = T, 
      caption = "Longtable") %>%
  kable_styling(latex_options = "repeat_header",
                bootstrap_options = "hover",
                repeat_header_text = "\\textit{(foo)}"
                )
```
````

Results in the following error:

```
Quitting from lines 11-25 (test_kableextra.Rmd) 
Error in htmlTable_styling(kable_input, bootstrap_options = bootstrap_options,  : 
  unused argument (repeat_header_text = "\\textit{(foo)}")
Calls: <Anonymous> ... freduce -> withVisible -> <Anonymous> -> kable_styling
Execution halted
```

PS: After removing `repeat_header_text = "\\textit{(foo)}"` the document can be knitted to html. 

```{r}
kable(long_dt, 
      longtable = T, 
      booktabs = T, 
      caption = "Longtable") %>%
  kable_styling(latex_options = "repeat_header",
                bootstrap_options = "hover"
                )
```

**Comment by haozhu233** [comment]
Hey, @hansvancalster, thanks for reporting this! I think this issue is gone in the develop version. Please check it out. Also, I made some edits on your issue to make it look better. Basically, on github you can put ```` outside of things like rmd to make it look like code.
