### ISSUE TITLE
bug when longtable starts at the top of a page

### ISSUE THREAD

**Issue by stla** [haozhu233/kableExtra#33]
Hello, 

 This is the `Rnw` file:

```
\documentclass{article}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage[table]{xcolor}
\usepackage{lipsum}
\begin{document}

<<setup, include=FALSE>>=
library(knitr)
opts_chunk$set(echo=FALSE)
library(kableExtra)
options(knitr.table.format = "latex")
dat <- mtcars
@

\lipsum[3-6]

a

b

c

d

e

f

g

<<results='asis'>>=
kable(dat, booktabs = TRUE, longtable = TRUE, caption = "My table") %>%
  kable_styling(latex_options = c("repeat_header", "striped")) 
@

\end{document}
```

And the output: 

![capture](https://user-images.githubusercontent.com/4466543/28872086-db5244e6-7787-11e7-871c-8e1297756575.PNG)

Do you have an idea ? Otherwise I can open an issue on texstackexchange. I will firstly search if this issue is a known one.

**Comment by stla** [comment]
I don't manage to get this bug when I add a line break before the table:

```
..........

f

g \\

<<results='asis'>>=
kable(dat, booktabs = TRUE, longtable = TRUE, caption = "My table") %>%
  kable_styling(latex_options = c("repeat_header", "striped")) 
@
```

Maybe it's a good practice to include this line break...

**Comment by stla** [comment]
Issue opened here: https://tex.stackexchange.com/questions/384422/issue-with-longtable-starting-at-the-top-second-caption-appears-first

**Comment by stla** [comment]
Again, the solution given by Ulrike Fischer works:

```
......
\usepackage{needspace}
\begin{document}

.......

\Needspace{6\baselineskip}
<<results='asis'>>=
kable(dat, booktabs = TRUE, longtable = TRUE, caption = "My table") %>%
  kable_styling(latex_options = c("repeat_header", "striped")) 
@
```

But the choice of the space depends on the height of the header. For example I've used `\Needspace{24\baselineskip}` for my real issue with a large header.

I don't know whether this code should be automatically inserted by `kableExtra`... One can manually insert it as above. But it's nice to know this solution.

**Comment by stla** [comment]
Ulrike Fisher has posted a better solution with the `xpatch` package. As I understand, this is a bug of the `longtable´ package which will be fixed in a next release. Therefore I close this issue.

**Comment by haozhu233** [comment]
Great! Sorry, I was on my way of traveling recently. Based on what I read from the answer and your conclusion, I also feel like we should keep `kableExtra` as is right now. It's nice that you post it here so people with similar problem may find a solution easier.
