### ISSUE TITLE
kable_styling no longer working on linux x86_64 environment for version 1.0.0

### ISSUE THREAD

**Issue by jmerone** [haozhu233/kableExtra#330]
Hello,

I currently use a databricks notebook to run R commands. kableExtra is no longer working with release 1.0.0
`library(kable)
library(kableExtra)

some_dataframe <- data.frame(Mean = 2.5, Median = 3, SD = 6)

some_dataframe %>%
kable() %>%
kable_styling()`

Here is my system information:
 sysname 
                                     "Linux" 
                                     release 
                            "4.4.0-1072-aws" 
                                     version 
"#82-Ubuntu SMP Fri Nov 2 15:00:21 UTC 2018" 
                                    nodename 
           "0713-123859-byte3-10-60-250-232" 
                                     machine 
                                    "x86_64" 
                                       login 
                                   "unknown" 
                                        user 
                                      "root" 
                              effective_user 
                                      "root" 
I see in the CRAN check that there was a warning: [Check](https://cran.r-project.org/web/checks/check_results_kableExtra.html)

**Comment by haozhu233** [comment]
@jmerone The CRAN check you see is for 0.9.0 and I think I fix the problem with 1.0.

Did you install from source for this package? It was updated like 2 days ago. 

Can you describe your error in details? Thanks!

**Comment by SebVen** [comment]
This issue may be related to mine on Windows 10 x64.
When a table is produced by `kable_styling()` it appears in the Viewer, but not below the chunk in an RMarkdown document. This is a kableExtra specific problem as simply using `kable()` without `kable_styling()` still works fine i.e. the table appears below the chunk.

**Comment by haozhu233** [comment]
@SebVen Thanks! I did make some changes to kable_styling in this update. Is it a notebook only problem? Can you also provide me the code? I’m at rstudio conf right now but will check it out this weekend.

**Comment by robertpdx** [comment]
I'm having the same issue with 1.0.0 on Win 7 x64. R version is 3.5.0 but I had the same issue on another PC with 3.5.2.  R-Studio is 1.1.453.  All my other CRAN packages are updated to the latest as of today (19JAN19).

My kable call inside a chunk is 
```
    print(kable(data) %>%
            kable_styling(bootstrap_options=c('striped', 'condensed')))
```
It no longer renders the tables in the preview or browser.  I rolled back to 0.9.0 and got it working again.

**Comment by haozhu233** [comment]
@SebVen I see. I didn't realize this problem because I usually don't use the notebook (or in-line output) feature. I will look into that. If this thing is fixable, I will make a CRAN release soon for this behavior. Thanks for the additional info!

**Comment by haozhu233** [comment]
I think I located the problem. It was because I removed the `print()` statement in https://github.com/haozhu233/kableExtra/commit/76762d80a3f084b0854afc92ec26709d30c0bd27#diff-bd6a00680436bea1540d52d8317c687d. Now I'm putting it back and will submit a CRAN update soon.

**Comment by SebVen** [comment]
@haozhu233 Excellent, many thanks

**Comment by haozhu233** [comment]
@SebVen Great! I will treat this issue as solved. I will fix a few extra unresolved issue today and submit it to CRAN tonight.
