### ISSUE TITLE
group_rows names are dropped when using longtable and repeat_header

### ISSUE THREAD

**Issue by steveputman** [haozhu233/kableExtra#331]
Something in the recent changes has broken how the captions for group_rows are handled. Removing *either* `longtable = T` from `kable()` or `repeat_header` from `kable_styling()` fixes the error, but then the formatting is adversely affected. Seems to affect single-row groups, which leads me to believe it may be related to #316 ?

````
---
title: ''
editor_options: null
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
output:
 pdf_document:
   keep_tex: yes
   latex_engine: xelatex
chunk_output_type: inline
---

```{r setup, echo=FALSE}

library(tidyverse)
library(knitr)
library(kableExtra)

df <- tribble(
  ~Type, ~Subtype, ~Units,
  "A", "B", 100,
  "C", "D", 200) %>%
  arrange(Type, Subtype)

gr <- count(df, Type)
gr <- setNames(gr$n, gr$Type)

df %>% select(-Type) %>%
  kable(longtable = TRUE) %>%
  kable_styling(latex_options = c("repeat_header")) %>%
  group_rows(index = gr)

```

````

[test_group_rows.pdf](https://github.com/haozhu233/kableExtra/files/2784359/test_group_rows.pdf)

**Comment by haozhu233** [comment]
Yeah, thanks to this issue, I recognized a bug that is related to #303 and a few others. I will work on this and it should be fixed by the next release

**Comment by haozhu233** [comment]
I just fixed this bug. Previously it was trying to use a `booktabs` rule on a non-booktabs table. :P
