### ISSUE TITLE
Is kableExtra compatible with sparklines?

### ISSUE THREAD

**Issue by VictorNautica** [haozhu233/kableExtra#336]
I have some issues trying to get sparklines getting to work with kableExtra. [This ](https://stackoverflow.com/questions/54244718/combining-sparkline-in-kableextra-table) person has a similar issue. I understand kableExtra is compatible with formattable - but when I try and throw htmlwidgets in to the mix I get the error:

```
Error in UseMethod("as.htmlwidget") : 
  no applicable method for 'as.htmlwidget' applied to an object of class "c('kableExtra', 'knitr_kable')"
```

Where I modified zoowalk's code to make it more similar to my issue:

```
library(sparkline)
library(tidyverse)
library(formattable)
library(kableExtra)

df <- data.frame(stringsAsFactors=FALSE,
                 V1 = c("country", "A", "B", "C"),
                 V2 = c(2000L, 100L, 600L, 50L),
                 V3 = c(2001L, 200L, 500L, 60L),
                 V4 = c(2002L, 300L, 400L, 70L),
                 V5 = c(2003L, 400L, 300L, 80L),
                 V6 = c(2004L, 500L, 200L, 90L),
                 V7 = c(2005L, 600L, 100L, 100L)
)

df.names <- df[1,]
names(df) <- df.names
df <- df[-1,]

graph <- df %>% 
    group_by(country) %>% 
    gather(key=year, value=value, -country) %>% 
    summarise(graph=spk_chr(
        value, 
        chartRangeMin = 0,
        type="line"))

df2 <- left_join(df, graph, by=c("country"))


df2 %>%
    kable("html", caption="Title", escape=T) %>% 
    kable_styling("striped", full_width = F) %>%
    group_rows("group1", 1, 2) %>%
    group_rows("group2", 3,3) %>% 
    as.htmlwidget() %>% 
    spk_add_deps()
```

Is there a way to get sparklines working in conjunction with kableExtra? kable is by far my favourite table package for Markdown so it will be a shame if I can't get the widgets to work.

**Comment by haozhu233** [comment]
@VictorNautica Yeah, it's possible. The trick is to call `sparkline(0)` somewhere on your document so all its dependencies get loaded. I wrote a document last year using this trick. You can check it out. https://cranky-chandrasekhar-cfefcd.netlify.app/
