### ISSUE TITLE
Writing a pdf table cause html tables of the same name to be deleted

### ISSUE THREAD

**Issue by mattnolan001** [haozhu233/kableExtra#338]
Using kableExtra::save_kable, I find that saving as a pdf causes a previously saved html table with the same name to be deleted.

In this example:
```
df <- data.frame(a = c(1:4), b = c(5:8))
df <- kableExtra::kable(df)
kableExtra::save_kable(df, file = "table.html")
kableExtra::save_kable(df, file = "table.pdf")
```
only table.pdf is saved.

After swapping the order:

```
df <- data.frame(a = c(1:4), b = c(5:8))
df <- kableExtra::kable(df)
kableExtra::save_kable(df, file = "table.pdf")
kableExtra::save_kable(df, file = "table.html")
```
both tables are now saved.

This gives a fix, but I'm wondering if this behavior is by design and whether it can be modified without re-ordering the code.

**Comment by mattnolan001** [comment]
That would be helpful. Thanks.

**Comment by vincentarelbundock** [comment]
This problem looks fixed in the most recent dev version on Github. Feel free to comment again if you still encounter it.
