### ISSUE TITLE
row_spec for the footnote?

### ISSUE THREAD

**Issue by etesdahl** [haozhu233/kableExtra#339]
Idea for a small added feature: row_spec style modification of the footnote.

My short term work-around for an HTML table:

```{r}
library(knitr); library(kableExtra)
mydt <- mtcars

table1 <- kable(mydt[1:5,]) %>%
    row_spec(1:5, bold = T, color = "white", background = "#377eb8") %>%
    row_spec(0, bold = T, color = "white", background = "#4daf4a") %>%
    footnote(general="kableExtra is a very useful package!", general_title = "")

table1<- gsub(table1, 
             pattern="padding: 0; border: 0", 
             replacement="padding: 0; border: 0; color: white;background-color: #4daf4a;")
table1
```

The pattern I use in gsub seems unlikely to work every time depending on circumstances - is there any discussion of making row_spec compatible with the foot note?

Thanks for this excellent package!

**Comment by wibeasley** [comment]
A few comments on your workaround: 
1. I think `sub()` is sufficient.
1. make sure there's not another digit or decimal immediately after the leading zero.  Maybe this works:
    ```r
    padding: 0[^\\d\.]?; border: 0[^\\.\\d]
    ```

1. be more forgiving if the white spaces aren't exact.  Of the top of my head, maybe change to

    ```r
    padding:\\s*0[^\\d\.]?;\\s*border:\\s*0[^\\.\\d]
    ```

1. Maybe allow a different order of the parameters.  I guess use alternation?

https://regex101.com/r/Yb1avK/2

Since this is probably a personal workaround, the last one might not be worth the effort, since you're the one controlling the input

**Comment by haozhu233** [comment]
@wibeasley Thanks a lot for your help as always!

@etesdahl Right now it seems quite difficult to come up with an elegant grammar to talk about this. However, in this case, you can think about using `kable_as_xml` and `xml_as_kable` to do it in the hard way. You can take a look at this doc for an example: https://haozhu233.github.io/kableExtra/kableExtra_and_xml2.html

```
library(kableExtra)
library(xml2)
mydt <- mtcars

table1 <- kable(mydt[1:5,]) %>%
  row_spec(1:5, bold = T, color = "white", background = "#377eb8") %>%
  row_spec(0, bold = T, color = "white", background = "#4daf4a") %>%
  footnote(general="kableExtra is a very useful package!", general_title = "")

table1_xml <- kable_as_xml(table1)

table1_xml %>%
  xml_child(3) %>%   # select tfoot <tfoot>
  xml_child(1) %>%   # select 1st row in tfoot <tr>
  xml_child(1) %>%   # select 1st cell in the 1st row <td>
  xml_set_attr("style", "padding: 0; border: 0; color: white;background-color: #4daf4a;")

xml_as_kable(table1_xml)
 ```

For all HTML features, kableExtra uses xml to do these things. If you are familiar with xpath, you can even simplify the call to be

```
table1_xml %>%
  xml_find_all("//tfoot//tr//td") %>%
  xml_set_attr("style", "padding: 0; border: 0; color: white;background-color: #4daf4a;")
```

**Comment by etesdahl** [comment]
Thank you very much @wibeasley  and @haozhu233 , I appreciate the suggestions.
