### ISSUE TITLE
column_spec destroys alignment 

### ISSUE THREAD

**Issue by nielsaka** [haozhu233/kableExtra#340]
## Problem

In LaTeX, when specifying the width of multiple columns as a vector in a single `column_spec` call, the column alignment is broken.

## Details

For example
```
library(kableExtra)
df <- dplyr::storms[1:5, 1:5]

kable(df, format = "latex", align = c("r", "c", rep("r", ncol(df) - 2))) %>%
  column_spec(1:2, width = c("7em", "5em"))
```

will successfully set the column width of the first column to 7em and of the second column to 5em. However, the centered alignment of the second column is broken. Instead, the alignment of the first column will be repeated. In LaTeX

```
\begin{tabular}{>{\raggedleft\arraybackslash}p{7em}|>{\raggedleft\arraybackslash}p{5em}|r|r|r}
```

There is a warning message

> Warning message:
> In table_info$align_vector[column] <- unlist(lapply(table_info$align_vector_origin[column],  :
>   number of items to replace is not a multiple of replacement length

## Workaround

With two separate calls to `column_spec` it works

```
kable(df, format = "latex", align = c("r", "c", rep("r", ncol(df) - 2))) %>%
  column_spec(1, width = "7em") %>%
  column_spec(2, width = "5em")
```
and the output is

```
\begin{tabular}{>{\raggedleft\arraybackslash}p{7em}|>{\centering\arraybackslash}p{5em}|r|r|r}
```

## Suggestion

As a user I would either wish 

* the behaviour documented ("a single character string for all columns") 
* or, even better, an error to be thrown when `width` is of length greater than one
* or, even better again, the alignment of each column is correctly adjusted.

## P.S.

love the package!

**Comment by paulrougieux** [comment]
I have the same warning "number of items to replace is not a multiple of replacement length" with this reproducible example:

```
iris %>% 
    head()  %>%
     knitr::kable(format='latex') %>%
    kableExtra::column_spec(1:2, width = c("5cm","5cm"))

\begin{tabular}{>{\raggedleft\arraybackslash}p{5cm}|>{\raggedleft\arraybackslash
}p{5cm}|r|r|l}
\hline
Sepal.Length & Sepal.Width & Petal.Length & Petal.Width & Species\\
\hline
5.1 & 3.5 & 1.4 & 0.2 & setosa\\
\hline
4.9 & 3.0 & 1.4 & 0.2 & setosa\\
\hline
4.7 & 3.2 & 1.3 & 0.2 & setosa\\
\hline
4.6 & 3.1 & 1.5 & 0.2 & setosa\\
\hline
5.0 & 3.6 & 1.4 & 0.2 & setosa\\
\hline
5.4 & 3.9 & 1.7 & 0.4 & setosa\\
\hline
\end{tabular}
Warning message:
In table_info$align_vector[column] <- unlist(lapply(table_info$align_vector_orig
in[column],  :
  number of items to replace is not a multiple of replacement length
```

**Comment by haozhu233** [comment]
Hi, @paulrougieux, you can check out the documentation. https://haozhu233.github.io/kableExtra/awesome_table_in_html.html#Column_spec The vector support in `column_spec` is supposed to let you customize each cell in one column. In your case, since both width are 5cm, you just need `width = "5cm"`.

@nielsaka Sorry for the very late reply! ❤️ your comments! Also, thanks for the solution you posted!

**Comment by paulrougieux** [comment]
@haozhu233 thanks but of course In my real use case I wanted to use 2 different column widths. I updated the example above with 2 different column widths. What can we do about this warning message?
