### ISSUE TITLE
Deletion of html results and lib directory when using kable_save

### ISSUE THREAD

**Issue by ghaarsma** [haozhu233/kableExtra#343]
When using kable_save to save as image or when creating a self-contained html, `kable_save` aggressively deletes file(s) and directories. This affects mostly the files it is outputting it self, but nn the worst case it could delete files it did not create itself. Anybody running `kable_save` would loose all contents inside any lib directory at the end of the file path (the path contained in within the file argument). 

I have create pull request #342 that should take care of the issue.

Thanks for the otherwise awesome package!
Gabe

``` r
library(knitr)
library(kableExtra)

df <- data.frame(x=1:11,y=rnorm(11),z=LETTERS[1:11])

x <- kable(df) %>% kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

# First create a html then a png, the png procedure will remove the html
save_kable(x, 'test1.html')
save_kable(x, 'test1.png')
file.exists('test1.html')
#> [1] FALSE

# First create a html (not self-contained), then create a self contained html
save_kable(x, 'test2a.html', self_contained = FALSE)
dir.exists('lib')
#> [1] TRUE
save_kable(x, 'test2b.html', self_contained = TRUE)
dir.exists('lib')
#> [1] FALSE
```

**Comment by haozhu233** [comment]
Yeah, this is a good suggestion! Thanks for the PR!
