### ISSUE TITLE
math expression in column name

### ISSUE THREAD

**Issue by sallyroman27** [haozhu233/kableExtra#355]
Compile PDF fails with escape=F for kable

I am using Rstudio with pdfLaTex as the compiler.  
R session info: 
sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

I have a dataframe sourced from an external R file.  My original dataframe has 770 rows and 11 columns. I want to have the name of a column include the term m^2.  When I set escape=F the PDF fails to compile.  I am able to inset math notation into other example data sets.

Small subset of my data set and code to produce a table:
```
table2.11<-structure(list(Survey = structure(c(2L, 2L, 2L, 2L, 2L), .Label = c("CAI_II", 
"MAB", "NL"), class = "factor"), `Scallops (baskets)` = c(0, 
0, 0, 0, 0), `$m^2$` = c(0, 0, 0, 0, 0), `Nematode Prevalence (%)` = c(0, 
0, 0, 0, 0)), .Names = c("Survey", "Scallops (baskets)", "$m^2$", 
"Nematode Prevalence (%)"), row.names = c(NA, 5L), class = "data.frame")

kable(table2.11,escape=F) - produces a PDF fail t o compile
```
Working example using code from https://stackoverflow.com/questions/45391566/latex-math-expression-in-knitr-kable-sweave:
```
data(mtcars)
dat <- mtcars[1:5,1:5]
names(dat)[1] <- "$x^2$"
kable(dat,booktabs = TRUE, caption = "My table", escape = FALSE) 
```
I have tried a bunch of different approaches for my dataset including 
\\mtextsuperscript{2}

**Comment by Janewyx** [comment]
It's because you have a special character `%` in your column name. Anywhere in your dataframe if there is a special character you need to issue the escape `\` for the table to render in PDF (replace `%` with `\\%` for `.Names`):

```
table2.11<-structure(list(Survey = structure(c(2L, 2L, 2L, 2L, 2L), .Label = c("CAI_II", 
"MAB", "NL"), class = "factor"), `Scallops (baskets)` = c(0, 
0, 0, 0, 0), `$m^2$` = c(0, 0, 0, 0, 0), `Nematode Prevalence (%)` = c(0, 
0, 0, 0, 0)), .Names = c("Survey", "Scallops (baskets)", "$m^2$", 
"Nematode Prevalence (\\%)"), row.names = c(NA, 5L), class = "data.frame")

kable(table2.11,escape=F)

```

**Comment by vincentarelbundock** [comment]
Adequate solution provided. Users can find this with the search function if they need it.
