### ISSUE TITLE
what about a cell_spec ?

### ISSUE THREAD

**Issue by p-phillips** [haozhu233/kableExtra#36]
What about having a cell_spec function which allowed you  to alter the bold/colour etc of an individual cell in the table ?

Even better,  would be great if we could pass it a formula which printed all failures in red or bold for example. (i.e., if any cells are <9, then print in red).

**Comment by haozhu233** [comment]
Hi, @p-phillips, I totally agree that it would be nice to have a conditional formatting function. I have been thinking about it for a while but it's a little difficult to design a function that is as intuitive as other functions in this package. I'm going to leave this issue open and keep thinking about it. 

If anyone have a good idea, please feel free to post it here as well. Thanks! :)

**Comment by p-phillips** [comment]
As you already have a row and column_spec function, why not a cell_spec ?  Then we could do the tests for conditional formatting outside the kableExtra call and build up a cell spec for individual cells ?

**Comment by vrybkin** [comment]
On this note, it would also be neat to be able to center justify cells. For example, if one cell in a row is two lines long, it would be nice to make the rest of the cells in that row be aligned vertically in the center of the cell, as opposed to being on the top line and having an "extra" line below them.

**Comment by haozhu233** [comment]
@p-phillips I added cell_spec and provided a very detailed documentation here http://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf

The CRAN ver will be released tomorrow.

**Comment by p-phillips** [comment]
Wow. That is excellent, and the way it works in the dplyr pipeline is terrific.  Thank you so much for this.
