### ISSUE TITLE
output not inline when working in rmarkdown

### ISSUE THREAD

**Issue by khusmann** [haozhu233/kableExtra#364]
When I'm working in rmarkdown and run a chunk that renders a kable, I get a blank table in the inline output in my Rmd file, but a populated table in the viewer tab. Is it possible to get my kables rendered inline in the Rmd? Thanks!

![image](https://user-images.githubusercontent.com/167160/54885298-f2d66d80-4e50-11e9-805b-5c9016a925e8.png)

**Comment by ladychili** [comment]
same here

**Comment by stefangeir** [comment]
In my case, the tables are being output inline but _also_ in the viewer pane, which I don't want, and I can't find a way to stop Rstudio from displaying them in the viewer pane.

I have the preview for the whole notebook in the viewer pane open, and I don't want that to keep disappearing if I run a single chunk that only has a kableExtra table. The inline preview is enough.

**Comment by maryellenlynall** [comment]
I also have this problem

**Comment by haozhu233** [comment]
It's possible you are using some older versions of rstudio. I think by upgrading rstudio to latest version, the problem should be gone.
