### ISSUE TITLE
include_empty do not work

### ISSUE THREAD

**Issue by vahabo** [haozhu233/kableExtra#367]
Thank you for this awesome package.

I want to add a table-top-border line while keeping the line below header_above.
I add_header_above with include_empty option. But cannot get a tabletop line of full length.

`
library(compareGroups)

mtcars %<>% mutate(am=factor(am, labels = c("No","Yes")), vs=factor(vs, labels = c("No","Yes")))

mytable<-descrTable(vs~wt+am,
data = mtcars, method = 4,
q.type = c(1,1),byrow = T,include.miss = T, digits = c(wt=0),
hide.no = "No")

export2md(mytable, format = "html", header.labels = c("p.overall"="p-value"),
caption = "Table 1 ") %>%
add_header_above(header = c("","n(%)"=2,""), line = T,include_empty = TRUE,
extra_css = "border-top:2px solid black;")`

**Comment by trianglegirl** [comment]
Hi @vahabo. I am also having this issue. I think this is a bug relating to the way `include_empty()` works. 
A temporary fix for now is to include `angle = 0` as an argument to `add_header_above()`. 
Please, see the MWE below. 
With `angle = 0` missing, the black line only spans part of the row. 
With `angle = 0` included, the black lines spans the whole row. 


```
library("tidyverse")
library("knitr")
library("kableExtra")

mtcars %>%
  kable(format = "html", escape = FALSE) %>%
  kable_styling() %>%
  add_header_above(c(" " = 2, "A" = 2, "B" = 8), line = T, include_empty = TRUE, angle = 0,
                   extra_css = "border-top:2px solid black;")
```

@haozhu233 I'm happy to try and fix this bug and make a pull request.

**Comment by vahabo** [comment]
Thank you for this temporary solution. 
I expect a bug fix including a working include_empty confined to the header above while leaving the extra_css working free. I mean we may want to use include_empty with the line true option while having a full border_above.
Thank you @haozhu233 for this awesome package and efforts to improve it.
