### ISSUE TITLE
Can't add left border to additional header row

### ISSUE THREAD

**Issue by karawoo** [haozhu233/kableExtra#369]
**Describe the bug**

When I add a header row to a table that has left and right outer borders, the border does not extend up through the additional header row. But, for some reason, a border is added on the right even though the rest of the table does not have a right border. Is there a way I can get a border on the left of an additional header row?

This seems like perhaps the opposite issue from issue #280.

**To Reproduce**

````
---
title: "Untitled"
output: 
  pdf_document
header-includes:
  - \usepackage{makecell}
  - \usepackage{multirow}
---

```{r test, message = FALSE}
library("tidyverse")
library("kableExtra")

## Create data
dat <- tibble(
  x = 1:5,
  y = 6:10
)

dat %>%
  kable("latex", escape = FALSE) %>%
  column_spec(1, border_left = TRUE) %>%
  add_header_above(c("combo" = 2))
```
````

![test](https://user-images.githubusercontent.com/4452678/55494580-e8099e80-55ef-11e9-94ea-a0e867bb408c.png)

(originally posted on [RStudio Community](https://community.rstudio.com/t/add-left-border-to-additional-header-row-in-kableextra/26330))

**Comment by haozhu233** [comment]
Hi, @karawoo I will add a `border_left` & `border_right` to add_header_above. :)

btw I just had a meeting with Sage earlier today when you submitted this issue. How coincident lol

**Comment by haozhu233** [comment]
<img width="468" alt="Screen Shot 2019-04-16 at 5 59 10 PM" src="https://user-images.githubusercontent.com/7014590/56246980-6004a980-6071-11e9-885f-cd6cd1c8b1b0.png">

Added now. :)
