### ISSUE TITLE
styling seems to break with kable()'s 'caption.short'

### ISSUE THREAD

**Issue by EhrmannS** [haozhu233/kableExtra#37]
A while ago knitr supported a short caption for the list of tables, please see https://github.com/yihui/knitr/issues/1199.

I am not 100% sure if this is an issue of kableExtra, but it seems so, because when I have a `kable` (including a short caption) and then attempt to use `kable_styling()` even without any options set, I get a latex-error "Not in outer par mode".

Looking at the *.tex file reveals with `kable_styling`

    \begin{table}[!h]
    \centering\begin{table}

    \caption[short caption]{long caption}
    \centering
    \begin{tabular}[t]{lllll}
    \toprule
    ...

in contrast to 

    \begin{table}

    \caption[short caption]{long caption}
    \centering
    \begin{tabular}[t]{lllll}
    \toprule
    ...

without `kable_styling`. Can you reproduce this? Or did I mess up setting something properly?

**Comment by haozhu233** [comment]
@EhrmannS Thanks for reporting this bug! I'm traveling recently. Once I get a chance, I will work on this bug.

**Comment by haozhu233** [comment]
@EhrmannS I think I probably have fixed this bug in the latest dev version. Could you help me check if it works for you in your case?

**Comment by EhrmannS** [comment]
I can confirm that it works now. Great work, thanks for all your efforts around this package!

**Comment by EhrmannS** [comment]
However, it seems to create another problem, not sure if this is connected to the same issue.

When I create a longtable with `kable_styling(latex_options = "repeat_header")`, the repeat-header seems to be formatted wrong. Without this latex_option, the problem does not arise.

without repeat_header:
```
\begin{longtable}[t]{>{\raggedright\arraybackslash}p{7em}>{\raggedright\arraybackslash}p{9em}>{\raggedright\arraybackslash}p{3em}>{\raggedright\arraybackslash}p{8em}>{\raggedright\arraybackslash}p{13em}}
\caption[Focal variables of the driver group \textsc{Habitat} - structural properties.]{\label{tab:focalVariablesHabitatStructural}Focal variables of the driver group \textsc{Habitat} - structural properties. $\dagger$ stands for 'determined from forest mensuration' and $\ddagger$ stands for 'determined from vegetation assessment'.}\\
\toprule
Scale & Variable & Unit & Detail & Comment\\
\midrule
```

with repeat_header:
```
\begin{longtable}[t]{>{\raggedright\arraybackslash}p{7em}>{\raggedright\arraybackslash}p{9em}>{\raggedright\arraybackslash}p{3em}>{\raggedright\arraybackslash}p{8em}>{\raggedright\arraybackslash}p{13em}}
\caption[Focal variables of the driver group \textsc{Habitat} - structural properties.]{\label{tab:focalVariablesHabitatStructural}Focal variables of the driver group \textsc{Habitat} - structural properties. $\dagger$ stands for 'determined from forest mensuration' and $\ddagger$ stands for 'determined from vegetation assessment'.}\\
\toprule
Scale & Variable & Unit & Detail & Comment\\
\midrule
\endfirsthead
\caption[]{Habitat} - structural properties.]{\label{tab:focalVariablesHabitatStructural}Focal variables of the driver group \textsc{Habitat} - structural properties. $\dagger$ stands for 'determined from forest mensuration' and $\ddagger$ stands for 'determined from vegetation assessment'. \textit{(continued)}}\\
\toprule
Scale & Variable & Unit & Detail & Comment\\
\midrule
\endhead
```

As you see, the repeated caption seems to cut off the string somewhere and returns only part of it and there is an additional "]", which probably breaks something...
This leads to a table, where the columns are aligned just as expected, but where the horizontal lines go infinitely to the right, so don't end where the table is supposed to end.

**Comment by EhrmannS** [comment]
Here is a reproducible example.

This is fine:
```
long_dt <- rbind(mtcars, mtcars)
kable(long_dt, longtable = T, booktabs = T, 
      caption.short = "An awesome \\textsc{Longtable}.",
      caption = "An awesome Longtable, with a caption.") %>%
  add_header_above(c(" ", "Group 1" = 5, "Group 2" = 6)) %>%
  kable_styling(latex_options = "repeat_header")
```
This not:
```
kable(long_dt, longtable = T, booktabs = T, 
      caption.short = "An awesome \\textsc{Longtable}.",
      caption = "An awesome Longtable, with a caption. In this case, the captions spans two lines. In this case, it even spans three lines making the table expand to the right.") %>%
  add_header_above(c(" ", "Group 1" = 5, "Group 2" = 6)) %>%
  kable_styling(latex_options = "repeat_header")
```

If I remove the `\\textsc` from the short caption, no problems. But I would expect that I can specify also the short caption with formatting, just like the normal caption:
```
kable(long_dt, longtable = T, booktabs = T, 
      caption.short = "An awesome Longtable.",
      caption = "An awesome \\textsc{Longtable}, with a caption. In this case, the captions spans two lines. In this case, it even spans three lines making the table expand to the right.") %>%
  add_header_above(c(" ", "Group 1" = 5, "Group 2" = 6)) %>%
  kable_styling(latex_options = "repeat_header")
```

**Comment by haozhu233** [comment]
@EhrmannS I improved the method which I used to extracted the captions. Now the new bug is gone

**Comment by qifei9** [comment]
Currently, for table with `caption.short` para, `magic_mirror` lost the last character when reading the caption. This affects the repeat_header for longtable.

I made a PR for this #57

**Comment by haozhu233** [comment]
@qifei9 Great! Thanks!
