### ISSUE TITLE
Mutate Issue within KableExtra

### ISSUE THREAD

**Issue by soleyjh** [haozhu233/kableExtra#373]
**Describe the bug**
When I updated the rlang package I'm getting a weird issue with dplyr mutate functions.

I get the following error from R:

Error in mutate_impl(.data, dots) : 
  Evaluation error: `as_dictionary()` is defunct as of rlang 0.3.0.
Please use `as_data_pronoun()` instead. 

**To Reproduce**
Having conditionals in the grid part of the report rendering.

```
grid %>%
  mutate_if(is.numeric, function(x) {format(x, digits = 2, big.mark = ",", decimal.mark = ".")}) %>%
  mutate(
    seven_day_unique_viewers = cell_spec(seven_day_unique_viewers,color = ifelse(grid$ppv_6hr_7days %in% 1,"Crimson","Black"), italic = (Sys.Date() - as.Date(grid$debut_date, "%B %d, %Y") < 8)),
    seven_day_rating = cell_spec(seven_day_rating, italic = (Sys.Date() - as.Date(grid$debut_date, "%B %d, %Y") < 8)),
    seven_day_linear_airings = cell_spec(seven_day_linear_airings,italic = (Sys.Date() - as.Date(grid$debut_date, "%B %d, %Y") < 8)),
    debut_date = cell_spec(debut_date,color = ifelse(grid$ppv_week_flag %in% 1,"DodgerBlue","black")),
    debut_date_unique_viewers = cell_spec(debut_date_unique_viewers,color = ifelse(grid$post_ppv_premiere %in% 1,"Crimson","Black")),
    live_linear_unique_viewers = cell_spec(live_linear_unique_viewers,color = ifelse(grid$post_ppv_premiere %in% 1,"Crimson","Black"))
  ) %>%
  mutate(post_ppv_premiere=NULL,
         ppv_6hr_7days=NULL,
         ppv_6hr_ever=NULL,
         ppv_week_flag=NULL) %>%
```

If you need to attach the entire rmarkdown doc, try to use ```` to quote your entire doc.

````
---
title: "A reproducible example in rmarkdown"
output: html_document
---

```{r}
library(kableExtra)
```
````

**Comment by haozhu233** [comment]
@soleyjh I don't think I have ever used these two functions here. You can use cell_spec outside of mutate - it's just an html/latex formatter.

**Comment by soleyjh** [comment]
Thanks for the speedy update. I needed to update the dplyr package which was server side and it confused the heck out of me. My apologies for bringing up an issue that was not yours.

**Comment by haozhu233** [comment]
Haha, no problem. I totally understand the pain. Also, you provided enough info so I can tell you it's not mine. ;)
