### ISSUE TITLE
cannot wrap text in latex with pack_rows

### ISSUE THREAD

**Issue by joshpk** [haozhu233/kableExtra#376]
Hello and thank you for the great package!  I'm using pack_rows to create grouping headers in a table, and in some cases the text for the grouping is long, meaning that it overflows over the table when outputted to pdf. I'm looking for a way of wrapping this text in a similar way to how you would set column_spec(width = xx) if this issue was for a column. As far as I can make out, there isn't a setting available for controlling this currently?

Code:

````
---
title: "Long Table w/ pack_rows"
output:
  pdf_document: default
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(kableExtra)

group_label = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eu faucibus dolor. Maecenas eget semper tortor. Nullam tempor, sapien ut porta vehicula, nisi nunc efficitur eros, eu hendrerit ipsum odio ac odio. Praesent tempus tincidunt mattis."

mtcars %>% 
    select(1:4) %>% 
    kable(booktabs = T, longtable = T) %>% 
    kable_styling(full_width = T, latex_options = c("repeat_header")) %>% 
    pack_rows(group_label, 1, 10)
```
````

And output showing the pack_rows text being truncated:

![image](https://user-images.githubusercontent.com/27865871/56758587-3e33b280-6754-11e9-825b-c30a8ae83b3d.png)

**Comment by haozhu233** [comment]
Hi, @joshpk, I added a `latex_wrap_text` option to `pack_rows`. 

![Screen Shot 2019-04-26 at 5 07 57 PM](https://user-images.githubusercontent.com/7014590/56836621-e07f9300-6845-11e9-8b6f-15a3df01d485.png)

**Comment by joshpk** [comment]
Great, thank you. Your help is much appreciated!
