### ISSUE TITLE
repeat_header options causes borders on first column to be longer than on other columns

### ISSUE THREAD

**Issue by sharlagelfand** [haozhu233/kableExtra#377]
I'm sorry -- using this package so heavily means I'm finding lots of little things 🐛 😂 

When `latex_options = "repeat_header"` is set in `kable_styling()`, it causes any borders on the first column to be longer than borders on the rest of the columns. This is true on any pages except the page with very bottom of the table, since the bottom horizontal line seems to prevent this from happening?

````
---
output: pdf_document
---

```{r setup, include=FALSE}
library(kableExtra)
```

```{r}
iris %>%
  kable(
    booktabs = TRUE,
    longtable = TRUE,
    caption = "repeat header"
  ) %>%
  kable_styling(
    latex_options = "repeat_header"
  ) %>%
  column_spec(
    column = 1:3,
    border_left = TRUE
  )
```


```{r}
iris %>%
  kable(
    booktabs = TRUE,
    longtable = TRUE,
    caption = "no repeat header"
  ) %>%
  kable_styling(
  ) %>%
  column_spec(
    column = 1:3,
    border_left = TRUE
  )
```
````

The first page of the first table:
![Screen Shot 2019-04-26 at 1 29 52 PM](https://user-images.githubusercontent.com/15895337/56825532-69d39d00-6827-11e9-80b0-380103fd8976.png)

And the first page of the second:
![Screen Shot 2019-04-26 at 1 29 43 PM](https://user-images.githubusercontent.com/15895337/56825536-6cce8d80-6827-11e9-8101-480335858e82.png)

**Comment by haozhu233** [comment]
This is the time my knowledge on latex also comes to a limit. Time to find some luck on tex overflow. lol

https://tex.stackexchange.com/questions/487806/vertical-border-in-longtable-booktabs-repeating-table-header

**Comment by haozhu233** [comment]
@sharlagelfand okay~ I guess it's fixed now.

**Comment by sharlagelfand** [comment]
oh amazing!! looks good to me now. thank you + the folks on tex overflow so much!
