### ISSUE TITLE
scale_down not working when using longtable = T

### ISSUE THREAD

**Issue by Vidaringa** [haozhu233/kableExtra#379]
Hello and thank you for an awesome package. I'm working with a large table, both wide and long. So I'm using `scale_down` , and that works fine. 
But when I add `longtable = T` the table will not scale, i.e. the `scale_down` is not used. But the `longtable = T` will work just fine.

Below is  the function I made to prodice the tables.

```
nice_table <- function(df) {
        df %>%
                kable(booktabs = T,
                      linesep = "",
                      format.args = list(big.mark = "."),
                      longtable = T,
                      align = c("l", rep("c", 8), "r")) %>%
                kable_styling(latex_options = c("HOLD_position","repeat_header", "scale_down")) %>%
                add_header_above(c(" ", "Heildarlaun" = 4, "Grunnlaun" = 4)) %>%
                column_spec(1,
                            width = "6cm") %>%
                column_spec(c(2, 6),
                            # bold = T,
                            background = "lightgray") %>%
                column_spec(10,
                            border_left = T) %>% 
                row_spec(seq(1, nrow(df), fjoldi_undir + 2), bold = T, font_size = 8)
}

```

**Comment by haozhu233** [comment]
Hi, @Vidaringa, if you use `scale_down` with `longtable`, you should see a warning message somewhere. 

https://github.com/haozhu233/kableExtra/blob/5ded5f0f63a4efca8558de171ef2e4b0a9723d7b/R/kable_styling.R#L392-L395

I also just added a sentence to the documentation. Hope it helps.

**Comment by Vidaringa** [comment]
Thank you for a quick reply. I just didn't notice this warning message.
