### ISSUE TITLE
row_spec background multiple rows, multiple colors.

### ISSUE THREAD

**Issue by Thell** [haozhu233/kableExtra#380]
**Describe the bug**
Coloring full rows using row_spec doesn't accept multiple colors.

**To Reproduce**
Think about using `reprex` to generate an example in R. 

````
```{r setup, include=FALSE}
library(knitr)
library(kableExtra)

knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format = "html") 
```


```{r, collapse=TRUE, results='asis'}
dt <- mtcars[1:5, 1:6]
my_backgrounds <- colorRampPalette(c("green", "red"))(5)

tbl1 <- dt %>%
  kable(escape = F) %>%
  kable_styling(full_width = F, position = "float_left") %>%
  row_spec(1:5, background = my_backgrounds[1:5])

tbl2 <- dt %>%
  kable(escape = F) %>%
  kable_styling(full_width = F, position = "float_right") %>%
  row_spec(1, background = my_backgrounds[1]) %>%
  row_spec(2, background = my_backgrounds[2]) %>%
  row_spec(3, background = my_backgrounds[3]) %>%
  row_spec(4, background = my_backgrounds[4]) %>%
  row_spec(5, background = my_backgrounds[5])

cat(tbl1, "\n", tbl2, "\n")
```
````

![image](https://user-images.githubusercontent.com/2185020/57197248-af305280-6f2a-11e9-8980-bc0a01adaf49.png)

----
I love kableextra but recently had quite a few issues making a four column table with scaled full-row background coloring.  Having row_spec cycle through the arguments when the rows argument and other arguments are of equal length would be helpful.
Also, as a side note, being able to use spec_color with the row_spec background parameter would be nice too.

Thanks.
Thell

**Comment by haozhu233** [comment]
Well, in my opinion, if `row_spec`'s arguments are going to take vector arguments, each element will be the value for each cell. I have implemented this design for `column_spec` recently and I sort of like that. See the second example on https://haozhu233.github.io/kableExtra/awesome_table_in_html.html#Column__Row_Specification

If you are looking for iteratively adding `row_spec` to different rows with different color. Here is an approach you can try. 

```
dt <- mtcars[1:5, 1:6]
my_backgrounds <- colorRampPalette(c("green", "red"))(5)

tbl1 <- dt %>%
  kable(escape = F) %>%
  kable_styling(full_width = F, position = "float_left") 

for (i in 1:5) {
  tbl1 <- row_spec(tbl1, i, background = mybackground[i])
}
```
