### ISSUE TITLE
 Error in footnote: unused arguments

### ISSUE THREAD

**Issue by ABSOD** [haozhu233/kableExtra#385]
**Describe the bug**
My application (a shiny dashboard) outputs an HTML table using knitr (v 1.22) and kableExtra (v 1.10).  The code:

outHTML <-  kable(outTab, format='html', table.attr='class="cleanTab"',
                    digits=1,
                    row.names=FALSE,
                    align=align_spec,
                    col.names = names_spaced,
                    caption="Community Quick Facts",
                    escape = FALSE)   %>%
    kable_styling() %>%
    column_spec(1, width = "4in") %>%
    add_header_above(header_span)  %>%
   footnote(symbol= c("Source: State Demography Office",captionSrc("ACS",ACS)),threeparttable = T) 
[captionSRC is a function that outouts a source string)
Just recently (yesterday, after several months of runing without an error), I received the following error:

Warning: Error in footnote: unused arguments (symbol = c("Source: State Demography Office", captionSrc("ACS", ACS)), threeparttable = T)

here is my library stack:
library(tidyverse, quietly=TRUE)
library(readr)
library(readxl, quietly=TRUE)
library(scales, quietly=TRUE)
library(codemogAPI, quietly=TRUE)
library(codemogProfile, quietly=TRUE)
library(codemogLib)
library(knitr, quietly=TRUE)
library(kableExtra, quietly=TRUE)
library(RPostgreSQL)
library(rmarkdown)
library(shiny, quietly=TRUE)
library(shinydashboard, quietly=TRUE)
library(shinyjs, quietly=TRUE)
library(eulerr)
library(rgdal)
library(geojsonio)
library(units)
library(grid)
library(gridExtra)
library(ggthemes)
library(maptools)
library(officer)
library(flextable)
library(ggplotify)

Any ideas what is going wrong with my footnote call?
TIA

**To Reproduce**
Think about using `reprex` to generate an example in R. 

```
# code to reproduce the bug.
```

If you need to attach the entire rmarkdown doc, try to use ```` to quote your entire doc.

````
---
title: "A reproducible example in rmarkdown"
output: html_document
---

```{r}
library(kableExtra)
```
````

**Comment by haozhu233** [comment]
It's a little difficult to tell what exactly happened without testing in the environment. My guess is that you updated some packages recently and one of the packages loaded after kableExtra introduced a function also named `footnote`. Here, what you can try is to replace `footnote` with `kableExtra::footnote()` so you call the kableExtra function explicitly. I mean If I ever develop this package again, I should have named these functions with a fixed prefix but it is what it is.

**Comment by haozhu233** [comment]
Another solution is to use the conflicted package. https://github.com/r-lib/conflicted

**Comment by ABSOD** [comment]
Thanks.
The explicit call is a good workaround.  Apparently, kableExtra and flextable are conflicting.
Cheers--
AB

**Comment by blueja5** [comment]
I just spent a long time finding this answer when my frequently used code threw an error. i wonder if it could be added to the vignette when next updated?
