### ISSUE TITLE
fix a row at the botton of the table in kable extra

### ISSUE THREAD

**Issue by uttam-1996** [haozhu233/kableExtra#388]
'''kable(mtcars, align = "c",padding = "1l") %>%
      kable_styling(bootstrap_options = "striped", full_width = T, position = "left",font_size = 17)%>%
      column_spec(1, bold = T) %>%
      scroll_box( height = "250px")'''

is there any way that i can fix the last row of the table fixed so that the scrolling happens between the header and the final row ?

**Comment by haozhu233** [comment]
Technically it's possible but I think the use case is very rare. You can think about using the `kable_as_xml` and modify the HTML components on your own. http://haozhu233.github.io/kableExtra/kableExtra_and_xml2.html
