### ISSUE TITLE
Using collapse_rows + stacked in html doesn't seem to work.

### ISSUE THREAD

**Issue by DavisBrian** [haozhu233/kableExtra#389]
Posted this on [Stackoverflow](https://stackoverflow.com/questions/56411387/using-collapse-rows-stacked-in-html-not-working?noredirect=1#comment99423432_56411387)
---------------------------------------------------------------------------------------------
Working with the LaTeX kableextra vignette, I can successfully get the examples in the "Group rows via multi_row cell" section to produce the expected output whenI knit to a pdf.

```library(tidyverse)
library(kableExtra)

collapse_rows_dt <- expand.grid(Country = sprintf('Country with a long name %s', c('A', 'B')),
                                State = sprintf('State %s', c('a', 'b')),
                                City = sprintf('City %s', c('1', '2')),
                                District = sprintf('District %s', c('1', '2'))) %>%
  arrange(Country, State, City) %>% 
  mutate_all(as.character) %>% 
  mutate(C1 = rnorm(n()), C2 = rnorm(n()))

kable(collapse_rows_dt, "latex", booktabs =T,align ="c",linesep ='') %>%
  collapse_rows(1:3,row_group_label_position ='stack')
```
However, if I knit to html (and change the kable call). The stacked first row is no longer stacked.

```
library(tidyverse)
library(kableExtra)

collapse_rows_dt <- expand.grid(Country = sprintf('Country with a long name %s', c('A', 'B')),
                                State = sprintf('State %s', c('a', 'b')),
                                City = sprintf('City %s', c('1', '2')),
                                District = sprintf('District %s', c('1', '2'))) %>%
  arrange(Country, State, City) %>% 
  mutate_all(as.character) %>% 
  mutate(C1 = rnorm(n()), C2 = rnorm(n()))

kable(collapse_rows_dt, "html", booktabs =T,align ="c",linesep ='') %>%
  collapse_rows(1:3,row_group_label_position ='stack')
````

This same example is not in the html version of the vignette. After searching for a solution I can't tell if this feature simply isn't supported in html, if it's a bug, or if there is a workaround to achieve a similar effect.

**Comment by haozhu233** [comment]
The stack part was contributed by an user and it was only implemented in latex. https://github.com/haozhu233/kableExtra/pull/159 However, I personally don't have a very strong interests in this functionality. If someone wants to contribute a html version, that would be awesome!

I'm going to close this issue for now. If someone wants to contribute, please reopen this issue.
