### ISSUE TITLE
Long footnote text causes striped row backgrounds and change in column alignment

### ISSUE THREAD

**Issue by meenaparam** [haozhu233/kableExtra#39]
This is issue is linked to #31.

When running the code below, the long footnote spans over more than one line, and so gets the striped background. It also then changes the alignment of the column on the far right. 

Is there a way to allow long footnotes to spread over more than one line whilst maintaining alignment of columns and with a non-striped background?

Demo .Rmd code, using the dev version of kableExtra:

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format = "latex")
```

```{r results='asis'}
library(knitr)
library(kableExtra)
dt <- cbind(mtcars[1:5, 1:6], mtcars[1:5, 1:6])

kable(dt, caption = "Demo Table[note]", booktabs = T) %>%
kable_styling(latex_options = c("striped", "hold_position")) %>%
add_header_above(c(" ", "Group 1[note]" = 3, "Group 2[note]" = 3)) %>%
add_footnote(c("This table is from mtcars. Lots more text to make the footnote nice and long. Even more text. And a bit more. That's enough.",
"Group 1 contains mpg, cyl and disp.",
"Group 2 contains hp, drat and wt."),
notation = "symbol")
```
![striped_foonote_rows](https://user-images.githubusercontent.com/7209522/29362065-39793912-8282-11e7-9ed3-0b7a35ff43de.png)

**Comment by haozhu233** [comment]
One solution in the current `kableExtra` is to use the `threeparttable` option in `add_footnote`. Note that since this feature needs LaTeX package `threeparttable`, which I haven't put into the default load list in `kableExtra`, *you need to load it by yourself using `usepackage_latex`*. 

```
library(knitr)
library(kableExtra)
usepackage_latex("threeparttable")
dt <- cbind(mtcars[1:5, 1:6], mtcars[1:5, 1:6])

kable(dt, "latex", caption = "Demo Table[note]", booktabs = T) %>%
kable_styling(latex_options = c("striped", "hold_position")) %>%
add_header_above(c(" ", "Group 1[note]" = 3, "Group 2[note]" = 3)) %>%
add_footnote(c("This table is from mtcars. Lots more text to make the footnote nice and long. Even more text. And a bit more. That's enough.",
"Group 1 contains mpg, cyl and disp.",
"Group 2 contains hp, drat and wt."),
notation = "symbol", threeparttable = T)
```

**Comment by meenaparam** [comment]
Thanks for the quick answer! That works fine for the example I gave you, but not in my actual work. There, using `threeparttable = T` seems to lead to `! LaTeX Error: \caption outside float.`

**Comment by haozhu233** [comment]
@meenaparam How about moving those two `group_rows` functions before `add_footnote`? The tex code you posted suggested that the `\begin{table}` and `\begin{threeparttable}` were converted to `\textbackslash{}begin\{table\}`. I'm afraid it was caused by the fact that most functions in `kableExtra` are very familiar with `threeparttable` so they treated `\begin{threeparttable}` totally as text. 😂😂😂 It's certainly a bug.

**Comment by meenaparam** [comment]
@haozhu233 Thanks for the suggestion - tried that, but same error as before. Don't worry, I will probably end up removing the longer footnotes if I can't fix it, so it's not a huge priority. Fair enough that most functions treat `threeparttable` as text, it's still a great package! In fact, everything was running perfectly fine when I was making html tables - it's only since switching to PDF reports that I am having problems.

Relatedly, the same table is also ignoring it's `hold_position` argument - the table appears before or after the section heading it's supposed to be directly under. Is there a LaTeX package I should import to make sure `hold_position` works?

**Comment by haozhu233** [comment]
@meenaparam I just successfully reproduced the bug. Short answer is that if you remove `scale_down` from your option list, you should be fine without changing anything else. 

A longer answer is that, `scale_down` typically put table into a resizable box outside of the `tabular` environment. However, for `threeparttable`, you have to put the resizable box outside of the `threepartable` which wraps up caption (optional), tabular, and tablenotes. https://tex.stackexchange.com/questions/205515/resizing-table-when-using-package-threeparttable

You may consider to use `font_size` in your case to make your table smaller. :P

**Comment by meenaparam** [comment]
@haozhu233 Thanks for the tip! Ok, I will see what happens if I remove `scale_down` from that table. It's strange, as the `hold_position` problem is happening even though I am not using `threeparttable` at all (at least, not deliberately, as that didn't work because of the caption error). Anyway, not to worry, thanks for all your help!
