### ISSUE TITLE
auto_index and factors

### ISSUE THREAD

**Issue by larmarange** [haozhu233/kableExtra#390]
`auto_index()` produces an error when applied to a factor.

```r
auto_index(letters)
## a b c d e f g h i j k l m n o p q r s t u v w x y z 
## 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
auto_index(factor(letters))
## Error in rle(x) : 'x' must be a vector of an atomic type
```

It should be easy to add a test at the beginning of the function to test if `x` is a vector and, if yes, to convert `x` into a character vector.

**Comment by haozhu233** [comment]
Fixed. Thanks!
