### ISSUE TITLE
remove dependency to phantomJS?

### ISSUE THREAD

**Issue by randomgambit** [haozhu233/kableExtra#392]
Hello @haozhu233 !

I was wondering if there is a way to use `save_as_image()` without using the phantomJS dependency. Indeed, the project is dead https://github.com/ariya/phantomjs/issues/15344

Saving as images is very important (say to share via email for instance) but I feel the package requirements are too complex here. What do you think?

**Comment by randomgambit** [comment]
Hi @haozhu233 ! did you get a chance to look at that? Thanks!

**Comment by haozhu233** [comment]
@randomgambit I did look at that project after you mention it the other day but didn't really think about this. Basically all I did here is use `webshot`, which uses `phantomjs` on the backend. Do you have any thoughts on what we can use to take a picture from HTML? Since HTML pages need to be loaded for the css to take effect, I think some level of js is necessary.

**Comment by randomgambit** [comment]
@haozhu233 thanks for the reply. I have seen a couple of headless javascript capable browsers. What about https://github.com/hrbrmstr/htmlunit ? That looks promising. The big issue with the current approach is that it requires to install an external component (phnsomJS) which I cant do at work AND that component is not maintained anymore (stuff will break in the future).

What do you think?
Thanks!

**Comment by randomgambit** [comment]
according to the author this one is an alternative to `phantomJS`. could be a good idea too!
https://github.com/hrbrmstr/splashr/issues/18

**Comment by haozhu233** [comment]
We will switch to this one in the future. 

https://github.com/rstudio/webshot2

**Comment by randomgambit** [comment]
why not now? :D

**Comment by randomgambit** [comment]
@haozhu233 what I mean is can we try a beta version of `kableExtra` with `webshot2`? Happy to report any bugs or errors!

**Comment by randomgambit** [comment]
Hi @haozhu233 how are you? Any plans on using webshot2 soon?
Thanks!

**Comment by haozhu233** [comment]
@randomgambit After so many months, I just reviewed webshot2 again and I realized it also requires users to install Chrome... Although I think many people do have chrome install, it does add a non-trivial dependency requirement. Say if the US government prohibited google's business activities in China or any other countries in the future, it will become an issue. (just saying). 

I mean stopping maintaining isn't too terrible as long as it's still usable and there isn't a terrible security bug... Bootstrap 3 is also dead but we are still using it. :P So I guess I tend to keep using webshot. What do you think?

**Comment by randomgambit** [comment]
@haozhu233 well at the same time using a deprecated soft can be source of unfixable bugs, malwares and other technical issues. Even if chrome is blocked at work (which is not), one could at least use his personal computer at home to use webshot2 dont you think?

**Comment by haozhu233** [comment]
@randomgambit well, the bottomline is that webshot2 is not on CRAN so that's basically a no for this option. At the same time, installing chrome on HPC or a linux server with strict access control can be another issue.
