### ISSUE TITLE
column_spec 

### ISSUE THREAD

**Issue by neuwirthe** [haozhu233/kableExtra#394]
`column_spec` parameters `border_left` and` border_right` seem not to be working with latex output format.

```{r}
library(kableExtra)
library(dplyr)
```

```{r}
mat <- matrix(1:9,nrow=3)
rownames(mat) <- c("A","B","C")
colnames(mat) <- c("x","y","z")
mat %>% as_tibble(rownames="rowx") -> mat_df
```

```{r}
mat_df %>% 
  kable("latex") %>%
  column_spec(2:3, border_left = FALSE,border_right = FALSE)
```

![2019-06-08_17-58-18](https://user-images.githubusercontent.com/157619/59149572-09836e00-8a17-11e9-84a3-e41519fff7eb.png)

**Comment by haozhu233** [comment]
These two arguments are there to add borders to book tabs tables. The default option is F

If you don’t want the vertical lines, you can put booktabs =T in kable
