### ISSUE TITLE
Cannot add footnote to pack_rows text.

### ISSUE THREAD

**Issue by DavisBrian** [haozhu233/kableExtra#396]
I posted this to [stackoverflow](https://stackoverflow.com/questions/56679924/how-to-add-a-footnote-to-pack-rows-text) a couple days ago, and after some more research I think this is a bug.

I'm trying to add a footnote to a table with a row that spans multiple columns using knitr + kableextra + pack_rows

Searching for solutions I have come up empty, other than the "make sure you use escape=F" type solutions. Also, it doesn't seem to matter if I knit to pdf or html. Both seem to insert the footnote string, but it's unclear if it just isn't escaped properly, or something else.

Judging by the output the footnote symbol gets added in the correct place, but doesn't seem to render in HTML or PDF.

A Minimal Reproducible example...

```
---
title: "Footnote Test"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(knitr)
library(kableExtra)
```

```{r cars}

dt <- mtcars[1:5, 1:6]

```

### Footnote Example

This works just fine!

```{r cars-footnote}

dt_footnote <- dt
names(dt_footnote)[2] <- paste0(names(dt_footnote)[2], 
                                footnote_marker_symbol(1))
row.names(dt_footnote)[4] <- paste0(row.names(dt_footnote)[4], 
                                footnote_marker_alphabet(1))
kable(dt_footnote, align = "c", 
          # Remember this escape = F        
      escape = F) %>%    
  kable_styling(full_width = F) %>%
  footnote(alphabet = "Footnote A; ",
           symbol = "Footnote Symbol 1; ",
           alphabet_title = "Type II: ", symbol_title = "Type III: ",
           footnote_as_chunk = T)

```

### Footnote on Span

the html or latex code to add the symbol get's displayed.

```{r cars-footnote-scan}

dt_span <- dt %>% 
  arrange(cyl) %>%
  select(cyl, everything())    

prlabel <- paste0("Six-Cylinder",
                  footnote_marker_alphabet(1))


  kable(dt_span, align = "c", escape = FALSE) %>%    
    kable_styling(full_width = FALSE) %>%    
    pack_rows(prlabel, 2, 4) %>%
    footnote(alphabet = "Footnote A", footnote_as_chunk = T, escape = FALSE)
```

**Comment by haozhu233** [comment]
Thank you for reporting this bug. I just get it fixed. Also, since you are including raw tex in group labels, you need to set escape to be F.
