### ISSUE TITLE
fixing headerabove to the header while scrolling 

### ISSUE THREAD

**Issue by uttam-1996** [haozhu233/kableExtra#399]
can you please make an improvement to the fixed_thread so that it could even fix the header_above row to the table thank you 
![Screenshot from 2019-07-01 16-33-30](https://user-images.githubusercontent.com/33053682/60431996-c041cb00-9c1e-11e9-9131-fe547e16e9f6.png)
![Screenshot from 2019-07-01 16-37-43](https://user-images.githubusercontent.com/33053682/60432000-c33cbb80-9c1e-11e9-87a8-0ab01fd90c1d.png)

**Comment by haozhu233** [comment]
This is actually very difficult to implement, if not impossible. I don't think I can make any changes on that but if somebody can contribute a fix, that would be the best.
