### ISSUE TITLE
Latex code in header won't work with kableExtra

### ISSUE THREAD

**Issue by p-phillips** [haozhu233/kableExtra#40]
Hi.

I have a dataframe where I have inserted latex code for bold:
`\textbf{92}`

and where I am using some latex code in the header:
`
print(kable(newpercentages,
caption="Percentage of readings $\\geq$  $^{\\circ}$C",
etc ...
`

It works in plain kable (I get the correct latex symbols in the header, and the value '92' comes out in bold), but when I use kableExtra the latex code is not interpreted, and I see the raw latex code in the table.

Have I missed something obvious or is this not possible with kableExtra ?

Pete

**Comment by EhrmannS** [comment]
I think you must set `kable(..., escape = FALSE, ...)`. But, this here is not a [support-forum](https://stackoverflow.com/search?q=knitr) but for reporting bugs.

**Comment by haozhu233** [comment]
Hi, @p-phillips can you provide a little more details on this?

I tried the following codes but I can't reproduce the bug. 
```
library(knitr)
library(kableExtra)
dt <- mtcars
dt[1, 1] <- "\\textbf{92}"
kable(dt, "latex", booktabs = T, escape = F, caption = "sss \\textbf{ss}") %>%  
  kable_styling(latex_options = "hold_position") %>%  
  group_rows("group", 1, 5)
```
