### ISSUE TITLE
save_kable_latex does not generate PDF file in Windows

### ISSUE THREAD

**Issue by dnidz** [haozhu233/kableExtra#401]
**Describe the bug**
When I use save_kable() with a latex kable, I get an error that the PDF file can't be read, but it works fine with kable_as_image. So I dug into the code, and in save_kable_latex() it isn't creating the PDF file in the first place.

Line 147 isn't working:
`  system(paste0("xelatex -interaction=batchmode ", temp_tex_file))
`
The problem seems to be that it wants only the .tex file name, but at this point temp_tex_file has the full path like C:\\data\\...\\file.tex (Yes, I'm working under Windows, and I realize that's probably the root of the problem...)

What works instead is:
`  system(paste0("xelatex -interaction=batchmode ", 
                tools::file_path_sans_ext(file), 
                ".tex")) `

**Comment by accraft** [comment]
If I had to guess, this is the same issue as [save_kable fails when there is space in path #444](https://github.com/haozhu233/kableExtra/issues/444), though I'm a bit surprised the solution you proposed works? Try the solution shown in #444 where you surround temp_tex_file with ".
