### ISSUE TITLE
caption cannot handle loop index

### ISSUE THREAD

**Issue by yesdavid** [haozhu233/kableExtra#407]
**Description**
I have a list of tables that I want to print using a for-loop.  
I want to print the name of the current list-element as the caption using `paste0()`.  
This is not possible and I get the following error message:

`! Missing $ inserted.  <inserted text> $  l.532 \end{longtabu} Error: Failed to compile`

_BUT_ if I say `caption = "This is my caption"` it works perfectly fine.

**Code**

```
for (table_name in names(list_of_tables)){
  
  current_table <- list_of_tables[[table_name]]
  
  my_caption <- paste0("Name: ", table_name, ", ks-Test")
  
  print(kable(current_table,
              "latex", 
              longtable = T,
              booktabs = T, 
              caption = my_caption))
}
```

**Comment by yesdavid** [comment]
I think I solved it: `caption = cat("Name: ", table_name, ", ks-Test")`

**Comment by yesdavid** [comment]
the problem now is, that in the knitted PDF-document the automated caption numbering etc. are missing (e.g. "Table 01:"). It just prints the text provided through `caption = cat("Name: ", table_name, ", ks-Test")`.

**Comment by haozhu233** [comment]
@yesdavid How about adding a homemade counter? 😉

Anyway, this kind of question should go to stackoverflow and `kable` function itself comes from `knitr`.
