### ISSUE TITLE
Feature request: Add caption option to toKable

### ISSUE THREAD

**Issue by ekoraytascilar** [haozhu233/kableExtra#411]
I find tables package very useful to generate summary tables and kableExtra very useful for easy formatting, and use the toKable function a lot.
Referring to this [stackoverflow question](https://stackoverflow.com/questions/55479669/captions-using-r-tables-package-with-kableextra-formatting), adding an option to the toKable function for captions to tables piped from a tabular function would be perfect.

**Comment by ekoraytascilar** [comment]
I forgot to mention that this concerns latex tables.

**Comment by haozhu233** [comment]
@ekoraytascilar `toKable` is actually a function from `tables`. I think you should contact Duncan.

https://cran.r-project.org/web/packages/tables/index.html
