### ISSUE TITLE
Remove ALL horizontal lines in a table 

### ISSUE THREAD

**Issue by leynu** [haozhu233/kableExtra#413]
I am trying to create a table with no column names and **NO LINES** in a PDF output. 
I have managed to remove the column names: `col.names = NULL`.
AND 
I can make the last line in the table to "vanish" by making it white: ` row_spec(nrow(mtcars), extra_latex_after = "\\arrayrulecolor{white}") ` 
BUT 
I still have the line on TOP of the table that I can not get ride of :(

This is maybe not the usual scenario but it would be nice to achieve that. 
Thanks!  

````
---
title: "test"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(kableExtra)
```

```{r mtcars, echo=TRUE}
mtcars <- mtcars[1:6, ]
kable(mtcars,  "latex", booktabs = T, col.names = NULL) %>%
  kable_styling( full_width = F, position = "left") %>%
  row_spec(nrow(mtcars), extra_latex_after = "\\arrayrulecolor{white}") %>%
  column_spec(1, width = "5em" ) 
```

````

**Comment by loreabad6** [comment]
Probably not the best solution, but as a workaround, adding this to the YAML does the trick:
```
---
title: "test"
output: pdf_document
header-includes:
  \usepackage{colortbl}
  \arrayrulecolor{white}
---
```

**Comment by 1beb** [comment]
Also looking for a solution here.

**Comment by haozhu233** [comment]
@loreabad6 @1beb For this problem you can just use some regular expression. There are a lot of regular expression in the latex part of this package so I promise it's a valid solution. 

```
kable(mtcars,  "latex", booktabs = T, col.names = NULL) %>%
  kable_styling( full_width = F, position = "left") %>%
  column_spec(1, width = "5em" ) %>%
  sub("\\\\toprule", "", .) %>%
  sub("\\\\bottomrule", "", .)
```
