### ISSUE TITLE
Trying to avoid hard-coding headers via add_header_above() by insert a string variable instead of writing out the string

### ISSUE THREAD

**Issue by davoodip** [haozhu233/kableExtra#415]
I'm trying to insert a string variable into as_header_above( ) because this sits within a function where the string variable can change based on what happens upstream from constructing the kable. So, I am trying to avoid typing out the headers. I have tried several things to no avail. Any ideas for how I could do this to make my code more automated and avoid hard-coding? Below is a shell for what I am attempting to do. Thanks!

````
string_var_1 <- "June 2019"
string_var_2 <- "July 2019"

df %>%  
      knitr::kable("html") %>% 
      kable_styling(c("striped","condensed","bordered"), font_size=12) %>% 
      add_header_above(c(" ", string_var_1 = 10, string_var_2 = 10))
````

**Comment by lipebento1** [comment]
you can use the setNames() function. 

Your kable would then become:
```
string_var_1 <- "June 2019"
string_var_2 <- "July 2019"

df %>%  
      knitr::kable("html") %>% 
      kable_styling(c("striped","condensed","bordered"), font_size=12) %>% 
      add_header_above(c(" ", setNames(10,string_var_1), setNames(10,string_var_2))) 
```

**Comment by haozhu233** [comment]
@lipebento1 Thanks for your help!

**Comment by rcyost** [comment]
This assumes we know the number of columns for put headers over. Can we generalize past this?
