### ISSUE TITLE
Will it be possible to make kableExtra working for other format?

### ISSUE THREAD

**Issue by CarolineXGao** [haozhu233/kableExtra#42]
I found knitting R markdown to word documents really useful when collaborating with non-latex users.  Is there a way to extend the package to markdown format? 
Thanks ! 

Caroline

**Comment by haozhu233** [comment]
Hi @CarolineXGao, as I said in the README, markdown has its limitation on table representation. If you want to have higher level of control on markdown-formatted tables, I think [pander](https://cran.r-project.org/web/packages/pander/pander.pdf) is the best option we can have right now.

**Comment by haozhu233** [comment]
Hi @CarolineXGao and @mbcann01,

I'm adding a new function in the dev version of this package that can convert LaTeX table codes to an image and insert it to a rmarkdown Word document. If you are interested, please install the latest dev version using `devtools::install_github("haozhu233/kableExtra")` and read the documentation in `?kable_as_image`.

Here is a minimal example. 

```
---
title: "kable_as_image"
author: "Hao"
date: "8/22/2017"
output:
  word_document: default
---
```{r, fig.width=3}
library(knitr)
library(kableExtra)

kable(mtcars, format = "latex", booktabs=TRUE, caption="hello") %>% 
  kable_styling(latex_options=c("scale_down", "hold_position")) %>%
  add_header_above(c(" ", "Group A" = 5, "Group B" = 6)) %>%
  kable_as_image("sss")
```

<img width="641" alt="screen shot 2017-08-28 at 10 56 51 am" src="https://user-images.githubusercontent.com/7014590/29779407-752f9520-8be0-11e7-9578-0d630f41fb47.png">

**Comment by mbcann01** [comment]
@haozhu233,

Agreed! This is better than nothing. I'm looking forward to trying it out.
