### ISSUE TITLE
group_rows' bold argument does not do anything with HTML

### ISSUE THREAD

**Issue by AdrienLeGuillou** [haozhu233/kableExtra#420]
Hello,

Bug:
Setting the argument `bold = TRUE` in `group_rows` does not do anything with HTML

Workaround:
I could remove the `<strong>` element by doing 

```R
kable(df) %>%
  pack_rows(index = index) %>%
  gsub(pattern = "(<strong>)|<strong/>", replacement = "")
```
A cleaner solution would be to pass the `bold` and `italic` arguments to `group_rows_html()` to condition the addition of `<strong>` or `<em>` elements, similarly to what is done in `group_rows_latex().

**Comment by haozhu233** [comment]
@AdrienLeGuillou Thanks for the fix!
