### ISSUE TITLE
Can we avoid setting the global option in package loading?

### ISSUE THREAD

**Issue by dracodoc** [haozhu233/kableExtra#424]
If I'm understanding correctly, the purpose of this behavior is to set default format option to save some manual work, and `kable` is a function in another package so you cannot modify it.

> when you load this package (library(kableExtra)), it will automatically set up the global option ‘knitr.table.format’ based on your current environment. 

Still, I think it'll be better to avoid modifying user global options if possible. What if you create a `kable` function in `kableExtra`, either use same name or slightly different name (like `kableh`), which is just a wrapper for `knitr::kable`, with the format option default to `html`?

Will this solve the same problem without changing the global option?

**Comment by haozhu233** [comment]
Yeah, I just added a wrapper function for `kable`, which does the format check in every call. This new function also comes with a detailed documentation for all the hidden arguments (especially in its latex part) in `kable`.

**Comment by haozhu233** [comment]
However, we will still set global options because many poeple explicitly use `knitr::kable` which requires the global option trick.
