### ISSUE TITLE
Using nrow() in row_spec with pipes

### ISSUE THREAD

**Issue by arnold-c** [haozhu233/kableExtra#426]
Hi, 

I'm not sure if this is a bug, or the way that the pipes work (if that's the case, apologies for bringing this to the wrong place), but when I try to bold the last rows and columns in a table, it's causing an error when I use it in a pipe. In the first example, it produces an error of `Error in xml_children(x)[[search]] : subscript out of bounds`, but when I separate the pipe it works. To my mind, there shouldn't be a difference in the way it is handled, but it could also just be me misunderstanding pipes.

```
library(tidyverse)
library(janitor)
library(kableExtra)

# This produces an error
mtcars %>%
  tabyl(cyl, am) %>%
  adorn_totals(where = c("row", "col")) %>%
  kable(align = "l") %>%
  row_spec(nrow(mtcars), bold = TRUE) %>%
  column_spec(ncol(mtcars), bold = TRUE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F, position = "center")
#> Error in xml_children(x)[[search]] : subscript out of bounds

# This works fine
test <- mtcars %>%
  tabyl(cyl, am) %>%
  adorn_totals(where = c("row", "col"))
  
kable(test, align = "l") %>%
  row_spec(nrow(test), bold = TRUE) %>%
  column_spec(ncol(test), bold = TRUE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F, position = "center")
```

Thanks,
Callum

**Comment by haozhu233** [comment]
```
mtcars %>%
  tabyl(cyl, am) %>%
  adorn_totals(where = c("row", "col")) 
```
The code above generates a table with 5 rows while `nrow(mtcars)` generates 32. The pipe symbol is not playing any roles here.
