### ISSUE TITLE
latex_options - striped dont print with full_width = T

### ISSUE THREAD

**Issue by olesendan** [haozhu233/kableExtra#427]
I trying to knitr some tables to pdf.

in the following code, setting full_width = T turns off "striped". If I cahnge full_width to FALSE, the tables are striped upon knitting.

Is this expected behaviour?

`
```{r vartest, echo=FALSE, eval=TRUE, include=TRUE, message=FALSE, warning=FALSE, fig.cap="Tabel som viser deltagernes menigfulde forandring over 12 måneder."}


z02 %>% 
    as_tibble() %>% 
    filter( t_p != 1, effect != "trivial") %>% 
    select(-max, -min) %>% 
    mutate_if( .predicate = is.numeric, .funs = ~round( ., 1)) %>% 
    gather( 'key2', 'value', antal:sd) %>% 
    unite( temp, t_p, effect, key2) %>% 
    group_by_at( vars(-value)) %>%
    #mutate( row_id = 1:n()) %>% 
    ungroup() %>% 
    spread( temp, value) %>% 
    kable( ., format = 'latex', booktabs = TRUE, longtable = TRUE, linesep = "", 
          col.names = c("variabel", 
                                                               "ant", "gns", "SD", "ant", "gns", "SD", 
                                                               "ant", "gns", "SD", "ant", "gns", "SD", 
                                                               "ant", "gns", "SD", "ant", "gns", "SD", 
                                                               "ant", "gns", "SD", "ant", "gns", "SD", 
                                                               "ant", "gns", "SD", "ant", "gns", "SD") ) %>% 
    kable_styling(latex_options = c("striped", "hold_postion", "repeat_header"), font_size = 8, full_width = T) %>% 
    add_header_above( c("         " = 1, 
                        " pos" = 3, " neg" = 3, 
                        " pos" = 3, " neg" = 3, 
                        " pos" = 3, " neg" = 3, 
                        " pos" = 3, " neg" = 3,
                        " pos" = 3, " neg" = 3)) %>% 
    add_header_above(c(" " = 1, 
                       " I til II" = 6, 
                       " II til III" = 6, 
                       " III til IV" = 6, 
                       " IV til V" = 6, 
                       "I til VI" = 6)) %>%
    footnote( threeparttable = TRUE, 
             general =" oversigt over positive og negative forandinger i tests") %>% 
    landscape() 


```

`

Greetings from Denmark
Dan Olesen

**Comment by majazaloznik** [comment]
Same thing happens if you try to specify background colour e.g. with cell_spec(). 

The odd thing is that this definitely used to work, I had a bunch of reports with full width tables that had conditional formatting of cell backgrounds back in April 2019, but they don't work anymore.. 

```
tab <- head(mtcars)[1:4]
tab$hp <- cell_spec(tab$hp, background = "red")
x_latex <- knitr::kable(tab,  "latex",    escape = F)

kable_styling(x_latex,
              latex_options =c( "striped")) 

kable_styling(x_latex,
              full_width = TRUE,
              latex_options =c( "striped")) 
```

**Comment by haozhu233** [comment]
@majazaloznik @olesendan and everyone who thumbed up this issue, the only way in latex to do automated full width table is through the package `tabu`. However, it seems that tabu has some issues with supporting background color while its own taburowcolors is very difficult to be integrated into this package. So unfortunately this issue is not fixable

See:
https://github.com/tabu-issues-for-future-maintainer/tabu/issues/1
https://github.com/tabu-issues-for-future-maintainer/tabu/issues/20
https://tex.stackexchange.com/questions/36089/bug-in-tabu-when-rowcolors-are-defined

**Comment by nikosbosse** [comment]
Would it be possible to create a message or warning to alert users of this? It took me a long time to find the issue on gh. Thank you!

**Comment by thedivtagguy** [comment]
This is still an issue. A warning of some kind is needed, I ended up reinstalling and tinkering around with things thinking it was a problem on my end.
