### ISSUE TITLE
knitr / fluidPage / markdown combination doesn't work

### ISSUE THREAD

**Issue by Gateux** [haozhu233/kableExtra#428]
I am trying to put kable_extra table into html markdown output. My intention is to run for loop with arranged output (using shiny::fluidPage), however, this doesn't work.
When I use parameter knitr(format = "html"), code is shown in the output. If I use format = "markdown", only column names are shown.

````
---
title: "Untitled"
output: html_document
---

```{r cars, echo = FALSE, warning = FALSE, message = FALSE}

  l <- htmltools::tagList()
  values <- c(-100, 0, 100)
  
  for (i in 1:3) {
    l[[i]] <- fluidPage(fluidRow(plot_ly(x = rnorm(100, values[i]))),
                        fluidRow(mtcars[1:5, 1:(5 + i)] %>% kable(format = "markdown") %>% kable_styling()))
  }
  
  l

```
````

Any suggestions?

**Comment by haozhu233** [comment]
kableExtra doesn't work with markdown format. It's too simple to do any formatting
