### ISSUE TITLE
Feature request: add the option of using 'addlinespace' instead of a 'hline' to separate groupings in collapse_rows

### ISSUE THREAD

**Issue by p-phillips** [haozhu233/kableExtra#429]
Collapse rows is a neat way to group data, but sometimes I'd rather have some vertical space between rows rather than the horizontal lines which collapse_rows produces.

Can the` latex_hline` option to `collapse_rows() `have an extra argument of "`linespace`" to insert an `\addlinespace` call into the code please ?

**Comment by haozhu233** [comment]
@p-phillips I just added this feature. Not sure if it's useful though. The small linespace doesn't look very obvious to me. 🤔

**Comment by p-phillips** [comment]
It's perfect - the space is perfectly visible.  Thank you.

However, after installing the dev version of kableExtra, my long tables are being printed on a single page with the 'continued' text being put at the top of the page above the original table header.  If I go back to the 1.1.0 version, everything works again. 

Is there some change in syntax for longtable in the dev version ?

**Comment by haozhu233** [comment]
Can you provide an example? I probably changed something.

**Comment by p-phillips** [comment]
> Can you provide an example? I probably changed something.

Certainly.

```
---
title: "kableExtra tests of linespace"
header-includes:
    - '\usepackage{longtable}'
    - '\usepackage{booktabs}'
output:
    pdf_document: 
      latex_engine: xelatex
---

```{r,echo=FALSE}
library(tidyverse)
library(kableExtra)
ncars<-mtcars %>% rownames_to_column(var="carname") 
bind_rows(ncars,ncars) %>% arrange(carb) %>% select(carb,carname) %>%
  kable(
    format = "latex",
    booktabs = T, longtable = T,
    linesep = ''
    #linesep = c(rep("", 4), "\\addlinespace")
  ) %>%
  kable_styling(latex_options = c("hold_position", "repeat_header")) %>%
  collapse_rows(columns = 1, latex_hline = "major", valign = "top") 
```
```

If you change the last line to 
```
  collapse_rows(columns = 1, latex_hline = "linespace", valign = "top") 
```
everything comes out on a single page, the page continuation block comes out on the same page as the first part of table.

Hope this help.
Pete

**Comment by haozhu233** [comment]
@p-phillips Fixed now :)

**Comment by p-phillips** [comment]
Hi.

I'm afraid there is still a bug in there somewhere. 

If you look at this example you will see that it works perfectly with latex_hline = "major", but with "linespace", some of the month numbers (the last ones before the page break, such as 4 and 10) get printed ABOVE the table on the next page.

Pete
```
---
title: "kableExtra tests of linespace"
header-includes:
    - '\usepackage{longtable}'
    - '\usepackage{booktabs}'
output:
    pdf_document: 
      latex_engine: xelatex
---
```{r,echo=FALSE}
library(tidyverse)
library(kableExtra)
library(nycflights13)
flights %>% 
  select(month,day,dep_time, arr_time, flight, tailnum, origin, dest) %>% 
  slice_sample(n=100) %>%
  arrange(month,day)  %>%  
  kable(
    format = "latex",
    booktabs = T, longtable = T,
    linesep = ''
  ) %>%
  kable_styling(latex_options = c("hold_position", "repeat_header")) %>%
  # collapse_rows(columns = 1, latex_hline = "major", valign = "top") 
  collapse_rows(columns = 1, latex_hline = "linespace", valign = "top") 
`````
