### ISSUE TITLE
[Request] Add text and background color to column_spec and row_spec

### ISSUE THREAD

**Issue by artemklevtsov** [haozhu233/kableExtra#43]
Hi,

Thank you for the awesome package.
It would be nice to add params to specify a colors for text and background. It should be easy for the HTML.

**Comment by haozhu233** [comment]
Hi, @artemklevtsov, thanks for your great suggestion! This feature has been implemented now. :)

now you can use 
`column_spec(..., color = "white", background = "red")` or similar for `row_spec` to specify color or background color for columns/rows

I will provide the documentation details afterwards.
