### ISSUE TITLE
pack_rows with indent = TRUE and collapse_rows does not produce indentings

### ISSUE THREAD

**Issue by jakob-r** [haozhu233/kableExtra#430]
The combination of `pack_rows` with `indent = TRUE` does not create indentings for cells that use multicol eg. through `collapse_rows`.

See the following code:
```r
library(kableExtra)
tab = data.frame(Set = c("A", "A", "B", "B", "C"), Entry = 1:5)
kable(tab, format = "latex") %>% 
  collapse_rows(columns = 1, latex_hline = "major") %>%  
  pack_rows("Group 1", 1, 5, indent = FALSE)
```
which produces
```latex
\begin{tabular}{l|r}
\hline
Set & Entry\\
\hline
\multicolumn{2}{l}{\textbf{Group 1}}\\
\hline
\hspace{1em} & 1\\

\multirow{-2}{*}{\raggedright\arraybackslash A} & 2\\
\cline{1-2}
\hspace{1em} & 3\\

\multirow{-2}{*}{\raggedright\arraybackslash B} & 4\\
\cline{1-2}
\hspace{1em}C & 5\\
\hline
\end{tabular}
```
which ultimately leads to
![image](https://user-images.githubusercontent.com/1888623/66303085-84439380-e8fa-11e9-9bcb-9f97b317b2b7.png)
.

The correct output would be to have the `\hspace` infront of `\multirow`. I guess this would be automatically working correct if we used `\\multirow{2}` instead of `\multirow{-2}`.

**Comment by haozhu233** [comment]
@jakob-r Thanks for reporting this issue. It turns out I forgot to escape a `*` :P
