### ISSUE TITLE
Double footnotes with pasted footnotetext

### ISSUE THREAD

**Issue by benfretwurst** [haozhu233/kableExtra#431]
Hi everybody

I trying to knitr some tables to pdf.

If add add_footnote in kable with pasted Text from a function-variable the footnote doubles in LaTeX. 
My Test.Rnw:

\documentclass{article}
\usepackage{threeparttable}
\usepackage{booktabs}

\begin{document}
<<echo=F,warning=F, message=F>>=
library(knitr)
library(tidyverse)
library(kableExtra)

dt <- mtcars[1:5, 1:6]

fun_tab <- function(V, Title, Question, Measure){V <- enquo(V) 
return(
  kable(dt, format = "latex", booktabs = TRUE, caption = Title)
   %>% add_footnote(c(paste0("Question (", V ,"): ", Question), Measure), threeparttable = T) # I have tried: str_c, paste, paste0
  )}

fun_tab(cars, Title = "Lot of Cars", Question = "What do you know about cars?", Measure = "Nominal")
@
\end{document}

Greetings from Zurich
Ben

[Test.pdf](https://github.com/haozhu233/kableExtra/files/3709189/Test.pdf)

**Comment by Markouski** [comment]
This issue seems to be not connected with `kableExtra`. 
Try replacing ```V <- enquo(V)``` in your function with ```V <- rlang::get_expr(enquo(V))``` to get the clean name of the object, which has been passed into the function.

**Comment by benfretwurst** [comment]
Thank You Markouski! Your solution work perfekt:

\documentclass{article}
\usepackage{threeparttable}
\usepackage{booktabs}

\begin{document}
<<echo=F,warning=F, message=F>>=
  library(knitr)
library(tidyverse)
library(kableExtra)

dt <- mtcars[1:5, 1:6]

fun_tab <- function(V, Title, Question, Measure){V <- rlang::get_expr(enquo(V))
return(
  kable(dt, format = "latex", booktabs = TRUE, caption = Title)
  %>% add_footnote(c(paste0("Question (", V ,"): ", Question), Measure), threeparttable = T) # I have tried: str_c, paste, paste0
)}

fun_tab(cars, Title = "Lot of Cars", Question = "What do you know about cars?", Measure = "Nominal")
@
  \end{document}
