### ISSUE TITLE
footnote_marker_alphabet(2, "html") in R markdown returns "<sup>b</sup>"

### ISSUE THREAD

**Issue by vlamenco** [haozhu233/kableExtra#432]
**footnote_marker_alphabet(2, "html") in R markdown returns "<sup>b</sup>"**

**To Reproduce**

    Hi, when I try to do this 'footnote_marker_alphabet()' example in R markdown, it doesn't work, which show up with '<sup>b</sup>' , not 'b', and it seems not on the top side either.

```{r, echo=FALSE}
library(kableExtra)
dt <- mtcars[1:5, 1:5]
colnames(dt)[1] <- paste0("mpg",footnote_marker_alphabet(2, "html"))
rownames(dt)[2] <- paste0(rownames(dt)[2], footnote_marker_alphabet(1, "html"))
footnote(knitr::kable(dt, "html"), alphabet = c("Note a", "Note b"))

```

 
   my output set are:

```output:   
  prettydoc::html_pretty:
    theme: cayman
    hightlight: vignette #github 
    math: katex
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
```

So what's wrong with my script?

**Comment by vlamenco** [comment]
I just find the solution， need to add the 'knitr::kable(dt, "html",escape = F)', but it did not related with function 'footnote_marker_alphabet'.

note: escape = 'It controls whether the contents and titles should be escaped against HTML or LaTeX. Default is TRUE.'

**Comment by haozhu233** [comment]
Yep, you found the right answer!
