### ISSUE TITLE
Table caption stays centered when table is left positioned

### ISSUE THREAD

**Issue by dkStevensNZed** [haozhu233/kableExtra#435]
I'm using kableExtra/kable_styling (THANKS!) to position a small (4 column) table on the left margin when knitting to pdf. My issue is that the caption stays in the center of the page rather than assuming the position of the table.

      d.df %>% kable(format='latex', align=align, escape=escape, col.names=col.names,
        row.names=rownames, booktabs = TRUE) %>%
        kable_styling(position = 'left', latex_options=c('striped','hold_position'),
          stripe_color=s.col,font_size=font_size,full_width=FALSE) -> x

How can I get the caption to move with the table?

**Comment by joshpk** [comment]
There is a good workaround for this [here](https://stackoverflow.com/questions/54931062/can-you-left-justify-or-bold-the-table-figure-caption-for-kable-in-rmarkdown).

**Comment by dkStevensNZed** [comment]
joshpk - thank you. I'll follow up there.
