### ISSUE TITLE
Table not correctly displayed in R Markdown output

### ISSUE THREAD

**Issue by Radibor** [haozhu233/kableExtra#439]
**Describe the bug**
Using kable_styling a table is not displayed correctly in the R Markdown output.  All the table entries are missing. It is shown, correctly, though, in the Viewer and in the html document.

I'm using RStudio 1.2.5019 on Windows
knitr 1.26
tidyverse 1.2.1

**To Reproduce**

```
```

````
---
title: "A reproducible example in rmarkdown"
output: html_document
---

```{r}
library(tidyverse)
library(knitr)
library(kableExtra)
df <- head(mtcars)
kable(df, format = "html", digits = 2) %>% kable_styling()
![Capture](https://user-images.githubusercontent.com/7673882/69044629-8585d700-09f5-11ea-862d-70147c03104d.PNG)


```
````

**Comment by Markouski** [comment]
It must be connected with RStudio theme styling. Try using another RStudio theme 
`Rools > Global Options > Appearance > Editor theme `
I was able to reproduce the problem using the themes with dark background. However, the table in your example is shown correctly when a bright theme is used, e.g. Textmate (default). 
![4](https://user-images.githubusercontent.com/8161754/69478015-5ceb4c00-0dfe-11ea-84f3-ca1f7a528986.png)

**Comment by jerrythomas** [comment]
I had the same problem when using `darcula` theme. The background for the table matched the text color and this made the text invisible. Is it possible to use a styling that does not force the background color to be white, but uses the default background color?

**Comment by Radibor** [comment]
I tried another RStudio theme, and indeed my table looks fine again. So thanks for your comments! I close the issue because the problem is not due to kableExtra.

**Comment by andrewheiss** [comment]
There's a temporary solution here too https://github.com/haozhu233/kableExtra/issues/689#issuecomment-1170167006
