### ISSUE TITLE
pack_rows() does not add group label for the last row in table

### ISSUE THREAD

**Issue by DzimitryM** [haozhu233/kableExtra#441]
`pack_rows()` or `group_rows()` does not add a group header when the group includes only one row and **it is the last row in the table**. The bug happens when `longtable = TRUE` and `"repeat_header"` options are enabled.

**To Reproduce**
![kableExtra](https://user-images.githubusercontent.com/8161754/69449793-bd31ad80-0d6c-11ea-93c7-0db03ae48b0f.png)
````
---
output: 
  pdf_document: 
    keep_tex: yes
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE)
library(dplyr)
library(kableExtra)

# Define test table [3x3]
testtable <- data.frame(matrix(paste("value", 1:9), nrow = 3), stringsAsFactors = F)
colnames(testtable) = paste("Column", 1:3)
```
```{r}
# Add a label to each row
testtable %>%
  kable(format = "latex",
        longtable = TRUE,
        row.names = TRUE,
        booktabs = T) %>%
  kable_styling(latex_options = c("repeat_header")) %>%
  pack_rows(group_label = "Row header 1", start_row = 1, end_row = 1) %>%
  pack_rows(group_label = "Row header 2", start_row = 2, end_row = 2) %>%
  pack_rows(group_label = "Row header 3", start_row = 3, end_row = 3)
``` 
````
`packageVersion("kableExtra")` *‘1.1.0’*

The same code without latex option `repeat_header` produces correct results:
Excluding this line ~`kable_styling(latex_options = c("repeat_header")) `~ adds headers for all rows, including the last row:
![kableExtra2](https://user-images.githubusercontent.com/8161754/69450184-a50e5e00-0d6d-11ea-95fa-47b8b2973401.png)

**Comment by haozhu233** [comment]
@DzimitryM @joshpk @tschlach @ChrisWaloszek It seems like this bug has caught quite a few people. Sorry for the delayed response. Now it has been addressed in #476.
