### ISSUE TITLE
save_kable fails when there is space in path

### ISSUE THREAD

**Issue by zhuchcn** [haozhu233/kableExtra#444]
My path has spaces unfortunately, so `save_kable` couldn't save the file successfully. And here is the reason.

https://github.com/haozhu233/kableExtra/blob/a9504c094436d8901a8ceb3e3f3dcf0025415174/R/save_kable.R#L147

I simply just added quotes around the `temp_tex_file` and the problem is solved for me.

**Comment by accraft** [comment]
I had the exact same issue and adding quotes worked for me as well. Have you opened a pull request on this? If not, I can do so.
