### ISSUE TITLE
Long table triggers chunk name 'multiply defined'

### ISSUE THREAD

**Issue by Emmanuel-R8** [haozhu233/kableExtra#446]
If creating a pdf with a long table that spans several pages, the rendering will complain about the chunk being multiply defined (although only defined once).  

The following snippet is the sort of chunk that triggers the issue ("very-long-table multiply defined").

```
    ```{r very-long-table}
    tibble(randomRows = rnorm(1000)) %>%
      knitr::kable(
        "latex",
        caption = "Caption of the Table",
        booktabs = T,
        longtable = T,
        col.names = c("Random Number")
      )   %>%
      kableExtra::kable_styling(latex_options = c("repeat_header")) 
```
```

**Comment by haozhu233** [comment]
[Untitled.pdf](https://github.com/haozhu233/kableExtra/files/5054901/Untitled.pdf)

It seems to work fine for me. I can't reproduce this bug.

**Comment by dchiu911** [comment]
Hi @haozhu233 for some reason, setting `repeat_header_method = "append"` still sometimes causes this warning to arise. Setting to `"replace"` does not. I can only reproduce this for certain tables.
