### ISSUE TITLE
Problem with german "Umlaute" UTF-8 for example ä or ü in Latex using kable_styling

### ISSUE THREAD

**Issue by Rathpete** [haozhu233/kableExtra#45]
Hello,

i have problems with using kable_styling from kableExtra and german "Umlaute" in Latex. I use:
test <- kable(tbldf, format="latex", booktabs=TRUE, caption="Test") %>%
            kable_styling(latex_options=c("striped","scale down"))

The result shows this, with the wrong german "Umlaute":

"\\rowcolors{2}{gray!6}{white}\n\\begin{table}\n\n\\caption{\\label{tab:}hallo}\n\\centering\n\\resizebox{\\linewidth}{!}{\\begin{tabular}[t]{lllllll}\n\\hiderowcolors\n\\toprule\nunbeb & 2011 & 2012 & 2013 & 2014 & 2015 & 2016\\\\\n\\midrule\n\\showrowcolors\nindividuelle Bauweise & 87 & 77 & 95 & 101 & 60 & 127\\\\\nGeschosswohnungsbau & 29 & 26 & 49 & 29 & 45 & 36\\\\\nklassisches Gewerbe & 10 & 18 & 22 & 13 & 13 & 11\\\\\n**terti攼㸴res Gewerbe** & 25 & 12 & 4 & 9 & 4 & 5\\\\\nNichtbauland & 126 & 108 & 91 & 122 & 103 & 93\\\\\nSumme unbebaute **Grundst昼㹣cke** & 277 & 241 & 261 & 274 & 225 & 272\\\\\n\\bottomrule\n\\end{tabular}}\n\\end{table}\n\\rowcolors{2}{white}{white}"
attr(,"format")
[1] "latex"
attr(,"class")
[1] "knit_asis"
attr(,"kable_meta")
attr(,"kable_meta")$tabular
[1] "tabular"

attr(,"kable_meta")$booktabs
[1] TRUE

attr(,"kable_meta")$align
[1] "lllllll"

Is there a solution for this???

Peter Rath

**Comment by wibeasley** [comment]
Hi @Rathpete, thanks for bringing this up.  To help the process, could do mind adding a second post that 
1. is [reproducible](https://gist.github.com/hadley/270442) and
1. demonstrates the undesired conversion occurs with `kableExtra::kable_styling()` (instead of `knitr::kable()`)
?

**Comment by Rathpete** [comment]
**Here ist the tbldf:**

structure(list(unbeb = c("individuelle Bauweise", "Geschosswohnungsbau", "klassisches Gewerbe", "tertiäres Gewerbe", "Nichtbauland", "Summe unbebaute Grundstücke"
), `2011` = c(" 87", " 29", " 10", " 25", "126", "277"), `2012` = c(" 77", " 26", " 18", " 12", "108", "241"),  `2013` = c(" 95", " 49", " 22", "  4", " 91", "261"), `2014` = c("101", " 29", " 13", "  9", "122", "274"), `2015` = c(" 60", " 45", " 13", "  4", "103", "225"), `2016` = c("127", " 36", " 11", "  5", " 93", "272")), .Names = c("unbeb", "2011", "2012", "2013", "2014", "2015", "2016"), row.names = c(NA, -6L), class = c("tbl_df", "tbl", "data.frame"))


**with knitr::kable() ist shows the corrcet "Umlaute" like this:**

**kable(Daten_Tabelle_unbeb, format = "latex", booktabs=TRUE, caption="hallo")**

structure("\\begin{table}\n\n\\caption{\\label{tab:}hallo}\n\\centering\n\\begin{tabular}[t]{lllllll}\n\\toprule\nunbeb & 2011 & 2012 & 2013 & 2014 & 2015 & 2016\\\\\n\\midrule\nindividuelle Bauweise & 87 & 77 & 95 & 101 & 60 & 127\\\\\nGeschosswohnungsbau & 29 & 26 & 49 & 29 & 45 & 36\\\\\nklassisches Gewerbe & 10 & 18 & 22 & 13 & 13 & 11\\\\\ntertiäres Gewerbe & 25 & 12 & 4 & 9 & 4 & 5\\\\\nNichtbauland & 126 & 108 & 91 & 122 & 103 & 93\\\\\nSumme unbebaute Grundstücke & 277 & 241 & 261 & 274 & 225 & 272\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table}", format = "latex", class = "knitr_kable")

**only with kableExtra:: kalbe_styling the undesired conversion occurs**

**kable(Daten_Tabelle_unbeb, format = "latex", booktabs=TRUE, caption="hallo") %>% kable_styling(latex_options=c("striped","scale_down"))**

**It put in <U+653C><U+3E34> for "ä" and U+663C><U+3E63 for "ü":**

structure("\\rowcolors{2}{gray!6}{white}\n\\begin{table}\n\n\\caption{\\label{tab:}hallo}\n\\centering\n\\resizebox{\\linewidth}{!}{\\begin{tabular}[t]{lllllll}\n\\hiderowcolors\n\\toprule\nunbeb & 2011 & 2012 & 2013 & 2014 & 2015 & 2016\\\\\n\\midrule\n\\showrowcolors\nindividuelle Bauweise & 87 & 77 & 95 & 101 & 60 & 127\\\\\nGeschosswohnungsbau & 29 & 26 & 49 & 29 & 45 & 36\\\\\nklassisches Gewerbe & 10 & 18 & 22 & 13 & 13 & 11\\\\\nterti<U+653C><U+3E34>res Gewerbe & 25 & 12 & 4 & 9 & 4 & 5\\\\\nNichtbauland & 126 & 108 & 91 & 122 & 103 & 93\\\\\nSumme unbebaute Grundst<U+663C><U+3E63>cke & 277 & 241 & 261 & 274 & 225 & 272\\\\\n\\bottomrule\n\\end{tabular}}\n\\end{table}\n\\rowcolors{2}{white}{white}", format = "latex", class = "knitr_kable", kable_meta = structure(list(
    tabular = "tabular", booktabs = TRUE, align = "lllllll", 
    valign = "[t]", ncol = 7L, nrow = 7, colnames = c("unbeb", 
    "2011", "2012", "2013", "2014", "2015", "2016"), rownames = c("unbeb", 
    "individuelle", "Geschosswohnungsbau", "klassisches", "tertiäres", 
    "Nichtbauland", "Summe"), caption = "\\label{tab:}hal", contents = c("unbeb & 2011 & 2012 & 2013 & 2014 & 2015 & 2016", 
    "individuelle Bauweise & 87 & 77 & 95 & 101 & 60 & 127", 
    "Geschosswohnungsbau & 29 & 26 & 49 & 29 & 45 & 36", "klassisches Gewerbe & 10 & 18 & 22 & 13 & 13 & 11", 
    "tertiäres Gewerbe & 25 & 12 & 4 & 9 & 4 & 5", "Nichtbauland & 126 & 108 & 91 & 122 & 103 & 93", 
    "Summe unbebaute Grundstücke & 277 & 241 & 261 & 274 & 225 & 272"
    ), centering = TRUE, table_env = TRUE, align_vector = c("l", 
    "l", "l", "l", "l", "l", "l"), align_vector_origin = c("l", 
    "l", "l", "l", "l", "l", "l"), valign2 = "\\[t\\]", valign3 = "t", 
    begin_tabular = "\\\\begin\\{tabular\\}\\[t\\]", end_tabular = "\\\\end\\{tabular\\}"), .Names = c("tabular", 
"booktabs", "align", "valign", "ncol", "nrow", "colnames", "rownames", 
"caption", "contents", "centering", "table_env", "align_vector", 
"align_vector_origin", "valign2", "valign3", "begin_tabular", 
"end_tabular")))

**Comment by haozhu233** [comment]
Hi, @Rathpete, somehow I couldn't reproduce the bug. Could it be your R environment issue?
<img width="672" alt="screen shot 2017-08-23 at 9 56 26 am" src="https://user-images.githubusercontent.com/7014590/29619687-b0054154-87e9-11e7-8b44-c100981ed283.png">

**Comment by Rathpete** [comment]
In don`t know...
I use the code above in a rmarkdown chunk and this is the ouput:

![grafik](https://user-images.githubusercontent.com/31278285/29621644-a3ad9a5e-8821-11e7-995c-2e64ed111d33.png)


My R environment is:
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.1 tools_3.4.1

**Comment by haozhu233** [comment]
I think this thread will help you out:
https://stackoverflow.com/questions/16347731/how-to-change-the-locale-of-r-in-rstudio

Basically, you can try `Sys.setenv(LANG = "en_US.UTF-8")` or something else on that question.

**Comment by Rathpete** [comment]
The system setting windows.1252 are the standard settings for windows in Germany. Everything in R works until now with this settings. I think the result ist, that i can not use the awesome package kableExtra to generate latex tables in R...

**Comment by Rathpete** [comment]
I hope you can fix it inside the package, because the kable()-function works with windows.1252

**Comment by Rathpete** [comment]
I check something out.
The problems with the depend on the latex_option="striped" 
Without this ist the output:
> kable(tt,  format="latex", booktabs=TRUE) %>%
+   
+   kable_styling()
\begin{table}[!h]
\centering
\begin{tabular}{lllllll}
\toprule
unbeb & 2011 & 2012 & 2013 & 2014 & 2015 & 2016\\
\midrule
individuelle Bauweise & 87 & 77 & 95 & 101 & 60 & 127\\
Geschosswohnungsbau & 29 & 26 & 49 & 29 & 45 & 36\\
klassisches Gewerbe & 10 & 18 & 22 & 13 & 13 & 11\\
tertiäres Gewerbe & 25 & 12 & 4 & 9 & 4 & 5\\
Nichtbauland & 126 & 108 & 91 & 122 & 103 & 93\\
Summe unbebaute Grundstücke & 277 & 241 & 261 & 274 & 225 & 272\\
\bottomrule
\end{tabular}
\end{table}


with the option this is the output:
\begin{tabular}{lllllll}
\hiderowcolors
\toprule
unbeb & 2011 & 2012 & 2013 & 2014 & 2015 & 2016\\
\midrule
\showrowcolors
individuelle Bauweise & 87 & 77 & 95 & 101 & 60 & 127\\
Geschosswohnungsbau & 29 & 26 & 49 & 29 & 45 & 36\\
klassisches Gewerbe & 10 & 18 & 22 & 13 & 13 & 11\\
terti�res Gewerbe & 25 & 12 & 4 & 9 & 4 & 5\\
Nichtbauland & 126 & 108 & 91 & 122 & 103 & 93\\
Summe unbebaute Grundst�cke & 277 & 241 & 261 & 274 & 225 & 272\\
\bottomrule
\end{tabular}
\rowcolors{2}{white}{white}
\end{table}

**Comment by Rathpete** [comment]
Only with "scale_down" everything is O.K.:

> kable(tt,  format="latex", booktabs=TRUE) %>%
+   
+   kable_styling(latex_options=c("scale_down"))
\begin{table}[!h]
\centering
\resizebox{\linewidth}{!}{\begin{tabular}{lllllll}
\toprule
unbeb & 2011 & 2012 & 2013 & 2014 & 2015 & 2016\\
\midrule
individuelle Bauweise & 87 & 77 & 95 & 101 & 60 & 127\\
Geschosswohnungsbau & 29 & 26 & 49 & 29 & 45 & 36\\
klassisches Gewerbe & 10 & 18 & 22 & 13 & 13 & 11\\
tertiäres Gewerbe & 25 & 12 & 4 & 9 & 4 & 5\\
Nichtbauland & 126 & 108 & 91 & 122 & 103 & 93\\
Summe unbebaute Grundstücke & 277 & 241 & 261 & 274 & 225 & 272\\
\bottomrule
\end{tabular}}
\end{table}

Maybe it is only a problem with the "striped" option. In will check out this tomorrow...

**Comment by haozhu233** [comment]
I get it. I will modify the code and add `enc2utf8` to places where necessary.

**Comment by Rathpete** [comment]
Great! Thank you!

**Comment by haozhu233** [comment]
@Rathpete I solved this issue in https://github.com/haozhu233/kableExtra/commit/d2c0f73e21c69c84a02de780cbdb5515e03baf1d.  I tested it and the bug seems to have gone away. Could you help me test it out in the battlefield? I will appreciate that.

**Comment by Rathpete** [comment]
It also works well!!!

Thank you very much!
