### ISSUE TITLE
Support for non-Bootstrap styling

### ISSUE THREAD

**Issue by michaelquinn32** [haozhu233/kableExtra#451]
Hi Hao!

In case you weren't aware, bootstrap 3 is no longer supported, and bootstrap 4 support will end in about a year. Twitter's release schedule mentions maintenance (minimal support) to start six months after the 4.4 release and the end of life (i.e. no support) to start six months.
https://github.com/twbs/release

The 4.4 released happened back in November.

Bootstrap isn't the only library for styling tables. For example, there's a material one:
https://material.io/components/data-tables

Would it be possible to add support for other css libraries in kableExtra?

Thanks!

**Comment by haozhu233** [comment]
Hi Mike! How have you being? Sorry for being late on this. I just added 4 alternative themes to this package. https://haozhu233.github.io/kableExtra/awesome_table_in_html.html#Alternative_themes 

It is absolutely okay to add additional css libraries. We just need to write additional `kable_classic`-like function in [`light_themes.R`](https://github.com/haozhu233/kableExtra/blob/master/R/light_themes.R) to put on the themes and the style sheet is [here](https://github.com/haozhu233/kableExtra/blob/master/inst/lightable-0.0.1/lightable.css). Do you have any other recommendations?

**Comment by michaelquinn32** [comment]
This is awesome! Thank you.

No need to get to it now, but one other style option is to use the CSS from datatables:
https://datatables.net/examples/styling/

They also support a few different table themes, if you're interested.
