### ISSUE TITLE
Footnote determines the width of the table.

### ISSUE THREAD

**Issue by bsalak** [haozhu233/kableExtra#453]
**Hi there,**
Unfortunately I have a similar problem like in issue 272 (see:[https://github.com/haozhu233/kableExtra/issues/272](url)) and others, which I can't get rid off by myself. Problem is a long footnote, but the "threeparttable=T" suggested in the post mentioned does not help to fix it. Maybe I am doing it wrong. However, the footnote determines the width of the table, although the columns are defined with units.
I would be grateful if anybody could help me out here.
Thanks!

```{r}
library(kableExtra)
kable(t3mmod_LS, align = c(rep("l",1), rep("c",3)),escape = F) %>% 
   kable_styling( bootstrap_options = c("condensed"), full_width = F) %>% 
   footnote(general = c("'Coeff' = coefficient, 'SE' = standard error, 'Coeff/SE' = z-score, 'CRA' = Cronbachs Alpha."), 
            alphabet = c("Coefficient is fixed; significance is not applicable." ,"No EFA was calculated for the utilitaristic landscape connotation items, as at least three indicators are recommended for measuring a latent construct. Instead, the mean of the displayed variables was applied."), threeparttable = T) %>% 
   column_spec(1, width = "2.5cm") %>% column_spec(2:4, width = "2cm") %>%
   pack_rows("Arcadic landscape connotation. \n[NOI 8, CRA 0.95]", 1,8) %>%
   pack_rows(paste0("Utilitarian landscape connotation.", footnote_marker_alphabet(2)), 9,10, escape = F)
```
````

**Comment by hongyuanjia** [comment]
Same problem here. When `escape` is set to `FALSE` in `kable()`, `kableExtra::column_spec()` won't take effect.

**Comment by bsalak** [comment]
Hey there,
1. When I use Rstudio with `kableExtra` package, no `booktabs` option appears. Do I need to have LaTeX installed for that? Please apologize my lack of knowledge.  I don't know anything about LaTeX.
2. Also, does `booktabs` have to be placed in `column_spec`command or already in `kable`command?
thx!

**Comment by hongyuanjia** [comment]
Hi @bsalak , `booktabs` is an option for `knitr::kable()`, not for `kableExtra()`.

```r
kable(..., escape = FALSE, booktabs = TRUE) %>%
   kableExtrac::kable_styling(...)
```

**Comment by bsalak** [comment]
HI @hongyuanjia ,
I was assuming that, but unfortunately the command `booktabs` does not exist in my `knitr` installation (1.28). So when I start to type in the first letters of the `escape` command, it gets auto-completed after the 3rd letter (as usual). Regarding `booktabs` nothing happens. (My) RStudio does not recognize this command.  Is that even possible?

When I check `?knitr::kable` I get the following list of commands implemented:
`kable(
  x,
  format,
  digits = getOption("digits"),
  row.names = NA,
  col.names = NA,
  align,
  caption = NULL,
  label = NULL,
  format.args = list(),
  escape = TRUE,
  ...
)`

Also in the package [website](https://yihui.org/knitr/options/#package-options), command `booktabs` does not appear. Is it maybe coming from another package?

**Comment by hongyuanjia** [comment]
Hi @bsalak, `booktabs` is an additional option that can be supplied in `...` but is only applicable to LaTeX output. You can see how to use it in the examples of `?knitr::kable()`

```r
# use the booktabs package
kable(mtcars, format = "latex", booktabs = TRUE)
```

**Comment by haozhu233** [comment]
@hongyuanjia Thanks a lot for helping solving this issue! @bsalak is your question soled right now? I tried to render your table and it seems like it's working excepting the linebreak in the first grouped row label. 

[Untitled.pdf](https://github.com/haozhu233/kableExtra/files/5052407/Untitled.pdf)
