### ISSUE TITLE
cell_spec a and text_spec: admit a target_blank=T/F argument

### ISSUE THREAD

**Issue by dan-reznik** [haozhu233/kableExtra#454]
it's useful for hyperlinks to open up in a new tab. to do this the href must be of the sort:

```
<a href="http://url.com" target="_blank">xxx</a>
```
so I was thinking you might want to include "target_blank", or "new_tab" as an argument to both cell_spec and text_spec, e.g.

```{r}
ts <- text_spec("google", link="google.com", new_tab=T)

**Comment by haozhu233** [comment]
Done in https://github.com/haozhu233/kableExtra/commit/dcbdff6c12060e5421f268791ee1871161788daa

Now you can use 
```
ts <- text_spec("google", link="google.com", new_tab=T)
```
