### ISSUE TITLE
`column_spec` producing compilation error in latex pdf

### ISSUE THREAD

**Issue by gaballench** [haozhu233/kableExtra#46]
Hi,

Thanks for this awesome package! I found a problem when using the `kableExtra::column_spec` function both with my own data frame and the example in the LaTeX vignette of the package. I'm using `knit` and editing my Rnw file in emacs with ESS.

The document will not compile unless the package `array` is in the preamble of the Rnw file. Despite the same occurs with the `booktabs` package that is needed for the knitr::kable function's argument `booktabs` to work, but I found no mention of the `array` package both in the vignette and the function manual. I suggest to include somewhere a list of the latex packages that would be potentially needed for the document to compile smoothly. This is just a suggestion but think that such move will improve greatly the user experience.

Thanks again,

Gustavo

**Comment by haozhu233** [comment]
`kableExtra` will load these latex packages automatically on start-up in a rmarkdown environment. I guess I should have provided this list for sweave users in the documentation. Thanks for your suggestion. I will add these to the vignette later. 

For now, you can check the [zzz](https://github.com/haozhu233/kableExtra/blob/master/R/zzz.R) file in this package to see what packages are necessary.

**Comment by haozhu233** [comment]
Hi, @gaballench, I just added some documentation to the pdf vignette. It's at the very beginning of the document and should be very easy to find. 
http://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf

If you find the documentation I provided isn't clear enough, feel free to let me know.
