### ISSUE TITLE
Feature request -- collapse_rows by start_row and end_row

### ISSUE THREAD

**Issue by sorenoneill** [haozhu233/kableExtra#460]
The collapse_rows function collapses rows on the basis of identical cell content

Say we wanted to collapse both columns, but col2 says something in relation to col1

```
---------          
| a | x |          
---------       
| a | x |       
---------         
| a | x |
---------       
| b | x |       
---------       

```

If we collapse both columns we would get something like: 

```
---------          
|    |    |          
| a |    |         
|    | x |
----|    |       
| b |    |       
---------       

```

But on some occasions, it may be useful to collapse on row numbers (start and end) to obtain this 

```
---------          
|    |    |          
| a | x |         
|    |    |
---------       
| b | x |       
---------       

```

**Comment by haozhu233** [comment]
@sorenoneill Done. See #484 for details.
