### ISSUE TITLE
when library(kableExtra) in bookdown, the text reference does not work

### ISSUE THREAD

**Issue by CavPeng** [haozhu233/kableExtra#461]
the text reference is a usage of bookdown
![image](https://user-images.githubusercontent.com/21274194/76674361-9f24dd00-65e9-11ea-8f18-b4fd7fd2c290.png)

But it doesn't work just after adding a line "library(kableExtra)" in the setup chunk, help...

THEN I find that when I set echo=TRUE in the "kable" chunk , it works again. why...
AND put the "library(kableExtra)" in the "kable" chunk , instead of putting in the "setup" chunk is also work

hereis the code:
---
title: "A"
author: "A"
date: "`r Sys.Date()`"
site: "bookdown::bookdown_site"
bookdown::gitbook:
  css: style.css
documentclass: ctexbook
description: "A"
---

# ch1

```{r setup}
library(tidyverse)
library(kableExtra)
```

(ref:text1) theTableCaption
```{r tab1,echo=FALSE,include=TRUE}
mtcars %>% 
  knitr::kable(caption = "(ref:text1)")
```

![image](https://user-images.githubusercontent.com/21274194/76674741-89b1b200-65ed-11ea-889b-c5e6ca4a5cc1.png)

put "library(kableExtra)" in the kable chunk:
![image](https://user-images.githubusercontent.com/21274194/76674779-e9a85880-65ed-11ea-8a88-0521e1792d9f.png)

here is the code

```{r setup}
library(tidyverse)

```

(ref:text1) theTableCaption
```{r tab1,echo=FALSE,include=TRUE}
library(kableExtra)
mtcars %>% 
  knitr::kable(caption = "(ref:text1)")
```
it also works when echo=TURE
![image](https://user-images.githubusercontent.com/21274194/76674828-4efc4980-65ee-11ea-9b90-62e8712c3df5.png)

![image](https://user-images.githubusercontent.com/21274194/76674818-39871f80-65ee-11ea-9123-e1d1cfac3598.png)

**Comment by nitramwin** [comment]
The roundabout solution in Bookdown is to do the following. Note the name of the R chunk with the table we want which is referenced with the following code in your paragraph: `\@ref(tab:thermal-service-temperatures)`.

```
```{r required-packages-for-demand-chapter, echo=FALSE, message=FALSE}
library(dplyr)
library(knitr)
library(kableExtra)```
```

```
```{r thermal-service-temperatures, echo = FALSE }
# Make lists
Service_Name <- c("Heating","Water Heating","Cooling","Refrigeration")
Supply_Temp <- c( 50, 65, 12, 3)
Return_Temp <- c( 30, 20, 18, 8)

# Make dataframe and column names
thermal_service_temps_df <- data.frame(Name,Supply,Return, stringsAsFactors = FALSE)
colnames <- data.frame("Name", "T.supply", "T.return", stringsAsFactors = FALSE)
colnames(thermal_service_temps_df) <- colnames

# Make Table
kable(thermal_service_temps_df, caption = "Temperatures", booktabs = TRUE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))```
```

**Comment by haozhu233** [comment]
@nitramwin Thanks for the solution! :)
