### ISSUE TITLE
Tune Caption Font

### ISSUE THREAD

**Issue by larry77** [haozhu233/kableExtra#462]
Thanks for this wonderful package!
One question more than a bug: I cannot find a way to tune the caption font size independently from the size of the rest of the table.
Can anyone help me here?
E.g.

``
kable(dt, "latex", caption = "Demo table", booktabs = T) %>%
kable_styling(latex_options = c("striped", "hold_position"))

``

**Comment by larry77** [comment]
I updated the example.

**Comment by haozhu233** [comment]
caption size? You will have to use the caption package and do it through the latex way. For this part, since they are so different in html and latex, I didn't include this feature.
