### ISSUE TITLE
Adding library(kableExtra) to RMarkdown knit to pdf file that uses parameters in latex, causes error.

### ISSUE THREAD

**Issue by Ljupch0** [haozhu233/kableExtra#463]
The code below uses params$cat parameter as inline r code in latex: 
```- \fancyhead[CO,CE]{`r params$cat`}``` 

The code below gives an error. Removing library(kableExtra), removes the error. Keeping library(kableExtra) and removing the r in latex ``r params$cat`` removes the error as well. 

````
---
output:
  pdf_document:
    latex_engine: xelatex
params:
  cat: "Felix"
  numb: 14
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead[CO,CE]{`r params$cat`}
---

# CHAPTER 1
Oh my \textbf{`r params$cat`}. 
$x = `r 2*params$numb`^2$

```{r }
library(kableExtra)
```
````

**Comment by haozhu233** [comment]
Interesting. This must be related to how they implemented rmarkdown latex part. 

One solution is to disable the automatic latex package loading behavior by kableExtra and load those packages by yourself. 

options(kableExtra.latex.load_packages = FALSE)

See page 3 of the pdf doc for details. https://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf
