### ISSUE TITLE
collapse_rows fails with large string

### ISSUE THREAD

**Issue by gerardhros** [haozhu233/kableExtra#464]
**Describe the bug**
when I have a table with a very long string in one of the columns, collapse rows fails with error "Error in sub(contents[i + 1], new_contents[i], out) :  invalid regular expression" coming from R211 in collapse_rows_latex. 

**To Reproduce**
# produce an example data.frame
dt <- data.frame(C1 = c(rep("a", 10), rep("b", 5)),
                C2 = c(rep("c", 7), rep("d", 3), rep("c", 2), rep("d", 3)),
                C3 = c(paste0(rep('a',1452),collapse=''),1:14),
                 C4 = sample(c(0,1), 15, replace = TRUE))
kable(dt, "latex", booktabs = T, align = "c")  %>% kableExtra::collapse_rows(columns = 1, latex_hline = "major", valign = "middle")
the code works fine as long as the lengt of C3[1] is smaller than 1450. if its 1450 or bigger, it fails with aforementioned error

# solution?
it has something to do with the default behaviour of text replacement of sub.
i didn't check into detail, but replacing statement 
"out <- sub(contents[i + 1], new_contents[i], out)" with
 "out <- sub(contents[i + 1], new_contents[i], out,perl=TRUE)" 
or with
"out <- stringr::str_replace(out,contents[i+1],new_contents[i])" prevented that error. 
something to test / consider?

**Comment by haozhu233** [comment]
I changed it to sub(..., perl=T) and tested it around. Everything seems to work. Thanks!
