### ISSUE TITLE
Cannot center align table in Bookdown via "Position" option

### ISSUE THREAD

**Issue by nitramwin** [haozhu233/kableExtra#465]
**Describe the bug**
"Position" command does not work in Bookdown for generated table. Also, using the following HTML code before and after the code chunk does not work:
`<div align="center">` and `</div>`
`<center>` and `</center>` 

**To Reproduce**
```
# To get started
library(knitr)
library(kableExtra)
dt <- mtcars[1:5, 1:6]

# Now to the example ... note that the position is not the default "left" but rather "center"
kable(dt) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "center")
```

**Comment by haozhu233** [comment]
The default position for tables in bookdown is centering, correct?

https://haozhu233.github.io/kableExtra/bookdown/cross-format-tables-in-bookdown.html#prepare-your-tables-for-all-formats
