### ISSUE TITLE
Problem with "["-bracket in data, if using collapse_rows()

### ISSUE THREAD

**Issue by Rathpete** [haozhu233/kableExtra#47]
There is a problem using collapse rows, if [ is in the data. Here are two examples. One with [ and one without [:

library(dplyr)
library(knitr)
library(kableExtra)

test <- tibble(A1=c(rep("A",3),"B"),A2=c("a","[","c","d"))
test2 <-tibble(A1=c(rep("A",3),"B"),A2=c("a","b","c","d"))
                    
kable(test, booktabs=TRUE, format="latex") %>% collapse_rows(1)

kable(test2, booktabs=TRUE, format="latex") %>% collapse_rows(1)

and the results:

![grafik](https://user-images.githubusercontent.com/31278285/29705271-7f310064-897d-11e7-99f1-08411d3be5ca.png)

**Comment by Rathpete** [comment]
a 3rd example:

library(dplyr)
library(knitr)
library(kableExtra)

test <- tibble(A1=c(rep("A",3),"B"),A2=c("[","[","[","["))
test2 <-tibble(A1=c(rep("A",3),"B"),A2=c("a","b","c","d"))
                    
kable(test, booktabs=TRUE, format="latex") %>% collapse_rows(1)

kable(test2, booktabs=TRUE, format="latex") %>% collapse_rows(1)

![grafik](https://user-images.githubusercontent.com/31278285/29705513-9b0f8624-897e-11e7-9165-ab760f7bb49e.png)

**Comment by haozhu233** [comment]
I see. I will look into that

**Comment by haozhu233** [comment]
Fixed now. It was a typo in one of my utility functions.

**Comment by Rathpete** [comment]
It works well!!!
Thank you!
