### ISSUE TITLE
Underscore in caption doesn't render to PDF correctly

### ISSUE THREAD

**Issue by dfrankow** [haozhu233/kableExtra#474]
**Describe the bug**
Underscore in caption doesn't render to PDF correctly

**To Reproduce**

Put this entire document in an Rmarkdown file (say `foo.Rmd`):

````
---
output: pdf_document
---
```{r table}
library(kableExtra)
df <- data.frame(a=c(1,2,3),b=c(4,5,6))
kable(df, caption="This is a caption with_some_underscores", escape=TRUE)
````

When rendered, it has TeX junk in it, and the caption is not present:

![image](https://user-images.githubusercontent.com/34655/83310238-f8f07880-a1d0-11ea-95e0-3160e4f604a4.png)

`escape=FALSE` does not help.

If I escape the underscores, it works:

````
---
output: pdf_document
---
```{r table}
library(kableExtra)
df <- data.frame(a=c(1,2,3),b=c(4,5,6))
kable(df, caption="This is a caption with\\_some\\_underscores")
````

![image](https://user-images.githubusercontent.com/34655/83310391-7916de00-a1d1-11ea-9e76-be1a2e00f255.png)

It works either way in HTML.

I'm using kableExtra 1.1.0, R 3.6.3, RStudio 1.2.5042, on OS X 10.14.

**Comment by haozhu233** [comment]
@dfrankow Thanks for reporting this issue. This is the default behavior of `kable` in `knitr` instead of this package. 

Also, although I agree that the behavior of escaping caption should have been consistent across HTML and LaTeX, this function has been out for so many years and people have kind of get used to manually escape their latex caption. Changing this will likely break many others' existing code.

**Comment by dfrankow** [comment]
Could you give a function (even here) to properly quote text for LaTeX in this package? I made this one, but it's probably missing something.

```
#' NOTE: currently only escapes underscores.  It may need more.
escape_string_for_latex <- function(str) {
  gsub("_", "\\\\_", str)
}
```

**Comment by haozhu233** [comment]
@dfrankow Just saw your reply. I think knitr:::escape_latex is what you need (there is a copy in this package as well). If you need 4 backslashes, you can use kableExtra:::escape_latex2. 

https://github.com/haozhu233/kableExtra/blob/master/R/from_knitr.R

**Comment by dfrankow** [comment]
Oh great, thank you!

For other readers:
- the triple-colon allows access to internal symbols
- [here's](https://rdrr.io/cran/kableExtra/src/R/from_knitr.R) the source
