### ISSUE TITLE
kable function 'as.image' fails when trying to store temporary file in impossible directory

### ISSUE THREAD

**Issue by RudolfLi** [haozhu233/kableExtra#475]
**Describe the bug**
When using kable from within markup in Rstudio, with output set to HTML, everything works. 
When I change output to Word and try to include the table as image, execution stops with an error message.

**To Reproduce**

---
title: "A reproducible example in rmarkdown"
output: html_document
---

```{r}
library(magrittr)
library(qwraps2)
library(kableExtra)

# create example data
mytab1 <- data.frame(matrix(ncol = 6, nrow = 0))
x <- c("Item", "Printlabel", "median", "75% pctl.", "min","max")
colnames(mytab1) <- x

mytab1[1,"Item"] = "I1"
mytab1[2,"Item"] = "I2"
mytab1[3,"Item"] = "I3"
mytab1[1,"Printlabel"] = "Printlabel 1"
mytab1[2,"Printlabel"] = "Printlabel 2"
mytab1[3,"Printlabel"] = "Printlabel 3"

mytab1[1,"median"] = 6.4
mytab1[2,"median"] = 6.4
mytab1[3,"median"] = 7.3
mytab1[1,"75% pctl."] = 6.9
mytab1[2,"75% pctl."] = 6.7
mytab1[3,"75% pctl."] = 7.7
mytab1[1,"min"] = 3.5
mytab1[2,"min"] = 5.0
mytab1[3,"min"] = 5.7
mytab1[1,"max"] = 8.4
mytab1[2,"max"] = 8.1
mytab1[3,"max"] = 8.9
# data is now ready in mytab1

# call kable to produce output (this works Ok)
my_img1 = kable(mytab1,digits=1) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F)  

# try to include kable output as image into Word output
# this halts with an error message
my_img1 = kable(mytab1,digits=1) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F) %>% as_image()

```

---
Additional remarks
---
In order to find what was causing the problem, I copy-pasted the command in the console (after running the chunk so that all data is available) and ran it.
This gave the following result:

![image](https://user-images.githubusercontent.com/15846250/83978238-550c7880-a906-11ea-90fa-beb7672b9cdf.png)

The problem is that the code tries to save a file to this directory (note the dot in front !): 
".\C:\Users\....."
Which can't exist on Windows. 

I did some further investigating and found that at some point the code produces this temporary filename: "C:\Users\....", which is fine. Only in the subroutine "save_kable_html()" does the code seem to generate the wrong filename with the dot in front.

**Comment by RudolfLi** [comment]
For completeness I include the traceback I got in RStudio:

![image](https://user-images.githubusercontent.com/15846250/83978504-30190500-a908-11ea-9031-ab8c7d00b3e3.png)

**Comment by haozhu233** [comment]
I can't reproduce this bug. Are you doing this on a company computer where you can't create temp files? Maybe you should consider save it as a local file and then load that image manually in rmarkdown.
