### ISSUE TITLE
Feature request: choose the target column in collapse_rows

### ISSUE THREAD

**Issue by DanChaltiel** [haozhu233/kableExtra#484]
Hi Haozhu,

I think it would be very useful to be able to differentiate the choosing column and the target column when collapsing cells.

In my case, I want to collapse the rows of the `label` column based on the `id` column.

```
    library(tidyverse)
    library(kable)
    library(kableExtra)
    df = tibble(id=rep(1:3, each=3), 
                label=rep(c("A", "B", "B"), each=3), 
                value=round(rnorm(9), 2)) 
    
    df %>% 
        kable() %>% 
        collapse_rows(valign="top")
    
```
![image](https://user-images.githubusercontent.com/15105152/88095909-22f16600-cb96-11ea-9aaf-3c48d386376e.png)

Here is the expected output, using `flextable` (which unfortunately do not always works perfectly with Rmarkdown):
```
    library(flextable)
    df %>% 
        flextable() %>% 
        merge_v(j="id", target = c("id", "label")) %>% 
        valign(valign="top")
```
![image](https://user-images.githubusercontent.com/15105152/88095846-09501e80-cb96-11ea-959f-328e23586137.png)

**Comment by haozhu233** [comment]
Done. Thanks for the suggestion. Now you can do 

```
library(tidyverse)
library(kableExtra)
df = tibble(id=rep(1:3, each=3), 
            label=rep(c("A", "B", "B"), each=3), 
            value=round(rnorm(9), 2)) 


df %>% 
  kable() %>%
  collapse_rows(valign = "top", target = 1)
```

and get
<img width="112" alt="Screen Shot 2020-08-03 at 9 17 21 AM" src="https://user-images.githubusercontent.com/7014590/89187177-ef85e280-d56a-11ea-8892-ae33469590f9.png">
