### ISSUE TITLE
latex_options = c("striped") not working well with pack_rows()

### ISSUE THREAD

**Issue by ChrisWaloszek** [haozhu233/kableExtra#485]
**Describe the bug**
When using `pack_rows()` on a table with `latex_options = c("striped")`, then rows are no longer striped alternatingly. Instead, the grouping rows and the next after are always striped in the same color, which leads to an unusual striping behavior.
Manually generating an alternating stripe pattern is not as straight forward as the MWE below illustrates.
A fix would thus be helpful, in particular, to allow for the automatic generation of (larger amounts of) tables.

**Automatic striping with kable_styling(latex_options = "striped")**
```
tab <- mtcars[1:5,1:4] %>% kable(booktabs = T) 

tab %>% 
  kable_styling(latex_options = "striped") %>% 
  # group rows together and give these groups labels
  pack_rows("Mazda", 1, 2, bold = FALSE, italic = TRUE) %>% 
  pack_rows("Datsun", 3, 3, bold = FALSE, italic = TRUE) %>% 
  pack_rows("Hornet", 4, 5, bold = FALSE, italic = TRUE)
```
![Screen Shot 2020-07-23 at 13 40 42](https://user-images.githubusercontent.com/6472717/88282771-74ab0500-ccea-11ea-9fe0-4a45f4b55c0c.png)

**Adding manual striping: `stripe_index = c(1,2,3,4,5)`**
```
tab %>% 
  kable_styling(latex_options = "striped", stripe_index = c(1,2,3,4,5)) %>% 
  # group rows together and give these groups labels
  pack_rows("Mazda", 1, 2, bold = FALSE, italic = TRUE) %>% 
  pack_rows("Datsun", 3, 3, bold = FALSE, italic = TRUE) %>% 
  pack_rows("Hornet", 4, 5, bold = FALSE, italic = TRUE)
```
![Screen Shot 2020-07-23 at 13 40 47](https://user-images.githubusercontent.com/6472717/88282781-783e8c00-ccea-11ea-9909-51465b1c2bd8.png)

**Adding manual striping: `stripe_index = c(1:2,3,4:5)`**
```
tab %>% 
  kable_styling(latex_options = "striped", stripe_index = c(1:2,3,4:5)) %>% 
  # group rows together and give these groups labels
  pack_rows("Mazda", 1, 2, bold = FALSE, italic = TRUE) %>% 
  pack_rows("Datsun", 3, 3, bold = FALSE, italic = TRUE) %>% 
  pack_rows("Hornet", 4, 5, bold = FALSE, italic = TRUE)
```
![Screen Shot 2020-07-23 at 13 40 55](https://user-images.githubusercontent.com/6472717/88282790-7bd21300-ccea-11ea-84b4-7741069dd473.png)

**Comment by haozhu233** [comment]
This used to be possible when latex `xcolor` package was still usable but an update in another latex package in 2019 forced me to specify the row colors manually in kableExtra, which doesn't understand group labels as rows. So I would say this is actually quite difficult to fix.

**Comment by xlejx-rodsxn** [comment]
Hi, I am having the same issues. It is a pity, my tables looked way cooler with the striped lines...  has there been any progress on this?

**Comment by haozhu233** [comment]
@xlejx-rodsxn you can manually set row colors via `row_spec`. As I said, since `xtable`'s color option is no longer usable in recent latex distribution, this is not something I can fix

**Comment by xlejx-rodsxn** [comment]
Oh ok, gotcha now. thanks for the quick reply :P
