### ISSUE TITLE
Label name for crossreference

### ISSUE THREAD

**Issue by marcofaga** [haozhu233/kableExtra#486]
Is there a built-in command on KableExtra for table crossreference name? 

I usually handle this adding '\label{name} in caption argument. 

But, I would like to know if theres a built-in  solution for that.

**Comment by haozhu233** [comment]
This is actually a built-in feature in knitr::kable. Just use `kable(..., label = "something")`. It's already there. 

https://github.com/yihui/knitr/blob/2e08d5a9cb0a3b83cd73fd30d507a18676b0c4a4/R/table.R#L39-L40
