### ISSUE TITLE
Next push to CRAN

### ISSUE THREAD

**Issue by 1beb** [haozhu233/kableExtra#487]
Hi Hao, do you have a timeline for your next push to CRAN?

**Comment by haozhu233** [comment]
@1beb I had been quite slow in terms of making improvements to this package. Are there specific features you are looking for?

**Comment by 1beb** [comment]
`latex_column_spec`. A parameter to `col_spec` was added to 1.1.0.900 is not available in the current CRAN version (1.1.0). It looks like it was added in April 2019: 
 (https://github.com/haozhu233/kableExtra/commit/8bc9622922ca6502f87855e9fcaa14bba5404918#diff-8e37d46f4efa245298a8fbf3502fef76). 

Wondering if this will go to CRAN soon or if it's better to point to github repo. Appreciate the response! Great work on this package.

**Comment by haozhu233** [comment]
I think I'm ready to do another cran release. However right now the CRAN team is on vacation. I will submit it next week when they are back.

**Comment by 1beb** [comment]
Thanks for the note Hao! I have a couple package authors that I'm bugging for new package releases for github/cran parity and the response is "CRAN on vacay" heh! Everyone needs a break :)

**Comment by haozhu233** [comment]
It's on cran now

**Comment by 1beb** [comment]
You the man Hao!
