### ISSUE TITLE
kable indent rows with specified hspace for all columns

### ISSUE THREAD

**Issue by myaseen208** [haozhu233/kableExtra#488]
The following code add indentations to the 2nd & 4th rows for first column only.

```
library(kableExtra)
knitr::kable(head(mtcars[ ,1:4]), "latex") %>% 
  add_indent(positions = c(2, 4))
```

Wondering how to add indentations of specific hspace to the 2nd & 4th rows for all columns. Something like this

```
library(kableExtra)
knitr::kable(head(mtcars[ ,1:4]), "latex") %>% 
  add_indent(positions = c(2, 4), hspace = "2em", allCols = TRUE)
```

**Comment by haozhu233** [comment]
@myaseen208 Done. Now you can use 

```
knitr::kable(head(mtcars[ ,1:4]), "latex", align = "l") %>% 
  add_indent(positions = c(2, 4), level_of_indent = 2, all_cols = TRUE)
```

Note that if your columns are right aligned, you won't be able to see the indentation, which makes sense. That's the reason why I put align = "l" in the example above.

**Comment by myaseen208** [comment]
Thanks @haozhu233 for your making necessary changes in `add_indent` function. The solution given on [Stackoverflow](https://stackoverflow.com/a/63120573/707145) works with `align = "l"`. Please have a quick look on this.
