### ISSUE TITLE
Option to use the [H] float specifier from the float package

### ISSUE THREAD

**Issue by robshep** [haozhu233/kableExtra#49]
Hi,

I've just been trying out a option that I have added to my local fork.

I find useful the [H] float specifier from the float package. 

You can see my implementation here, and seems to work fine.

https://github.com/robshep/kableExtra/commit/c59d15e4cace6ce33c3e43aa9ec40ca2731f6471

**Comment by haozhu233** [comment]
Thanks, it makes sense. Do you want to start a pull request?

Also, you can put `usepackage_latex("float")` in the `if` statement, so it will load the `float` package in a rmarkdown environment.

**Comment by haozhu233** [comment]
I merged the changes you made. Thanks again for your contribution!
