### ISSUE TITLE
collapse_rows(valign = "top") not working well in latex table

### ISSUE THREAD

**Issue by cristinamarchant** [haozhu233/kableExtra#493]
First of all, I love this package!

I have a little issue with the top-aligned columns. This appears related to #416 and #297. Reprex at the bottom.

I have not problems when I use booktabs = FALSE.

<img width="126" alt="issue1" src="https://user-images.githubusercontent.com/55768429/90829844-8d6d0180-e30e-11ea-9064-455d141db449.png">

But, when I use booktabs = TRUE, the alignment of the column go to the middle instead.

<img width="117" alt="issue2" src="https://user-images.githubusercontent.com/55768429/90830180-3a477e80-e30f-11ea-8f96-ebc10697d945.png">

Also, I can write this without problems bookstabs = TRUE plus latex_hline = "major":

<img width="103" alt="issue3" src="https://user-images.githubusercontent.com/55768429/90830228-4cc1b800-e30f-11ea-8553-1f8817b67246.png">

But, if I drop the latex_hline = "major", the alignment of the column come back to the center.

<img width="115" alt="issue4" src="https://user-images.githubusercontent.com/55768429/90830249-56e3b680-e30f-11ea-82ef-717bd6ef8a4d.png">

``` r
example <- data.frame(C1 = c(rep("a", 10), rep("b", 5)),
C2 = 1:15)

kableExtra::kable(example, caption = 'Ok', booktabs = FALSE) %>%
collapse_rows(columns = 1, valign = "top")

kableExtra::kable(example, caption = 'Not Ok', booktabs = TRUE) %>%
collapse_rows(columns = 1, valign = "top")

kable(example, caption = "Ok", booktabs = TRUE) %>% 
    collapse_rows(columns = 1, valign = "top", latex_hline = "major")

kable(example, caption = "Not Ok", booktabs = TRUE) %>% 
    collapse_rows(columns = 1, valign = "top")

```

Thanks a lot for the great package!

**Comment by haozhu233** [comment]
Yeah, I also encountered this issue before but this is a bug in the latex package multirow. Basically booktabs' cmidrule screws up multirow's row height calculation. 

https://tex.stackexchange.com/questions/66564/vertical-alignment-using-multirow-and-booktabs

**Comment by rcyost** [comment]
So was there a fix? I cannot do booktabs AND make text vertical aligned?
