### ISSUE TITLE
Strings italicized when surrounded by parentheses

### ISSUE THREAD

**Issue by vincentarelbundock** [haozhu233/kableExtra#494]
Again, thanks so much for your work on `kableExtra`. For me, it is one of the most useful packages, period.

With version 3e21ff9560ae639db0 , when my table includes strings with parentheses, the parentheses are removed and the string is italicized.

MWE:

```r
library(kableExtra)
library(magrittr)
dat <- data.frame(a = c("(parentheses)", "no parentheses"))
kable(dat) %>% kable_styling()
```

Produces this image:

![Rplot](https://user-images.githubusercontent.com/987057/90840694-aaaec980-e328-11ea-8c16-6a639d7779e5.png)

This is very problematic in my use-case. In the `modelsummary` package, I must display standard errors in parentheses.

Edit for session info:

```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.5

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] kableExtra_1.1.2

loaded via a namespace (and not attached):
 [1] viridisLite_0.3.0 digest_0.6.25     R6_2.4.1          lifecycle_0.2.0
 [5] magrittr_1.5      evaluate_0.14     scales_1.1.1      highr_0.8
 [9] httr_1.4.2        stringi_1.4.6     rlang_0.4.7       rstudioapi_0.11
[13] xml2_1.3.2        rmarkdown_2.3     webshot_0.5.2     tools_4.0.2
[17] stringr_1.4.0     glue_1.4.1        munsell_0.5.0     xfun_0.16
[21] compiler_4.0.2    colorspace_1.4-1  rvest_0.3.6       htmltools_0.5.0
[25] knitr_1.29
```

**Comment by vincentarelbundock** [comment]
The present proposal cannot move forward until I know more about this issue:

https://github.com/haozhu233/kableExtra/issues/494

**Comment by haozhu233** [comment]
@vincentarelbundock Nice catch. It's great that you caught this bug before it goes to cran. 

Recently I loaded mathjax library in the live print-out in order to solve #473 and I didn't config it correctly. It's an easy fix.

**Comment by vincentarelbundock** [comment]
Excellent! I reinstalled and everything looks good. Thanks for the quick fix!
