### ISSUE TITLE
Collapsed rows don't alternate striping

### ISSUE THREAD

**Issue by dchiu911** [haozhu233/kableExtra#495]
**Describe the bug**
Rows that have been collapsed don't alternate striping. Instead, the colour is carried over from the first non-collapsed row of the next column.

**To Reproduce**
Adapted reprex from #361:

In the first example, the first column has correct striping because the first group happens to have an odd number of rows. This causes the second group in the first column to be darker.
```r
library(kableExtra)
df <- data.frame(
  first = c(1, 1, 1, 2, 2),
  second = c("a", "b", "b", "a", "b"),
  third = c("x", "y", "z", "z", "x"),
  price = c(10, 42, 9, 6, 23)
)

df %>%
  kable() %>%
  kable_styling(full_width = FALSE, bootstrap_options = "striped") %>%
  collapse_rows(columns = 1, valign = "top")
```
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> first </th>
   <th style="text-align:left;"> second </th>
   <th style="text-align:left;"> third </th>
   <th style="text-align:right;"> price </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;vertical-align: top !important;" rowspan="3"> 1 </td>
   <td style="text-align:left;"> a </td>
   <td style="text-align:left;"> x </td>
   <td style="text-align:right;"> 10 </td>
  </tr>
  <tr>
   
   <td style="text-align:left;"> b </td>
   <td style="text-align:left;"> y </td>
   <td style="text-align:right;"> 42 </td>
  </tr>
  <tr>
   
   <td style="text-align:left;"> b </td>
   <td style="text-align:left;"> z </td>
   <td style="text-align:right;"> 9 </td>
  </tr>
  <tr>
   <td style="text-align:right;vertical-align: top !important;" rowspan="2"> 2 </td>
   <td style="text-align:left;"> a </td>
   <td style="text-align:left;"> z </td>
   <td style="text-align:right;"> 6 </td>
  </tr>
  <tr>
   
   <td style="text-align:left;"> b </td>
   <td style="text-align:left;"> x </td>
   <td style="text-align:right;"> 23 </td>
  </tr>
</tbody>
</table>

However, when the first group has an even number of rows, then the colour is copied over and now there is no alternate striping for the first column. Is it possible to modify this so that the first column is always striped irrespective of the other columns?
```r
library(kableExtra)
df <- data.frame(
  first = c(1, 1, 1, 1, 2, 2),
  second = c("a", "b", "b", "a", "a", "b"),
  third = c("x", "y", "z", "y", "z", "x"),
  price = c(10, 42, 9, 19, 6, 23)
)

df %>%
  kable() %>%
  kable_styling(full_width = FALSE, bootstrap_options = "striped") %>%
  collapse_rows(columns = 1, valign = "top")
```
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:right;"> first </th>
   <th style="text-align:left;"> second </th>
   <th style="text-align:left;"> third </th>
   <th style="text-align:right;"> price </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;vertical-align: top !important;" rowspan="4"> 1 </td>
   <td style="text-align:left;"> a </td>
   <td style="text-align:left;"> x </td>
   <td style="text-align:right;"> 10 </td>
  </tr>
  <tr>
   
   <td style="text-align:left;"> b </td>
   <td style="text-align:left;"> y </td>
   <td style="text-align:right;"> 42 </td>
  </tr>
  <tr>
   
   <td style="text-align:left;"> b </td>
   <td style="text-align:left;"> z </td>
   <td style="text-align:right;"> 9 </td>
  </tr>
  <tr>
   
   <td style="text-align:left;"> a </td>
   <td style="text-align:left;"> y </td>
   <td style="text-align:right;"> 19 </td>
  </tr>
  <tr>
   <td style="text-align:right;vertical-align: top !important;" rowspan="2"> 2 </td>
   <td style="text-align:left;"> a </td>
   <td style="text-align:left;"> z </td>
   <td style="text-align:right;"> 6 </td>
  </tr>
  <tr>
   
   <td style="text-align:left;"> b </td>
   <td style="text-align:left;"> x </td>
   <td style="text-align:right;"> 23 </td>
  </tr>
</tbody>
</table>

**Comment by haozhu233** [comment]
In both bootstrap and all of the current lightable themes, we made the striped color by using the CSS nth child technique, which basically counts the number of `<tr>`. Unfortunately, when you have a cell that spans multiple rows, this is how it will behave and it's not very easy to change...

**Comment by dchiu911** [comment]
I see, it's not a big deal, just wanted to see if anyone else ran into this. Instead I've copied tables into word and re-striped the first column
