### ISSUE TITLE
`save_kable(tab, "table.tex")` should save a .tex file and not try to compile to PDF or image.

### ISSUE THREAD

**Issue by vincentarelbundock** [haozhu233/kableExtra#496]
My understanding is that `save_kable` is meant as a universal entry point to save `kableExtra` output. As such, I expected this code to save a `.tex` file, and not to try to compile an image:

```r
  library(magrittr)
  library(kableExtra)

  data.frame(a = 1:3) %>%
    kbl("latex") %>%
    kable_styling() %>%
    save_kable("test.tex")
```
As I understand it, the problem comes from this line of code:

https://github.com/haozhu233/kableExtra/blob/master/R/save_kable.R#L158

This check is too capacious: `if (tools::file_ext(file) != "pdf") {`

Instead, it should check if the extension if `.tex`, and write to file directly if that's the case, without attempting to compile an image.

I'm happy to try a PR if that's something you'd be interested in.

**Comment by haozhu233** [comment]
When I need to save as tex, I usually just do `kable() %>% ... %>% cat("file.tex")`. However I guess your understanding of `save_kable` as a universal entry point also makes sense. Yeah, if you can do a PR, that will be very helpful!

**Comment by haozhu233** [comment]
When I want to save as a tex, I usually just do

```
kable(mtcars, "latex") %>%
  cat("something.tex")
```
