### ISSUE TITLE
Markdown support in `footnote`

### ISSUE THREAD

**Issue by vincentarelbundock** [haozhu233/kableExtra#498]
The document now recommends using `footnote` instead of `add_footnote`:

http://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf

Unfortuantely, `footnote` does not appear to support markdown. Is there interest in adapting the markdown-specific code in `add_footnote` to improve `footnote`?

**Comment by haozhu233** [comment]
`add_footnote` was the first function in this package. At that time I was still trying to provide minimal support to markdown format. However, as I'm adding more features to this package, I realized that it was not possible so I stopped that attempt. When I recreated `footnote` based on people's request of creating different kinds of footnotes at the same time, I didn't include the markdown piece just as what I did for many other functions.

I mean I think it's definitely possible to add this functionality but other than the small group of people who's willing to look into the code, most people won't know that "ah this footnote function will work on markdown table too". :P

**Comment by vincentarelbundock** [comment]
Good to hear about where you're coming from on this! Totally understand that this is low/none-priority.

My use-case is to print regression tables in the Console, and the legend for significance stars is displayed at the bottom of the table. So footnotes in markdown is actually quite a common thing. But `add_footnote` works perfectly as it is, so there's really no need to spend time on this.

I'll close this.
