### ISSUE TITLE
`save_kable(tab, "~/test.jpg")` does not work with relative paths or absolue paths from root

### ISSUE THREAD

**Issue by vincentarelbundock** [haozhu233/kableExtra#499]
As of https://github.com/haozhu233/kableExtra/commit/5585d9c9c4b55efe32f3594ed072d1927ba2bd51, we can only save images in the current directory or in folders nested within the current directory. Also, `save_kable` does not accept relative paths for image files:

```r
    library(kableExtra)
    tab <- kbl(data.frame(a = 1:2))

    save_kable(tab, file = "~/test.jpg")
    #> Warning in file.create(file_temp_html): cannot create file './~/
    #> test179966037041a.html', reason 'No such file or directory'
    #> Warning in normalizePath(file_temp_html): path[1]="./~/test179966037041a.html":
    #> No such file or directory
    #> Error in setwd(dir): cannot change working directory

    save_kable(tab, file = "/Users/username/test.jpg")
    #> Warning in file.create(file_temp_html): cannot create file './/Users/username/
    #> test17996251ca946.html', reason 'No such file or directory'
    #> Warning in normalizePath(file_temp_html): path[1]=".//Users/username/
    #> test17996251ca946.html": No such file or directory
    #> Error in setwd(dir): cannot change working directory
```

This is due to this line, which does not properly normalize file paths:

https://github.com/haozhu233/kableExtra/blob/master/R/save_kable.R#L63

**Comment by haozhu233** [comment]
Yeah, I will look into that. I also realized that `tempfile` doesn't work with file.path() on windows so it's good to do a code review here. Thanks!

**Comment by thegeologician** [comment]
Hi @haozhu233 , I had a quick look at https://github.com/haozhu233/kableExtra/blob/a73cf4ac100860a1ee5991896ef2404cab654d82/R/save_kable.R#L63

In lines 63 - 71, I noticed two things:
- When you call `tempfile()`, you explicitly give tempdir= as either "." or "" - by default, that would use a call to `tempdir()`, which should usually return a temporary location the user has write access to. You might not need to specify tempdir=... explicitly.
- You call `file.create(file_temp_html)`, and THEN `normalisePath(file_temp_html)`. I guess calling `normailsePath(file_temp_html)` before trying to create the file might help to avoid the issue of this thread.

**Comment by haozhu233** [comment]
@vincentarelbundock @thegeologician I looked into this issue tonight and I realized that I tried to fix this issue two years ago. 

https://github.com/rstudio/htmltools/issues/104
https://github.com/rstudio/htmltools/pull/105

**Comment by haozhu233** [comment]
It turns out a single `basename` is all I need. :P

**Comment by vincentarelbundock** [comment]
Great news! Thanks for all your work, as always.
