### ISSUE TITLE
kableExtra with latex package in yaml

### ISSUE THREAD

**Issue by GuangchuangYu** [haozhu233/kableExtra#5]
Here is a minimal example:

```
---
title: "Untitled"
output:
  bookdown::pdf_book: default
header-includes:
  - \usepackage{tocloft}  
---

\renewcommand{\cftfigfont}{Figure }


```{r cars}
library(knitr)
library(kableExtra)
usepackage_latex('tocloft')
dt <- mtcars[1:5, 1:6]

options(knitr.table.format = "latex")

kable(dt,booktabs = T) %>%
   kable_styling(latex_options = c("striped", "hold_position"), full_width = T)
```

If not loading the latex package `tocloft` manually using `usepackage_latex('tocloft')`, knitting the file will throw the following error, even I do load `tocloft` in `yaml` via `header-includes`.

```
! LaTeX Error: \cftfigfont undefined.

Error: Failed to compile Untitled.tex. See Untitled.log for more info.
Execution halted
```

`header-includes` in `yaml` works fine if not using `kableExtra`.

**Comment by haozhu233** [comment]
This bug is being fixed in https://github.com/rstudio/rmarkdown/issues/1026

After the fix being merged, this problem will go away with the latest dev version of rmarkdown.
