### ISSUE TITLE
Omit environments

### ISSUE THREAD

**Issue by ggrothendieck** [haozhu233/kableExtra#500]
It would be useful in customized output  to be able to omit the latex table and/or tabular environments.  For example, we might want to put several tables in the same table environment.  Suggest that `table.envir` and `latex_table_env` arguments each allow a value of FALSE in which case the corresponding environment is suppressed from the output.

**Comment by haozhu233** [comment]
Well, it's actually kinda hard to do. To the end, the latex part of this package is a collection of regex tricks, which rely on these table/tabular key words to understand kable. If time can go back to a few years ago, I probably won't make it in this way but it is what it is. Anyway, for your case, if I understand your need correctly, I think you can try write your own version of regex function to remove the pieces you don't want at the end of process.

**Comment by ggrothendieck** [comment]
If the problem is that they need to be there as placeholders would it work if the code commented them out instead of removing them?

**Comment by haozhu233** [comment]
That might actually work, haha

I will take a look at it.

**Comment by ggrothendieck** [comment]
Actually thinking about it a bit more I just thought of another way that would not require any change to the software at all.  One could use `table.envir="@empty"` and `latex_table_env="@empty"`.  That would just turn them into environments that do nothing.

**Comment by haozhu233** [comment]
@ggrothendieck there is always a magical latex trick!
