### ISSUE TITLE
column_spec_html_cell is missing a default for image argument when include_thead=TRUE

### ISSUE THREAD

**Issue by matthewcarlucci** [haozhu233/kableExtra#504]
**Describe the bug**
Introduced in 5fe235c93b0699115cf6fb0fb23f7e2f3edf5321 `include_thead=TRUE` appears to be broken.

**To Reproduce**

From the example in column_spec:

```r
# Works
x <- kableExtra::kable(head(mtcars), "html")
column_spec(x, 1:2, width = "20em", bold = TRUE, italic = TRUE)

# Error
x <- kableExtra::kable(head(mtcars), "html")
column_spec(x, 1:2, width = "20em", bold = TRUE, italic = TRUE, include_thead = FALSE)
#Error in column_spec_html_cell(target_cell, width, width_min, width_max,  : 
#  argument "image" is missing, with no default
```

**Comment by haozhu233** [comment]
Yeah, it was a bug that introduced recently with the changes to column_spec. I think it's fixed now.

**Comment by lexzhou** [comment]
> Yeah, it was a bug that introduced recently with the changes to column_spec. I think it's fixed now.

Hi haozhu233, I am currently using the function "column_spec" on my new laptop and I cannot solve this issue... I got this error another day in my old laptop and I ended up solving it by reinstall "kableExtra" package, but it does not work on my new laptop. Hope you can help me...

My codes are: 

for (i in 1:ncol(resultsTable)) {
  tTable = tTable %>% column_spec(i+1, background = groupColors[i], include_thead = TRUE) %>%
    column_spec(i+1, background = "inherit")
}
Error in column_spec_html_cell(target_cell, width, width_min, width_max, : argument "image" is missing, with no default
