### ISSUE TITLE
merge columns kableExtra

### ISSUE THREAD

**Issue by TerriGibson** [haozhu233/kableExtra#509]
HI Everyone, 

I'm making a table and I'd like to merge columns. I have columns with values and standard error, and I'd like to merge them into one column that displays the value and standard error next to it in brackets. value(standard errror) 

Is there any way to do this in kableExra? 

I've already tried flextable and gt and have come up against other limitations there. 

This is what I have so far to give you an idea:

library("kableExtra")

AP.BD.table<- AP.BD.SE %>% kbl(caption = "Table 1. Mean aeration porosity and bulk density for productive 
      and unproductive ACR and GLSA fields. The standard error of the mean is shown in brackets.
       There was no interaction between field quality and field type.", 
                               col.names = c('Field Quality', 'Depth', 'Time', 'Field Type',
                                             'n', 'Aeration Porosity (%)', 'sd', 'se', 'ci',
                                             'n', 'Bulk Density (Mg kg "*m^-3*")', 'sd', 'se', 'ci'),digits=2) %>%
  kable_classic(full_width = F, html_font = "Times New Roman")%>%
  collapse_rows(columns = 1:4, valign = "top")%>%
  remove_column(7)%>%remove_column(8)%>%remove_column(10)%>%remove_column(11)%>%
  add_header_above(c(" " = 4, "Aeration Porosity" = 3, "Bulk Density" = 3))

I'm quite new to R and coding, thank you for your help!

**Comment by r2evans** [comment]
I'd think the best way to merge the columns it to do it in R, before `kable` or `kableExtra` are even in the picture. For instance,

```r
AB.BD.SE %>%
  mutate(newval = sprintf("%0.02f [%0.02f]", mu, sd)) %>%
  kbl(...)
```

**Comment by haozhu233** [comment]
@r2evans thanks for helping solving issues here! Very appreciated! 

@TerriGibson @r2evans's suggestion is what I was trying to say. At least right now it's a cleaner practice to modify column outside.

**Comment by TerriGibson** [comment]
Thank you both for your help with this issue! 

I also added brackets around the standard error values before putting it into kableExtra.

AP.BD.SE1$seAP <- with(AP.BD.SE1,  paste0("(", seAP, ")"))
