### ISSUE TITLE
kable_styling  stripe_color = "gray!6"

### ISSUE THREAD

**Issue by abusjahn** [haozhu233/kableExtra#510]
the default stripe_color is a non-valid color, "gray!6"

kable_styling <- function(kable_input,
                          bootstrap_options = "basic",
                          latex_options = "basic",
                          full_width = NULL,
                          position = "center",
                          font_size = NULL,
                          row_label_position = "l",
                          repeat_header_text = "\\textit{(continued)}",
                          repeat_header_method = c("append", "replace"),
                          repeat_header_continued = FALSE,
                          stripe_color = "gray!6",
                          stripe_index = NULL,
                          latex_table_env = NULL,
                          protect_latex = TRUE,
                          table.envir = "table",
                          fixed_thead = FALSE,
                          htmltable_class = NULL,
                          html_font = NULL,
                          wraptable_width = '0pt')

**Comment by haozhu233** [comment]
Although not that obvious from its name (:P), that stripe color option is only for latex. In latex, it's a valid color with xcolor which is loaded by default by the default pandoc latex template now.
