### ISSUE TITLE
column_spec_html_cell fails when used after pack_rows

### ISSUE THREAD

**Issue by EcoulMontero** [haozhu233/kableExtra#512]
After updating to version 1.2.1 of kableExtra, the `column_spec()` function doesn't work when used after the `pack_rows()` function for html documents:

```{r}
kable(mtcars, 'html')  %>%
  pack_rows(index = c("Beautiful cars" = 2, "Ugly cars" = 4)) %>% 
  column_spec(1, width = "46%")
```
This yields the error "Error in if (bold) { : missing value where TRUE/FALSE is required". However, the following chunk still works,

```{r}
kable(mtcars, 'html') %>% 
  column_spec(1, width = "46%") %>%
  pack_rows(index = c("Beautiful cars" = 2, "Ugly cars" = 4))
```

**Comment by haozhu233** [comment]
Sure, it's a bug introduced very recently. Thanks for reporting this issue! Fixed now

**Comment by EcoulMontero** [comment]
It works! Thanks for your prompt reply.
