### ISSUE TITLE
The HTML output is incomplete and it is limited to a specific character length in a data frame

### ISSUE THREAD

**Issue by cyrusjoudieh** [haozhu233/kableExtra#513]
**Describe the bug**

Attached files:
[result_df.zip](https://github.com/haozhu233/kableExtra/files/5174849/result_df.zip)

kable function column_spec is failing with this current data frame in result_df.zip.

Error text:
  Error in xml_children(x)[[search]] : subscript out of bounds

If you remove the function column_spec the output of the html is incorrect (incomplete)

The table output should be from 2017-01 till 2020-09
but when it fails without using the function column_spec the output is from 2017-01 till 2018-10

If you change the size of the column name for example: "count" to "counts" or one of the values under any column starting from AA 123 the output is correct and also if you add or delete a column the output is complete

**To Reproduce**
Included the r script below to reproduce the error.

```
# code to reproduce the bug.
library(kableExtra)

result_df <- readRDS("result_df.rds")

vect_align = c("l", "r", "c")
n_col = ncol(result_df)

for(i in seq_len(n_col-3)) {
  vect_align = c(vect_align, "r")
}

html <- result_df %>%
  kable(format = "html", escape = F, align = vect_align) %>% 
  kable_styling("striped", fixed_thead = TRUE) %>%
  column_spec(1:n_col, width = "2.2cm")
````
Versions:
```
R: 3.6.3
kabelExtra: 1.2.1
OS: Windows 10 Pro 2004
Rstudio: 1.3.1073
```

**Comment by haozhu233** [comment]
The problem you described is very strange and I can't reproduce it using the code and data you provided. Without column_spec, the function works fine with all the rows. I think you should probably try to review your code again and see what exactly happened.

**Comment by cyrusjoudieh** [comment]
The same code under Linux works fine with no issues, as I realized the problem only occurs under windows.

* Here is the code that outputs incomplete table
```
library(kableExtra)

result_df <- readRDS("result_df.rds")

vect_align = c("l", "r", "c")
n_col = ncol(result_df)

for(i in seq_len(n_col-3)) {
  vect_align = c(vect_align, "r")
}

result_df %>%
  kable(format = "html", escape = F, align = vect_align) %>% 
  kable_styling("striped", fixed_thead = TRUE) 

#%>%  column_spec(1:n_col, width = "2.2cm")
```
Prints output till 2018-10
outputs incomplete html which causes column_spec function to fail: see attached picture incomplete
![Incomplete](https://user-images.githubusercontent.com/1870894/92298435-71de3980-ef51-11ea-970c-7018a12b50c7.png)

* After renaming column count to counts the code works fine. 
```
library(kableExtra)

result_df <- readRDS("result_df.rds")

names(result_df)[names(result_df) == "count"] <- "counts"

vect_align = c("l", "r", "c")
n_col = ncol(result_df)

for(i in seq_len(n_col-3)) {
  vect_align = c(vect_align, "r")
}

result_df %>%
  kable(format = "html", escape = F, align = vect_align) %>% 
  kable_styling("striped", fixed_thead = TRUE) 

#%>%  column_spec(1:n_col, width = "2.2cm")
```
Prints output till 2020-09
outputs complete HTML and here if you enable column_spec it does not fail: 
![complete](https://user-images.githubusercontent.com/1870894/92298433-6f7bdf80-ef51-11ea-8bcc-725faaad9628.png)

**Comment by haozhu233** [comment]
@cyrusjoudieh Sorry for the delay. I run into other things and was super busy. 

I looked into this problem again. It seems to be an xml2 issue. Check out this example:

```
library(kableExtra)
library(xml2)

result_df <- readRDS("result_df.rds")
vect_align = c("l", "r", "c")
tb <- result_df %>%
  kable(format = "html", escape = F, align = vect_align)
# We know that aaa is working on windows

tb_xml <- read_xml(as.character(tb))
xml_child(xml_child(tb_xml, 2), 23) 
# The code above will read the raw html code as xml. Then it will select the 2nd child (tbody) and the 23rd row in tbody.
# The 23rd row is supposed to be there but in this case it will fail and produce the same error as you received. 
```

Since kableExtra uses xml2 to do all the xml mapping, there is nothing I can do at this moment to solve this bug. I think you should try to report this issue to xml2 but again it seems to be kind of difficult to isolate this behavior...

**Comment by cyrusjoudieh** [comment]
I have attached another file result_df2.rds that works with your earlier code.

[result_df2.zip](https://github.com/haozhu233/kableExtra/files/5378219/result_df2.zip)

Further more I have narrowed down the issue where the read_xml fails only when applying the **align=vect_align** to all the columns in **kable** function and proceeded further with function **kable_styling**.

As you can see in the second part of the code where all the columns are being set to right align.

```
library(kableExtra)
library(xml2)

result_df <- readRDS("result_df2.rds")
vect_align = c()

tb <- result_df %>%
  kable(format = "html", escape = F, align = vect_align)  %>% 
  kable_styling("striped", fixed_thead = TRUE)

# We know that aaa is working on windows

#This one doesn't crash
tb_xml <- read_xml(as.character(tb))
xml_child(xml_child(tb_xml, 2), 23)

#writeLines(tb, con="x.html")

n_col = ncol(result_df)

for(i in seq_len(n_col)) {
  vect_align = c(vect_align, "r")
}

tb <- result_df %>%
  kable(format = "html", escape = F, align = vect_align) %>% 
  kable_styling("striped", fixed_thead = TRUE)

#This one crashes
tb_xml <- read_xml(as.character(tb))
xml_child(xml_child(tb_xml, 2), 23)
```

**Comment by haozhu233** [comment]
@cyrusjoudieh Thank you for further tracing down the issue! However, when it comes to system-specific xml parsing bug, it's really beyond my capacity to fix it. 😣
