### ISSUE TITLE
kableExtra opening tables in browser

### ISSUE THREAD

**Issue by mjdufort** [haozhu233/kableExtra#514]
This issue is very similar to [closed issue 131](https://github.com/haozhu233/kableExtra/issues/131).  The issue first appeared for me after updating to R 4.0.2 and kableExtra 1.2.1. I was not seeing it when previously running similar code with R 3.6.2 and kableExtra 1.1.0.

When I output a kable using kableExtra inside a loop or function within an Rmarkdown script generating HTML output, instead of being output to the markdown file, the kable is opened in my web browser.

I have traced the issue specifically to kableExtra within loops/functions.  If I generate a kable using only kable(), it is output to the markdown document even if it is within a loop/function.  And if I modify a kable using kableExtra, but not inside a loop/function, it is also output correctly.  If I print a kable modified using kableExtra _within a loop or function_, it gets sent to the browser.

The code below reproduces the odd behavior for me, with examples of normal behavior from kable, and from kableExtra outside loop/function.

````
---
title: "Code for kableExtra issue reproducible example"
output:
  html_document
---

# Load packages

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
library(kableExtra)
```

# Generate fake data

```{r generate_fake_data}
nrow_df <- 10
df <-
  data.frame(
    letter = letters[1:nrow_df],
    number = 1:nrow_df,
    random = rnorm(nrow_df))
```

# Output kable using kable()

## Standard kable

```{r output_kable}
kable(df)
# outputs to markdown document
```

## Using kable(), within loop

```{r output_kable_within_loop, results="asis"}
for (i in 1) {
  kable(df) %>%
    print()
}
# outputs to markdown document
```

## Using kable(), within function

```{r output_kable_within_function, results="asis"}
foo1 <- function(x) print(kable(x))
foo1(df)
# outputs to markdown document
```

# Output kable using kableExtra

## Standard kableExtra

```{r output_kable_with_kableExtra}
kable(df) %>%
  kableExtra::kable_styling()
# outputs to markdown document
```

# Using kableExtra, within loop

```{r output_kable_with_kableExtra_within_loop, results="asis"}
for (i in 1) {
  kable(df) %>%
    kableExtra::kable_styling() %>%
    print()
}
# outputs to browser
```

# Using kableExtra, within function

```{r output_kable_with_kableExtra_within_function, results="asis"}
foo2 <- function(x) print(kableExtra::kable_styling(kable(x)))
foo2(df)
# outputs to browser
```
````

**Comment by haozhu233** [comment]
You don't not need to use the print() function in R markdown. You might want to replace print() with cat() for the thing you are trying to do. kableExtra's own print method will output a html table to the rstudio viewer. But I guess you are right, if someone is not using rstudio, it doesn't make too much sense for the live preview feature.

**Comment by mjdufort** [comment]
Thank you, replacing print() with cat() in the Rmarkdown code fixed the problem.

**Comment by Matherion** [comment]
Awesome! Thank you for this, I was running into the same thing with dozens of browser tabs being opened. Also here, replacing `print` with `cat` in the `for` loops did the trick. Thank you both!!!

**Comment by gosianow** [comment]
Hello, I had the same issue when using `for` loops and `print`. Thank you for proposing the solution. In my case, tables were displayed in the tabs but not inserted in the HTML rmarkdown output. However,  with `cat` I have tables in the HTML rmarkdown output and no tabs opening, but the tables are not displayed in the Viewer when I am preparing my script in RStudio. That is a pity... Before, with `print` all worked...

**Comment by gosianow** [comment]
I use kableExtra in a show method in my package for my objects. I used to use `print` in my show method and with the old version of kableExtra all was fine. With the current version of  kableExtra I have to use either `print` or `cat`.  However, with `print`, I can display tables in the viewer when calling my function, but I get my output printed to separate tabs when rendering a rmarkdown file. With `cat`, the output is printed into the markdown HTML file when rendering, but I cannot display tables in the viewer. Any chance you will bring back the old functionality? Or could you stop displaying tables in browser  tabs when rendering code with `print`? Many thanks for your feedback.

**Comment by gosianow** [comment]
I have found a way to make the `print` command display tables in the viewer when using RStudio and to insert them into the markdown output without opening browser tabs when rendering. I place `options(kableExtra_view_html = interactive())` at the beginning of my Rmd file.

**Comment by haozhu233** [comment]
Hey, for everyone in this thread, I just want to give an update on this issue. I recently added a similar check to the print function of kableExtra so it will behave just like how it did in version 1.1.0.

**Comment by Matherion** [comment]
Great, thank you!!!

**Comment by blueja5** [comment]
I am also having this problem (with the additional difficulties of being a relative R novice). I am using Notebook in R studio. 

I have tried these options to print my table: 

`CS17WithScience2Plot_y7 %>% dplyr::group_by(School) %>% my_skim() %>% yank ("numeric")`
- works fine but table not well formatted. 


`df %>% dplyr::group_by(School) %>% my_skim() %>% yank ("numeric") %>% kbl() %>% kable_paper() %>% scroll_box(width = "500px", height = "200px")`
looks as intended in the preview, but when I knit to html, the table appears in the browser in its own tab. 


`df %>% dplyr::group_by(School) %>% my_skim() %>% yank ("numeric") %>% kbl() %>% kable_paper() %>% scroll_box(width = "500px", height = "200px") %>% print()`

looks as intended in the preview, but when I knit to html, the table appears in the browser in its own tab. 

`df %>% dplyr::group_by(School) %>% my_skim() %>% yank ("numeric") %>% kbl() %>% kable_paper() %>% scroll_box(width = "500px", height = "200px") %>% cat()`

preview in notebook shows all the html formatting. when I knit to html, the table appears in the browser in its own tab. 

i tried adding options(kableExtra_view_html = interactive())  in the code chunk that opens all my libraries  and now it works fine. Sorry if this is poorly formatted but it I only found this by chance, all other suggestions seem to be for cat and print which didn't work for me. Perhaps there still a quirk to fix here? Or if I have missed something I am keen to know. 

Also my thanks to all those who take their time to make/troubleshoot, I am daily grateful.
