### ISSUE TITLE
Stripe option coloring wrong rows

### ISSUE THREAD

**Issue by Goregg** [haozhu233/kableExtra#516]
When generating a latex table with kable and the kable_styling option striped the wrong rows get colored.
![grafik](https://user-images.githubusercontent.com/39563843/92488428-d36f0400-f1ee-11ea-8c00-904762a9217a.png)

I think the problem is produced by two rows starting with 2 empty cells and then a cell with the same text. 
I tried coloring the row with stripe_index and only the 5th one would produce this bug.
I'm generating multiple reports and some of them have this error, always with 2 rows starting the same.
If i edit one of the rows, e.g. change one of the "C43" to "C43+" the rows are colored correct again.

```{r}
example <- data.frame(name = c("abc", "", "", "defgh", "", "", "", ""),
                        n_z1 = c("1", "", "", "2", "", "", "", ""),
                        icd.x = c("Top ICD-10", "C43", "D03", "Top ICD-10", "C43", "D04", "C44", "D03"),
                        n_z2 = c("1", "", "", "0", "", "", "", ""),
                        icd.y = c("Top ICD-10", "C43", "", "Top ICD-10", "", "", "", ""))
kable(example, format = "latex", booktabs = T, escape = F, linesep = "") %>%
    kable_styling(latex_options = "striped", stripe_color = 'gray_lk')
```

**Comment by Goregg** [comment]
I wrote a workaround if anyone else stumbles across this problem.
It just adds xxx1, xxx2, ... to the first column, generates the latex table and removes the xxx1 from the text. In case the table is needed later again it gets cleaned as well.
```{r}
  example <- data.frame(name = c("abc", "", "", "defgh", "", "", "", "", "", "", "", ""),
                        n_z1 = c("1", "", "", "2", "", "", "", "", "", "", "", ""),
                        icd.x = c("Top ICD-10", "C43", "D03", "Top ICD-10", "C43", "D04", "C43", "D03", "C43", "D04", "C43", "D03"),
                        n_z2 = c("1", "", "", "0", "", "", "", "", "", "", "", ""),
                        icd.y = c("Top ICD-10", "C43", "", "Top ICD-10", "", "", "", "", "", "", "", "")) %>%
    mutate(name = as.character(name))
  
  for(trash in 1:nrow(example)){
    example[trash, 1] = paste0(example[trash, 1], 'xxx', trash)
  }
  
  exTex <- kable(example, format = "latex", booktabs = T, escape = F, linesep = "") %>%
    kable_styling(latex_options = "striped", stripe_color = 'gray_lk')
  
  gsub("xxx[0-9]+", "", exTex)
  
  for(trash in 1:nrow(example)){
    example[trash, 1] = gsub("xxx[0-9]+", "", example[trash, 1])
  }
```

**Comment by haozhu233** [comment]
I think I probably fixed it. @Goregg If you can check the latest github version with the other examples you mentioned, that would be very helpful!

**Comment by Goregg** [comment]
Hey haozhu233, thanks for answering.
Sadly the problem doesn't seems to be fixed. I tried the simple example posted above and the real tables but all of them still have the error. 
I downloaded the latest version from GitHub. RStudio shows Version 1.2.1.9000 in the packages tab. Is that the correct version?

And to clarify:
![grafik](https://user-images.githubusercontent.com/39563843/95176304-fcb68c00-07bc-11eb-939b-80172393d46d.png)

**Comment by rhurlin** [comment]
Hi Goregg,

Patch https://github.com/haozhu233/kableExtra/commit/63c1aa96ed27b9e65aeb0d05dcb144fefacec23a works pretty fine for me.

Are you sure, that this patch is included in your copy of version 1.2.1.9000 of kableExtra? If not sure, could you please refetch and install once again:

```
detach(package:kableExtra)
library(devtools)
install_github("kableExtra")
library(kableExtra)
```

and now rerun the example ...

**Comment by Goregg** [comment]
@rhurlin your install_github command is not working. I used the command on the wiki page again.
devtools::install_github("haozhu233/kableExtra")
Now it worked for me even though this was the same thing i did the first time. Maybe I still had the old package loaded in RStudio.
Thaks for the Fix :)

**Comment by rhurlin** [comment]
> @rhurlin your install_github() command is not working. I used the command on the wiki page again.
> devtools::install_github("haozhu233/kableExtra")

Sorry for the typo. I meant `install_github("haozhu233/kableExtra")`, of course.

> Now it worked for me even though this was the same thing I did the first time. Maybe I still had the old package loaded in RStudio.

There have been several commits in the last days on Github, all under version 1.2.1.9000.

My assumption was, that you grabbed version 1.2.1.9000 a little too early, just before patch https://github.com/haozhu233/kableExtra/commit/63c1aa96ed27b9e65aeb0d05dcb144fefacec23a was committed ;)

> Thanks for the Fix :)

Nice to hear that it works now :)
