### ISSUE TITLE
add "pdf" as an option for latex output

### ISSUE THREAD

**Issue by r2evans** [haozhu233/kableExtra#524]
**Describe the bug**

`png` works fine but tends to be very granular. Using a `spec_line` example,

![image](https://user-images.githubusercontent.com/5815808/92957562-950b5c00-f41d-11ea-8fab-70aff1f43e30.png)

Whereas a similar pdf rendering using `pdf()`:

![image](https://user-images.githubusercontent.com/5815808/92957583-a18fb480-f41d-11ea-8833-a7d3d56c3a40.png)

(`spec_hist` and `spec_boxplot` tend to be fine either way since their lines are always horiz/vert)

This has a slight difference on file size, not a huge surprise. Rendering your `awesome_table_in_pdf.Rmd` with my `spec_line` addition,

- `png()` sparklines: 549790 bytes
- `pdf()` sparklines: 572885 bytes

I'd like to submit this for a PR as well. Would you prefer to keep `png` as the default when `is_latex()`, or do you think changing to `"pdf"` as a default is reasonable?

Another path would be to allow the user to set `dev` themselves: there are [several options](https://rdrr.io/r/grDevices/Devices.html), including the current `png` and `svg`, including: `pdf`, `postscript`, `jpeg`, `bmp`, and `tiff`, perhaps somebody has *reason* to use one of them.

Thoughts?

**Comment by haozhu233** [comment]
Oh, I didn't realize the difference is that big between png and pdf! Have you compared the speed to generate them? That is the only concern I can think about. If using pdf won't dramatically slow everything down, I think it's definitely a better idea to use pdf.

**Comment by r2evans** [comment]
Quick benchmarks.

An extreme, 1M points, where `pdf` does take twice as long:

```r
x <- rnorm(1e6); y <- rnorm(1e6)
system.time({pdf("~/Downloads/pts.pdf"); plot(x,y,pch=16); dev.off();})
#    user  system elapsed 
#   39.72    1.76   42.64 
system.time({svg("~/Downloads/pts.svg"); plot(x,y,pch=16); dev.off();})
#    user  system elapsed 
#   14.43    0.79   18.43 
system.time({png("~/Downloads/pts.png"); plot(x,y,pch=16); dev.off();})
#    user  system elapsed 
#    4.72   21.41   26.52 
file.info(list.files("~/Downloads", pattern = "^pts.", full.names = TRUE))[,"size",drop=FALSE]
#                                      size
# C:\\Users\\r2/Downloads/pts.pdf  57752648
# C:\\Users\\r2/Downloads/pts.png      5948
# C:\\Users\\r2/Downloads/pts.svg 243509695
```

So file size is *significantly* in-favor of `png` here. No real surprise.

A more natural example, 100 points:

```r
x <- rnorm(1e2); y <- rnorm(1e2)
system.time({pdf("~/Downloads/pts.pdf"); plot(x,y,pch=16); dev.off();})
#    user  system elapsed 
#    0.01    0.00    0.02 
system.time({svg("~/Downloads/pts.svg"); plot(x,y,pch=16); dev.off();})
#    user  system elapsed 
#    0.00    0.03    0.05 
system.time({png("~/Downloads/pts.png"); plot(x,y,pch=16); dev.off();})
#    user  system elapsed 
#    0.01    0.02    0.03 
file.info(list.files("~/Downloads", pattern = "^pts.", full.names = TRUE))[,"size",drop=FALSE]
#                                  size
# C:\\Users\\r2/Downloads/pts.pdf 10317
# C:\\Users\\r2/Downloads/pts.png  2991
# C:\\Users\\r2/Downloads/pts.svg 39124
```

File sizes are still in favor of `png` (still, no surprise), but `svg` is certainly not as punishing as the 1M example.
Render time is better shown with a larger sample size (of times rendered):

```r
microbenchmark::microbenchmark(
  pdf={pdf("~/Downloads/pts.pdf"); plot(x,y,pch=16); dev.off();},
  svg={svg("~/Downloads/pts.svg"); plot(x,y,pch=16); dev.off();},
  png={png("~/Downloads/pts.png"); plot(x,y,pch=16); dev.off();}
)
# Unit: milliseconds
#  expr     min       lq     mean   median      uq     max neval
#   pdf  8.4523  9.48845 10.87263 10.33950 11.9174 22.0999   100
#   svg  8.6926 10.13750 11.27196 10.93725 12.1997 15.8777   100
#   png 16.3365 17.59225 19.61571 18.46455 21.0674 32.8655   100
```

To me, it's well worth the general advantage of `pdf` over `png`: the ability to zoom in and not pixelate. However, it's context-sensitive and personal preference, so I don't think mandating one over the other is correct: making it a more-flexible option is appropriate.

I'd think that the user can provide either:

- `character`, one of `"png"`, `"svg"`, `"pdf"`; it might still be good for the default value to be determined by `is_latex()`, over to you if you want to default to `"svg"` or `"pdf"` (I vote for the latter); or, the user can provide
- a `function`, which allows the user to use one of the others, including `bmp`, `cairo_pdf` (if a difference is needed), etc. One disadvantage of this is that `pdf` uses `file=`, whereas *every other graphics capture function* uses `filename=`. Fortunately, for all it is the first argument, so it's not bad to use the user-defined function with the first argument be the temp filename *unnamed* (or it can be verified with `formals`).

Something like (untested code):

```r
spec_line <- function(..., file_type = if (is_latex()) "pdf" else "svg") {
  if (is.character(file_type)) {
    if (!file_type %in% c("pdf", "svg")) {
      width <- width / res
      height <- height / res
    }
    file_type <- match.fun(file_type)
  }
  # ...
  # no need for conditioning on file_type anymore
  file_type(file, width = width, height = height, bg = "transparent")
  graphics::par(...)
  # ... plot/boxplot/hist/points/...  
  grDevices::dev.off()
  if (identical(file_type, grDevices::svg)) {
    svg_xml <- ...
  } else svg_text <- NULL
  # ...
}
```

For all of: pdf, bmp, svg, png, jpeg, tiff ... they all take these arguments: width, height, family, bg, and pointsize, and they all have the first argument as the file to save to (whether named "file" or "filename").

```r
frmls <- lapply(list(pdf=pdf, bmp=bmp, svg=svg, png=png, jpeg=jpeg, tiff=tiff),
                function(f) names(formals(f)))
sapply(frmls, `[[`, 1)
#        pdf        bmp        svg        png       jpeg       tiff 
#     "file" "filename" "filename" "filename" "filename" "filename" 
incommon <- c(Reduce(intersect, frmls), "file", "filename") # because file/filename are always first arg
incommon
# [1] "width"     "height"    "family"    "bg"        "pointsize" "file"      "filename" 
str(lapply(frmls, setdiff, incommon), vec.len = 99)
# List of 6
#  $ pdf : chr [1:13] "onefile" "title" "fonts" "version" "paper" "encoding" "fg" "pagecentre" "colormodel" "useDingbats" "useKerning" "fillOddEven" "compress"
#  $ bmp : chr [1:6] "units" "res" "restoreConsole" "type" "antialias" "symbolfamily"
#  $ svg : chr [1:3] "onefile" "antialias" "symbolfamily"
#  $ png : chr [1:6] "units" "res" "restoreConsole" "type" "antialias" "symbolfamily"
#  $ jpeg: chr [1:7] "units" "quality" "res" "restoreConsole" "type" "antialias" "symbolfamily"
#  $ tiff: chr [1:7] "units" "compression" "res" "restoreConsole" "type" "antialias" "symbolfamily"
```

**Comment by haozhu233** [comment]
@r2evans Haha, for some reason I always got a sense that rendering to pdf is slower than png. Now obviously this is not the case. I think in most realistic cases, file size is not an issue. People can definitely afford that. Also, I totally agree that making it dynamic is a great choice. I think we can use a NULL or "default" to represent the default setting, which means svg for html and pdf for latex. 

At the same time, using your benchmark on `svglite` of the 1M points, I'm getting

```
user  system elapsed 
   7.66    5.50   17.21 
 size
C:/Users/Hao/Documents/Downloads/pts.pdf 159005156
```
So in terms of size, it's about 40% better than base::svg but still quite large. The trade off is that the svglite package depends on BH which is a common yet large dependency on linux. I'm not sure if the cost overcomes the benefits here.

**Comment by r2evans** [comment]
This was changed in 95a0428ff3efe1a655305139407d5eacad4b8779 and #529.
