### ISSUE TITLE
add on stylist format, ranking within a column

### ISSUE THREAD

**Issue by englianhu** [haozhu233/kableExtra#525]
![formattable ranking](https://user-images.githubusercontent.com/7227582/92994373-308af280-f52c-11ea-86c4-e1caee614886.png)
**source** : https://github.com/renkun-ken/formattable

Is it possible to add-on stylist format and ranking argument?

**Comment by haozhu233** [comment]
You can do that before your dataframe gets into kable

**Comment by englianhu** [comment]
```r
md <- read_rds(path = 'data/md.rds')
md2 <- md

## https://www.colorhexa.com/color-names
md2 %<>% 
  formattable(
    list(
        AIC = formatter('span', style = x ~ formattable::style(
            color = ifelse(rank(x) <= 3, 'darkgoldenrod', 'grey')), 
            x ~ paste0(round(x, 2), 
                       ' (rank: ', sprintf('%1.f', rank(x)), ')')))) %>% 
    mutate(df = color_tile('#2a52be', 'white')(df))#colbalt
```
![kableExtra formattable](https://user-images.githubusercontent.com/7227582/93223859-16a71500-f7a3-11ea-99e8-e51d9c7e1163.png)

---

以上正常操作，以下有误，是**代码有误**？请赐教...
```r
md2 %>% 
  kbl('html', caption = '最优模型', escape = F, align = 'c') %>% 
  #kable_paper('hover', full_width = F) %>% 
  kable_styling(
    bootstrap_options = c('striped', 'hover', 'condensed', 'responsive')) %>% 
  kable_material() %>% 
  scroll_box(height = '400px')
```
![kableExtra formattable2](https://user-images.githubusercontent.com/7227582/93225059-62a68980-f7a4-11ea-8141-bfdfacf6314d.png)

**Comment by englianhu** [comment]
```r
md <- read_rds(path = 'data/md.rds')
md2 <- md

## https://www.colorhexa.com/color-names
md2 %<>% 
  mutate(
    df = color_tile('#2a52be', 'white')(df), #colbalt
    AIC = ifelse(
      rank(AIC) <= 3, 
      cell_spec(
        paste0(round(AIC, 2), ' (rank: ', sprintf('%1.f', rank(AIC)), ')'), 
        'html', background = 'black', color = '#fefe22', bold = T), #laser-lemon
      cell_spec(
        paste0(round(AIC, 2), ' (rank: ', sprintf('%1.f', rank(AIC)), ')'), 
        'html', background = 'black', color = 'darkgoldenrod', italic = T)))

md2 %>% 
  kbl('html', caption = '最优模型', escape = F, align = c('c', 'r', 'r')) %>% 
  #kable_paper('hover', full_width = F) %>% 
  kable_styling(
    bootstrap_options = c('striped', 'hover', 'condensed', 'responsive')) %>% 
  kable_material() %>% 
  scroll_box(height = '400px')
```

---

![download](https://user-images.githubusercontent.com/7227582/93252075-98109e80-f7c7-11ea-9af2-d56a92e548e2.png)
自己解决了... 如果可以混合使用`color_tile`让整个矢量深浅色变化，然后再添加个`ranking`会更好...

**Comment by haozhu233** [comment]
color_tile 是formattable的功能，不追求这种圆角tile的话现在你用column_spec更简单些，用法文档里有

加个ranking可以自己加 一行就能解决，我觉得没必要放进这个包
mtcars %>% mutate(mpg_rank = paste0(mpg, " (rank: ", order(mpg), ")"))

**Comment by englianhu** [comment]
```r
mtcars %>% 
    mutate(mpg = paste0(mpg, ' (rank: ', order(mpg), ')')) %>% 
    kbl('html') %>% 
    column_spec(1:2, width = "20em", bold = TRUE, italic = TRUE, 
                background = '#2a52be', color = 'white')
```
![c4dd1858-42c9-4975-5760-1ec5475efc5d](https://user-images.githubusercontent.com/7227582/93373042-5a734a80-f887-11ea-9ade-196d59bd7412.png)
source : https://tinyurl.com/yyewreks

---

试了一下，有两个缺点：

1) 一来没有根据数字多寡变色（背景颜色）
2) 而来没有设定头三等级的颜色（数字颜色）
