### ISSUE TITLE
'pack_rows' fails with top row when using latex option 'striped'

### ISSUE THREAD

**Issue by ph492** [haozhu233/kableExtra#528]
Hi, 

Thank you very much for this wonderful package. I think this is a minor bug and possibly related to #331 and #366. The grouping works except when the group title is the first row. 

Thanks

[pack_rows.pdf](https://github.com/haozhu233/kableExtra/files/5218894/pack_rows.pdf)

```
---
title: 'pack_rows with latex_options = "striped" error'
output: pdf_document
---

```{r}
library(knitr)
library(kableExtra)

kbl(mtcars[1:10, 1:6], caption = "Group Rows", booktabs = T) %>% 
  kable_styling(latex_options = "striped") %>%
  pack_rows("Group 1", 1, 5)

```

```

**Comment by haozhu233** [comment]
@ph492 Fixed now in github version
