### ISSUE TITLE
add tabularx environment instead of kable_styling(full_width = T) ?

### ISSUE THREAD

**Issue by randomgambit** [haozhu233/kableExtra#53]
Hello @haozhu233 !

I tried to use the nice `kable_styling(full_width = T)` option to stretch my latex table but the result is unfortunately quite disappointing in terms prettyness.

 Would it be possible to add some option where the table is actually written in a `tabularx` environment? That will naturally handle the stretching beautifully.

What do you think?
Thanks!

**Comment by haozhu233** [comment]
Yeah, I guess the current `full_width` isn't in its best shape. I can work on a `tabularx` solution later

**Comment by randomgambit** [comment]
@haozhu233 that would be so great! this is an important option

**Comment by haozhu233** [comment]
@randomgambit I improved the way how `full_width` works. It should be able to give you a desired result in most cases. I'm using the `tabu` environment for a more stable interface for both regular tables and long tables. 

Also, I add an option `latex_tex_env` so you can specify environments like `tabularx` if you like.

**Comment by randomgambit** [comment]
@haozhu233 nice ! amazing work! btw I thought tabu was a dead project. Is it still OK to use it?

**Comment by haozhu233** [comment]
@randomgambit I'm not sure. I tested it and it seems to work. Do you or anyone who's good with LaTeX have a better suggestion?

**Comment by haozhu233** [comment]
After you install the latest dev, you can try
```
kable(rbind(mtcars[1:5], mtcars[1:5]), "latex", booktabs = T, 
      # longtable = T, 
      align = c("c", "r", "c", "l", "r")) %>%
  kable_styling(full_width = T) %>%
  column_spec(1, width = "10em")
```

**Comment by randomgambit** [comment]
huummm if it works, why bother? 😉 let me do a few tests thanks!!

**Comment by haozhu233** [comment]
lol that's what I'm thinking 😝

Let me know if you encounter any bugs.

**Comment by Eyayaw** [comment]
How can I get \begin{tabularx}{\textwidth}{lXXX} added to the table environment, or how to pass automatic text width to width in column_spec()? column_spec(-1, width = "10cm") does not produce the the right output as I desire---works with `tabu` env.

**Comment by marcofaga** [comment]
There's a problem with tabu: we can't use \cellcolor and tabu together.. It's a problem when we want a full-width striped table.  :-(

**Comment by TC-RAC** [comment]
Hi - tabu appears to be completely broken now - can anyone recommend an alternative to the use of kable_styling please?
https://github.com/tabu-issues-for-future-maintainer/tabu

**Comment by thmschk** [comment]
One more question: When I add `latex_table_env = "tabularx",...`  the LaTeX code produces e.g.

```
\begin{tabularx}{>{\raggedright\arraybackslash}p{4cm}rrrrr}
...
```

so, the 2nd argument {1\textwidth} is missing. Do you have any hint how to overcome this?

**Comment by dmurdoch** [comment]
@thmschk :  You can (ab)use the `valign` argument:

```
kbl(mtcars, format="latex", tabular = "tabularx", valign="{\\textwidth}")
```
