### ISSUE TITLE
kableExtra: Line at the bottom of the table does not span full table width

### ISSUE THREAD

**Issue by TerriGibson** [haozhu233/kableExtra#530]
HI,

I am making a table with kableExtra, for some reason the bottom border doesn't span the full width of the table. Perhaps because I collapsed some of my rows. Is there a way to change that? 

AP.BD.table<- AP.BD.SE %>% kbl("latex", caption = "Table 1. Mean aeration porosity and bulk density for productive 
      and unproductive ACR and GLSA fields. The standard error of the mean is shown in brackets.", 
                               col.names = c('Field Quality', 'Depth', 'Time', 'Field Type',
                                             'n', '(%)   ',
                                             'n', '(Mg m$^{-3}$)'),align=rep('r', 4)) %>%
 kable_classic(full_width = F, html_font = "Times New Roman")%>%
  collapse_rows(columns = 1:4, valign = "top")%>%
  add_header_above(c(" " = 4, "Aeration Porosity" = 2, "Bulk Density" = 2))

Here you can see the bottom of the table: 

![Screen Shot 2020-09-15 at 12 24 25 AM](https://user-images.githubusercontent.com/69482957/93179201-329ab000-f6ea-11ea-87b2-1d24f3d38d2d.png)

**Comment by haozhu233** [comment]
@TerriGibson Thanks for reporting! Fixed now.
