### ISSUE TITLE
Issues with column_spec when using latex option 'striped'

### ISSUE THREAD

**Issue by ycl6** [haozhu233/kableExtra#533]
**Describe the bug**
When using `latex_options = "striped"`, the `column_spec` style settings such as `bold`, `color`, etc were applied in a *striped fashion*, and not to the whole column. See [example FDR](https://github.com/haozhu233/kableExtra/files/5251755/striped_column_spec.pdf)

```R
---
title: 'incompatibility between striped and column_spec'
output: rmarkdown::pdf_document
---

library(knitr)
library(kableExtra)

kbl(mtcars[1:10, 1:6], caption = "with striped", booktabs = T) %>%
  kable_styling(latex_options = c("striped", "hold_position")) %>%
  column_spec(1, bold = TRUE, color = "red")

kbl(mtcars[1:10, 1:6], caption = "without striped", booktabs = T) %>%
  kable_styling(latex_options = c("hold_position")) %>%
  column_spec(1, bold = TRUE, color = "red")
```

**Comment by haozhu233** [comment]
Fixed now

**Comment by rhurlin** [comment]
The fix in https://github.com/haozhu233/kableExtra/commit/bdcffde135d1c6df32e8d8b47bfab6a7ad30cf4c works fine for me.

Many many thanks!

**Comment by ycl6** [comment]
Thanks @haozhu233 
I installed from the latest GitHub repo `haozhu233/kableExtra@HEAD` and it works fine.
