### ISSUE TITLE
Print from HTML (Webpage) to PDF loses coloring?

### ISSUE THREAD

**Issue by PieprzonaWagina** [haozhu233/kableExtra#535]
Hey haozhu233,
I saw you had this issue 3 years ago, but that the thread was closed.
I'm faced with the same issue today, did you ever manage to solve it?

**Comment by vincentarelbundock** [comment]
Could you link to the original issue and provide y a [Minimal Reproducible Example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)

**Comment by haozhu233** [comment]
This is not something I can fix. This is a problem with twitter bootstrap theme and it affects not only tables but also everything on the rmarkdown page. See https://stackoverflow.com/questions/33410724/bootstrap-print-css-removes-background-color

You might want to explicitly define your color as "#000000 !important" but this practice has its own issues.
