### ISSUE TITLE
kableExtra now opening tables in separate tab in browser? 

### ISSUE THREAD

**Issue by CarolineXGao** [haozhu233/kableExtra#536]
I think the old bug ( https://github.com/haozhu233/kableExtra/issues/131) seems to show up again in the new version.  V1.1.0 seems to be fine. 
Many thanks!!!! 
Best, 
Caroline

**Comment by vincentarelbundock** [comment]
Could you supply a replicable example?

Alternatively, could you take a look at the Rmd file I posted in this Issue and tell me if it suits your needs?

https://github.com/haozhu233/kableExtra/issues/537

**Comment by haozhu233** [comment]
Hi, @CarolineXGao I think we fixed this in fd44608.
