### ISSUE TITLE
Printed tables with functions from `kableExtra` are printed into the web browser

### ISSUE THREAD

**Issue by guilhermeparreira** [haozhu233/kableExtra#537]
I just updated all of my packages. When I load `kableExtra` package and print a table via `kbl` or `kable() %>% kable_styling()` the table is printed straight way to the web browser, instead in a document. (I did the reproducible code inside of a function, because I need to print some `data.frame` inside functions). It follows the example:

````
---
title: "Out"
output:
  html_document
---

# It prints the table into the report (with formatting)
```{r, results='asis'}
library(knitr)
A <- function(){
  print(kable(iris))
}
A()
```

# It prints the table into the report
```{r, results='asis'}
library(kableExtra)
A <- function(){
  print(kable(iris))
}
A()
```

# It doesn't print the table into the report documment (but it prints straight way into my internet browser with the following name: file:///tmp/RtmpYC0EEW/viewhtml17ee315afa3d2/index.html)
```{r, results='asis'}
A <- function(){
  print(kbl(iris))
}
A()
```

# It doesn't print the table in the report documment (but it prints straight way into my internet browser with the following name: file:///tmp/RtmpYC0EEW/viewhtml17ee362c4da6a/index.html)
```{r, results='asis'}
A <- function(){
  print(kable(iris) %>% 
          kable_styling())
}
A()
```
````

I would be glad if you could have a look! Thanks.

Session Info:
```
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=pt_BR.UTF-8      
 [2] LC_NUMERIC=C              
 [3] LC_TIME=pt_BR.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=pt_BR.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=pt_BR.UTF-8      
 [8] LC_NAME=C                 
 [9] LC_ADDRESS=C              
[10] LC_TELEPHONE=C            
[11] LC_MEASUREMENT=pt_BR.UTF-8
[12] LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils    
[5] datasets  methods   base     

other attached packages:
[1] knitr_1.30       kableExtra_1.2.1
```

**Comment by vincentarelbundock** [comment]
Did you try:

1. Loading `kableExtra`
2. Removing the `print` calls
3. Using `kbl` instead of `kable`.

This document compiles to html on my computer with correct tables:

````
---
title: "Out"
output:
  html_document
---

# It prints the table into the report (with formatting)
```{r, results='asis'}
library(kableExtra)
library(knitr)
A <- function(){
  kbl(iris)
}
A()
```

# It prints the table into the report
```{r, results='asis'}
library(kableExtra)
A <- function(){
  kbl(iris)
}
A()
```

# It doesn't print the table into the report documment (but it prints straight way into my internet browser with the following name: file:///tmp/RtmpYC0EEW/viewhtml17ee315afa3d2/index.html)
```{r, results='asis'}
A <- function(){
  kbl(iris)
}
A()
```

# It doesn't print the table in the report documment (but it prints straight way into my internet browser with the following name: file:///tmp/RtmpYC0EEW/viewhtml17ee362c4da6a/index.html)
```{r, results='asis'}
A <- function(){
  kbl(iris) %>% 
          kable_styling()
}
A()
```
````

**Comment by guilhermeparreira** [comment]
It works now! Thanks.

But it doesn't work if I have a plot() call inside function:

---
title: "Out"
output:
  html_document
---

# It prints the table into the report (with formatting)
```{r, results='asis'}
library(kableExtra)
library(knitr)
A <- function(){
  kbl(head(iris, 5))
  plot(1:10,1:10)
}
A()
```

# It doesn't print the table in the report documment (but it prints straight way into my internet browser with the following name: file:///tmp/RtmpYC0EEW/viewhtml17ee362c4da6a/index.html)
```{r, results='asis'}
A <- function(){
  kbl(head(iris, 5)) %>% 
          kable_styling()
  plot(1:10,1:10)
}
A()
```

**Comment by vincentarelbundock** [comment]
Can you use separate functions for plots and tables?

**Comment by guilhermeparreira** [comment]
It would result in a more verbose code. But yes, I can. This is my real function: 
![image](https://user-images.githubusercontent.com/13880005/94990316-83ffc780-0551-11eb-8f97-0b75b57a9580.png)
I have two other functions with same structure.

Or, I could use a previous version of the package? (It seems that it was working with the previous version).

**Comment by vincentarelbundock** [comment]
> Or, I could use a previous version of the package? (It seems that it was working with the previous version).

Sure, but then you'll forever be stuck with the old version and you'll have to be careful never to update the package.

**Comment by guilhermeparreira** [comment]
Ok. But do you guys intend to fix this in a update?

**Comment by vincentarelbundock** [comment]
Sorry for the confusion. I'm not actually a developer here. Just trying to help. So I can't answer about future plans.

**Comment by guilhermeparreira** [comment]
Ok. Thanks

**Comment by haozhu233** [comment]
@guilhermeparreira can you install from github and let me know if this issue has been fixed? Thanks!

**Comment by guilhermeparreira** [comment]
Hi Hao. Just did. And this issue has not been fixed.

thank you!

**Comment by haozhu233** [comment]
@guilhermeparreira I mean I changed something 20 minutes ago. It seems to be fixed on my end... If you are using the latest version, please tell me more about how you are rendering this document. Are you using rstudio, base R gui or use R in a terminal?

**Comment by guilhermeparreira** [comment]
I just installed the last version via github but I still get the error. I am using Rstudio Ctrl+Alt+K shortcut to compile the report:
![image](https://user-images.githubusercontent.com/13880005/94993003-422c4c80-0564-11eb-9828-553819d250e2.png)

**Comment by haozhu233** [comment]
@guilhermeparreira I guess in this case, you need to add your cat() back. 

```
A <- function(){
  kbl(head(iris, 5)) %>% 
          kable_styling() %>%
    cat()
  plot(1:10,1:10)}
A()
```

will just do the trick. 

Just as any other R function calls, if you don't explicitly print out the results, R will only return the last object.

**Comment by guilhermeparreira** [comment]
Tks @haozhu233. It worked!
