### ISSUE TITLE
Spurious \vphantom

### ISSUE THREAD

**Issue by mk9y** [haozhu233/kableExtra#538]
```
library(kableExtra)
moodOverlay <- tibble(
P = c(6, 5, 4, 7, 7, 5, 5, 7, 7, 7), 
N = c(5, 4, 4, 3, 4, 3, 4, 4, 4, 5), 
U = c(3, 3, 4, 4, 4, 3, 1, 2, 2, 4)
)
kable(
  moodOverlay,
  booktabs = TRUE,
  linesep = "",
  format = "latex"
  ) %>%
  column_spec(1:3, latex_column_spec = "S[table-format] = 2.2]")
```
Output
```
\begin{tabular}{S[table-format] = 2.2]S[table-format] = 2.2]S[table-format] = 2.2]}
\toprule
P & N & U\\
\midrule
6 & 5 & 3\\
5 & 4 & 3\\
4 & 4 & 4\\
7 & 3 & 4\\
7 & 4 & 4\\
5 & 3 & 3\\
5 & 4 & 1\\
7 & 4 & \vphantom{1}2\\
7 & 4 & 2\\
7 & 5 & 4\\
\bottomrule
\end{tabular}
```

**Comment by haozhu233** [comment]
Hi, @mk9y \vphantom{*} was added to differentiate duplicated rows. It's quite hacky but works well. I think here you can do something like 

```
kable(
  moodOverlay,
  booktabs = TRUE,
  linesep = "",
  format = "latex"
) %>%
  column_spec(1:3, latex_column_spec = "S[table-format] = 2.2]") %>%
  gsub("\\\\vphantom\\{[^\\}]*}", "", .)
```

**Comment by mk9y** [comment]
Thank you. 

I also learned that one must enclose the cellcolor command in braces to hide it from siunitx and make sure the signed number is not between braces. My grep is rusty. Could you suggest a second edit?

MK

**Comment by haozhu233** [comment]
Can you provide some additional details on that? 

Part of it is understandable, given that siunix is very different from the rest of the latex table world. I know some of the features provided by this package won't work with siunix and that's the reason why it's not an official feature.

**Comment by mk9y** [comment]
Cell(1, 1) is aligned only when you restore braces.
