### ISSUE TITLE
Removing the rstudio check in `print.kableExtra`

### ISSUE THREAD

**Issue by vincentarelbundock** [haozhu233/kableExtra#539]
Opening an issue to discuss commit https://github.com/haozhu233/kableExtra/commit/fd44608629c9fbd218acf7d79e81086720dbc4e3

I realize there were several issues opened by people who didn't like that `kableExtra` was opening html pages in new tabs. However, we also need to think about the use-cases that break because of the new change.

In particular, with the new check, `kableExtra` only works nicely in RStudio. For any user with the traditional R interface, or using R from the terminal, `kableExtra` will only print a jumble of HTML.

From my (own self-serving) perspective, this is extremely problematic. I personally use R in a vim/terminal setup, and I print a lot of regression tables on a day to day basis using my `modelsummary` package. The new condition means that I can no longer use `kableExtra` for this purpose, without major hacks (catching the output and post-processing tables through `htmltools` or some such).

Would you please consider removing the `rstudioapi::isAvailable()` from the condition on this line?

https://github.com/haozhu233/kableExtra/blob/master/R/print.R#L4

Note that the many issues opened about opening new tabs mostly related to Rmarkdown documents, so the `interactive()` check should be sufficient to limit those problems.

**Comment by haozhu233** [comment]
That makes sense! It also reminded me why I made that change last year. Haha

**Comment by vincentarelbundock** [comment]
Thanks!
