### ISSUE TITLE
Print from HTML (Webpage) to PDF loses coloring?

### ISSUE THREAD

**Issue by soleyjh** [haozhu233/kableExtra#54]
This may not be your issue but I figured I'd ask. When I try to print from an HTML webpage to a PDF I am unable to maintain the coloring of text (all black) or background coloring within the table itself. 

for example: in the webpage the following code turns the first row of the table yellow.

row_spec(1, background = "yellow")

However, when I go to PDF the page in Chrome, FF, & IE they all do not maintain the background coloring. Any ideas? (I've been Googling all day).

Thanks!

**Comment by haozhu233** [comment]
It *is* not my issue, haha :P

If you are curious why, here is a good read: https://stackoverflow.com/questions/33410724/bootstrap-print-css-removes-background-color

I'm not exactly sure about your case but I would suggest maybe you can try to use Safari and check "print background" on the printing page. I'm a loyal chrome user but I found myself best luck there. 

Also, if you really really want your color on your prints, pdf_document is always there, even though it's probably not that preferable to you (& to me) than html. It does have its shiny points on paging and keeping everything as it is. 

The good news is that I tried to keep the user experience on using this package similar for html/latex. So at least you won't need to change too much of your codes before you get a good copy of pdf rendered by R.

**Comment by soleyjh** [comment]
I really appreciate your help. I will likely attempt to alter the css directly in Chrome.
