### ISSUE TITLE
pack_rows() call after kable_styling creates problem with striped

### ISSUE THREAD

**Issue by spotlight19** [haozhu233/kableExtra#543]
A small bug in latex output of table. Earlier the sequence of using `kable_styling` and `pack_rows` didn't matter. However, if we use 'striped' in `latex_options`, it creates a problem.  See attachment for details.

This seems to have come in some update of the package as I stumbled upon it while running an old working code on a new pc.
[kable_bug.pdf](https://github.com/haozhu233/kableExtra/files/5344985/kable_bug.pdf)

**Comment by rhurlin** [comment]
This bug should be solved already in a not yet released version of kableExtra with https://github.com/haozhu233/kableExtra/commit/bdcffde135d1c6df32e8d8b47bfab6a7ad30cf4c. To use the fix before the next official release comes out, you can run:

```
devtools::install_github("haozhu233/kableExtra")
```

This should install version 1.2.1.9000 of kableExtra, which contains the fix.

Before or after the update of the package you should detach and reload the package, for example like this:

```
detach(package:kableExtra)
library(kableExtra)
```

HTH,
Rainer

**Comment by spotlight19** [comment]
Thanks. Reinstalled as recommended and now works.
