### ISSUE TITLE
Using Print() in on a kable_styling object in an rmarkdown file generates an extraneous NULL that breaks knitting to html output.

### ISSUE THREAD

**Issue by kjewell** [haozhu233/kableExtra#544]
**Describe the bug**
Using Print() in on a kable_styling object in an rmarkdown file generates an extraneous NULL that breaks knitting to html output.
Using Print() on a kable is required to use kable within a loop.  
This behavior was not present prior to last month.  (Can't be certain if kableextra changed to generate the NULL, or something else changed in the Rmarkdown ecosystem to make this a breaking behavior.)

**To Reproduce**

````
---
title: "A reproducible example in rmarkdown"
output: html_document
---

```{r}
library(kableExtra)
```
```{r error}
# code to reproduce the bug.
dt <- mtcars[1:5, 1:6]

print(
  kable_styling(
    kable(dt, tab.cap = NULL, caption = "TABLE Test 1", align=c(rep('r', 10)))
  )
)
```
````

**Comment by haozhu233** [comment]
@kjewell Check out the latest github version. We should have fixed it.

**Comment by kjewell** [comment]
Yep, dev version is fixed.  thanks.
