### ISSUE TITLE
How to add double lines to the top and bottom of a table with KableExtra?

### ISSUE THREAD

**Issue by jimingshuo** [haozhu233/kableExtra#546]
**Describe the bug**
I have been trying to add double lines to the top and bottom of a table for PDF output. I find the package of "Stargazer" can do this, however what it exports is a LaTex format document, and I have to copy and paste it into my Rmarkdown file, but cannot generate the table within R code chunk.

May I know if you can help me with this? Attached please find a sample picture which I copied from https://www.datadreaming.org/post/apa-tables-using-rmarkdown-part-5/

![How-to-add-double lines](https://user-images.githubusercontent.com/33013981/95660505-fc383100-0aed-11eb-8ee6-52fd149fd5d9.png)

**Comment by haozhu233** [comment]
I mean the most direct solution is to

**Comment by jimingshuo** [comment]
Great, thank you very much, it works!
