### ISSUE TITLE
table content contains `&` related to latex convert to `&amp;`

### ISSUE THREAD

**Issue by Hochia** [haozhu233/kableExtra#548]
**Describe the bug**
`&` in latex convert to `&amp;` when adding more features through functions such as `column_spec()`.
**To Reproduce**

*Case 1* is absolutely fine.
*Case 2* is not seems to be a problem as we reproduce it directly in R, since the **Viewer** panel shows nothing wrong. However, if we reproduce it in R markdown, then we are able to find that `&` convert to `&amp;` thus the file shows the redundant `amp;`.
*Case 3* is a way to solve, but there may be a more general way to avoid this problem.
```
df = data.frame(
  A = c("$x\\lt y$", 
  "
  $$
  \\begin{aligned}
  x&=1\\\\
  y&=2
  \\end{aligned} 
  $$
  ")
)

# Case 1
kbl(df, escape = FALSE)

# Case 2
kbl(df, escape = FALSE) %>% 
  column_spec(1, color = "red")

# Case 3
kbl(df, escape = FALSE) %>% 
  column_spec(1, color = "black") %>% 
  gsub(x = ., "&amp;", "&")
```

Here is the rmarkdown doc.

````
---
title: "A reproducible example in rmarkdown"
output: html_document
---

```{r}
library(kableExtra)

df = data.frame(
  A = c("$x\\lt y$", 
  "
  $$
  \\begin{aligned}
  x&=1\\\\
  y&=2
  \\end{aligned} 
  $$
  ")
)

# Case 1
kbl(df, escape = FALSE)

# Case 2
kbl(df, escape = FALSE) %>% 
  column_spec(1, color = "red")

# Case 3
kbl(df, escape = FALSE) %>% 
  column_spec(1, color = "black") %>% 
  gsub(x = ., "&amp;", "&")
```

````

**Comment by haozhu233** [comment]
It works on my computer though. Is it a windows only problem?

**Comment by Hochia** [comment]
I don't get it. You mean that even if `&` related to latex convert to `&amp;`, the knit .html doc will show the math equation correctly. Or, it doesn't convert to `&amp;` on your computer?

```{r}
kbl(df, escape = FALSE) %>% 
  kableExtra::column_spec(1, color = "red") %>% 
  as.character()

## [1] "<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> A </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;color: red !important;\"> $x\\lt y$ </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;color: red !important;\"> $$\n  \\begin{aligned}\n  x&amp;=1\\\\\n  y&amp;=2\n  \\end{aligned} \n  $$ </td>\n  </tr>\n</tbody>\n</table>"
```

**Comment by haozhu233** [comment]
Hey @Hochia I just took a closer look into this issue and I see what happens here. This package uses `xml2` to process html tables while XML doesn't permit single use of `&`. https://www.w3.org/TR/REC-xml/#syntax As a result, `xml2`, which uses `xmllib2` escapes `&` to `&amp;` by default and there is no way to turn it off.....

I don't have a good solution here either. My best recommendation is to use the regex solution you posted by yourself.

**Comment by Hochia** [comment]
Thanks for the information!
