### ISSUE TITLE
Piped data frame not available to column_spec 

### ISSUE THREAD

**Issue by joseepoirier** [haozhu233/kableExtra#550]
While trying to define a condition statement to do conditional formatting, a piped dataframe doesn't appear to be available to `column_spec`:

```
mtcars[1:8, 1:8] %>%
      arrange(wt) %>%
      kbl(booktabs = T, linesep = "") %>% 
      kable_paper(full_width = F) %>%
      column_spec(6, color = "white", background = ifelse(mtcars[1:8,1:8]$drat > 3, "red", "green"))
```
silently fails and returns a formatting reflecting the original order of the dataframe, not the arranged one:
![image](https://user-images.githubusercontent.com/4512594/95884596-4ddcf780-0d4a-11eb-981d-b61fe63d463e.png)

Using the dot notation instead of referring to the dataframe by name also fails:
```
mtcars[1:8, 1:8] %>%
     arrange(wt) %>%
     kbl(booktabs = T, linesep = "") %>% 
     kable_paper(full_width = F) %>%
     column_spec(6, color = "white", background = ifelse(.$drat > 3, "red", "green"))
```
and returns the error: `Error in .$drat : $ operator is invalid for atomic vectors`. Referring to the column name without the dot and $ selector returns `Error in ifelse(drat > 3, "red", "green") : object 'drat' not found.`

**Comment by haozhu233** [comment]
I think I answered this on rstudio community. ;)
