### ISSUE TITLE
printing broken in Rmd files

### ISSUE THREAD

**Issue by jdnewmil** [haozhu233/kableExtra#553]
**Describe the bug**
Printing a table inline in an Rmd file either creates a separate webpage and opens it in the default browser, or fails to do anything. 

**To Reproduce**
````
---
title: "Test KableExtra"
output:
  html_document:
    df_print: paged
---

```{r}
library(knitr)
library(kableExtra)
# should work, but doesn't
myprint <- print
# workaround
#myprint <- knitr:::print.knitr_kable
```

```{r}
lmtcars <- split( mtcars, mtcars$cyl )
```

```{r mtcars, results='asis'}
for ( i in seq_along( lmtcars ) ) {
  tbl <- kable( lmtcars[ i ]
              , format = "html"
              )
  myprint( kable_styling( tbl # does not show inline
                        , "striped"
                        , full_width = FALSE
                        )
         )
  # myprint( tbl ) # works regardless of definition of myprint
  cat( "\n" )
}
```
````

Note the commented out workaround in the first chunk... s3 dispatch from a `kableExtra` table into `knitr::print.knit_kable` appears to be broken.

I can see that the `class(tbl)` is a single string, but the output from `kable_styling` has two classes. In R v4.0.0 NEWS file they mention skipping s3 dispatch in between the global and base environments by default... perhaps an s3method() call is needed to enable dispatch properly? (I had this exact same problem in R3.6.3 at work, though, so I am really not sure what the problem is.)

```
## R version 4.0.2 (2020-06-22)
## Platform: x86_64-pc-linux-gnu (64-bit)
## Running under: Ubuntu 20.04.1 LTS
## 
## Locale:
##   LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
##   LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
##   LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
##   LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   
## 
## Package version:
##   askpass_1.1        base64enc_0.1.3    callr_3.5.1        colorspace_1.4-1  
##   compiler_4.0.2     curl_4.3           digest_0.6.26      evaluate_0.14     
##   farver_2.0.3       glue_1.4.2         graphics_4.0.2     grDevices_4.0.2   
##   highr_0.8          htmltools_0.5.0    httr_1.4.2         jsonlite_1.7.1    
##   kableExtra_1.2.1   knitr_1.30         labeling_0.3       lifecycle_0.2.0   
##   magrittr_1.5       markdown_1.1       methods_4.0.2      mime_0.9          
##   munsell_0.5.0      openssl_1.4.3      processx_3.4.4     ps_1.4.0          
##   R6_2.4.1           RColorBrewer_1.1.2 rlang_0.4.8        rmarkdown_2.4     
##   rstudioapi_0.11    rvest_0.3.6        scales_1.1.1       selectr_0.4.2     
##   stats_4.0.2        stringi_1.5.3      stringr_1.4.0      sys_3.4           
##   tinytex_0.26       tools_4.0.2        utils_4.0.2        viridisLite_0.3.0 
##   webshot_0.5.2      xfun_0.18          xml2_1.3.2         yaml_2.2.1
```

**Comment by haozhu233** [comment]
Hi @jdnewmil, this issue is no related to dispatch, haha. Thanks for all your thoughtful consideration though! 😉

In short, I removed some interactive checks in the last update to improve printing in console support but it causes this unexpected behavior when you use kable in a for loop. (if you don't use for loop, the print will be handled by knit_print, which is the print dispatch system in knitr and works totally fine). We have already taken care of this issue in the latest github version. The new version will be on cran soon.
