### ISSUE TITLE
Resizebox option

### ISSUE THREAD

**Issue by marcofaga** [haozhu233/kableExtra#554]
Hi, is there any built-in option to use \resizebox in latex tables?

Like this:

`
\begin{table}[!h]
\resizebox{\textheight}{!} {
\begin{tabular}
....`
Many thanks!

**Comment by haozhu233** [comment]
Yeah, I was using resize box to implement the "scale_down" feature. What is your use case?

https://github.com/haozhu233/kableExtra/blob/bdcffde135d1c6df32e8d8b47bfab6a7ad30cf4c/R/kable_styling.R#L436

**Comment by marcofaga** [comment]
Yeah, that's the purpose!
