### ISSUE TITLE
Problems combining long table and booktabs with spaces in table

### ISSUE THREAD

**Issue by EmptyKonigs** [haozhu233/kableExtra#555]
#Hello,
I'm trying to put a complex regression model in a nice looking table. For this purpose I have a data frame with some "empty" spaces. Because I want to use the table directly in a Rmarkdown PDF document, I would like to combine longtable = T and booktabs = T. Unfortunately it only produces the following error:

! Undefined control sequence.
<argument> ...al \expandafter \let \cmrsideswitch 
                                                  \@tempa \fi \fi 
l.143 (Intercept)
                  & -5.9 & -21, 8.7 & 0.4\\ 

I already found, that the Problem seems to be the empty spaces in the data frame. I added the dataframe as zip and put the code below.
Is there any possibility to fix this? I'm new to writing things in Rmarkdown and would really appreciate your help.

Kind regards,
Lea

```{r}
library(kableExtra)
kbl(data, booktabs = T, longtable = T)
```
````

**Comment by rhurlin** [comment]
The added dataframe zip file seems to be lost ...

You did not tell us what version of kableExtra you use. If it is version 1.2.1, would you please try to update to the just released version 1.3.0 and report back?

**Comment by EmptyKonigs** [comment]
Sorry! One more try with the Zip:

[reg1.csv.zip](https://github.com/haozhu233/kableExtra/files/5423697/reg1.csv.zip)

I updated to version 1.3.0, but the error still emerges

**Comment by rhurlin** [comment]
I read in the data with `data <- read.csv("./reg1.csv")`. 

```
> str(data)
'data.frame':	93 obs. of  5 variables:
 $ X                  : int  1 2 3 4 5 6 7 8 9 10 ...
 $ X..Characteristic..: chr  "(Intercept)" "sex.f" "male" "female" ...
 $ X..log.OR...       : num  -5.9 NA NA 0.78 -12 NA NA 0.13 0.14 0.45 ...
 $ X..95..CI..        : chr  "-21, 8.7" "" "" "0.26, 1.3" ...
 $ X..p.value..       : chr  "0.4" "" "" "0.004" ...
```

After this, `library(kableExtra); kbl(data, booktabs = T, longtable = T)` produces a html page without an error.

Is your data read in this way? You have an error at line 143, but the csv data only has 93 rows!? And the data, shown in the error message, seems to be from line 1?

**Comment by EmptyKonigs** [comment]
Thank you for your fast response! 
After importing the data the way you did, there is this first column "X" which should be there (probably my fault with exporting the data) and there are some NAs left in the third column. I remove this column and NAs with the following:

`
library(kableExtra)
library(dplyr)

data <- read.csv("./reg1.csv")  %>% select (-X)

data[is.na(data)] <- ""

`

After this I try to knit the table to pdf but there is still the same error. It doesn't appear, when I knit to html.

**Comment by rhurlin** [comment]
OK, after some fiddling around I think I can reproduce your error. The error is with the produced .tex file, which the pdf compiler tries to interpret. It looks like the character string '`(Intercept)`' in first place of the csv file is misinterpreted in pdflatex. If you change this string into something like '`Intercept`' (w/o braces), it works!

Could you please confirm? Thanks :)

**Comment by EmptyKonigs** [comment]
Yeah great! Now it works! 
Thank you very much 👍
