### ISSUE TITLE
R notebook kableExtra output gets transparent

### ISSUE THREAD

**Issue by Brunogeertsen** [haozhu233/kableExtra#556]
**Describe the bug**
When I run the following code to make a simple kableExtra table the output in the R notebook gets almost transparent. For a split-second it looks fine, but then it's like the entire table get's an alpha-value of 0.5. When I knitr the code and opens the html.file it looks fine again.   

I have not had this issue with other kableExtra tables, but when I go back to some of my older markdowns an run the code, I encounter the same problem. 

My R. version is 4.0.3, but I've tested it with 4.0.2 and 3.6.0 with the same results.   

I'm not entirely sure if this is a kableExtra bug or maybe an internal bug in some other software.

**To Reproduce**
Think about using `reprex` to generate an example in R. 

```
```{r}
studentdata_tbl %>% 
    kable() %>% 
    kable_styling(full_width = TRUE) 
```
```

If you need to attach the entire rmarkdown doc, try to use ```` to quote your entire doc.

````
---
title: "A reproducible example in rmarkdown"
output: html_document
---

```{r}
library(kableExtra)
```
````

**Comment by nischalshrestha** [comment]
I also came across the same issue and don't know exactly what's going on. But, try the `kable::kable_paper`, it seems to come out much better with no alpha messed up.

**Comment by vincentarelbundock** [comment]
This should be fixed in the `master` development branch on Github. Please comment if you still run into the issue after installing from Github and restarting R.
