### ISSUE TITLE
kableExtra error in Markdown when rendering to PDF?

### ISSUE THREAD

**Issue by fgoerlich** [haozhu233/kableExtra#559]
**Describe the bug**
This comand
`knitr::kable(data, caption = '**_Matriz de Confusión_**', col.names = c('_Positivo_', '_Negativo_'),
             row.names = TRUE, booktabs = TRUE) %>%
       kableExtra::add_header_above(c('', 'Observados' = 2))`

give me a warning:
**Warning in kableExtra::add_header_above(., c("", Observados = 2)): Please
specify format in kable. kableExtra can customize either HTML or LaTeX outputs.
See https://haozhu233.github.io/kableExtra/ for details.**

and has no effect on output.

If I add `format = 'latex'`:

`knitr::kable(data, caption = '**_Matriz de Confusión_**', col.names = c('_Positivo_', '_Negativo_'),
             row.names = TRUE, booktabs = TRUE, format = 'latex') %>%
       kableExtra::add_header_above(c('', 'Observados' = 2))`

Then I get a latex table, but rendering is incorrect:
![Captura](https://user-images.githubusercontent.com/6486324/98049262-a24a3300-1e2f-11eb-9b33-614e9d8878fd.JPG)

**Below is an Rmd file to reproduce the above**
---
title: 'Discrepancias'
output:
  pdf_document: default
---

```{r data generation, echo = FALSE, results = 'hide'}
library(magrittr)
library(exams)

i <- sample(1:4, 1)

txt <- c('verdaderos positivos', 'falsos positivos', 'falsos negativos', 'verdaderos negativos')
elemento <- c('(1,1)', '(1,2)', '(2,1)', '(2,2)')

TP <- sample(150:250, 1)*100
FP <- sample(20:80, 1)*100
FN <- sample(15:30, 1)*100
TN <- sample(100:200, 1)*100

data <- data.frame(Positivo = c(TP, FN), Negativo = c(FP, TN))
row.names(data) <- c('_Positivo_', '_Negativo_')

if (i == 1){
    sol <- TP
} else if (i == 2){
    sol <- FP
} else if (i == 3){
    sol <- FN
} else if (i == 4){
    sol <- TN
}
```

Question
========
Un modelo de clasificación binario genera la siguiente **matriz de confusión**. Indica el número de **`r txt[i]`** del clasificador.

**Nota:** Considera que el **suceso de interés** representado en la **matriz de confusión** es _Positivo_.

\renewcommand{\tablename}[3]{}

```{r knitr, echo = FALSE, results = 'asis'}
knitr::kable(data, caption = '**_Matriz de Confusión_**', col.names = c('_Positivo_', '_Negativo_'),
             row.names = TRUE, booktabs = TRUE)
```

```{r kableExtra, echo = FALSE, results = 'asis'}
knitr::kable(data, caption = '**_Matriz de Confusión_**', col.names = c('_Positivo_', '_Negativo_'),
             row.names = TRUE, booktabs = TRUE, format = 'latex') %>%
       kableExtra::add_header_above(c('', 'Observados' = 2))
```
Solution

El número de **`r txt[i]`** del clasificador es simplemente el **elemento `r elemento[i]`** de la **matriz de confusión**, por tanto, el número de **`r txt[i]`** es $`r fmt(sol, 0)`$.

**Comment by haozhu233** [comment]
@fgoerlich kableExtra only works for latex/html tables. Markdown as a syntax is not capable to handle complex formatting. 

On the other hand, when rmarkdown/pandoc encounters a latex block, it will treat the latex block as is. It means that it will not convert the markdown syntax you wrote in your table to latex properly. That says, it is okay to write `__bold__` as bold if you only need a simple markdown table but it won't work if you create a latex table. 

If you need to italicize the header row and the first column, you need to use `row_spec(0, italic = T)` and `column_spec(0, italic = T)`

**Comment by fgoerlich** [comment]
Many thanks. I understand now.
On the other hand `row_spec(0, italic = T)` works perfectly well, but `column_spec(1, italic = T)` give me an error:
`! LaTeX Error: Illegal character in array arg.`
Also native latex works in the `caption` option in `kbl`, but not in `add_header_above`, for example `add_header_above(c('', '\\textit{Observados}' = 2))` does not work properly. Similarly with `cell_spec`.
Thanks a lot!
