### ISSUE TITLE
Add variable in add_header_above

### ISSUE THREAD

**Issue by bjungbogati** [haozhu233/kableExtra#565]
I want to add a variable in add header above but it's now working, 

file_date <- paste("username:", getwd(), Sys.time())

kableExtra::kbl(cars, align="l", escape = F, bootstrap_options = "basic") %>%
  kableExtra::kable_minimal(full_width = T) %>% 
  kableExtra::add_header_above(header = file_date, escape = F, line = F, align = "l")

Error in htmlTable_add_header_above(kable_input, header, bold, italic,  : The new header row you provided has a total of 1 columns but the original kable_input has 2.

I tried with, date <- c(file_date = 2) however it replace value to 2 and colspan won't work either.

**Comment by vincentarelbundock** [comment]
You need a named vector, so this should work:

```r
file_date <- setNames(2, paste("username:", getwd(), Sys.time()))
```
