### ISSUE TITLE
save_kable() removes bold formatting

### ISSUE THREAD

**Issue by gaberunte** [haozhu233/kableExtra#569]
I am attempting to save a kable table with specific values bolded by condition. This prints well in the Rmd, but when piped into save_kable() I lose the formatting and get only raw text. 

```
%>% 
  save_kable(here("figures", "polished", "permanova_table_main.pdf"))

```
The above is the code that goes from a working, bolded table to a table with only raw text.

**Comment by vincentarelbundock** [comment]
Could you try to specify `format="latex"` in your `kbl` call?

```
library(kableExtra)

dat = data.frame(a = 1:3, b=3) %>%
  kbl(format="latex") %>%
  row_spec(2, bold=TRUE) %>%
  save_kable("test.pdf")
```

**Comment by vincentarelbundock** [comment]
This appears to work with any value of the `format` argument, using the latest version from Github. Closing now, but feel free to comment if you still run into problems.
