### ISSUE TITLE
table caption width compressed with kable and longtable

### ISSUE THREAD

**Issue by mstantial** [haozhu233/kableExtra#570]
I am having this exact issue and I've tried everything but I can't fix it.  Any thoughts?

https://stackoverflow.com/questions/46085067/r-markdown-table-caption-width-with-kable-and-longtable/65148535#65148535

**Comment by haozhu233** [comment]
Yeah, as the answer suggested, it seems to be an unplanned behavior of the longtable package. Latex packages also have bugs and when bugs happen, it's usually quite difficult to fix. I think the solution to that SO question makes sense. You can just try to use the caption package to modify the caption width... If it's not working, I'm sorry but I really can't provide any useful insights here...
