### ISSUE TITLE
option `longtable=TRUE` causes grey text

### ISSUE THREAD

**Issue by johngodlee** [haozhu233/kableExtra#573]
**Describe the bug**
When the option `longtable = TRUE` is used in `kable()`, with Sweave, the color of all text in the table, including the caption is coloured grey.

**To Reproduce**

An example `.Rnw` document

````
\documentclass{article}

\usepackage{longtable}

\begin{document}

<<>>=
library(kableExtra)
kable(mtcars,
	longtable = TRUE)
@

\end{document}
````

This might be the offending line in the resulting `.tex`:

```
\definecolor{shadecolor}{rgb}{0.345, 0.345, 0.345}\color{fgcolor}\begin{kframe}
```

Is it possible to disable this behaviour and just have black colour text?

**Comment by haozhu233** [comment]
`\definecolor{shadecolor}{rgb}{0.345, 0.345, 0.345}\color{fgcolor}\begin{kframe}` this line doesn't look very familiar to me. I think it's probably defined in r sweave. I remember in rmarkdown they defined a similar thing called shaded for those code boxes. 

Another point is that if you are only using `kable`, you are actually not using any functions in this package...
