### ISSUE TITLE
bookdown, short.caption (kable) is not compatible with font.size (kableExtra), ! LaTeX Error: Not in outer par mode.

### ISSUE THREAD

**Issue by ivanek** [haozhu233/kableExtra#58]
I am getting an error for setting font size parameter in kable_styling function when combined with short.caption parameter from kable itself. I need to use short.caption for list of tables.  The error is 
`! LaTeX Error: Not in outer par mode.`

It seems like the short.caption is causing extra "table" environment inserted in tex document.

[https://gist.github.com/ivanek/d58158006992c5e9c7251d3a1bdad049](https://gist.github.com/ivanek/d58158006992c5e9c7251d3a1bdad049)

**Comment by haozhu233** [comment]
Hi @ivanek, have you tried the dev version or latest CRAN (I just updated it today)? I fixed a similar one in https://github.com/haozhu233/kableExtra/issues/37

**Comment by ivanek** [comment]
That fixed this issue too. Thanks Robert
