### ISSUE TITLE
kableExtra in rmarkdown question

### ISSUE THREAD

**Issue by wilson0106** [haozhu233/kableExtra#581]
Hi,

I trying to use kableExtra in RMarkown for a text table as the following example:

```{r}
text_tbl <- data.frame(
  Items = c("Item 1", "Item 2", "Item 3"),
  Features = c(
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vehicula tempor ex. Morbi malesuada sagittis turpis, at venenatis nisl luctus a. ",
    "In eu urna at magna luctus rhoncus quis in nisl. Fusce in velit varius, posuere risus et, cursus augue. Duis eleifend aliquam ante, a aliquet ex tincidunt in. ", 
    "Vivamus venenatis egestas eros ut tempus. Vivamus id est nisi. Aliquam molestie erat et sollicitudin venenatis. In ac lacus at velit scelerisque mattis. "
  )
)
kbl(text_tbl, booktabs = T) %>%
  kable_styling(full_width = F) %>%
  column_spec(1, bold = T, color = "red") %>%
  column_spec(2, width = "30em")
```

However I would to change the text of the table by inserting operators in one column and the example with some explanation in another, similar to this site: https://www.tutorialspoint.com/r/r_operators.htm. but I would like to see in output just the table with code inside, not the code that produce the table:

I produced this following code, with some variations, but not worked.

```{r}
text_tbl <- data.frame(
  Items = c(" <- ", " %in% "),
  Features = c(
    " Here it's an example: $x <- 3$",
    " Here it's an example: $c(1, 1, 1, 2, 5, 8, 10) %in% 1$ "
  )
)
kbl(text_tbl, booktabs = T) %>%
  kable_styling(full_width = F) %>%
  column_spec(1, bold = T, color = "red") %>%
  column_spec(2, width = "30em")
```

Thank's

@haozhu233 
@bookdown
@rmarkdown
@rstudio

**Comment by vincentarelbundock** [comment]
There is no clear feature request or bug report, and this hasn't been answered in 2 years. Perhaps you'll have better luck on StackOverflow or another forum like that.

Sorry!
