### ISSUE TITLE
RMD kable styling repeates rows when rendering striped table to LaTeX in some data combination

### ISSUE THREAD

**Issue by zahlenzauber** [haozhu233/kableExtra#582]
I use RStudio to render (version 1.4.1103) with R-version 4.0.3 and kableExtra-package 1.3.1, knitr 1.30.

I'm not quite sure if it's about the dot in my dataframe. But somehow there seems to be a special combination in my example data that leads to wrong table output when I try to get a striped table in LaTeX. For HTML everything is as expected. Without stripes there is no problem.

When I change my data in some way everything seems to be fine. But with the data I called _dfWithDot_ I get the effect. I thought that it has something to do with the value "A." - but when I replace B1=c("A1B1", "A2B1", "A.B1") by B1=letters[1:3] it works fine. So I'm a bit clueless.

So maybe, it's not the dot but something else. But I'm quite sure that it's something with kable_styling because the md-file and tex-file contain the data as they are shown in the PDF.

It's very special, I know. But maybe it's a bug, that crossed my path. I just wanted to report. For me there is no need for anybody to get deeper in it. I'm very grateful for the package.

Here is my MWE (the resulting PDF is attached):

````
---
title: "RMD kable styling repeates rows when rendering striped table to LaTeX in some data combination"
author: "Thomas Buhl"
date: '2021-01-20'
output:
  pdf_document: default
  html_document:
    df_print: paged
---


```{r prepare , eval=TRUE ,   echo=TRUE , tidy=TRUE, message=FALSE , warning=FALSE , results='asis'}

rm(list=ls())

library("knitr")
library("kableExtra")

dfWithDot <- data.frame(A=c("A1", "A2", "A."),   
                        B1=c("A1B1", "A2B1", "A.B1"), 
                        B2=c("A1B2", "A2B2", "A.B2"), 
                        B3=c("A1B3", "A2B3", "A.B3"), 
                        B.=c("A1B.", "A2B.", "A.B."))


dfNoDot <- data.frame(A=c("A1", "A2", "A_"),
                      B1=c("A1B1", "A2B1", "A_B1"), 
                      B2=c("A1B2", "A2B2", "A_B2"), 
                      B3=c("A1B3", "A2B3", "A_B3"), 
                      B.=c("A1B_", "A2B_", "A_B_"))

```

# Problem: Striped styling repeates rows 

```{r stripedDot , eval=TRUE ,   echo=TRUE , tidy=TRUE, message=FALSE , warning=FALSE , results='asis'}


if ((knitr::is_latex_output()))
  {
    dfWithDot  %>% 
      knitr::kable( format="latex")%>%
     kable_styling(latex_options =c( "striped" ), position = "center")
      }else{
    print("Please, render as LaTeX /PDF")}#end of if






```

# Without "striped" table as expected

```{r NotStripedDot , eval=TRUE ,   echo=TRUE , tidy=TRUE, message=FALSE , warning=FALSE , results='asis'}



if ((knitr::is_latex_output()))
  {
    dfWithDot  %>% 
      knitr::kable( format="latex")%>%
     kable_styling( position = "center")
      }else{
    print("Please, render as LaTeX /PDF")}#end of if



```


# Slightly chanced data: Striped table as expected

```{r NotStripedNoDot , eval=TRUE ,   echo=TRUE , tidy=TRUE, message=FALSE , warning=FALSE , results='asis'}



if ((knitr::is_latex_output()))
  {
    dfNoDot  %>% 
      knitr::kable( format="latex")%>%
     kable_styling(latex_options =c( "striped" ), position = "center")
      }else{
    print("Please, render as LaTeX /PDF")}#end of if



```
````
[MWEkableDot.20210120.pdf](https://github.com/haozhu233/kableExtra/files/5844321/MWEkableDot.20210120.pdf)

**Comment by vincentarelbundock** [comment]
Fixed here: https://github.com/haozhu233/kableExtra/pull/797
