### ISSUE TITLE
Error loading kableExtra package

### ISSUE THREAD

**Issue by hongyunsoo** [haozhu233/kableExtra#586]
Hi,
I am having an issue while loading the package. I noticed that a similar issue was raised in the thread but it had been closed.

I have tried uninstalling and reinstalling the package, uninstalling and reinstalling both R and RStudio, and updated all the packages. None of it has worked so far. Currently, I am using R version 4.0.3. The exact message is after library(kableExtra) is:

Error: package or namespace load failed for ‘kableExtra’ in readRDS(nsInfoFilePath):
error reading from connection
In addition: Warning message:
In readRDS(nsInfoFilePath) : error reading the file

Thanks for all your help!

**Comment by haozhu233** [comment]
Have you tried to clean up the RData? For example, try to create a new
rstudio project? nsInfoFilePath isn’t something I can recognize..

**Comment by hongyunsoo** [comment]
Hi,
Thanks for the quick response.
Yes, I have tried it with several different rstudio projects but it didn't seem to work on any one of them.
Any word of advice would be greatly appreciated!

**Comment by haozhu233** [comment]
https://r.789695.n4.nabble.com/R-3-3-0-Crashing-Error-in-readRDS-nsInfoFilePath-unknown-input-format-td4720766.html

This might be helpful

**Comment by hongyunsoo** [comment]
Thanks for a great source of information!
The idea that there might be a bug in one of the packages got me thinking. Initially, I tried deleting packages that I installed most recently (during the past month or so) but it did not work. I just deleted the entire folder ("My Documents\R\win-lib\4.0") and reinstalled both R and RStudio. That seemed to do the trick!

Thanks again!
