### ISSUE TITLE
shiny output for kable/fortmattable 

### ISSUE THREAD

**Issue by variani** [haozhu233/kableExtra#587]
Hi,

I really like the features of kableExtra like `kable_styling` & `add_header_above` and wish to combine them with `fortmattable` ones such as `color_tile` & `color_bar` in shiny.

The shiny example in [Use kable in Shiny](https://cran.r-project.org/web/packages/kableExtra/vignettes/use_kable_in_shiny.html) works fine. However, the displayed html table with the updates below doesn't look as expected.

Code in the server part of shiny with a new line `mutate(mpg = color_tile("white", "orange")(mpg))`:

```
server <- function(input, output) {
  output$mtcars_kable <- function() {
    req(input$mpg)
    mtcars %>%
      mutate(car = rownames(.)) %>%
      select(car, everything()) %>%
      filter(mpg <= input$mpg) %>%
      mutate(mpg = color_tile("white", "orange")(mpg)) %>%   # the new line
      knitr::kable("html") %>%
      kable_styling("striped", full_width = F) %>%
      add_header_above(c(" ", "Group 1" = 5, "Group 2" = 6))
  }
}
```

Shiny html output for the `mpg` colum:

```
<span style="display: block; padding: 0 4px; border-radius: 4px; background-color: #ffae1b">18.7</span>
```

Do you have any clues how to fix it?

Best,
Andrey

**Comment by haozhu233** [comment]
You can try to add an `escape=F` in the kable call

**Comment by variani** [comment]
That resolves the issue, thanks!
