### ISSUE TITLE
Problems with the new version of svglite

### ISSUE THREAD

**Issue by thomasp85** [haozhu233/kableExtra#589]
Hi team

The new version of svglite causes some issues with kableExtra... Specifically the `graphics_dev()` function fails since it assumes that only one of `file` and `filename` exists as arguments in the device function.

The new version of svglite has both in order to be argument compatible with `svg()` and this will throw off `graphics_dev()`

An easy fix is to change:

```r
found <- na.omit(match(frmls, filenames))
```

to 

```r
found <- na.omit(match(frmls, filenames))[1]
```

**Comment by haozhu233** [comment]
Thanks for letting me know! I will do an update on this.

**Comment by thomasp85** [comment]
Great!

Do you have any idea when a fix will be available on CRAN?

**Comment by haozhu233** [comment]
It seems quite straightforward. I can send it to CRAN later today.

**Comment by thomasp85** [comment]
That would be amazing! I'll ask CRAN to proceed with the svglite release then

Thanks for the swift response

**Comment by haozhu233** [comment]
I sent the updates to CRAN earlier this afternoon. It may take a while because it's pending for a manual check.

**Comment by haozhu233** [comment]
Oh, on CRAN now.
