### ISSUE TITLE
kable_styling(full_width = T) doesn't work for tables with a caption

### ISSUE THREAD

**Issue by Markouski** [haozhu233/kableExtra#59]
I am getting an error for setting `kable_styling(full_width = T)` when combined with `caption` parameter from 'kable' itself. I'm trying to render a pdf with 'knitr'.

Example:
**1. basic table, this works fine**
```
library(kable)
library(kableExtra)
kable(mtcars[1:5, 1:5],
      format = "latex",
      booktabs = TRUE) %>%
  kable_styling(full_width = TRUE)
```
![image](https://user-images.githubusercontent.com/8161754/30167770-212ff074-93f0-11e7-96f8-bf9ac6b561d7.png)

**2. When a caption has been set this gives an error**
```
kable(mtcars[1:5, 1:5],
      format = "latex",
      caption = "A caption",
      booktabs = TRUE) %>%
  kable_styling(full_width = TRUE)
```
output:
```
! Package array Error:  Illegal pream-token (t): `c' used.
```

**Comment by haozhu233** [comment]
Hi, thanks for reporting this critical bug! I fixed this bug in the latest dev ver. Please try it out using `devtools::install_github()`.
 I feel like since this bug is kind of critical, I will plan for a quick CRAN bug-fix release very soon.

**Comment by haozhu233** [comment]
@Markouski Fix is on CRAN now
