### ISSUE TITLE
[Feature Request] Option to change the line colour of kableExtra::spec_pointrange when knitting PDF

### ISSUE THREAD

**Issue by CLRafaelR** [haozhu233/kableExtra#590]
This feature request was originally posted as a [StackOverflow question](https://stackoverflow.com/questions/65616558/how-to-change-line-color-of-kableextraspec-pointrange-when-knitting-pdf) by myself, but I would like to repost it here as a feature request since the question has received no answer for months.

`kableExtra` creates a table with some plots, as [its manual](https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_pdf.pdf#page=13) demonstrates. We will have the following table with a pointrange plot with `kableExtra::spec_pointrange()`, running the code at the bottom of this post.

But how can I change colour of ***line***s of the plot (Note, NOT the colour of the centre dots), when knitting a PDF? It should be awesome if we can freely specify the colour of the error bar and vertical dot line also in PDF, since somehow it seems to be possible to change the line colour interactively when knitting HTML as suggested in [a blog post](https://themockup.blog/posts/2020-10-31-embedding-custom-features-in-gt-tables/).

[![enter image description here][1]][1]

    coef_table <- data.frame(
      Variables = c("var 1", "var 2", "var 3"),
      Coefficients = c(1.6, 0.2, -2.0),
      Conf.Lower = c(1.3, -0.4, -2.5),
      Conf.Higher = c(1.9, 0.6, -1.4)
    )
    data.frame(
      Variable = coef_table$Variables,
      Visualization = ""
    ) %>%
      kbl(booktabs = T) %>%
      kable_classic(full_width = FALSE) %>%
      column_spec(
        2, 
        image = spec_pointrange(
          x = coef_table$Coefficients,
          xmin = coef_table$Conf.Lower,
          xmax = coef_table$Conf.Higher,
          vline = 0
        )
    )

  [1]: https://i.stack.imgur.com/YnwPK.png

**Comment by haozhu233** [comment]
@CLRafaelR Sounds good to me. I just added a `line_col` option to `spec_pointrange`.
