### ISSUE TITLE
Unable to update kableExtra due to svglite

### ISSUE THREAD

**Issue by hnguyen19** [haozhu233/kableExtra#591]
**Describe the bug**
Unable to update kableExtra due to `svglite`

I updated kableExtra the usual way (with the Update button in Rstudio) but that didn't work so I uninstalled it and tried the following. It returned 2 errors. 

 install.packages('kableExtra', repos='https://cran.ma.imperial.ac.uk/')
also installing the dependency ‘svglite’

  There are binary versions available but the source versions are later:
            binary source needs_compilation
svglite    1.2.3.2  2.0.0              TRUE
kableExtra   1.3.2  1.3.4             FALSE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) yes
installing the source packages ‘svglite’, ‘kableExtra’

trying URL 'https://cran.ma.imperial.ac.uk/src/contrib/svglite_2.0.0.tar.gz'
Content type 'application/x-gzip' length 122260 bytes (119 KB)
==================================================
downloaded 119 KB

trying URL 'https://cran.ma.imperial.ac.uk/src/contrib/kableExtra_1.3.4.tar.gz'
Content type 'application/x-gzip' length 1646490 bytes (1.6 MB)
==================================================
downloaded 1.6 MB

* installing *source* package ‘svglite’ ...
** package ‘svglite’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/cpp11/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/systemfonts/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c cpp11.cpp -o cpp11.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/cpp11/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/systemfonts/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c devSVG.cpp -o devSVG.o
devSVG.cpp:21:10: fatal error: 'png.h' file not found
#include <png.h>
         ^~~~~~~
1 error generated.
make: *** [devSVG.o] Error 1
ERROR: compilation failed for package ‘svglite’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/svglite’
Warning in install.packages :
  installation of package ‘svglite’ had non-zero exit status
ERROR: dependency ‘svglite’ is not available for package ‘kableExtra’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/kableExtra’
Warning in install.packages :
  installation of package ‘kableExtra’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/_y/gy3_9sj93ws6kj18xhq1fsyr0000gn/T/Rtmp2rO1IP/downloaded_packages

Fixes here do not work for me https://github.com/haozhu233/kableExtra/issues/60

**Comment by haozhu233** [comment]
Yeah, I added svglite dependency because CRAN told me that the base svg doesn't work on some systems and I need to setup a check or something. 

Normally you don't need to build svglite by yourself. The reason you see that is that they just updated it on CRAN a few days ago and it hasn't been built for windows/Mac. The solution here is to select "no" when they ask you if you want to compile. kableExtra works with previous version of svglite.
