### ISSUE TITLE
include_thead is ignored when adding borders

### ISSUE THREAD

**Issue by mvacher** [haozhu233/kableExtra#594]
I'm trying a add vertical borders in a table.
It's seems to work fine in the table but not in the header, even when using the *include_thead* parameter.

Example:

```
library(knitr)
library(kableExtra)
library(dplyr)

dt <- mtcars[1:5, 1:6]
dt %>% 
kable() %>%
# add the vertical lines for all the columns
column_spec (1:7,border_left = T, border_right = T) %>%
kable_styling()
```

But using   include_thead = T does not work
```
dt %>% 
kable() %>%
column_spec (1:7,border_left = T, border_right = T, include_thead = T) %>%
kable_styling()
```
and returns the following error:

```
Error in UseMethod("nodeset_apply") : no applicable method for 'nodeset_apply' applied to an object of class "NULL"
```

How can I borders in the whole table ?

Thank you

**Comment by vincentarelbundock** [comment]
This appears to be fixed in the latest development version. Please install from Github, restart R, try again, and report here if it still doesn't work for you.
