### ISSUE TITLE
collapse_rows not working as expected?

### ISSUE THREAD

**Issue by SPFL-Analysis** [haozhu233/kableExtra#595]
Hello, I've been using this package for a while and all was great but today I updated to rvest v1.0.0 and it seems to have stopped the collapse_rows() function working as it did, please see example below. 

```
df <- data.frame("col1" = c("a", "a", "b"), "col2" = 1:3)
kableExtra::collapse_rows(knitr::kable(df), columns = 1)
```

For me this no longer collapses the first 2 rows of col1 with the "a" values.
Any help would be much appreciated.
Thanks.

**Comment by unDocUMeantIt** [comment]
same here. i suspect this is due to `rvest:::html_table()` having [changed its output format](https://github.com/tidyverse/rvest/releases/tag/v1.0.0). a quickfix to get the expected data frame back could be wrapping it in `as.data.frame(html_table())`.

**Comment by haozhu233** [comment]
@SPFL-Analysis @unDocUMeantIt Fixed now. Thank you for reporting and making that suggestion!

**Comment by motocci** [comment]
Same above.　(v. 1.3.4)
I'm looking forward to the features coming to work.

**Comment by unDocUMeantIt** [comment]
i'm happy to confirm that the commit is fixing the issue.

> I'm looking forward to the features coming to work.

until there's a new official release of the package, you can install the fixed version directly from github:

```r
devtools::install_github(repo="haozhu233/kableExtra", ref="a6af5c0")
```

`ref` here is the bugfix commit mentioned above. you should start a fresh R session afterwards.

**Comment by motocci** [comment]
> 
> 
> i'm happy to confirm that the commit is fixing the issue.
> 
> > I'm looking forward to the features coming to work.
> 
> until there's a new official release of the package, you can install the fixed version directly from github:
> 
> ```r
> devtools::install_github(repo="haozhu233/kableExtra", ref="a6af5c0")
> ```
> 
> `ref` here is the bugfix commit mentioned above. you should start a fresh R session afterwards.

It is the same display as the document and is the ideal display.
I appreciate it.

**Comment by motocci** [comment]
Sorry.
I tested git one. 
Another problem has occurred.

If I use the table below,

C1 	C2 	C3 	C4
A 	c 	1 	1
		2 	1
		3 	0
	d 	4 	0
		5 	1
		6 	1
B 	c 	71 	0
		8 	0
	d 	9 	1
		10 	1
		11 	0 
C 	d 	12 	1
		13 	1
		14 	0
D 	c 	15 	0
		16 	0 

It appears llike below.
C1 	C2 	C3 	C4
A 	c 	1 	1
		2 	1
		3 	0
	d 	4 	0
		5 	1
		6 	1
B 	c 	71 	0
		8 	0
	d 	9 	1
		10 	1
		11 	0 
C 	 	12 	1
		13 	1
		14 	0
D 	c 	15 	0
		16 	0 

C1=C 's C2 not appeared.
Regards.

**Comment by christopherkn** [comment]
`collapse_rows()` is still not working for me, even with the version installed directly from github @unDocUMeantIt can you explain what you meant by "a quickfix to get the expected data frame back could be wrapping it in `as.data.frame(html_table())`." What is the "it" you wrap in that? I'm just working with the data from the kableExtra documentation:

```
collapse_rows_dt <- data.frame(C1 = c(rep("a", 10), rep("b", 5)),
                               C2 = c(rep("c", 7), rep("d", 3), rep("c", 2), rep("d", 3)),
                               C3 = 1:15,
                               C4 = sample(c(0,1), 15, replace = TRUE))
kbl(collapse_rows_dt, align = "c") %>%
  kable_paper(full_width = F) %>%
  column_spec(1, bold = T) %>%
  collapse_rows(columns = 1:2, valign = "top")
```

wrapping the whole thing in  `as.data.frame(html_table())` :

```
as.data.frame(html_table(kbl(collapse_rows_dt, align = "c") %>%
  kable_paper(full_width = F) %>%
  column_spec(1, bold = T) %>%
  collapse_rows(columns = 1:2, valign = "top")))
```
gives `Error in UseMethod("html_table") :  no applicable method for 'html_table' applied to an object of class "c('kableExtra', 'knitr_kable')"`

wrapping just the dataframe:
```
kbl(as.data.frame(html_table(collapse_rows_dt)), align = "c") %>%
  kable_paper(full_width = F) %>%
  column_spec(1, bold = T) %>%
  collapse_rows(columns = 1:2, valign = "top")
```
which gives: `Error in UseMethod("html_table") : no applicable method for 'html_table' applied to an object of class "data.frame"`

**Comment by unDocUMeantIt** [comment]
> can you explain what you meant by "a quickfix to get the expected data frame back could be wrapping it in as.data.frame(html_table())."

i was refering to the source code of `kableExtra`, which is what was added with haozhu233/kableExtra@a6af5c0 .

**Comment by m-oldham** [comment]
It isn't working for me either. Using rvest 1.0 and kableextra 1.3.4. I've been using it for a blogdown post and it previously worked but has now ceased to do anything.

**Comment by dholstius** [comment]
I installed 1.3.4.9000 from GitHub. The example from `?collapse_rows` doesn't seem to work:

```r
dt <- data.frame(a = c(1, 1, 2, 2), b = c("a", "a", "a", "b"))
(x <- knitr::kable(dt, format = "markdown"))
```

|  a|b  |
|--:|:--|
|  1|a  |
|  1|a  |
|  2|a  |
|  2|b  |

```r
collapse_rows(x)
```

|  a|b  |
|--:|:--|
|  1|a  |
|  1|a  |
|  2|a  |
|  2|b  |

In addition:

```r
Warning message:
In collapse_rows(x) :
  Please specify format in kable. kableExtra can customize either HTML or LaTeX outputs. See https://haozhu233.github.io/kableExtra/ for details.
```

I'm expecting three rows of output, like:

|  a|b  |
|--:|:--|
|  1|a  |
|  2|a  |
|  2|b  |

**Comment by Robsteranium** [comment]
a6af5c0 with rvest `1.0.2` works for me

**Comment by burgerga** [comment]
At @dholstius, collapse_rows doesn't work on "markdown" format (see https://github.com/haozhu233/kableExtra/blob/master/R/collapse_rows.R#L56-L61) so you just get your input back

**Comment by fthielen** [comment]
This is still not resolved. Is the package still maintained?
