### ISSUE TITLE
Error when installing the package 

### ISSUE THREAD

**Issue by JTORRES531** [haozhu233/kableExtra#60]
When I try to install the package I get the following errors related to the URL not being found, lib not specified and telling me kableExtra is not available for my current R version. 

Could you help? 

> install.packages("kableExtra")
Warning in install.packages :
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/src/contrib/PACKAGES.rds': HTTP status was '404 Not Found'
Installing package into ‘C:/Users/2151521/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘kableExtra’ is not available (for R version 3.4.0)

**Comment by haozhu233** [comment]
Err... Usually if you try to install it again, this error will be gone. 

If not, you can try
```r
install.packages('kableExtra', repos='https://cloud.r-project.org/')
#or 
install.packages('kableExtra', repos='https://cran.ma.imperial.ac.uk/')
```
Or any CRAN server addresses on this list https://cran.r-project.org/mirrors.html

**Comment by JTORRES531** [comment]
That worked, thanks!

[Description: cid:image001.png@01CB0899.8ED65220]
Joe Torres | Category Analytics Specialist| Merchandise Financial Planning & Category Analytics
Meijer | 2350 3 Mile Rd. NW  | Grand Rapids, MI 49544 | 989/1
P: 616-791-2478
Joseph.Torres@meijer.com<mailto:Joseph.Torres@meijer.com>

**Comment by julianashwin** [comment]
I'm also having trouble installing either with `install.packages()` or using `devtools`. 

`Warning: S3 methods ‘as.col_spec.NULL’, ‘as.col_spec.character’, ‘as.col_spec.col_spec’, ‘as.col_spec.default’, ‘as.col_spec.list’, ‘format.col_spec’, ‘output_column.POSIXt’, ‘output_column.default’, ‘output_column.double’, ‘print.col_spec’, ‘print.collector’, ‘print.date_names’, ‘print.locale’ were declared in NAMESPACE but not found
Error in library.dynam(lib, package, package.lib) : 
  shared object ‘readr.so’ not found
ERROR: lazy loading failed for package ‘kableExtra’
* removing ‘/home/rstudio/R/x86_64-pc-linux-gnu-library/3.4/kableExtra’
Warning in install.packages :
  installation of package ‘kableExtra’ had non-zero exit status`

Any ideas what's causing this?

**Comment by paobranco** [comment]
I had exactly the same problem!
First I tried to install the readr package
```
install.packages("readr")
```

I got also an error...
```
ERROR: failed to lock directory ‘/home/pbranco/R/x86_64-pc-linux-gnu-library/3.4’ for modifying
Try removing ‘/home/pbranco/R/x86_64-pc-linux-gnu-library/3.4/00LOCK-readr’
Warning in install.packages :
  installation of package ‘readr’ had non-zero exit status
```
 So, I followed the suggestion of removing the file 00LOCK-readr.
After have this done, I could install the readr package.
Then, I was also able to install the kableExtra.
And that's it!

**Comment by haozhu233** [comment]
@paobranco Thanks for looking into this and provide a solution!
