### ISSUE TITLE
library(kableExtra) causes kable to make ugly tables by default

### ISSUE THREAD

**Issue by arencambre** [haozhu233/kableExtra#600]
**Describe the bug**
You get an ugly table if this is your .Rmd:
````
---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(kableExtra)
knitr::kable(mtcars[1:5, ])
```
````

If you merely remove `library(kableExtra)`, you get a good looking table.

**Comment by sayaliph** [comment]
I am experiencing the same issue and looking for solutions. There are certain features in kableExtra which are functionally important for my purpose, but the changed look is definitely not ideal. The alternative is to add the special features directly in LaTeX. However, that is quite tedious.

**Comment by vincentarelbundock** [comment]
This should be fixed in the master development branch on Github. Please comment if you still run into the issue after installing from Github and restarting R.
