### ISSUE TITLE
Package load fails for kableExtra

### ISSUE THREAD

**Issue by eisbrinde** [haozhu233/kableExtra#601]
Hello,

I have installed the kableExtra package, but it fails to load afterwards:

```
> install.packages("kableExtra")
versuche URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/kableExtra_1.3.4.tgz'
Content type 'application/x-gzip' length 1844129 bytes (1.8 MB)
==================================================
downloaded 1.8 MB


The downloaded binary packages are in
	/var/folders/pm/2t8wl69546qcmgdmd72vg1zc0000gn/T//RtmpgTcHNB/downloaded_packages
> library(kableExtra)
Fehler: package or namespace load failed for ‘kableExtra’ in dyn.load(file, DLLpath = DLLpath, ...):
 kann shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so' nicht laden:
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so, 6): Library not loaded: /opt/X11/lib/libfreetype.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so
  Reason: image not found
```

Does anyone have an idea how to solve this?

**Comment by cdigenna** [comment]
I am having this same issue!

**Comment by haozhu233** [comment]
Same issue here: https://github.com/haozhu233/kableExtra/issues/644

kableExtra depends on svglite, which depends on systemfonts.

**Comment by haozhu233** [comment]
Looked into this a little bit more. Overall this is a dependency problem. Here is a general recommendation for anyone encountering this in the future:

1. Start a new R session
2. Try to reinstall the systemfonts package
3. If it fails, try to install the two system requirements of systemfonts (SystemRequirements: fontconfig, freetype2) on your machine and then try again. You may consider to install them in a conda environment if you don't have system permission
4. Try to reinstall kableExtra again.
