### ISSUE TITLE
kableExtra: how to set table spacing to single if the global LaTeX spacing is doublespacing

### ISSUE THREAD

**Issue by mickeyang** [haozhu233/kableExtra#606]
Hi team,
I have set my global PDF spacing to double by using the below code in my RMarkdown file.

```
header-includes:
  \usepackage{setspace}
  \doublespacing
```

But this global set the kable spacing to double as well, which is not ideal most of the time.

To fix the issue, I have manually wrapped raw LaTeX language around my table.
```
\begin{singlespace}
a kable
\end{singlespace}
```

I am wondering is it possible to control the kable spacing by adding a table_spacing (something like that) parameter, please?

Thanks in advance.
Look forward to hearing from you.

Have a good day.

**Comment by eteitelbaum** [comment]
Hi, I am having the same problem and am wondering why the issue was closed. Is there an obvious setting to change the spacing of the table when the global setting is doublespace?
