### ISSUE TITLE
kable_styling(latex_options=c("repeat_header")) Fails

### ISSUE THREAD

**Issue by vbmike013** [haozhu233/kableExtra#609]
My apologies.  I hope I am getting this right, and I hope I didn't just miss that it has already been reported.

**Describe the bug**
When I use both `booktab=TRUE` and `longtables=TRUE` in kable with latex output, kable_styling fails with `Error in 1:header_rows_end: NA/NaN argument`

**To Reproduce**
Think about using `reprex` to generate an example in R. 

---
author: erickson
date: 2021-04-19
output: "reprex::reprex\\_document"
title: full-husky\_reprex.R
---

``` r
library(kableExtra)

a <- data.frame(a=1:2, b=3:4)
kable(a, booktabs=TRUE, longtable=TRUE, format="latex")
```

``` r
kable(a, booktabs=TRUE, longtable=TRUE, format="latex") %>%
  kable_styling(latex_options=c("repeat_header"))
#> Error in 1:header_rows_end: NA/NaN argument
```

<sup>Created on 2021-04-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Finally, if it helps — 

```
> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] kableExtra_1.3.4

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13   knitr_1.32        xml2_1.3.2       
 [4] magrittr_2.0.1    rvest_1.0.0       munsell_0.5.0    
 [7] colorspace_2.0-0  viridisLite_0.4.0 R6_2.5.0         
[10] rlang_0.4.10      stringr_1.4.0     httr_1.4.2       
[13] tools_4.0.5       webshot_0.5.2     xfun_0.22        
[16] htmltools_0.5.1.1 systemfonts_1.0.1 digest_0.6.27    
[19] lifecycle_1.0.0   glue_1.4.2        evaluate_0.14    
[22] rmarkdown_2.7     stringi_1.5.3     compiler_4.0.5   
[25] scales_1.1.1      svglite_2.0.0  
```

**Comment by vbmike013** [comment]
Also, without `booktabs=TRUE`, it works just fine as well.

```
> kable(a, longtable=TRUE, format="latex") %>%
+   kable_styling(latex_options=c("repeat_header"))

\begin{longtable}{r|r}
\hline
a & b\\
\hline
\endfirsthead
\multicolumn{2}{@{}l}{\textit{(continued)}}\\
\hline
a & b\\
\hline
\endhead
1 & 3\\
\hline
2 & 4\\
\hline
\end{longtable}
```

**Comment by vbmike013** [comment]
I just tried the solution described for Issue #607, and it solves this issue as well.

The solution is described here: <https://stackoverflow.com/a/67167067/559676>

I just added this to my preamble:

```
options(
  knitr.table.toprule = '\\toprule',
  knitr.table.midrule = '\\midrule',
  knitr.table.bottomrule = '\\bottomrule'
)
```

I this the issue should be left open until `kable()` is updated.  Does that sounds right?

**Comment by yihui** [comment]
I'll update **knitr** on CRAN today or tomorrow. Hopefully you can close this issue soon. The problem has been fixed in the development version of **knitr**:

```r
remotes::install_github('yihui/knitr')
```

**Comment by yihui** [comment]
The new version of **knitr** has been published on CRAN. This issue can be closed now.

**Comment by krlmlr** [comment]
Confirming that knitr 1.33 fixes the issue for me.
