### ISSUE TITLE
Feature request: Replace ":" with "*" or "x" in ANOVA tables' interaction terms

### ISSUE THREAD

**Issue by hnguyen19** [haozhu233/kableExtra#611]
Hello,

Thanks for a neat package to manipulate tables. I am wondering if you could add the above-mentioned request to the next version. Some journals require the interaction term to be written with x or * instead of the default ":" from R's ANOVA tables. I asked this question on tex.stackexchange and got a fair answer for a simple 3-row table but this involves manipulating the exact term in a particular table. What I am looking for is a solution for all the tables in a manuscript or for bigger tables with multiple interactions.   
Here is the link to my question. Thank you for your time and consideration. 
<https://tex.stackexchange.com/questions/594324/how-to-replace-all-with-or-x-in-an-anova-table/594349?noredirect=1#comment1491169_594349>

**Comment by vincentarelbundock** [comment]
I think this is out of scope. There are many other packages to draw regression tables, including some that rely on kableExtra to draw the table.
