### ISSUE TITLE
Feature request = col.names argument to allow named vectors

### ISSUE THREAD

**Issue by tjebo** [haozhu233/kableExtra#615]
These are basically two feature request, but on the same argument in `kable`. 1

- I would find it neat if the argument would take named vectors, in order to allow explicit naming of columns. At the moment, it renames the columns by position
- It would also be great if only specific columns could be renamed. E.g., passing a named vector of `length(vector) < length(names(df))`, would work. 

``` r
library(kableExtra)
library(tidyverse)

# does not take named vector
mtcars %>%
  select(mpg, cyl) %>% 
  head(1) %>%
  kable(col.names = c(cyl = "still first", mpg = "still second")) 
```

<table>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
still first
</th>
<th style="text-align:right;">
still second
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Mazda RX4
</td>
<td style="text-align:right;">
21
</td>
<td style="text-align:right;">
6
</td>
</tr>
</tbody>
</table>

``` r
# col.names must be of the same length, so this here does not work. 
mtcars %>%
  select(mpg, cyl) %>% 
  head(1) %>%
  kable(col.names = c(cyl = "still first")) 
#> Error in dimnames(x) <- dn: length of 'dimnames' [2] not equal to array extent
```

<sup>Created on 2021-05-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by tjebo** [comment]
I have not looked into the source code but I assume it's not super easy. I am happy to try a pull request if you should like the idea, but would only start to work on it if you like it.

**Comment by Xitian9** [comment]
I strongly second this request, for the following reasons.

When designing documents, I'll often go through several iterations of table presentation to find what works best. This often involves rearranging columns. Every time I do this, I need to make sure I manually re-order `col.names` into *exactly* the correct order. This is error-prone and if missed can result in mislabelled tables, which greatly affects the reliability of the code.

A more robust alternative is to manually rename the columns with `dplyr::rename`, however then you are subject to all the column name restrictions. Duplicate column names are absolutely unacceptable in a data frame, but perfectly valid in a table for presentation (especially if there are column groupings).

**Comment by Xitian9** [comment]
Apologies. Since the `kbl` function here is just a wrapper around `knitr::kable`, this issue is a better fit for knitr. I'll raise this upstream.

**Comment by vincentarelbundock** [comment]
Closing because the original poster decided to raise this upstream. The feature is also trivial to achieve (in fewer keystrokes) using existing tools:

```r
library(dplyr)
library(kableExtra)
mtcars |>
  select(`first` = mpg, `blah blah` = cyl) |>
  head(5) |>
  kbl() 
```
