### ISSUE TITLE
Is it possible to use webhot2 instead of webshot in the save_kable function?

### ISSUE THREAD

**Issue by henricombrink** [haozhu233/kableExtra#618]
I can not get webshot to work on my system due to deprecated library dependencies. As a result, save_kable() fails. 
The new webshot2 ([https://github.com/rstudio/webshot2](url)) does work. 
Could webhot2 be used instead of webshot in the save_kable() function?

─ Session info 
 setting  value                        
 version  R version 4.0.3 (2020-10-10) 
 os       Debian GNU/Linux bullseye/sid
 system   x86_64, linux-gnu            
 ui       RStudio                      
 language (EN)                         
 collate  en_US.UTF-8                  
 ctype    en_US.UTF-8                  
 tz       America/Los_Angeles          
 date     2021-05-21

**Comment by henricombrink** [comment]
I tried this on a forked version locally by calling webshot2 instead of webshot. It seems to work without issues.

**Comment by haozhu233** [comment]
webshot2 is not on CRAN and it doesn't look like it will go to CRAN in anytime soon. Also, I remember the mechanism is quite different. If you have a script that is working and you are willing to share it on a gist of blog, I'm happy to put them in the doc or function doc in save_kable().

**Comment by daaronr** [comment]
I just realize I raised a similar issue https://github.com/haozhu233/kableExtra/issues/657, but detailing my bug a bit more. 

@henricombrink  I'd love to see your forked version! I'm trying to engineer something similar

**Comment by vincentarelbundock** [comment]
FWIW, `webshot2` is now available on CRAN: https://cran.r-project.org/web/packages/webshot2/index.html

**Comment by vincentarelbundock** [comment]
Fixed here: https://github.com/haozhu233/kableExtra/pull/768
