### ISSUE TITLE
Put a few rows of a table into many categories programmatically

### ISSUE THREAD

**Issue by MYaseen208** [haozhu233/kableExtra#62]
I guess it would be a good feature to _Put a few rows of a table into many categories programmatically_ like

```
library(knitr)
library(kableExtra)

x <- knitr::kable(head(mtcars, 10), "latex")
kableExtra::group_rows(kable_input = x, group_label = c("Group 1", "Group 2"), start_row = c(1, 5), end_row = c(2, 6))
```

**Comment by haozhu233** [comment]
Great suggestions! I also saw your question about column/row spec. They will all be features in the next version.

**Comment by MYaseen208** [comment]
Thanks for your consideration. Can you provide any solution now.

**Comment by haozhu233** [comment]
Feature added in https://github.com/haozhu233/kableExtra/commit/49483bf10d0e1cb42c61a6c7b0a72bf7a2b24ee3
