### ISSUE TITLE
Caption size can be too small if font size is large.

### ISSUE THREAD

**Issue by dmurdoch** [haozhu233/kableExtra#621]
**Describe the bug**

The `kable_styling(font_size = ...)` setting forces the caption size to `font-size: initial !important;`, which is unlikely to
be correct.  Should it be `inherited` or `inherited !important` instead?

For example, this SO question shows that `initial` produces tiny text when large text is desired:  https://stackoverflow.com/q/67750737/2554330 

**To Reproduce**
 
This document (from SO) shows the issue:

````
---
title: Here is my title 
author:
  - name: Name and Surname
affiliation:
    address: Department, University
column_numbers: 3
logoright_name: https&#58;//raw.githubusercontent.com/brentthorne/posterdown/master/images/betterhexlogo.png
logoleft_name: https&#58;//raw.githubusercontent.com/brentthorne/posterdown/master/images/betterhexlogo.png
output: 
  posterdown::posterdown_html:
    self_contained: false
knit: pagedown::chrome_print
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Intro

```{r table1, echo = FALSE, warning = FALSE, message = FALSE, results = 'asis', fig.pos='!h'}
library(tidyverse)
library(kableExtra)

col_1 <- c(1,2,3)
col_2 <- c(4,5,6)
col_3 <- c(7,8,9)

data.frame(col_1, col_2, col_3) %>% 
  kable(format='html',booktabs=TRUE, caption = "This is the caption", escape=F) %>% 
  kable_styling(font_size = 45)

```

````

It looks as though the problematic `kableExtra` code is here:  https://github.com/haozhu233/kableExtra/blob/4c93f1afc26efcd04fa729cb4a522d5f262bb6bd/R/kable_styling.R#L259

**Comment by davidizquierdogomez** [comment]
Eventually, what would be the solution to format the font size of the a kable() caption? the "font_size" attribute of the kable_styling() does not change the size of the caption; it only changes the one of the text contained in the table.

Thanks a lot,

**Comment by dmurdoch** [comment]
The caption is normally formatted with the default font size of the document.  You can set that using the YAML `fontsize:` entry.  Allowable values depend on whether it is HTML or PDF output.  For the example (using `posterdown::posterdown_html`, which is an HTML format) you can add this line at the end of the YAML:

    fontsize: 45pt

If this was a PDF format, that's not a legal value.  There are only a few for `article` class:  10pt, 11pt, 12pt.  There are other ways in LaTeX to set a non-standard font size, you'd have to use one of those.
