### ISSUE TITLE
knitrExtra not available for R 4.1 ??

### ISSUE THREAD

**Issue by tbates** [haozhu233/kableExtra#629]
`install.packages("knitrExtra")` fails with the warning that  ‘knitrExtra’ is not available for this version of R

This happens for R 4.1.0 (2021-05-18) on MacOS, and (according to Rhub) on Debian.

```R
# code to reproduce the bug.
install.packages("knitrExtra")
```
> Warning message:
package ‘knitrExtra’ is not available for this version of R

**Comment by rhurlin** [comment]
Hi Tim,

Do you mean [kableExtra](https://ftp.gwdg.de/pub/misc/cran/web/packages/kableExtra/index.html) instead of `knitrExtra`?

HTH, best wishes,
Rainer

**Comment by tbates** [comment]
Retrospectively, I meant "I may need glasses" :-) Thanks @rhurlin! :-)
