### ISSUE TITLE
Specify the look of selected rows programatically

### ISSUE THREAD

**Issue by MYaseen208** [haozhu233/kableExtra#63]
Currently `kableExtra 0.5.1` only supports _Put a few rows of a table into one category_. It would be nice to a feature which can _Specify the look of selected rows programatically_ like this

```
multirow_spec <- function(x, rows, ...) {
  for (row in rows) 
    x <- kableExtra::row_spec(x, row, ...)
  x
}

x <- knitr::kable(head(mtcars), "latex")
multirow_spec(x, c(1, 3, 4), bold = TRUE, italic = TRUE)

```

**Comment by haozhu233** [comment]
I added support to vector row/column in the latest dev version. Feel free to try it out.
