### ISSUE TITLE
Error: package or namespace load failed 

### ISSUE THREAD

**Issue by martynagalazka** [haozhu233/kableExtra#644]
Hello, 

I'm getting an error message when loading kableExtra such that: 
Registered S3 method overwritten by 'systemfonts':
  method             from       
  print.font_feature R_GlobalEnv
Error: package or namespace load failed for ‘kableExtra’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so, 6): Library not loaded: /opt/X11/lib/libfreetype.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so
  Reason: image not found

I have  tried: 
1. Updated RStudio to version 1.4
2. Uninstalled and installed both knitr and kableExtra
3. tried installing dev version

Is there anything else I could do? 
Help much appreciated.

**Comment by vincentarelbundock** [comment]
closed as duplicate
