### ISSUE TITLE
Escaping does not work in blogdown with `.Rmarkdown` extensions when a bibliography is used

### ISSUE THREAD

**Issue by andrewheiss** [haozhu233/kableExtra#649]
When using `kableExtra::kbl()` in a blogdown HTML document, the `escape = FALSE` argument does not work when two conditions are met:

1. There's a bibliography set in the YAML
2. The extension of the  R Markdown document is `.Rmarkdown`

Here's a minimal reprex that would need to be included in a basic blogdown installation (i.e. after running `blogdown::create_site()`):

**refs.bib**: Create an empty file

**content/post/without-bib/index.Rmarkdown**

````
---
title: "Without bibliography"
---

```{r warning=FALSE, message=FALSE}
library(dplyr)

tribble(
  ~`column_1`, ~`column_2`,
  1, 5
) %>% 
  kableExtra::kbl(escape = FALSE)
```
````

**content/post/with-bib/index.Rmarkdown**

````
---
title: "With bibliography"
bibliography: "refs.bib"
---

```{r warning=FALSE, message=FALSE}
library(dplyr)

tribble(
  ~`column_1`, ~`column_2`,
  1, 5
) %>% 
  kableExtra::kbl(escape = FALSE)
```
````

Finally, run `blogdown::build_site(build_rmd = TRUE)` to build the site.

The resulting `without-bib/index.html` will have this table:

| column_1 | column_2 |
| --- | --- |
| 1 | 5 |

But `with-bib/index.html` will have this table:

| column\\_1 | column\\_2 |
| --- | --- |
| 1 | 5 |

Escaping works fine when the extension is `.Rmd`, and escaping works fine when using `knitr::kable(escape = FALSE)` instead of `kableExtra::kbl(escape = FALSE)` in both `.Rmd` and `.Rmarkdown`. It's just the combination of `.Rmarkdown` and `kableExtra::kbl()` that doesn't work.

This is likely related to how blogdown treats `.Rmarkdown` files and passes them through pandoc when there's a bibliography (see https://bookdown.org/yihui/blogdown/output-format.html and https://github.com/rstudio/blogdown/issues/626#issuecomment-849405516)

**Comment by vincentarelbundock** [comment]
Closing because this is an upstream issue and a weird corner case. It's quite unlikely we'll be able to fix this here. Feel free to comment again if this is still an annoyance and you think there's something we can do here.
