### ISSUE TITLE
longtable printed onto bottom margin

### ISSUE THREAD

**Issue by alatzka** [haozhu233/kableExtra#65]
I have an RMarkdown script that uses kable + kableExtra (great job, by the way!) to print a large table to a formatted pdf. In my YAML header, I specify some narrow margins, and call a variety of latex packages for formatting the table and other parts of the document:
`---
title: 
output:
  pdf_document: default
geometry: "left=0.4in,right=0.4in,top=0.3in,bottom=0.3in"
params:
  waterbody: NA
header-includes:
   \usepackage{graphicx}
   \usepackage{fancyhdr}
   \usepackage{eurosym}
   \usepackage{booktabs}
   \usepackage{longtable}
   \usepackage{array}
   \usepackage{multirow}
   \usepackage[table]{xcolor}
   \usepackage{wrapfig}
   \usepackage{float}
   \usepackage{colortbl}
   \usepackage{pdflscape}
   \usepackage{tabu}
   \usepackage{threeparttable}
   \pagestyle{fancy}
   \fancyhf{}
   \addtolength{\headheight}{2.5cm}
   \fancyhead[R]{\fontsize{18}{10} \selectfont My Title Here}
   \lhead{\includegraphics[width=6cm]{path/to/logo.png}}
   \rfoot{Page \thepage}
   \fancypagestyle{plain}{\pagestyle{fancy}}
---`
The first page prints some text specific to the RMarkdown parameter inputted. 

Then I format a data.frame generally with ~50-300 rows, and and use kable & kableExtra to knit it:

`kable(data.frame,
      longtable=T,booktabs=T,row.names=F,
      col.names=c("Col1","Col2","Col3","Col4","Col5")) %>%
  kable_styling(latex_options = c("repeat_header")) %>%
  add_header_above(c("Waterbody history"=5),bold=T)`
Everything looks great, except the table is printed onto the bottom margin of each page, and ends up getting cut off. It looks like some rows are completely lost between the bottom of that page and the start of the next. I'm guessing the height of the table isn't adjusting for my custom margins (although the table width looks right) or the text that is printed above the table on page 1. Is there any way to handle this?

Thanks!

**Comment by haozhu233** [comment]
Hi, @alatzka, I do wish I could help but I'm not a LaTeX pro and this issue doesn't seem like a kableExtra related problem either. It was still there after I removed `kable_styling` and `add_header_above`. I think the TeX stackexchange(https://tex.stackexchange.com/) is a better place to ask this question.

**Comment by alatzka** [comment]
Yeah, it does seem like  TeX / longtable issue after reading a bit more. Thanks anyway!

**Comment by alatzka** [comment]
Just in case anyone else comes across this and is having the same issue, I did find a solution.

.Rmd Header: 

` ---
title: 
output:
  pdf_document: default
classoption: landscape
geometry: "left=0.4in,right=0.4in,top=0.3in,bottom=0.8in,headheight=1.5cm,includehead"
params:
  waterbody: NA
header-includes:
   \usepackage{graphicx}
   \usepackage{fancyhdr}
   \usepackage{eurosym}
   \usepackage{booktabs}
   \usepackage{array}
   \usepackage{multirow}
   \usepackage[table]{xcolor}
   \usepackage{wrapfig}
   \usepackage{float}
   \usepackage{colortbl}
   \usepackage{pdflscape}
   \pagestyle{fancy}
   \fancyhf{}
   \fancyhead[R]{\fontsize{18}{10} \selectfont My Title Here}
   \lhead{\includegraphics[width=2.8cm,resolution=200]{path/to/logo.png}}
   \rfoot{Page \thepage}
   \fancypagestyle{plain}{\pagestyle{fancy}}
   \usepackage{tabu}
   \usepackage{threeparttable}
   \usepackage{longtable}
---`

Kable/KableExtra:

`kable(data.frame,
      longtable=T,booktabs=T,row.names=F,
      col.names=c("Col1","Col2","Col3","Col4","Col5")) %>%
  kable_styling(latex_options = c("repeat_header","HOLD_position","scale_down"),
                position='float_left') %>%
  add_header_above(c("Waterbody History"=5),bold=T)`
