### ISSUE TITLE
format "latex" doesn't display on rmarkdown in RStudio

### ISSUE THREAD

**Issue by toms-coding** [haozhu233/kableExtra#651]
**Describe the bug**
When running chucks in an rmarkdown document in RStudio, no preview is rendered when using the format "latex". It will still work when the full pdf if knit. I notice reprex produces an error on the section of the code but that it now true in RStudio. It is not an impossible issue to work around, it just takes more time to generate pdfs all the time or to keep changing everything back and forward bwtween "latex" and "html"

**To Reproduce**
```
mtcars[1:10, 1:2] %>%
kbl(format = "latex", escape = F)
#> Error in mtcars[1:10, 1:2] %>% kbl(format = "latex", escape = F): could not find function "%>%"
```
Full markdown
````
---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
```

```{r}
mtcars[1:10, 1:2] %>%
kbl(format = "latex", escape = F)
```
````

**Comment by vincentarelbundock** [comment]
This is normal, because Rmarkdown documents in RStudio are previewed in HTML, not PDF. They don't run `pdflatex` everytime you change something (which would be tremendously costly). I don't see how this can be fixed within `kableExtra`, unfortunately.
