### ISSUE TITLE
kableExtra formatting lost in loop

### ISSUE THREAD

**Issue by StevenVB12** [haozhu233/kableExtra#656]
Dear Hao Zhu,

I'm using kableExtra to display tables with a for loop. When using the kable function (plus formatting functions) separately, it works fine, but when I use it in a loop it just prints the column names and row values line by line.

I have added results="asis", used print() and added a cat("\n") at the end, as suggested in other issue threads. However, this does not solve the problem as it does for the library(kable) function.

Many thanks for any help with this!

Best regards,

Steven

**Comment by vincentarelbundock** [comment]
This issue does not include a fully reproducible code example, and does not include a feature request. It has been here a long time and has received no answer. Therefore, I am closing this. Sorry!

You may have more chance on a website like StackOverflow.

Alternatively, you can try commenting in this thread again with a more detailed example.
