### ISSUE TITLE
Align column headings separately from column cells

### ISSUE THREAD

**Issue by eipi10** [haozhu233/kableExtra#66]
It doesn't look like it's possible to align column headings separately from column cells. For example, I'd like to be able to have the column heading centered, even if the data in the column cells is right-aligned for left-aligned. I'm writing to suggest this as a potential enhancement to `kableExtra`.

**Comment by haozhu233** [comment]
Hey, @eipi10, this is a very interesting feature and I can see it can be useful to many people. My instant feeling is that it can work well with the `row_spec(0, centering = T)` idea I proposed in #26. What do you think?

**Comment by eipi10** [comment]
Yes, I didn't notice that issue. Ideally, I'd like to be able to set alignments by cell in addition to by row or column, but an alignment argument to `row_spec` (and `column_spec`) would be very helpful. Instead of `centering =TRUE`, what about an `align` argument that can be set to `c`, `r`, or `l`, e.g., `row_spec(0, align="c")` and overrides the default row alignment? If you can do this with both the `row_spec` and `column_spec` functions, then you'd have to decide which function takes precedence (presumably the last function called) for the cell in which a row and column intersect.

**Comment by haozhu233** [comment]
I guess for html, the last function called takes precedence. For LaTeX, I'm not sure since column alignment is specified through the string after `\begin{tabular}` but row_spec is basically looping through that row and add things. I guess row_spec will win. :P

**Comment by haozhu233** [comment]
I just added this requested feature to the dev ver. Now you can use `row_spec(0, align = "c")` to align the header row differently with others. :)

**Comment by eipi10** [comment]
Thanks!

**Comment by myaseen208** [comment]
Very good feature.

**Comment by catwarner** [comment]
Hey, thanks for an awesome package.

Is it possible to align the row_spec like

`row_spec(0, align = "lcc")`

kind of like how you can align in `kbl(align = "llr")`? :)

**Comment by philipshirk** [comment]
> Hey, thanks for an awesome package.
> 
> Is it possible to align the row_spec like
> 
> `row_spec(0, align = "lcc")`
> 
> kind of like how you can align in `kbl(align = "llr")`? :)

I'm also looking for this functionality.
