### ISSUE TITLE
cannot save (LaTeX) table as image using kable_as_image()

### ISSUE THREAD

**Issue by VikrantDogra** [haozhu233/kableExtra#67]
Error Message: Error in open.connection (path, "wb") : cannot open the connection Calls: ... kable_as_image -> write_file-> open -> open.connection execution halted

While knitting an RMarkdown file with the following commands:

`library(knitr)
library(kableExtra)
dt <- mtcars[1:5, 1:6]
options(knitr.table.format = "latex")
kable_as_image(kable_input = kable(dt),filename = "abcd",file_format = 
"png",latex_header_includes = NULL, keep_pdf = FALSE)`

------------------

Working Directory: "C:/Users/xyz/Documents"

> sessionInfo()

R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_India.1252  LC_CTYPE=English_India.1252   
[3] LC_MONETARY=English_India.1252 LC_NUMERIC=C                  
[5] LC_TIME=English_India.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] kableExtra_0.5.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12         digest_0.6.12        rprojroot_1.2       
 [4] R6_2.2.2             backports_1.1.0      magrittr_1.5        
 [7] evaluate_0.10.1      httr_1.3.0           rlang_0.1.2         
[10] stringi_1.1.5        magick_1.3           xml2_1.1.1          
[13] rmarkdown_1.6.0.9004 tools_3.4.1          stringr_1.2.0       
[16] readr_1.1.1          hms_0.3              yaml_2.1.14         
[19] compiler_3.4.1       rvest_0.3.2          htmltools_0.3.6     
[22] knitr_1.17           tibble_1.3.3

**Comment by haozhu233** [comment]
Hi, @VikrantDogra, thanks again for moving this issue from Stackoverflow to github. 

I just made some adjusts to my code and should have solved this Windows problem. 

Once you downloaded the dev version using `devtools::install_github()`, you also need to install a software called ghostscript on your windows machine. https://www.ghostscript.com/

I also provided some documentations and an error message about ghostscript in this fix.

**Comment by VikrantDogra** [comment]
Hi @ haozhu233 works perfectly fine now. Thanks a lot.
Just a few additional comments for now:
1)	Stripes does not work
2)	For quite a few examples (described in your note “Create Awesome LaTeX Table with knitr::kable and kableExtra”), the tables in the saved image do not occupy 100% of image size. Problems with- stripes, hold position, font size, row spec, grouped columns/ rows, group rows via labelling, table footnotes, in-table markers. Have attached a sample output file.

Great to finally get an R package that directly creates tables as png. Will bother you later once I work more on your package.
![kableextra_04](https://user-images.githubusercontent.com/19929442/30480746-fa1fa782-9a38-11e7-9947-dbcd7b08bf30.png)

**Comment by haozhu233** [comment]
Hmm, I got a note from CRAN last night about changing the dependency on `magick` from imports to suggest. I'm going to make a fix today. Please note that you might need to load `magick` manually after this change. 

@VikrantDogra Yeah, this feature is quite "experimental" regarding its functionality and quality. Glad you like this idea. Feel free to report more issues here. ;)
