### ISSUE TITLE
group_rows limited by number of groups / number of rows?

### ISSUE THREAD

**Issue by jordanwatson** [haozhu233/kableExtra#68]
Hi. Maybe this isn't a bug but I think it might be...I seem to reach a point with group_rows where it maxes out on groups. Maybe it only works for the first page of a longtable? In the example below, I create an index of group headers (myindex). I have some arbitrary number of headers (9 here, spaced six rows apart). In group_rows, if I include 6 of these headers it works. If I include 7 it does not. In this example the headers end at the first page. In my actual example they work for the first two pages. Is there a limit on rows / headers? If so, maybe this could just be included in the documentation. If not, perhaps there is some other argument necessary?  

````{r setup, include=FALSE}
library(knitr)
library(kableExtra)
library(dplyr)
```

```{r cars,results='asis'}

myindex <- c(rep(6,9))
names(myindex) <- paste("MyHeader",1:9)

kable(bind_rows(mtcars,mtcars,mtcars),format='latex',booktabs=TRUE,linesep="",
      col.names=c("mpg","cyl","disp","hp","drat","wt","qsec","vs","am","gear","carb"),longtable=T,caption="This is my table caption") %>% 
    group_rows(index=myindex[1:6])
````

**Comment by haozhu233** [comment]
Hi, @jordanwatson, it does seem like a bug. I will look into it.

**Comment by haozhu233** [comment]
Hi, @jordanwatson, thank you for bringing this bug to my attention. Now this bug has been addressed in the latest dev version. :)
