### ISSUE TITLE
Continued on Next Page for longtable

### ISSUE THREAD

**Issue by MYaseen208** [haozhu233/kableExtra#69]
I am using `kableExtra` for `longtable` with the following code. 

    library(knitr)
    library(kableExtra)
    
    long_dt <- rbind(mtcars, mtcars)
    
    kable(
          long_dt, 
          format    = "latex", 
          longtable = T, 
          booktabs  = T, 
          caption   = "Longtable"
          ) %>%
    add_header_above(c(" ", "Group 1" = 5, "Group 2" = 6)) %>%
    kable_styling(latex_options = c("repeat_header"))

The output is

[![enter image description here][1]][1]

I wonder how to add text *(Continued on Next Page ...)* at the bottom of the table if it spans to next page. Any help will be highly appreciated. Thanks

  [1]: https://i.stack.imgur.com/9kW3j.png

**Comment by haozhu233** [comment]
Sorry for the delay. I have been super busy with my regular job recently. This is certainly a feature I can add. I personally feel like the lack of bottom line in this case is clear enough that this table is not ending but I can see the need. I will add an extra option (like the one allowing you to customized table caption on the next page) when I have time.

**Comment by haozhu233** [comment]
I added a new argument `repeat_header_continued` to control this feature. Default value is `FALSE` and you can set it to either `TRUE` or a customized string for your DIY need. If you set it to `TRUE`, it will put `(continued ...)` at the end of each page for the longtable.
