### ISSUE TITLE
Is there a way to reduce the size of the md knitted generated file on github_document output?

### ISSUE THREAD

**Issue by javierfs** [haozhu233/kableExtra#696]
I am having some problem with the size of the md knitted generated file (basically is too large for github to display, and when I show the preview locally it takes some time and it slows down Rstudio). The reason why the file has that large is using the kableExtra package to output some table inline plotting. Specifically using spec_hist, spec_boxplot, spec_plot which basically plots the distribution of variables inside of a table.

```
---
title: My title
output:
  github_document:
    fig_width: 8
    fig_height: 6
    dev: png
editor_options: 
  chunk_output_type: console
always_allow_html: true
---
```
I had to add  `always_allow_html: true` because otherwise it wouldn't preview

This is the code I use to display the table:
```
plot_tbl_distr <- function(df, col_name){
  df_metric <- df %>% filter(metric_val== col_name)
  val_list <- split(df_metric$values, df_metric$metric_user)
  
  inline_plot <- data.frame(percentile = c('max', 'p95', 'p75', 'p50', 'min'), 
                            box = "", 
                            hist = "",
                            points_same_scale = "",
                            points_free_scale = "")
  
  inline_plot %>%
    kbl(booktabs = TRUE) %>%
    kable_paper(full_width = FALSE) %>%
    column_spec(2, image = spec_boxplot(val_list)) %>%
    column_spec(3, image = spec_hist(val_list)) %>%
    column_spec(4, image = spec_plot(val_list, same_lim = TRUE, type = "p")) %>% 
    column_spec(5, image = spec_plot(val_list, same_lim = FALSE, type = "p")) 
}
```

```
col_name = c('metric1, 'metric1', 'metric3', 'metric4')
plot_tbl_distr(df_high_lvl_metrics, col_name[1])
```
<img width="589" alt="image" src="https://user-images.githubusercontent.com/13203962/159742475-04abe43b-3e20-4c56-bf2b-c762a36ba47e.png">

**Comment by dmurdoch** [comment]
kableExtra doesn't include anything to reduce the size.  I don't know if there are external tools, etc that could do it, or options when you produce the output.
