### ISSUE TITLE
"HOLD_position" fails for 4th level heading in bookdown::pdf_document2

### ISSUE THREAD

**Issue by cathblatter** [haozhu233/kableExtra#705]
**Describe the bug**
I'm not sure if this is a bug or just a LaTeX-behaviour, but I observed this: 
The option`kable_styling(latex_options = "HOLD_position")` is disregarded in a section with level-4 heading (####) when there is no text previous to the table, while it perfectly worked for level 3 headings (bookdown::pdf_document2). 

I can do several workarounds - at this point I am just curious if there is an explanation for this behaviour?

Thanks for your great package!

**To Reproduce**

````
---
title: "me"
output: 
  bookdown::pdf_document2:
    toc: true
date: '2022-04-21'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(kableExtra)
```

# Header 1

Text in section 1

## Header 2

Text in section 2

### Including Tables in Header 3 - works

With text before the table:

```{r one, echo=FALSE}
  kable(head(cars)) %>% 
  kable_styling(latex_options = "HOLD_position")
```

### Including Tables in Header 3 w/o text - works

```{r two, echo=FALSE}
  kable(head(cars)) %>% 
  kable_styling(latex_options = "HOLD_position")
```

#### Including Tables in Header 4 - works

With text the placement works: 

```{r three, echo=FALSE}
  kable(head(cars)) %>% 
  kable_styling(latex_options = "HOLD_position")
```


#### Including Tables in Header 4 w/o text - fails

```{r four, echo=FALSE}
  kable(head(cars)) %>% 
  kable_styling(latex_options = "HOLD_position")
```
````

**Output**

<img width="598" alt="Screenshot 2022-04-21 at 17 52 11" src="https://user-images.githubusercontent.com/24943957/164502521-0c3357f9-23c3-40dc-99d6-8b37b1211489.png">

Someone else asked a similar question recently on SO https://stackoverflow.com/questions/71312878/hold-position-argument-and-related-solutions-dont-work-with-4th-level-header

---

R version 4.1.3 (2022-03-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.3.1

kableExtra_1.3.4

**Comment by haozhu233** [comment]
This is more like a latex behavior. We are using the `H` option from the `float` latex package here. If it doesn't work, it doesn't work. 

I remember quite some people prefer against `subsubsubsection` (level-4 heading). That's probably one of the reasons.

**Comment by cathblatter** [comment]
thanks @haozhu233  for the reply and confirming my suspicions  about latex,
again - thanks for the great package!
