### ISSUE TITLE
Error in webshot::webshot(file_temp_html, file, ...) when using save_kable

### ISSUE THREAD

**Issue by hillaryle18** [haozhu233/kableExtra#707]
yesterday I was able to save my knitted tables as images for figures in my paper. However, sometime in the evening something went awry while downloading other packages and now I cannot execute the code and am getting this error:

"Could not load c:%5CUsers%5Clehi%5CAppData%5CLocal%5CTemp%5C1%5CRtmpKkDUDx%5Ctable_1A4e045152702b.html Error in webshot::webshot(file_temp_html, file, ...) : webshot.js returned failure value: 1"

5.stop("webshot.js returned failure value: ", res)

4.webshot::webshot(file_temp_html, file, ...)

3.save_kable_html(x, file, bs_theme, self_contained, extra_dependencies, density, ...)

2.save_kable(., file = "table_1A.png")

1.dt %>% kbl(caption = "Table 1: Pregnancy Data") %>% kable_classic(full_width = F, html_font = "Cambria") %>% save_kable(file = "table_1A.png")

Here is reproducible code:

```
library(knitr)
library(kableExtra)
library(tidyverse)
library(readxl)
dt <- mtcars[1:5, 1:6]
dt %>% 
  kbl(caption = "Table 1: Pregnancy Data") %>%
  kable_classic(full_width = F, html_font = "Cambria") %>% save_kable(file = "table_1A.png")
```

I have tried to update all the relevant R packages, I've tried clearing the temp files of junk, I've uninstalled and reinstalled R and Rstudio. I am completely stumped and would love some help.

![Screenshot 2022-05-03 121358](https://user-images.githubusercontent.com/104928151/166746562-73deb326-29ae-4ce4-9f39-b55407467bfa.png)

**Comment by haozhu233** [comment]
Hi @hillaryle18, I received another report on the same issue but I couldn't reproduce the behavior by myself. 

Have you reinstall phantomJS which is required by webshot? 

`webshot::install_phantomjs()`

**Comment by haozhu233** [comment]
phantomjs is a js library. 

Can you let me know the result of `webshot::webshot("https://www.google.com/")`

**Comment by hillaryle18** [comment]
That worked fine and it took this image and placed it in the correct folder.
![webshot](https://user-images.githubusercontent.com/104928151/166794700-91d9b8a0-7401-4436-beb7-187587f323df.png)

**Comment by haozhu233** [comment]
I see. So webshot updated 3 weeks ago with the following update:

https://github.com/wch/webshot/commit/b62f9ee67f89d2941109b5d0145900e53fa63bb3

It creates some issues on handling file paths on windows.

**Comment by hillaryle18** [comment]
I see that makes sense because I can find the html file it is looking for to take the image but I guess the code is having a hard time. Is there anyway I can move the html to the folder to the same folder and then take a webshot of it using a different code?

**Comment by hillaryle18** [comment]
That makes sense! Okay so to fix it I actually changed the output to save_kable(file = "table_1A.html") which spit out the figure in an html format in the folder and then did webshot::webshot("file:///C:/Users/lehi/Dropbox%20(OHSU)/EDOD%20Group/HL/Physiological_analysis/table_1A.html", file = "table_1A.png") to export it as a .png and it worked! It makes it 2 step process but I'm able to get the figure image and it's beautiful :) Thanks again Hao for the advice and developing such an awesome package :)
