### ISSUE TITLE
 virus in css lightable?

### ISSUE THREAD

**Issue by norcalbiostat** [haozhu233/kableExtra#718]
I know this isn't specifically with kableExtra directly, but with one of the css files that is being used in a file that i'm working on. Deleting it is only temporary, as when i render the file it comes back. Is this a known thing? Box is spamming my email hourly about this file

![virus_screenshot](https://user-images.githubusercontent.com/10426521/184186446-55b3fb2e-f23a-4463-ad02-399b67ebeeab.PNG)
.

**Comment by dmurdoch** [comment]
Not kableExtra related.
