### ISSUE TITLE
In collapse_rows align="top" does not align the text across the columns

### ISSUE THREAD

**Issue by dysonsphere-startmail** [haozhu233/kableExtra#719]
Using the sample code from the kableExtra documentation reproduces my problem:

```
collapse_rows_dt <- data.frame(C1 = c(rep("a", 10), rep("b", 5)),
C2 = c(rep("c", 7), rep("d", 3), rep("c", 2), rep("d", 3)),
C3 = 1:15,
C4 = sample(c(0,1), 15, replace = TRUE))
kbl(collapse_rows_dt, booktabs = T, align = "c") %>%
column_spec(1, bold=T) %>%
collapse_rows(columns = 1:2, latex_hline = "custom", custom_latex_hline = 1:2, valign = "top")
```

This almost works, so close...but the vertical alignment is not consistent across the columns. This makes it unreadable when the table runs over multiple pages.

Vertical alignment not consistent across columns:
![collapse_test](https://user-images.githubusercontent.com/22195888/184209965-bff9cd6c-3b78-4a28-af71-35ed6341747d.png)

valign= "bottom" works perfectly though:
![bottomWorks](https://user-images.githubusercontent.com/22195888/184210042-e120721b-68f8-4392-8cf6-bb7c84bb3338.png)

**Comment by AhmedKhaled945** [comment]
Hello, did you find a solution for this?
