### ISSUE TITLE
add a function to format caption

### ISSUE THREAD

**Issue by haozhu233** [haozhu233/kableExtra#72]
again...before I forget....

**Comment by jimingshuo** [comment]
I just find you have opened this issue for some time. I try to use add
caption {
    font-size: 160%;
    font-weight: light;
}
in the CSS <style> section, but it seems it has no effect at all, except the "font-weight:". I also try "font-size: 0.5em", "font-size: 4px", still has no effect.

I am really looking forward to this enhancement. 

Thanks,
