### ISSUE TITLE
Errors in Bookdown after updating R 4.3.0

### ISSUE THREAD

**Issue by selfaddicted** [haozhu233/kableExtra#750]
**Describe the bug**
Failed to load the pkg in book down environment
the error message is as below

Error: package or namespace load failed for 'kableExtra':
 .onLoad failed in loadNamespace() for 'kableExtra', details:
  call: !is.null(rmarkdown::metadata$output) && rmarkdown::metadata$output %in% 
  error: 'length = 2' in coercion to 'logical(1)'

**To Reproduce**
1. Create a bookdown project
2. Call `library(kableExtra)` in a Rmd file
3. Build the project

it's too simple to reproduce.
when I rolled back R to 4.2.3 and the error was gone.

**Comment by acebollada80** [comment]
I have the same problem. 
I have updated to R 4.2.3 and uninstall and  install the latest version of kableextra, with install.packages and with devtools and I had same message when I runned knit to word.

Any solution??

Thanks in advance

**Comment by oldiya** [comment]
Same issue here on R 4.3. Does downgrading to 4.2.3 help?

**Comment by oldiya** [comment]
I installed the patched version from @kupietz and it works, see[ his comment for more information  ](https://github.com/haozhu233/kableExtra/pull/751#issuecomment-1522887005)

**Comment by acebollada80** [comment]
I have noticed several issues with the new version of R that caused conflicts for me. 
Previously, I had the following line: 'options(OutDec = ",")' that I have removed.
In terms of the output format, I used to have the following header:

output:
pdf_document:
toc: yes
toc_depth: '6'
bookdown::pdf_document2:
toc: yes
toc_depth: '6'
word_document:
toc: yes
toc_depth: '6'
html_document:
toc: yes
toc_float: yes
toc_collapsed: yes
toc_depth: 6
number_sections: yes
theme: lumen

However, if I change it and leave only the following for the 'word_document' output format:

output:
word_document:
toc: yes
toc_depth: '6'
I was able to solve my conflicts with the new version of R. I hope this solution is helpful to other users who may be experiencing similar issues."

**Comment by acebollada80** [comment]
> I installed the patched version from @kupietz and it works, see[ his comment for more information ](https://github.com/haozhu233/kableExtra/pull/751#issuecomment-1522887005)

Could I do this? How can I installed the patched version?
Thanks in advance

**Comment by kjewell** [comment]
I got the same error knitting an existing .Rmd file to html after upgrading to 4.3.0

The dev version from @kupietz did not solve the problem, but deleting the following header lines from my file;
```
output:
  html_document: default
  pdf_document: default
```
avoided the error.

**Comment by kupietz** [comment]
> I got the same error knitting an existing .Rmd file to html after upgrading to 4.3.0
> 
> The dev version from @kupietz did not solve the problem, but deleting the following header lines from my file;
> 

Can you tell me the error message you got and have you restarted your R session after installing `kupietz/kableExtra`?

**Comment by rhurlin** [comment]
I don't think you really need to restart your R session. The following should do the trick:

```
detach(package:kableExtra)
library(kableExtra)
```

**Comment by kjewell** [comment]
Ok, ran into the same/similar issue again on another file, using the @kupietz dev version.

error: 

> Quitting from lines 8-10 (test_output.Rmd) 
> Error: package or namespace load failed for 'kableExtra':
>  .onLoad failed in loadNamespace() for 'kableExtra', details:
>   call: if (!is.null(rmarkdown::metadata$output) && names(rmarkdown::metadata$output)[1] %in% 
>   error: missing value where TRUE/FALSE needed
> Execution halted

Here, the difference seems to be that the output was defined using slightly different syntax: 
output: html_document

To Reproduce

    Create a markdown file with the following content:
`---
output: html_document
---

```{r setup, include=FALSE}
library(kableExtra)
```
`
    knit the file.

Deleting the 
'output: html_document'
line resolves the issue.

**Comment by kupietz** [comment]
> Ok, ran into the same/similar issue again on another file, using the @kupietz dev version.
> 
> error:
> 
> > Quitting from lines 8-10 (test_output.Rmd)
> > Error: package or namespace load failed for 'kableExtra':
> > .onLoad failed in loadNamespace() for 'kableExtra', details:
> > call: if (!is.null(rmarkdown::metadata$output) && names(rmarkdown::metadata$output)[1] %in%
> > error: missing value where TRUE/FALSE needed
> > Execution halted
> 
Thanks for the report! I've fixed the problem in kupietz/kableExtra and in PR #751 via c50a4ccfb6b2e9a5e5f413efd3d9c0f3c1ca18e2 .

**Comment by Felipe-Juan1** [comment]
Once I installed the patch from @kupietz, I had an issue with the `kable_styling` function, where the function is not found in the patched version once I try to knit the file. I've tried deleting the file outputs and restarting sessions when I apply these changes.

**Comment by go4ino** [comment]
I have a similar issue in r 4.3.1 when trying to knit a pdf / html / word document.

When I knit the document and leave out `library(kableExtra)`, it renders just fine. 

Does the switching to the dev version of the library fix this?


```
processing file: doc1.Rmd
                                                                                                            

Quitting from lines 37-138 [setup] (doc1.Rmd)
Error:
! package or namespace load failed for 'kableExtra':
 .onLoad failed in loadNamespace() for 'kableExtra', details:
  call: !is.null(rmarkdown::metadata$output) && rmarkdown::metadata$output %in% 
  error: 'length = 2' in coercion to 'logical(1)'
Backtrace:
 1. base::library(kableExtra)
 2. base::tryCatch(...)
 3. base (local) tryCatchList(expr, classes, parentenv, handlers)
 4. base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5. value[[3L]](cond)
Execution halted
```

**Comment by raffaem** [comment]
@kupietz Thanks, that worked!
@haozhu233 Is this still maintained?

**Comment by bshor** [comment]
I am using [Fedora COPR R archive](https://copr.fedorainfracloud.org/coprs/iucar/cran/). I have to install the Github version because the COPR version is still 1.3.4.
