### ISSUE TITLE
Compilation of beamer presentation fails when using column_spec

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [haozhu233/kableExtra#757]
When using `kableExtra::column_spec()` in a beamer presentation, LaTeX won't compile. (The symptoms are similar to bug report https://github.com/haozhu233/kableExtra/issues/721.)

Here's a MWE that I borrowed from [this SO question](https://stackoverflow.com/q/73611678), stored in `test_kabelExtra.Rmd`:

````
---
title: "Test document"
output: beamer_presentation # pdf_document, beamer_presentation
---

```{r setup}
library(dplyr)
```

```{r}
iris %>%
  knitr::kable(format="latex") %>%
  kableExtra::column_spec(2, width = "10em")
```
````

Here is the output:

````
output file: test_kableExtra.knit.md

! Undefined control sequence.
<argument> r|>{\raggedleft \arraybackslash 
                                           }p{10em}|r|r|l
l.32 ...{\raggedleft\arraybackslash}p{10em}|r|r|l}

Error: LaTeX failed to compile test_kableExtra.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See test_kableExtra.log for more info.
Execution halted
````

**Comment by allenbenz-doma** [comment]
Can be worked around by putting the following in the yaml config (where title: and output: are)
```
header-includes:
  - \usepackage{makecell}
```

**Comment by AlfonsoMuskedunder** [comment]
@allenbenz-doma Thank you!

As a side: Do you have any idea why the alternative

````
output:
  beamer_presentation:
    extra_dependencies: ["makecell"]
````

does not work? It throws the error

````
Error in (function (toc = FALSE, slide_level = NULL, number_sections = FALSE,  : 
  unused argument (extra_dependencies = "makecell")
Calls: <Anonymous> -> create_output_format -> do.call
Execution halted
````

**Comment by allenbenz-doma** [comment]
No idea, I'm completely unfamiliar with this. I looked at #721, added all the packages and then started removing them until identified which one was necessary.
