### ISSUE TITLE
add_footnote notation too inflexible

### ISSUE THREAD

**Issue by jpritikin** [haozhu233/kableExtra#76]
APA formatted tables have "three types of notes for tables: general, specific, and probability notes. All of them must be placed below the table in that order." [Here is link.](https://owl.english.purdue.edu/owl/resource/560/19/)

It seems like `add_footnote` is suitable for specific and probability notes. Can you add something like `add_footer` for the general note?

Or am I missing something?

**Comment by haozhu233** [comment]
Hi, @jpritikin, sorry for the late reply. I'm not so familiar with the APA format. Are you suggesting we should have several numbering systems including one unnumbered? Am I understanding it correctly?

If so, I guess it goes beyond what kableExtra currently is capable to do. `add_footnote` is actually the first function I put into this package long time ago and it was not so well designed. It's sort of difficult to fix it at this moment.  In the future when I have time to clean it up, I will definitely take this  suggestion into consideration.

**Comment by jpritikin** [comment]
> Are you suggesting we should have several numbering systems including one unnumbered?

Yes, and all together in a single table.

Here's how I worked around it for now,

```
str <- kable(...)
gsub('\\item [a]','', str, fixed=TRUE)

```

For this table, I didn't need other lists, just an unnumbered \emph{Note}. Besides this issue, I found your package very easy to work with and the output looks great. It's definitely a step up from `xtable`.

**Comment by haozhu233** [comment]
Awesome! I'm glad you worked out your own solution! I'm closing this issue for now and also adding a label to this issue so I can quickly find it out later.

**Comment by p-phillips** [comment]
Just want to record my support for this enhancement.  (I'm really enjoying the new functionality with kableExtra!).
