### ISSUE TITLE
`full_width() = F` does not work

### ISSUE THREAD

**Issue by petzi53** [haozhu233/kableExtra#761]
The option `full_width() = F` does not work for me. I am working with Quarto documents, but the same issue arises with R Markdown documents too.

```{r}
library(kableExtra)

dt <- mtcars[1:5, 1:3]

dt %>%
  kbl(caption = "Recreating booktabs style table") %>%
  kable_classic(full_width = F, html_font = "Cambria")
```
The above code chunk results in a correct inline output (a small centered table) but it uses the full width in the HTML document.

See the [screenshot at Imgur](https://imgur.com/a/vuHH2YC)

***
macOS Ventura 13.4.1
R version 4.3.1
RStudio: Version 2023.06.1+524
Quarto version: 1.4.232
kableExtra version: 1.3.4
knitr version: 1.43
pandoc version: 3.1.4

During the rendering process of the document to HTML I got the following message in the tab "Background Jobs":

pandoc 
  to: html
  output-file: Tests.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en

**Comment by dmurdoch** [comment]
I think this has been fixed (at least in the devel version).
