### ISSUE TITLE
kableExtra installation

### ISSUE THREAD

**Issue by jimegon** [haozhu233/kableExtra#763]
**Describe the bug**
I am using the latest version of R (Version 4.3.1). I am working on Rmd files and have tried to knit the file to either PDF or html file, but I get the following error:

Quitting from lines 617-619 [unnamed-chunk-41] 
Error:
! Package `kableExtra` required for this function to work.
  Please install it by running `install.packages(`kableExtra`)`.
Backtrace:
 1. modelsummary::modelsummary(...)
 2. modelsummary:::factory(...)
 3. modelsummary (local) factory_fun(...)
 4. insight::check_if_installed("kableExtra")
Execution halted

-------------------
I have tried installing "kableExtra" multiple times, but it keeps giving me the same error. 

**To Reproduce**
Think about using `reprex` to generate an example in R. 

```
# code to reproduce the bug.
```

If you need to attach the entire rmarkdown doc, try to use ```` to quote your entire doc.

````
---
title: "A reproducible example in rmarkdown"
output: html_document
---

```{r}
library(kableExtra)
```
````

**Comment by dmurdoch** [comment]
This looks like a problem with the install, not a problem in `kableExtra` per se.  A common problem is that packages are installed into a library different from the main one, and then when you try to knit something, R only uses the main library.  Symptoms of this are that `install.packages()` will give a message about failing to install in the main library.  The best solution is to run R as an admin during installs so they all go into the main library, but if you can't do that, use `.libPaths` (see its help page) in your document to tell R to look at the alternate location.
