### ISSUE TITLE
unexpected behavior when table cell ends with a latex space "\ "

### ISSUE THREAD

**Issue by mjsmith037** [haozhu233/kableExtra#765]
**Describe the bug**
When a table cell ends with an explicit space, specified in latex as "\ ", `kable` inappropriately prunes the space, resulting in erroneous latex code that cannot be compiled.

**To Reproduce**
``` r
library(kableExtra)
data.frame(x="\\ ") %>% kable(format="latex", escape=FALSE)
```

produces:

```
\begin{tabular}{l}
\hline
x\\
\hline
\\\
\hline
\end{tabular}
```

Note that line 5 of the output should be "\ \\" (with a space between the first and second backslashes).

When attempting to compile this with `save_kable`, either an erroneous `.pdf` is produced:

``` r
data.frame(x="\\ ") %>% kable(format="latex", escape=FALSE) %>% save_kable(file="test.pdf")
```
[test.pdf](https://github.com/haozhu233/kableExtra/files/12441192/test.pdf)

or, if also using `collapse_rows`, it either fails silently:

```r
data.frame(x=c('a', 'b'), y=c('A\\ ', 'B')) %>%
  kable(booktabs=TRUE, format="latex", escape=FALSE) %>%
  collapse_rows(1, latex_hline="major") %>%
  save_kable(file="test.pdf")
```

or, in some cases, produces an uninformative error:

```
Error in save_kable_latex(x, file, latex_header_includes, keep_tex, density) : 
  We hit an error when trying to use magick to read the generated PDF file. You may check your magick installation and try to use magick::image_read to read the PDF file manually. It's also possible that you didn't have ghostscript installed.
```

**Comment by dmurdoch** [comment]
That's a `kable()` error, not related to `kableExtra`.  The first example doesn't use `kableExtra` at all.
