### ISSUE TITLE
Knit to Word

### ISSUE THREAD

**Issue by mbcann01** [haozhu233/kableExtra#8]
Hello!
So far I love kableExtra for HTML tables. For me, it would be really useful to have features like add_indent available for knitting to Word documents as well. Do you plan to add support for knitting to Word documents in the future? Thanks!

**Comment by haozhu233** [comment]
Hi, @mbcann01, I'm glad you like this package. Very unfortunately, there is no way to pass "raw" table codes into Word. You can pass a word template file to pandoc through rmd but that's all you can do (you can check out this post http://rmarkdown.rstudio.com/articles_docx.html). However, if what you want to do is to `add_indent` to specific rows, I have a feeling that it is too much for that template file to handle.

**Comment by mbcann01** [comment]
@haozhu233 Bummer! Thanks for the response!
