### ISSUE TITLE
group_rows error: expecting a string

### ISSUE THREAD

**Issue by kylec** [haozhu233/kableExtra#80]
I 'm running your example in the documentation but got the following error.
```
kable(mtcars[1:10, 1:6], format="html", caption = "Group Rows") %>%
  kable_styling("striped", full_width = F) %>%
  group_rows("Group 1", 4, 7) %>%
  group_rows("Group 2", 8, 10)
```
Error in node_set_attr(x$node, name = attr, nsMap = ns, value) : 
  expecting a string

My software versions
kableExtra_0.5.2    
knitr_1.17
tidyr_0.7.1 
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.9.5 (Mavericks)

**Comment by haozhu233** [comment]
Hi, @kylec, the code you posted works for me. Can you also tell me your `xml2` and `stringr` version? Maybe a full `sessionInfo()` will be helpful.
