### ISSUE TITLE
RTL arabic script with `full_witdh`or `scale_down`

### ISSUE THREAD

**Issue by PhillRob** [haozhu233/kableExtra#81]
Works well with `latex_options = c("striped"), but attempting to scale_down or reduce width with arabic text returns the polyglossia error `Package polyglossia Error: The current roman font does not contain the Arabic`. Cannot get the table to fit the page in right to left arabic.

**Comment by haozhu233** [comment]
I don't think I have ever touched any font settings here. scale_down is using the `graphix`'s `resizebox`. Striped color is just using `rowcolor`. Is that related? My current assumption is that if there is a bug, that's a bug in those latex packages.
