### ISSUE TITLE
cell_spec escaping for html does not work after update to 1.4.0

### ISSUE THREAD

**Issue by zahlenzauber** [haozhu233/kableExtra#811]
**Describe the bug**

**Describe the bug**
There is an error in my system after the update to 1.4.0: Rendering text to html gives the html-code even when escape=FALSE in kable(). For version 1.3.4 everything was fine. Is this reproducible?

Code from: 
https://stackoverflow.com/questions/55582678/rmarkdown-formattable-styling-from-kableextra-renders-html-code-not-formatted

```
# code to reproduce the bug.
library("kableExtra")
library("tidyverse")

mtcars %>% 
  rownames_to_column('car') %>% 
  select(car, mpg, disp, hp, wt) %>% 
  mutate(wt = ifelse(wt < 2, 
                     kableExtra::cell_spec(wt, color = 'red', bold = TRUE), 
                     wt)) %>% 
  kableExtra::kable(escape = F) %>% 
  kableExtra::kable_styling()

```

**Comment by dmurdoch** [comment]
And of course it also works if you use `kableExtra::kbl` instead of `kableExtra::kable`.  In that case you don't need the `format = "html"` specification.

**Comment by haozhu233** [comment]
Yeah, we recently changed the way how kableExtra does for auto-formatting. In most cases it should feel the same but here is a case we missed. And yeah, the recommended solution is to change from `kable` to `kbl` or set the format option manually. I know it probably has caused some breaking changes to existing codes. Sorry for the inconvenience for everyone who gets impacted.

**Comment by zahlenzauber** [comment]
Thank you very much for the concrete help. I am very happy that you share your knowledge and your time with me. kableExtra has already enabled me to create many beautiful tables and the problem I described has been solved by your suggestions.
