### ISSUE TITLE
`row_spec` arguments `hline_after` and `extra_latex_after` inserting space between rows in package version 1.4.0

### ISSUE THREAD

**Issue by k96nb01** [haozhu233/kableExtra#815]
**Describe the bug**
The `row_spec` arguments to introduce lines in a table now also insert space in version 1.4.0

```
library(kableExtra)

kbl(mtcars[1:5, 1:5], "latex", booktabs = TRUE) %>% row_spec(2, extra_latex_after = "\\cline{2-6}") %>% row_spec(4, hline_after = TRUE)
```
Output version 1.3.4:

<img width="271" alt="image" src="https://github.com/haozhu233/kableExtra/assets/83467161/d12db463-4c78-4587-b215-44e633a35999">

Output version 1.4.0: 

<img width="268" alt="image" src="https://github.com/haozhu233/kableExtra/assets/83467161/2b8f8154-22e1-420e-9ae4-db07c481981e">

**Comment by dmurdoch** [comment]
The problem is that the output Latex looks like this:
```
\begin{tabular}[t]{lrrrrr}
\toprule
  & mpg & cyl & disp & hp & drat\\
\midrule
Mazda RX4 & 21.0 & 6 & 160 & 110 & 3.90\\
Mazda RX4 Wag & 21.0 & 6 & 160 & 110 & 3.90\\
\cline{2-6}\\
Datsun 710 & 22.8 & 4 & 108 & 93 & 3.85\\
Hornet 4 Drive & 21.4 & 6 & 258 & 110 & 3.08\\
\midrule\\
Hornet Sportabout & 18.7 & 8 & 360 & 175 & 3.15\\
\bottomrule
\end{tabular}
```
Those `\\` line breaks in `\cline{2-6}\\` and `\midrule\\` shouldn't be there, and weren't there in 1.3.4.
