### ISSUE TITLE
! LaTeX Error: File `kableExtra.sty' not found.

### ISSUE THREAD

**Issue by bsshults** [haozhu233/kableExtra#82]
Hi. I have loaded the kableExtra Package and have run into this error Knitting to PDF in RStudio.  Any ideas? Thanks

**Comment by haozhu233** [comment]
I have never defined such a file in this package......

**Comment by bsshults** [comment]
Hi. Thank you for the quick response. I've substituted your "awesome_table_in pdf.R" code into my markdown file and do not get the same error. The file Knits into a pdf  without errors. I'll dig deeper into my coding. Thanks Again for your help!
