### ISSUE TITLE
Add Borders in Align?

### ISSUE THREAD

**Issue by masterofzion** [haozhu233/kableExtra#825]
In the past, I've been able to use the "|" character to add a border to a column in kable call.  Now I'm getting errors that 'align'must be a character vector of possible values 'l', 'r', and 'c'.

I'm using PDF output, and this has worked numerous times in the past?

Repo: 
data %>% 
  ungroup() %>% 
  mutate_all(~as.character(.)) %>%
  kable(.,
     col.names = c("One", "Two", "Three", Four", "Five", "Six"),
     align = c("|l", "c", "c", "c", "c", "c|"))

**Comment by masterofzion** [comment]
I may have solved it.  I was missing the "format = 'latex'" argument.  Sorry!  Not sure If I should close this or not?

**Comment by dmurdoch** [comment]
Yes, that would be the issue.  I'll close.

**Comment by masterofzion** [comment]
Thank you!
