### ISSUE TITLE
Table does not show up with content in html, only lines (sequential kable tables mystery)

### ISSUE THREAD

**Issue by gklarenberg** [haozhu233/kableExtra#826]
I started having issues with creating sequential tables and I thought it might have to do with issue #561 and the recent update - but going back to version 1.3.4 did not solve anything. I started having this problem earlier this year (Jan 2024), meaning the tables looked fine before. After moving things are around and updating packages I started running into issues. 
I am using `kabelExtra` to create tables in an html document created with Rmarkdown. For some reason, one of my tables looks fine inline when I run the chunk in RStudio, but after knitting it only shows up as grey lines - no content.
Even stranger is that when I tried to make a reprex, it came out fine in the html. So then I reckoned there is something in the (very large) original RMarkdown document that is messing something up. And sure enough, when I moved the chunk before another chunk that also creates a (complicated) kable table, it showed up fine. However, commenting out this chunk with `eval = FALSE` still did nothing for the table after it. I feel like I should be able to find out what the problem is, but I have been working on this for hours and hours now and am still no closer to solving it.

The code is on github: https://github.com/GTMNERR-Science-Transfer/Survey-results/tree/main/9_FINAL_REPORT, file survey_results_Aug2023.Rmd. 
**Chunk 14 renders the table properly. Chunk 15 is the complicated table with colors. Chunk 16 is the same code as chunk 14 but only shows the grey lines and no content in the html (both work fine in-line in RStudio). So I reckoned chunk 15 is messing something up, but setting `eval = FALSE` does not change the output for chunk 16. Chunk 14 works, but it is not where it should be in the document, chunk 16 is in the correct place.**

Aside from tidyverse code for data cleaning, the code for the table in chunk 14 and 16 is:
```
txt_data_yes_YD6 %>%
  kbl(col.names = c("", ""), escape = FALSE) %>%
  remove_column(2) %>%
  kable_minimal("striped", font_size = 12, full_width = FALSE) %>%
  pack_rows(index = index_table)
```
and the code for the table in chunk 15 is:
```
yes_data_table %>%
  rename(Question = q_text) %>%
  ungroup() %>%
  select(-main) %>%
  kbl(escape = FALSE) %>% 
  kable_minimal("striped") %>%
  pack_rows(index = tbl_headers)
```
This table has colors assigned to cells based on their values.

All chunks have the same settings: `echo = FALSE, warning = FALSE, message = FALSE`.
There are no errors and no messages - not when I run the chunks and not when I knit (I specifically checked).

Any pointers, hints, thoughts would be appreciated, because I am completely stumped with what is going on. I tend to be pretty good at troubleshooting, but I have exhausted my options. 
I also looked at the html code, but could not find what the issue is (but granted, I am not an html expert).

If this is of any help, this is what the html looks like for the correct table:
```
<table class=" lightable-minimal lightable-striped" style="font-size: 12px; font-family: &quot;Trebuchet MS&quot;, verdana, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
</tr>
</thead>
<tbody>
<tr grouplength="2">
<td colspan="1" style="border-bottom: 1px solid;">
<strong>Water quality information (including nutrients and
algae)</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Personal interest
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Vegetation management on lake
</td>
</tr>
<tr grouplength="2">
<td colspan="1" style="border-bottom: 1px solid;">
<strong>Water level information (tides, Guana lake, river)</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Guana Dam management
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
I would access it more if I knew how to get to the data
</td>
</tr>
<tr grouplength="2">
<td colspan="1" style="border-bottom: 1px solid;">
<strong>Information on vegetation (salt marsh or uplands)</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Monitoring of invasive plant species sites for re-ocurrence / growth
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Personal use, plus is helpful during some of the volunteer programs
</td>
</tr>
<tr grouplength="2">
<td colspan="1" style="border-bottom: 1px solid;">
<strong>Weather information</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Recreation
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Prescribed fire weather forecasts
</td>
</tr>
<tr grouplength="1">
<td colspan="1" style="border-bottom: 1px solid;">
<strong>Reserve or trail closures</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Leisure
</td>
</tr>
<tr grouplength="1">
<td colspan="1" style="border-bottom: 1px solid;">
<strong>Information on terrestrial animals</strong>
</td>
</tr>
<tr>
<td style="text-align:left;padding-left: 2em;" indentlevel="1">
Personal interest; useful in some of my volunteer activities
</td>
</tr>
</tbody>
</table>
```
And this is what it looks like for the empty table. Weirdly enough it is showing some text ("In terms of usage of data, respondents added the following under “Other”:" at the beginning, and "In summary, the three usages mentioned here most are personal use, volunteer activities, and management purposes (vegetation / invasive plants, prescribed fire)." at the end) as part of the table. While in the RMarkdown document they are not part of the code chunk, it's markdown text.
```
<table style="width:79%;">
<colgroup>
<col width="79%" />
</colgroup>
<tbody>
<tr class="odd">
<td><strong>In terms of usage of data, respondents added the following
under “Other”:</strong></td>
</tr>
<tr class="even">
<td></td>
</tr>
<tr class="odd">
<td></td>
</tr>
<tr class="even">
<td></td>
</tr>
<tr class="odd">
<td></td>
</tr>
<tr class="even">
<td></td>
</tr>
<tr class="odd">
<td></td>
</tr>
<tr class="even">
<td></td>
</tr>
<tr class="odd">
<td></td>
</tr>
<tr class="even">
<td></td>
</tr>
<tr class="odd">
<td></td>
</tr>
<tr class="even">
<td></td>
</tr>
<tr class="odd">
<td></td>
</tr>
<tr class="even">
<td>In summary, the three usages mentioned here most are personal use,
volunteer activities, and management purposes (vegetation / invasive
plants, prescribed fire).</td>
</tr>
</tbody>
</table>
```

**Comment by haozhu233** [comment]
Hi, sorry for the delay. Yeah, my guess is that it's related to changes in #561. I will look into this later today.

**Comment by gklarenberg** [comment]
As an FYI: I use `renv` and have set it up in such a way that the Rmarkdown file uses version 1.3.4 again. However, this kept giving the same issue.

However, I just got it working - I honestly have no idea what the mechanism here is, but this appeared to be the issue: the "line" I created in the markdown section between the two tables... I use `--------------------------------------------------------` to create a grey line between sections, and the following did **not** work:

```
CHUNK 15 with complicated table

--------------------------------------------------------
**In terms of usage of data, respondents added the following under "Other":**

CHUNK 16 with table with text (the "problematic" table)
```
However, this, adding a return/empty line between the line and text, **did** work:
```
CHUNK 15 with complicated table

--------------------------------------------------------

**In terms of usage of data, respondents added the following under "Other":**

CHUNK 16 with table with text (the "problematic" table)
```

Who would have thought...? So TL;DR it's not an issue with the new version of `kabelExtra` as far as I can tell.
