### ISSUE TITLE
Double "Table" in caption

### ISSUE THREAD

**Issue by EricMarcon** [haozhu233/kableExtra#831]
`kable_styling()` makes "Table" appear twice in captions when knitted by bookdown to HTML with kableExtra v. 1.4.0. 
This was not the case with v. 1.3.

This is a MWE of .Rmd file:
````
---
title: "Double Table"
output:
  bookdown::html_document2
---

```{r}
cars |>
  knitr::kable(caption = "Cars data") |>
  kableExtra::kable_styling()
```
````

The caption obtained in the HTML output is "**Table 1: Table 2: Cars data**". This does not happen when the output format is `bookdown::pdf_document2`.
Removing `kable_styling()` from the pipeline solves the issue.

Thanks for your great package.

**Comment by dmurdoch** [comment]
That happens when you use `knitr::kable` without specifying the format, because `kable` produces a markdown table, and `kable_styling` can't recognize the existing label in it.  Workarounds are to specify `format = "html"` in the call to `kable`, or use `kableExtra::kbl()` instead.  Then things are fine.

**Comment by dmurdoch** [comment]
The reason `kable_styling` has trouble here is that it's looking for a caption using the format that `html_document` produces, but `bookdown::html_document2` produces captions in a different format, since it includes table numbers.

**Comment by NewGraphEnvironment** [comment]
I just dealt with this same double table in the captions of bookdown reports and was able to get around it by specifying param `label = NA` within the `knitr::kable()` function.
