### ISSUE TITLE
`cell_spec(..., italic = TRUE)` gives incorrect format for PDF table

### ISSUE THREAD

**Issue by marklhc** [haozhu233/kableExtra#834]
**Describe the bug**
When using `cell_spec(..., italic = TRUE)` with PDF output, the resulting table is a markdown table with LaTeX format, and is not rendered properly. I first reported this in [this quarto issue](https://github.com/quarto-dev/quarto-cli/issues/9283). I've attached the Rmd source code, but the same happens with `qmd` output (with `knitr`). 

**To Reproduce**

````
---
output: pdf_document
---

```{r}
library(kableExtra)
```

```{r}
tbl1 <- head(iris)
tbl1[1, 1] <- cell_spec(tbl1[1, 1], bold = TRUE)
tbl1  # `\\textbf{}` is added
knitr::kable(tbl1) # format is fine
```

```{r}
tbl2 <- head(iris)
tbl2[1, 1] <- cell_spec(tbl2[1, 1], italic = TRUE)
tbl2  # `\\em{}` is added
knitr::kable(tbl2)  # format is off
```
````

This is the resulting table:

![image](https://github.com/haozhu233/kableExtra/assets/6175332/3d98a886-195b-4a12-8fc0-e24cd3b0f50b)

**Comment by dmurdoch** [comment]
You should be using `kbl(tbl2, escape=FALSE)`.  You probably also want to add `booktabs=TRUE`, and maybe some of the other options listed on `?kbl`.

**Comment by marklhc** [comment]
Thank you for the suggestion, but that does not solve the problem, as in the following picture:

![image](https://github.com/haozhu233/kableExtra/assets/6175332/6df34836-ddb6-4a1a-a17c-03dff8b8582e)

**Comment by dmurdoch** [comment]
You didn't use `kbl()`.

**Comment by marklhc** [comment]
Oh sorry for missing that. Thank you and that works.
