### ISSUE TITLE
HTML escape = FALSE broken since 1.4.0 unless format explicitly declared

### ISSUE THREAD

**Issue by slodge** [haozhu233/kableExtra#842]
**Describe the bug**
Since upgrading 1.4 we've seen our HTML tables ignoring the `escape` parameter.

To fix this we need to explicitly add `format = 'html' `

**To Reproduce**

```
# just a tibble
t <- tibble(A = 1:10) |> mutate(B = if_else(A > 5, paste0('<b>', A, '</b>'), paste0('Num:', A))) 

# this table renders HTML with `<b>` visible in the output
knitr::kable(t, escape = FALSE) |>  kable_styling()

# this table renders HTML with bold text in the output
knitr::kable(t, escape = F, format='html') |>  kable_styling()
```

**Comment by dmurdoch** [comment]
You should use `kableExtra::kbl()` instead of `knitr::kable()`.  It does a better job of setting the default format.

**Comment by slodge** [comment]
Thanks - I was mainly posting here to make others aware of this change in kableExtra functioanlity - hopefully they'll see this recommended `kbl` workaround too :+1:
