### ISSUE TITLE
latex_options creates second table label in distilled output

### ISSUE THREAD

**Issue by CosmicOutlaw** [haozhu233/kableExtra#845]
**Describe the bug**
```
languages_top15 %>% 
  kable(caption = "Top 15 Programming Languages") %>% 
  kable_styling(latex_options = "HOLD_position")
```
This will create a label Table 1: Table 2: Top 15 Programming Languages. While:
```
languages_top15 %>% 
  kable(caption = "Top 15 Programming Languages")
```
will render into Table 1: Top 15 Programming Languages.

**Impact**
Renders kable_styling or latex_options useless when rendering into distilled output.

**Comment by dmurdoch** [comment]
Can you post a reproducible example, using `kbl()` instead of `kable()`?  There are lots of possible ways to wrap what you've written, and the first one I tried didn't show the issue you described.  (You should almost always use `kbl()` instead of `kable()` with `kableExtra` recent versions).

**Comment by dmurdoch** [comment]
They choose the default format differently.  `kable()` usually outputs markdown if you don't specify otherwise; `kbl()` chooses HTML or LaTeX.  It also documents some hidden arguments for `kable()`.
