### ISSUE TITLE
Empty Latex Table

### ISSUE THREAD

**Issue by nmwitzig** [haozhu233/kableExtra#848]
Hi!

If I do:

```{r}
kbl(mtcars[1:8, 1:4], booktabs = T, linesep = "") %>% kable_styling(latex_options = "striped", stripe_index = c(1,2, 5:6)) %>%
  save_kable(file = "test.tex")
```

the results latex file is empty. I am pretty sure I used to do things like this all the time, so I am curious what could fix this issue.

Thank you!

**Comment by dmurdoch** [comment]
The `kbl()` function was not told that you want LaTeX output, and it guessed HTML instead.  Just add `format = "latex"` and it will work.
