### ISSUE TITLE
use of \ref in add_footnote doesn't appear to work

### ISSUE THREAD

**Issue by p-phillips** [haozhu233/kableExtra#85]
I'm trying to refer to another table in the footnote of a kableExtra table.

```
kable(results, format="latex",booktabs = T) %>%
kable_styling(latex_options=c("hold_position")) %>%
	add_footnote(c("Length positions refer to the distance from the sole of the foot as shown in Table  \ref{tab1}"),notation = "alphabet")
```
But the output I get is:

```
a Length positions refer to the distance from the sole of the foot as
shown in Table ef{tab1}
```
Doubling up the backslash doesn't help either.

I can reference the table outside of kableExtra with \ref{tab1}, so the labelling is working OK.

**Comment by haozhu233** [comment]
I think adding `escape = FALSE` in add_footnote will solve this issue. Could you try it out?

**Comment by p-phillips** [comment]
That works.  Thanks.
 (Couldn't see it in the options for add_footnote.)
