### ISSUE TITLE
kableExtra output not displaying p values from modelsummary

### ISSUE THREAD

**Issue by michaelherndon97** [haozhu233/kableExtra#855]
When I create a table using modelsummary and specify that I want the output as a kableExtra object, the labels specifying p value levels disappear. Instead, it gets cut off after "+ p". I think the "<" symbol is tripping it up. 

**To Reproduce**
library(broom)
data(mtcars)

# Run a linear regression model
model <- lm(mpg ~ wt + hp, data = mtcars)

# Create a summary table using modelsummary
modelsummary(model, output = "kableExtra", stars = TRUE, escape = TRUE) 

![image](https://github.com/user-attachments/assets/7ef5e4a0-3894-483b-bd93-a6a8a1b0c648)

**Comment by dmurdoch** [comment]
Isn't this a `modelsummary` issue, rather than a `kableExtra` issue?

**Comment by dmurdoch** [comment]
Yes, it's a `modelsummary` bug, here:  https://github.com/vincentarelbundock/modelsummary/blob/3c60e219b4a6eb741568354dc97944585c6e1ad6/R/factory_kableExtra.R#L155 .  It should have `escape` set to `TRUE`.
