### ISSUE TITLE
 `latex_table_env = "tabularx"` not working

### ISSUE THREAD

**Issue by thmschk** [haozhu233/kableExtra#856]
When I add `latex_table_env = "tabularx",...`  the LaTeX code produces e.g.

```
\begin{tabularx}{lXXX}
...
```

so, the 2nd argument {\textwidth} is missing. Do you have any hint how to overcome this?

Originally posted by @thmschk in https://github.com/haozhu233/kableExtra/issues/53#issuecomment-2208474067_

**Comment by dmurdoch** [comment]
@thmschk : You can (ab)use the valign argument:
```
kbl(mtcars, format="latex", tabular = "tabularx", valign="{\\textwidth}")
```

**Comment by thmschk** [comment]
perfect, thx.
