### ISSUE TITLE
Error using save_kable when using library kableExtra to create a table in R Quarto

### ISSUE THREAD

**Issue by onecare-business-intelligence** [haozhu233/kableExtra#859]
I would like to save a table generated with kableExtra as a PNG file in a quarto report. I'm using the example provided in the help file of save_kable
```
kable(mtcars[1:5, ], "html") %>%
  kable_styling("striped") %>%
  row_spec(1, color = "red") %>%
  save_kable('test.png')
```
And receive the following error

Error: rsession-utf8.exe: GeometryDoesNotContainImage `C:\test.png' @ warning/attribute.c/GetImageBoundingBox/534

I'm using R version 4.4.0 (2024-04-24 ucrt) in RStudio with the following libraries:

kableextra 1.4
chromote 0.3.1
webshot 0.5.5
webshot2 0.1.1

Windows 11.

**Comment by dmurdoch** [comment]
This question was also posted on StackOverflow.  You should mention that you were given a workaround there:  https://stackoverflow.com/a/78977096.

**Comment by dmurdoch** [comment]
Does it work if you use `kbl()` instead of `kable()` on the first line?  The help page should be updated to do that.

**Comment by onecare-business-intelligence** [comment]
> kbl(mtcars[1:5, ], "html") %>%
> kable_styling("striped") %>%
> row_spec(1, color = "red") %>%
>  save_kable('test.png')

Returns the same error as when I use kable().  

Error: rsession-utf8.exe: GeometryDoesNotContainImage

**Comment by dmurdoch** [comment]
Thanks for the test.  I don't see the issue on a Mac, using Quarto or RMarkdown.  I'm using the same versions of those packages as you.  The version of Chrome is probably relevant because chromote uses it; I'm using Google Chrome 128.0.6613.137 .

**Comment by onecare-business-intelligence** [comment]
Have updated to Chrome  Version 128.0.6613.138 (Official Build) (64-bit) and re-run the code on Windows 11 in Quarto and error remains.  Error: rsession-utf8.exe: GeometryDoesNotContainImage

**Comment by dmurdoch** [comment]
Actually "rsession-utf8.exe" is part of RStudio or maybe Quarto.  So this looks like an RStudio issue, not a `kableExtra` issue.
