### ISSUE TITLE
Error in escape argument

### ISSUE THREAD

**Issue by selesnow** [haozhu233/kableExtra#864]
**Describe the bug**
I am used escape argument in kable() function in kableExtra 1.3.4 version. But after i updated for kableExtra version 1.4.0 this argument not work.

**To Reproduce**

Example
```r
library(kableExtra)

df <- data.frame(PU = '<a href="https://example.com">Example</a>', 
                 date = '01.09.2024', 
                 period = '01.09.2024 - 30.09.2024')

df_html <- kable(df, escape = F) %>%
  kable_styling(bootstrap_options = c("striped", "bordered"))
```

Result in kableExtra 1.3.4

![](http://img.netpeak.ua/alsey/INIZ7R.png)

Result in 1.4.0
![](http://img.netpeak.ua/alsey/INJ1H4.png)

Argument escape not works.

```
# code to reproduce the bug.
```

```r
library(kableExtra)

df <- data.frame(PU = '<a href="https://example.com">Example</a>', 
                 date = '01.09.2024', 
                 period = '01.09.2024 - 30.09.2024')

df_html <- kable(df, escape = F) %>%
  kable_styling(bootstrap_options = c("striped", "bordered"))
```

**Comment by dmurdoch** [comment]
Don't use `kable()`, use `kbl()`.  Then your example is fine.

**Comment by selesnow** [comment]
Oh, thanks!
