### ISSUE TITLE
Feature Request: ability to have footnotes preceded by Note:

### ISSUE THREAD

**Issue by p-phillips** [haozhu233/kableExtra#87]
The Chicago Manual of Style recommends the use of superscript numbers, letters or symbols for notes which are specific to a particular part of the table.

For general notes it says "_A note applying to the table as a whole follows any source note and is introduced by the word Note, in italics and followed by a colon, though other treatments are acceptable if consistently followed._"

Could add_footnote have another notation option (notation = "note") which prints Note: (in italics) and then the label ?  (Or is there another way to achieve this ?)  Another option to get closer to CMOS layout would be notation="source", which prints Source: (in italics) and then the label.

This is what the CMOS uses as its table example:

[chi-cms2017-fig-3-11.pdf](https://github.com/haozhu233/kableExtra/files/1412736/chi-cms2017-fig-3-11.pdf)

**Comment by WillemSleegers** [comment]
This appears to be implemented now; but in a way that makes it impossible to NOT have it say 'Note:'. I personally would like the option to display that word or not.

**Comment by p-phillips** [comment]
I don't think this has been implemented - just had a look at Hao's code for
add_footnote and only the three options (alphabet etc) are available.

Willem - can you explain how you got this to work ?

Pete

**Comment by haozhu233** [comment]
@p-phillips @WillemSleegers @jpritikin I added a new function called `footnote` which is intended to replace the `add_footnote`. It allows you to have multiple sets of footnotes with different notation systems. You can also specify titles for each section, change the order or choose to squeeze footnotes into chunks. Feel free to download the dev ver and check it out. For now, you can use the function help page for reference. I will add it to the package vignette later. 

Hao

**Comment by jpritikin** [comment]
Wow, that sounds great. I'll try it out for the next manuscript.

**Comment by p-phillips** [comment]
Terrific.  Thank you for implementing that.

A related question  - is there any way to force footnotes which are wider than the table to wrap ?  (threewaytable doesn't work for the footnote function).

**Comment by haozhu233** [comment]
It shouldn't be too difficult to add threeparttable to `footnote`. I can try to add it later.

**Comment by haozhu233** [comment]
@p-phillips threeparttable added now.

**Comment by p-phillips** [comment]
Beautiful.  Works perfectly.   Once again, thank you.

**Comment by jjchern** [comment]
@haozhu233 Thanks for adding the feature. I might be wrong, but it seems for threeparttable, we are still not able to have footnotes preceded by "Note: " (and in *italics*).

In particular, right now the threepartable function (https://github.com/haozhu233/kableExtra/blob/master/R/footnote.R#L304-L323) inserts `\item` and `\textbf` directly.

```R
latex_tfoot_maker_tpt_ <- function(ft_contents, ft_title, ft_chunk, ncol) {
  footnote_text <- apply(ft_contents, 1, function(x) {
    if (x[1] == "") {
      paste0('\\\\item ', x[2])
    } else {
      paste0('\\\\item[', x[1], '] ', x[2])
    }
  })
  if (ft_title != "") {
    title_text <- paste0('\\\\item \\\\textbf{', ft_title, '} ')
    footnote_text <- c(title_text, footnote_text)
  }
  footnote_text <- paste0(footnote_text, collapse = "\n")
  # if (!ft_chunk) {
  #   footnote_text <- paste0(footnote_text, collapse = "\n")
  # } else {
  #   footnote_text <- paste0(footnote_text, collapse = " ")
  # }
  return(footnote_text)
}
```

**Comment by haozhu233** [comment]
@jjchern Do you mind to create a new issue and let me know what exactly are you trying to make?
