### ISSUE TITLE
Bracket in kbl() <align>  argument causes GREPL error "scale_down" option

### ISSUE THREAD

**Issue by jlambvo** [haozhu233/kableExtra#876]
I have a table using a custom alignment that requires a width parameter, and I am attempting to scale the resulting table to fit, i.e.:

`kbl(... 
        align =  c("C{2cm}")) |> 
kable_styling( latex_options = "scale_down")`

However, I am getting an error from sub(...) in `kableExtra:::styling_latex_scale` because of the "{}":

` invalid regular expression ... Invalid contents of {}`

Using escape characters such as `align =  c("C\\{2cm\\}"))` does not avoid the issue. I also tried fixInNamespace() to set "fixed = T" in the GREPL call which avoids the issue but of course does not insert the resize code. 

Any fix or workaround for this? Thanks!

**Comment by dmurdoch** [comment]
Could you please include a full document illustrating the issue?  (It shouldn't be your real document, just a minimal one that gives the error you saw.)

**Comment by jlambvo** [comment]
Here's a reproducible example:

```
kbl(x = mtcars,
    format = "latex",
    align = Reduce(paste0, c("C{2cm}",rep("C{2cm}",length(mtcars))))) %>%
  kable_styling(latex_options = "scale_down")
```

```
>> Error in sub(table_info$begin_tabular, paste0("\\\\resizebox{\\\\ifdim\\\\width\\",  : 
  invalid regular expression '\\begin\{tabular\}\[t\]{lC{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C{2cm}C', reason 'Invalid contents of {}'
```

**Comment by dmurdoch** [comment]
The first example fails if I comment out the `kable_styling()` call at the end of the pipe, presumably because you need to specify some particular LaTeX packages.  Please post a *reproducible* example.

**Comment by jlambvo** [comment]
I realized my snippet used a custom column definition, though I don't know why that would make any difference within R? 

Either way, this should work (I also removed the unnecessary Reduce() call):

```
kbl(x = mtcars,
    format = "latex",
    align = c("p{2cm}",rep("p{2cm}",length(mtcars)))) %>%
  kable_styling(latex_options = "scale_down")
```

Thanks!

**Comment by dmurdoch** [comment]
It makes a difference if I can't test the solution.  However, I can work with your latest submission.

**Comment by dmurdoch** [comment]
This required changes at a fairly low level, so there's a good chance that some other bug has been introduced.  Please check carefully, and report any issues.

**Comment by haozhu233** [comment]
I will take a look next week. I'm finishing my PhD defense. 😆

**Comment by dmurdoch** [comment]
Congratulations!  No rush to look at it -- if anything pops up, I'll try to handle it.

**Comment by jlambvo** [comment]
Informally, I grabbed the latest dev branch and my use case now works, fantastic! Thank you so much, @dmurdoch . 

(And good luck, @haozhu233, I'll hopefully be doing the same soon)

**Comment by haozhu233** [comment]
@jlambvo UI? I-L-L
