### ISSUE TITLE
Export table to html-file?

### ISSUE THREAD

**Issue by sebastiansauer** [haozhu233/kableExtra#90]
This is a great package, many thanks!

What I wondered is if it is possible to export the table to an html file? In other words, can I get this well polished html table in a standalone file? This would be quite handy for me.

As far as I know, `kable` gives back the R code only, awaiting for knitr routines to convert it to html, latex etc.

**Comment by kiefersmith** [comment]
I am also curious if this is possible.

**Comment by haozhu233** [comment]
Hi, @sebastiansauer @kiefersmith, I just added this feature to the dev version of this package. Now when you run things like `kable() %>% kable_styling()`, it will be automatically rendered in the RStudio viewer panel or your browser if you are running R in terminal. I guess you can save tables from there. :)
