### ISSUE TITLE
how to control the bolder lines?

### ISSUE THREAD

**Issue by jimingshuo** [haozhu233/kableExtra#91]
"BootStrap style"
![image](https://user-images.githubusercontent.com/33013981/32146942-c1bb3320-bcac-11e7-9f26-85c396a6225b.png)

"Magazine style"
![image](https://user-images.githubusercontent.com/33013981/32146947-cf0bdc6e-bcac-11e7-9491-d2fdd3230590.png)

I have been trying to see how to add extra bolder lines on the top and below the bottom, then highlight the one under the header while hide other row lines, I am not sure if you have an easy way to do this? 

I have tried to use "latex" option, but "magick" reports it cannot create RGB png file for gray-scale image, while I don't know how I can fix it.

**Comment by haozhu233** [comment]
This is more like a css question on stackoverflow. You don't need kableextra here. Just put 

```
<style>
.table thead tr:first-child th {
  border-top: double !important;
}
.table thead tr:last-child th {
  border-bottom: 1px solid;
}
.table tbody tr td {
  border-top: none;
}
.table tbody tr:last-child td {
  border-bottom: double;
}
</style>
```
in your rmarkdown outside of r chunks

**Comment by jimingshuo** [comment]
Thanks a lot! Now I have got the table exactly as what I want. So I should have studied CSS too, cool.
