### ISSUE TITLE
formattable integration not working with "latex" option

### ISSUE THREAD

**Issue by jjaiprakash** [haozhu233/kableExtra#95]
Not sure whether this is possible with this package. I am trying to output to a pdf document after certain rows have been formatted using formattable. It is working as expected in html.

**Comment by wibeasley** [comment]
@jjaiprakash, how are you trying it?  Is there a [minimum code example](https://stackoverflow.com/help/mcve) you can share?

**Comment by jjaiprakash** [comment]
In the following code if I change to kable(ds, "latex", escape = F) and knit to pdf, the code does not work as the styling from formattable::formatter is not carried through.

`  


        ds <- read.table(header = TRUE, text ="
                         Group Attribute
                         A high
                         A medium
                         B low
                         C low
                         C medium
                         ")
    
        ds <- ds %>% mutate(Group = formatter("span",
            style = x ~ style("text-decoration" = ifelse(ds$Attribute == "medium", "line-through", NA)))(Group),
            Attribute = formatter("span",
            style = x ~ style("text-decoration" = ifelse(ds$Attribute == "medium", "line-through", NA)))(Attribute))
        
        knitr::kable(ds, "html", escape = F) %>%
              kable_styling(full_width = F)

`

**Comment by wibeasley** [comment]
@jjaiprakash, Does your Rmd file and table look something like this and this?
```r
---
output: html_document
# output: pdf_document
---

```{r}
library(magrittr); library(dplyr); library(kableExtra); library(formattable)
ds <- read.table(header = TRUE, text ="
                 Group Attribute
                 A high
                 A medium
                 B low
                 C low
                 C medium
                 ")

ds <- ds %>% 
  mutate(
    Attribute     = formatter(
      "span", 
      style = x ~ style(
        "text-decoration" =
          ifelse(
            ds$Attribute == "medium", 
            "line-through", 
            NA_character_
          ) # Close ifelse
      ) # Close style
    )(Attribute) # Close formatter
    
  )

ds %>% 
  knitr::kable("html", escape = F) %>%
  # knitr::kable("latex", escape = F) %>%
  kable_styling(full_width = F)
```

![image](https://user-images.githubusercontent.com/1372890/32511707-33f6d552-c3ba-11e7-971f-09fca8c457b6.png)

And with the pdf/latex values toggled (in the yaml header and in the `knitr::kable()` call), the table looks like this?
![image](https://user-images.githubusercontent.com/1372890/32511751-57a74900-c3ba-11e7-934a-f13ff8bd7cda.png)


I'm wondering if this is a kableExtra issue, because when that last ~4 lines of code is replaced with this, the table still shows that **html** markup, like the previous screenshot.  If I'm understanding correctly, the problem is that `formattable::formatter()` is for ["making HTML elements"](https://www.rdocumentation.org/packages/formattable/versions/0.2.0.1/topics/formatter).  Those html tags are meaningless when you run them through `kable(ds, "latex", escape = F)`, as you said above.
```r
ds %>% 
  knitr::kable("latex", escape = F) #Not called: %>% kable_styling(full_width = F)
```

![image](https://user-images.githubusercontent.com/1372890/32511874-c4bef09c-c3ba-11e7-86ce-3e361ef4b939.png)

**Comment by jjaiprakash** [comment]
yes, that's what I get. I was trying to use `formattable::formatter()` because all css elements are not available as styling elements in kableExtra. It works well with html, but for latex the existing functions would need to extended and I don't yet know how to do that. My current workaround is to print as html and then using a html to pdf converter. But that cannot work in a seamless way for knitting a larger document from Rmarkdown. Thanks.

**Comment by haozhu233** [comment]
Hi, @jjaiprakash, as @wibeasley suggested, `formattable::formatter()` will only give you some raw HTML codes, which won't be rendered by `pdf_document`. You can't do too much with it unless you are using webshoot. 

I haven't added the text strikethrough feature to `kableExtra` (maybe I should). For the purpose of your case, in fact, you don't need either `formattable` or `kableExtra`. 

    ---
    output: pdf_document
    header-includes:
      - \usepackage{ulem}
    ---
    
    ```{r}
    library(dplyr); library(kableExtra); library(knitr)
    ds <- read.table(header = TRUE, text ="
                 Group Attribute
                 A high
                 A medium
                 B low
                 C low
                 C medium")

    ds %>%
      mutate(
        Attribute = ifelse(
          Attribute == "medium", 
          paste0("\\sout{", Attribute, "}"), Attribute
          )) %>%
      kable("latex", escape = F, booktabs = T)
    ```

**Comment by jjaiprakash** [comment]
Thanks for the latex education. That's perfect.
