### ISSUE TITLE
HTML Code Escaped

### ISSUE THREAD

**Issue by ParsaAkbari** [haozhu233/kableExtra#96]
The HTML included by conditional logic of cells is escaped when running the following set of commands: The HTML appears as plain text in the table.

```
options(knitr.table.format = "html")
results.table %>%
mutate(Pvalue = cell_spec(Pvalue, format="html", color = ifelse(Pvalue < (5/100), "red", "#555555"))) %>%
kable(format="html", digits=4) %>%
kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

**Comment by haozhu233** [comment]
You need to put escape = F in kable.

**Comment by ParsaAkbari** [comment]
Sorry to re-open.
On a slightly tangential topic, if you use HTML and escape=F the 'digits' option for rounding numbers no longer works.

**Comment by haozhu233** [comment]
@ParsaAkbari after you use `cell_spec`, the contents of the column you modified are turned into character string with CSS text. That's why the digits won't work. You'd better do the rounding in `mutate` before you use `cell_spec`.

**Comment by rdornas** [comment]
Unfortunately it didn't work as expected to me using "latex" format. If I `mutate` and `round` before `cell_spec` it shows me the number of digits I chose but the trailing zeros are removed. If this is the pattern, no problem, but I prefer having all cells with the same number of digits instead of having the cell_spec working in this case.

In case you didn't understand what I am talking about, I can provide a reproducible example.

**Comment by haozhu233** [comment]
Don't use `round`. Use `formatC` instead. https://stackoverflow.com/questions/47419519/avoiding-rounding-with-formatc See the question as an example.

**Comment by haozhu233** [comment]
@rdornas Don't use `round`. Use `formatC` instead. https://stackoverflow.com/questions/47419519/avoiding-rounding-with-formatc See the question as an example.

**Comment by rdornas** [comment]
Thank you for your quick response. Ok,  I got the hacky now. I was trying to do a conditional `cell_spec` with double numbers. What I did to make it work was to convert the numbers in character (via `sprintf`, although I also tried the `formatC` option, but I am more used to `sprintf`) and then I did the `cell_spec` detecting values that had a minus sign. For the records, I transcript here what I did:

```
   mutate_if(is.double, funs(sprintf("%0.2f", .))) %>% #transform to character double numbers in two digit format
  mutate_if(is.character, function(x) {kableExtra::cell_spec(x, "latex", color = ifelse(str_detect(x, "-") == T, "red", "black"), align = "r")}) %>%  #present negative numbers in red
```
