### ISSUE TITLE
column_spec not working with longer tables

### ISSUE THREAD

**Issue by ahdee** [haozhu233/kableExtra#97]
Hi I find that column_spec with background color does not appear to be working with longer datframes. So for example when I do. 

```
dt <- mtcars[1:5, 1:6]

kable(dt, format = "latex", booktabs = T, caption = "Demo Table") %>%
    kable_styling(latex_options = c("hold_position"), 
                full_width = F) %>%
  column_spec(1:2, italic = T, color = "black", background = "lime") %>%
  column_spec(4, bold = T, border_right = T, background = "olive") 
```
this seem to work however on more complicated longer dataframe the bold and italic would work but the background color does not show up.  Weird thing is that if I change style to 
`latex_options = c("striped", "hold_position")`
this would color but only the header portion and not the table.  Do you have any suggestion? 
thanks! great package! 
A

**Comment by haozhu233** [comment]
Hi, @ahdee,

In LaTeX, `column_spec` does its trick by changing the column alignment/formatting section. It doesn't alter every cell. I guess it loss it's battle against`\rowcolor...` for the striped rows. 

You can, use the new `cell_spec` function to forcefully add color to every cell but you need to put `escape = F` in `kable`. Also, `cell_spec` doesn't work on row.names of the data.frame.

```
dt %>%
  mutate(mpg = cell_spec(mpg, "latex", background = "lime")) %>%
  kable(format = "latex", booktabs = T, caption = "Demo Table",
        escape = F) %>%
    kable_styling(latex_options = c("hold_position", "striped"), 
                full_width = F)
```

**Comment by ahdee** [comment]
@haozhu233 great thank you.  If that is the case why not just use the same strategy for all column_spec function? just a thought. thanks. I'm gonna try this out.

**Comment by haozhu233** [comment]
I guess for HTML, I can do that but for LaTeX, since we want to modify column width, those formatting things have to stay on top.
