### ISSUE TITLE
Feature request - Add inline CSS parameter to row_spec, column_spec and cell_spec

### ISSUE THREAD

**Issue by stephLH** [haozhu233/kableExtra#98]
Hi,
First thanks very for this very useful package !

Would it be possible to add a custom CSS parameter (as a string parameter) to spec family functions ?
For instance, I try to set the padding-right to the values of a specified column.
With a regex, I tried to add inside the kableExtra output the style "padding-right: 20px;" but it broke my ioslides output.

**Comment by haozhu233** [comment]
Sounds like a good idea. 👍

**Comment by haozhu233** [comment]
I just added this feature in b1de967e10965214d970a8505cfc3f8fc2c6b419. Sorry for the delay. :P

**Comment by stephLH** [comment]
thanks a lot !
I'll try that soon :)
