### ISSUE TITLE
Feature_request: add strikeout

### ISSUE THREAD

**Issue by ahdee** [haozhu233/kableExtra#99]
Hi, is it possible to add strikeout. Currently for latex I notice there is bold and italic but what really important sometimes to strikeout.  The reason is because its a nice way to show if a sample is not included in an analysis for example.  thanks! 
A

**Comment by haozhu233** [comment]
There were some discussion in https://github.com/haozhu233/kableExtra/issues/95. It should be fairly easy for HTML but for LaTeX, I have been hesitate on that for a long time whether I should import a whole package just for the strikethrough feature. 😂

**Comment by ahdee** [comment]
oh you mean you need an additional package for strikeout? I would vote for that =D what about only loading when the feature is requested?

**Comment by haozhu233** [comment]
Hi, @ahdee, I just added strikeout and underline to those spec functions. Feel free to try it out in the dev version using `devtools::install_github()`

**Comment by ahdee** [comment]
Wow Hao, you rock man. Thanks for your continuous update to this package.
Alex

`-:-.   ,-;"`-:-.   ,-;"`-:-.   ,-;"`-:-.   ,-;"
   `=`,'=/     `=`,'=/     `=`,'=/     `=`,'=/Alex.Lee/ Ph.D
==/650.898.7331 =/ Summer Winds
   ,=,-<=`.    ,=,-<=`.    ,=,-<=`.    ,=,-<=`.
,-'-'   `-=_,-'-'   `-=_,-'-'   `-=_,-'-'   `-=_

**Comment by yihui** [comment]
@haozhu233 `strikeout` doesn't seem to work for `column_spec()`, but it does work for `row_spec()`. Any ideas?

````
---
title: "An important report"
output:
  pdf_document: 
    keep_tex: true
---

```{r}
library(knitr)
library(kableExtra)
# doesn't work
kable(head(iris, 5)) %>%
  column_spec(5, strikeout = TRUE)
# works
kable(head(iris, 5)) %>%
  row_spec(5, strikeout = TRUE)
```
````

**Comment by haozhu233** [comment]
Hi, @yihui , `column_spec` works by modifying the column alignment section but it seems that `\sout` is not working there... I didn't realize that until you pointed it out. Thanks! I will see if there is a fix.

**Comment by haozhu233** [comment]
@yihui Took me a while but it's fixed now. I changed column_spec a lot and it's now even taking conditional formats. The trick is to many options from column alignment setting to cell setting in latex. :P

**Comment by yihui** [comment]
Great! Thank you!
